### ISSUE TITLE
OpenAPI import does not respect multiple server environments

### ISSUE THREAD

**Issue by seanburke-wf** [getinsomnia/insomnia#4234] opened 2021-11-19 19:00 UTC
### Expected Behavior

When opening an OpenAPI 3.0.2 YAML, a separate environment will be created from each entry in the `servers` list, named based on the `description` field of the server object.

### Actual Behavior

The first entry in the `servers` list has its URL parsed and placed in an "OpenAPI env" environment (without respect to description), and subsequent entries are ignored.

### Reproduction Steps

Import the following OpenAPI file as a request collection. From the collection, go to "Manage Environments" and note name of environment and lack of additional environments.

```
openapi: 3.0.2
info:
  title: repro
  version: 1.0.0

servers:
  - url: "http://localhost:8080/api/v1"
    description: local
  - url: "https://example.com/repro/api/v1"
    description: prod

paths:
  /foo:
    get:
      description: Get the foo
      responses:
        "200":
          description: The foo, I suppose
          content:
            application/json:
              schema:
                type: string
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.6.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.3 LTS

### Installation method

snapcraft.io snap

**Comment by develohpanda** [comment] 2021-11-23 05:11
Thank you for raising this and the detailed explanation! I'll leave it open and cross-link to the discussion at https://github.com/Kong/insomnia/discussions/3627. If you'd like to comment your notes into that discussion and close this issue, that works too!

**Comment by ryanholden8** [comment] 2021-12-03 20:50
For what it's worth, we had this same expectation. We were also surprised `server.variables` was not imported as environment variables. - https://swagger.io/specification/#server-object

**Comment by develohpanda** [comment] 2021-12-05 22:54
Closing as duplicate of https://github.com/Kong/insomnia/discussions/3627

**Closed as completed by develohpanda** 2021-12-05 22:54 UTC
Labels: PA-importers, A-design, S-verified
