### ISSUE TITLE
[Bug] Doesn’t update Host header after changing port in URL

### ISSUE THREAD

**Issue by vfaronov** [getinsomnia/insomnia#841] opened 2018-03-31 19:47 UTC
- Insomnia Version: 5.14.9
- Operating System: Ubuntu 16.04

## Details

1. Run some HTTP server on localhost port 3000.
2. In Insomnia, create and send a new GET request to `http://localhost:3000/`.
3. Run some HTTP server on localhost port 4000, such that you may inspect the raw HTTP headers received. The easiest option is `nc -l 4000`
4. In Insomnia, change the request’s URL to `http://localhost:4000/` and send it again.

Insomnia sends an HTTP request to localhost port 4000, but, inspecting its raw bytes, you see:

```
Host: localhost:3000
```

That is, Insomnia forgets to update the Host header.

**Comment by gschier** [comment] 2018-06-06 20:14
Hmm, I can't reproduce this one. Going to close it now, but can re-open if someone else has the same problem

**Closed by gschier** 2018-06-06 20:14 UTC
Labels: Accepted

**Comment by gschier** [comment] 2018-09-13 15:32
@supervirus5 did you also unset the proxy consideration in the Insomnia preferences?

**Comment by supervirus5** [comment] 2018-09-13 17:29
> @supervirus5 did you also unset the proxy consideration in the Insomnia preferences?

Yeah I had to remove the proxy from Insomnia Settings Manually, Thanks !
