### ISSUE TITLE
Failed to render Hl

### ISSUE THREAD

**Issue by Aghiles-smoteo** [getinsomnia/insomnia#6863] opened 2023-11-23 07:35 UTC
### Expected Behavior

Render the request view

### Actual Behavior

Render Failure: e.includes is not a function

TypeError: e.includes is not a function
    at KVe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:470:868)
    at _l (file:///Applications/Insomnia.app/Contents/Resources/app.asar/debug-672b1df6.js:53:34237)
    at FS (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:42:19553)
    at aF (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:44101)
    at tF (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:39819)
    at qpe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:39745)
    at Fd (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:39596)
    at Px (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:35959)
    at QO (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:34906)
    at N (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:29:1615)
    at Immediate.me [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:29:1987)
    at process.processImmediate (node:internal/timers:476:21)

<img width="949" alt="Capture d’écran 2023-11-23 à 11 13 18" src="https://github.com/Kong/insomnia/assets/151514361/d41e92a3-a384-4c56-af94-8e123e73150b">

### Reproduction Steps

1. Upgrade to the last version
2. Open the HI

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.4

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.1.1

### Installation method

download the file from the site

**Comment by Keerthanaa-K** [comment] 2023-11-23 09:50
+1

**Comment by justadamhopkins** [comment] 2023-11-23 10:00
+1

**Comment by Deuh** [comment] 2023-11-23 10:27
+1

The app is broken cannot do anything.
I'm sorry but in the recent month I feel that insomnia is becoming worse an worse it's turning into a postman with unfriendly UX multiclick just to rename etc...

I might just go for [bruno](https://github.com/usebruno/bruno) or something else...

**Comment by edutedu** [comment] 2023-11-23 12:04
+1

**Comment by CosminPerRam** [comment] 2023-11-23 12:10
+1
> I'm sorry but in the recent month I feel that insomnia is becoming worse an worse it's turning into a postman with unfriendly UX multiclick just to rename etc...

Feeling the same.

**Comment by serhii-piskunov** [comment] 2023-11-23 12:21
Downgrade to this version fixed the issue https://github.com/Kong/insomnia/releases/tag/core%408.4.2

**Comment by ihexxa** [comment] 2023-11-23 14:08
This is duplicated with: [#6858](https://github.com/Kong/insomnia/issues/6858)
And please fallback to the previous version : https://github.com/Kong/insomnia/releases/tag/core%408.4.2
We are actively working on this, sry for the inconvenience.

**Comment by matteofuzz** [comment] 2023-11-23 14:58
+1

**Comment by filfreire** [comment] 2023-11-23 16:15
Hey folks, we will launch a new release with a fix for this today, 8.4.5.

Closing this as a duplicate of #6857

**Closed as not planned by filfreire** 2023-11-23 16:15 UTC
Labels: B-bug, S-unverified

**Comment by filfreire** [comment] 2023-11-23 17:22
Update [here](https://github.com/Kong/insomnia/issues/6857#issuecomment-1824752852)
