### ISSUE TITLE
Freshly installed Insomnia appears as Electron

### ISSUE THREAD

**Issue by Terule** [getinsomnia/insomnia#8107] opened 2024-10-20 20:35 UTC
### Expected Behavior

Insomnia icon and name

### Actual Behavior

Electron icon and name

![image](https://github.com/user-attachments/assets/add29230-bdae-4861-8e15-d8efad436692)

### Reproduction Steps

Installed and logged in to my account

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro version 23H2

### Installation method

download from insomnia.rest

**Comment by Mullayam** [comment] 2024-10-21 08:06
same here🤣🤣🤣🤣🤣

**Comment by DJ-caddev** [comment] 2024-10-21 08:19
Seems like a duplicate of #8092 and #8100

**Comment by subnetmarco** [comment] 2024-10-21 11:04
This will be fixed this week in a patch release.

**Comment by subnetmarco** [comment] 2024-10-24 19:40
This should have been fixed with the latest [patch release](https://github.com/Kong/insomnia/releases/tag/core%4010.1.1).

**Closed as completed** 2024-10-24 19:41 UTC
Labels: B-bug, S-unverified

**Comment by sinanerkan** [comment] 2024-10-24 19:42
Did it though? I just upgraded and still see Electron shortcut and icon.

![image](https://github.com/user-attachments/assets/dd6bf302-89cc-489d-ae6c-4e39f276965b)

Edit: I had to uninstall reinstall to fix it. Direct upgrade did not fix it.

**Comment by subnetmarco** [comment] 2024-10-24 20:05
> I had to uninstall reinstall to fix it. Direct upgrade did not fix it.

Yes, not ideal but I am glad that it's working now.

**Comment by Terule** [comment] 2024-10-24 22:09
I've reinstalled, the app icon still electron's but the name is right

![image](https://github.com/user-attachments/assets/0bfde2a5-b462-4447-bbfd-44177041ed96)

**Comment by subnetmarco** [comment] 2024-10-24 22:14
@Terule a fresh new installation of Insomnia still shows the Electron icon?

**Comment by Terule** [comment] 2024-10-25 03:47
> @Terule a fresh new installation of Insomnia still shows the Electron icon?

Yes. But it could be a cache problem since every other place the icon was right
