### ISSUE TITLE
Cannot select proto folder on Manjaro linux KDE

### ISSUE THREAD

**Issue by nmiculinic** [getinsomnia/insomnia#3420] opened 2021-05-25 09:42 UTC
**Describe the bug**
* Cannot select folder where my protos are located

**To Reproduce**
* Select proto folder
* Got folder selection prompt with folders unselectable

**Expected behavior**
I can enter into subfolder and navigate to my protos directory

**Screenshots**
[
![Screenshot_20210525_113958](https://user-images.githubusercontent.com/3183610/119476105-0b52b300-bd4e-11eb-8345-d9121013564c.png)
](url)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.1] linux, KDE
 - Installation Method: [e.g. homebrew]: AUR
 - App Version [e.g. v7.0.3] insomnia-bin 2021.3.0-1

**Additional context**
* You probably have to enable folder selection in the dialog. For file type filter I could only select files, and you probably have to put folders as well

**Comment by develohpanda** [comment] 2021-05-25 09:49
Thank you for reporting this! Marking as duplicate of https://github.com/Kong/insomnia/issues/3347, and there's a PR open to fix it too: https://github.com/Kong/insomnia/pull/3348. I don't have access to a Linux machine but will make sure this gets taken care of for the next stable release. 🙌🏽

**Closed as completed** 2021-05-26 14:24 UTC
Labels: M-duplicate, B-bug, A-grpc, S-verified
