### ISSUE TITLE
Searching requests is unusably bad

### ISSUE THREAD

**Issue by JakeBooher** [getinsomnia/insomnia#6644] opened 2023-10-04 13:53 UTC
### Expected Behavior

Searching for a specific request name (For example, "Create post") should come up with that request, and not every request that contains the word "create"

### Actual Behavior

Searching "Create post" comes up with results for every request that contains the word "Create", for example:

"Create article",
"Create subscription",
"Create page"

### Reproduction Steps

1. Create a request called "Create post"
2. Create a request called "Create article"
3. Search "Create post"
4. Get results for "Create post", and "Create article"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.1.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.5

### Installation method

Downloaded from website

**Comment by filfreire** [comment] 2023-10-04 14:49
Fixed in #6640, duplicate of #6494

Fix will be out on upcoming 8.2 version

**Closed as completed by filfreire** 2023-10-04 14:49 UTC
Labels: B-bug, S-unverified

**Comment by subnetmarco** [comment] 2023-10-04 19:09
8.2 is out, by the way.
