### ISSUE TITLE
[Bug] [Improvement] Improve the import of Postman variables

### ISSUE THREAD

**Issue by LamineMbn** [getinsomnia/insomnia#2051] opened 2020-04-24 18:25 UTC
**Describe the bug**
In my new job they're using Postman and personally I prefer Insomnia. So I tried to import postman environnement variables to Insomnia and it didn't work for because the variables were either *nested* (`openapi.tokenId`) or with a *dash*

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Data'
3. Import data using this example :

```json
{
  "id": "65851a98-bb7b-4132-a0b4-5175edc63f01",
  "name": "env",
  "values": [
    {
      "key": "dev_or_prod_vpc",
      "value": "dev",
      "enabled": true
    },
    {
      "key": "color",
      "value": "abidjan",
      "enabled": true
    },
    {
      "key": "service-gateway-host",
      "value": "service-gateway-{{dev_or_prod_vpc}}.eu-west-1.elasticbeanstalk.com:8080",
      "enabled": true
    },
    {
      "key": "openAM.tokenId",
      "value": "AQIC5wM2LY4SfcztVCmR1P5o2QlyQQpJuapG3IZgT6E3AZc.*AAJTSQACMDIAAlNLABQtNDIwNjIxMDAxNTIyODQyMDAxNwACUzEAAjAx*",
      "enabled": true
    }
  ],
  "_postman_variable_scope": "environment",
  "_postman_exported_at": "2020-04-20T09:40:11.697Z",
  "_postman_exported_using": "Postman/7.22.1"
}

```
You'll get an error.

**Solution**
So I wrote some code to handle this for my own purpose and then I decided to add it to the Insomnia source code and it work like a charm.

So I can make a PR if this issue is relevant.

Thank you for your great work.

**Comment by develohpanda** [comment] 2020-04-24 21:59
Hi @LamineMbn! Thanks for using Insomnia! ♥️ 

This is a commonly reported issue: #1666 and #456, and the limitations for why it's a tricky one are outlined in the linked there too.

However! If you have something working, feel free to submit a PR and we'll take a look. We were talking about the _dash_ restriction just yesterday!

I'll leave this ticket open for the nesting failure, but this is a duplicate of #1666. 😊

**Comment by develohpanda** [comment] 2020-05-22 17:12
Closing this issue to keep discussing in #1666 :)

**Comment by wongstein** [comment] 2022-08-01 21:00
I'm going to close this issue in favor of other issues reported in the comment above.

**Closed as not planned by wongstein** 2022-08-01 21:00 UTC
Labels: needs-triage
