### ISSUE TITLE
When creating a new request the focus is now placed on the address bar not the request name

### ISSUE THREAD

**Issue by OllieCrook** [getinsomnia/insomnia#5299] opened 2022-10-18 10:54 UTC
### Expected Behavior

When creating a new request the cursor should be placed on the name of the request so you can name it.

### Actual Behavior

When creating a new request the cursor is placed into the address bar.

### Reproduction Steps

1. Go to the add button
2. Click "HTTP Request"
3. Cursor is placed directly into the address bar

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It's now three more clicks to name a request and go back to editing vs the previous way of naming first.

This is more of a feature request but it would be even better if after renaming a request you have just created pressing Enter saves the name and focuses the address bar. This would mean pasting in a curl would be `CMD/Ctrl+N`, Name the request, `Enter`, `CMD/Ctrl+v`

### Insomnia Version

v2022.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### Installation method

Homebrew

### Last Known Working Insomnia version

Before 22nd June 2022

**Comment by filfreire** [comment] 2022-10-31 17:24
Hi @OllieCrook thanks for reporting this. 

For now this specific behavior is by design.

There was a similar issue that might have affected you that we've since fixed, https://github.com/Kong/insomnia/issues/5274, and it should be released in our upcoming beta release iteration (beta.4)

**Closed as completed by filfreire** 2022-10-31 17:24 UTC
Labels: B-bug, S-unverified

**Comment by OllieCrook** [comment] 2022-10-31 17:45
Yes that other issue affected me too but this is definitely one that is affecting me on every new request I make.

If fixing that issue caused this one isn't that an unintended side effect? I don't see any acknowledgement of this in the fix PR.
