### ISSUE TITLE
Support for split specifications

### ISSUE THREAD

**Issue by JBonwick** [getinsomnia/insomnia#2186] opened 2020-05-15 14:51 UTC
**Is your feature request related to a problem? Please describe.**
Currently, if you have a specification split into multiple files, there is no way to import these files (gives an error) or write in this style as detailed in the [OpenApi spec](https://swagger.io/specification/#document-structure).
This is often represented in the following file structure:
- openapi.yml
- paths
    - users.yml
- components
    - schemas
        - user.yml

**Describe the solution you'd like**
The ability to import pre-existing split specs and to be able to edit in the style, creating files for new routes and parameters. [Swagger Repo](https://github.com/Redocly/swagger-repo) is an example of a tool that can currently do this.

**Describe alternatives you've considered**
For pre-existing api specs, they could be combined back to a singular file however this is not a viable solution for any large specs.

**Comment by develohpanda** [comment] 2020-06-09 23:12
Duplicate of #2082 

(Please re-open if this request is different)

**Closed as completed** 2020-06-09 23:12 UTC
Labels: M-duplicate
