### ISSUE TITLE
Add support for comments in Query Variables section

### ISSUE THREAD

**Issue by ad-si** [getinsomnia/insomnia#3470] opened 2021-06-13 18:45 UTC
**Is your feature request related to a problem? Please describe.**

I'd like to add comments to the specified query variables for documentation. E.g. where the specified value was retrieved.

**Describe the solution you'd like**

Support comments JavaScript style comments `//`, although they are not strictly party of JSON.

**Describe alternatives you've considered**

Allow specifying the Query Variables as YAML.

**Comment by dimitropoulos** [comment] 2021-06-14 21:15
Thank you for this.  I want this too.  I'm going to close this as a duplicate of https://github.com/Kong/insomnia/issues/2829.  If that's a mistake, please let me know.

**Closed as completed by dimitropoulos** 2021-06-14 21:15 UTC
