### ISSUE TITLE
Insomnia icon is too large on macOS

### ISSUE THREAD

**Issue by AndrewChurchill** [getinsomnia/insomnia#5932] opened 2023-05-01 18:12 UTC
### Expected Behavior

The Insomnia icon should be the same size as other icons on macOS.

### Actual Behavior

The Insomnia icon is too large after the update.

As you can see in the picture, the icon is larger than other standard applications on MacOS.

<img width="278" alt="Screenshot 2023-05-01 at 1 06 39 PM" src="https://user-images.githubusercontent.com/8657392/235503233-7e832561-e3c6-4bc9-998e-d5c4ab1d55f1.png">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.0

### What operating system are you using?

macOS

### Operating System Version

13.2.1

### Installation method

Downloaded from Insomnia website

**Comment by Gradsta** [comment] 2023-05-01 22:20
The border radius also seems too large, but perhaps the size of the icon is throwing off my perception.

**Comment by filfreire** [comment] 2023-05-02 08:24
duplicate of #5922 - fix is already merged and will go out in next patch release

**Closed as completed by filfreire** 2023-05-02 08:24 UTC
Labels: B-bug, S-unverified

**Comment by DanLanthier** [comment] 2023-05-19 14:49
🙏🏻 😅
