### ISSUE TITLE
Possibility to hide menubar on the top

### ISSUE THREAD

**Issue by ramizdemiurge** [getinsomnia/insomnia#389] opened 2017-08-01 09:05 UTC
## Overview
- `Insomnia Version:` 5.6.3
- `Operating System:`  ubuntu 16.04.1 (amd54)
- `Summary: ` Visual improvement

I think, it will be really cool, if you will make possibility to hide menubar on the top. :)
It makes insomnia little bit ugly.

Thanx. Love insomnia :+1:

**Comment by gschier** [comment] 2017-08-01 16:46
Thanks for the suggestion @ramizdemiurge! This has been discussed quite a bit before and is a duplicate of #314

**Closed by gschier** 2017-08-01 16:46 UTC
