### ISSUE TITLE
Feature Request: Multiple yml files in .insomnia/Workspace repo

### ISSUE THREAD

**Issue by walkerlangley** [getinsomnia/insomnia#2216] opened 2020-05-26 13:27 UTC
The ability to store multiple yml files in the .insomnia/Workspaces directory which would allow a "swagger" repo that would hold details for multiple api's.

**Comment by nijikokun** [comment] 2020-05-28 21:23
Duplicate of #2082

**Closed as completed by nijikokun** 2020-05-28 21:23 UTC
Labels: M-duplicate
