### ISSUE TITLE
[Bug] Insomnia uses Internet Explorer as internal browser which is no longer supported by GitHub

### ISSUE THREAD

**Issue by hf-kklein** [getinsomnia/insomnia#1811] opened 2019-11-26 15:15 UTC
When using GitHub as an authentication provider (via auth0) for implicit granty type OAuth2 Authorization the GitHub Login page is opened in a browser window embedded in Insomnia.

There's a warning on top of the window that says:
 > Please note that GitHub no longer supports your web browser.
We recommend upgrading to the latest Google Chrome or Firefox.

![grafik](https://user-images.githubusercontent.com/23094997/69645711-e8671600-1066-11ea-8c32-ac8eaae6b096.png)

After I entered a 2FA code there's an error message:
> What‽
Your browser did something unexpected. Please contact us if the problem persists.

![grafik](https://user-images.githubusercontent.com/23094997/69645930-41cf4500-1067-11ea-888d-5f633d0dcec5.png)

Although there's this error message, the access token was successfully be retrieved on second try.

I configured Firefox to be my default browser.

- Insomnia Version: 7.03 (Shell 3.1.13, Node 10.2.0, V8 6.6346.32, Architecture x64)
- Operating System: Windows 10

**Comment by gschier** [comment] 2019-11-26 17:31
Duplicate of https://github.com/getinsomnia/insomnia/issues/1774

**Closed by gschier** 2019-11-26 17:31 UTC
