### ISSUE TITLE
[Feature request] Running request folder via Plugin API should show latest response data

### ISSUE THREAD

**Issue by rapsalands** [getinsomnia/insomnia#6536] opened 2023-09-19 20:30 UTC
### Expected Behavior

Triggering requests via Plugins (tried plugin [Exec-Suite](https://insomnia.rest/plugins/insomnia-plugin-exec-suite) and [Run Folder](https://insomnia.rest/plugins/insomnia-plugin-run-folder).), should reset the response window for each request to show the latest response data.

### Actual Behavior

Actual Behavior: Response window still show the previous response and not the latest response. This happens when requests are triggered via plug-in.

### Reproduction Steps

1. Install plugin [Exec-Suite](https://insomnia.rest/plugins/insomnia-plugin-exec-suite) or [Run Folder](https://insomnia.rest/plugins/insomnia-plugin-run-folder).
2. Have a folder inside Insomnia project with some requests.
3. In menu options of folder, click `Execute All Requests` or respective command to run all requests in a folder.
4. All requests should run sequentially.
5. Click each request one by one to see the response.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.4.1

### Installation method

download from Insomnia.rest

**Comment by filfreire** [comment] 2023-09-27 11:29
duplicate of #6512

**Closed as completed by filfreire** 2023-09-27 11:29 UTC
Labels: N-investigation, A-plugin-api, C-improvement, S-verified
