### ISSUE TITLE
[Improvement] Setting to disable fuzzy search in sidebar

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#988] opened 2018-06-15 06:21 UTC
- Insomnia Version: 5.16.6
- Operating System: win10

## Details
Fuzzy search works incorrectly - it's too sensitive and finds every request with entered characters 
in its name. Most time, when I want to find some request by its name, I know the exact pattern and want to find only names with this exact pattern in the name: 
![image](https://user-images.githubusercontent.com/38757986/41453054-fceaa65e-707c-11e8-8896-53f8da5a5876.png)

In case this is intended behavior, please add some configuration property to enable/disable fuzzy search.

**Comment by gschier** [comment] 2018-06-20 15:23
This is the intended behavior but, I agree, it's probably good to have an option to disable this. Your example seems extremely frustrating.

**Comment by besolov** [comment] 2018-06-22 12:19
Another option is to implement case-sensitive fuzzy search. Should help in this case.

**Comment by 4ekki** [comment] 2018-06-22 16:56
Case-sensitive search solves this particular case but the same problem will remain in hundreds of other cases. 
And I doubt that my list of request names will someday be THAT large that I'll need to find things instead of filtering =) IMO, fuzzy search is a bit overkill for this particular use-case.

**Comment by gschier** [comment] 2018-06-26 20:55
Looks like the `fuzzysearch` library we were using exposes a `score` . I just restricted the score a bit and now it's A LOT better

![image](https://user-images.githubusercontent.com/587576/41938680-ae83d04c-7961-11e8-9f39-0983aa3b6c8d.png)

**Comment by gschier** [comment] 2018-06-26 20:55
Still allows stuff like this too

![image](https://user-images.githubusercontent.com/587576/41938703-c0b146dc-7961-11e8-9746-5b7a443b14dc.png)

**Comment by gschier** [comment] 2018-06-26 20:58
Since it's so much better now, I'm going to close this and not add a setting yet.

**Closed** 2018-06-26 20:58 UTC
Labels: Accepted, Good First Issue
