### ISSUE TITLE
[Bug] JsonPath query regression with filtering array

### ISSUE THREAD

**Issue by jrods** [getinsomnia/insomnia#1624] opened 2019-08-07 12:29 UTC
- Insomnia Version: 6.6.0
- Operating System: Kubuntu 18.10

## Details
In the latest version, my query through a list of objects comparing/equating to a certain property doesn't work anymore.

In my example data, my query is `$.clients[?(@.id == 2049)]`
In my dataset, clients is an array of objects with several properties, with id being a number. In the previous version of insomnia (i don't remember the exact version, the previous release of 6.6.0)

Any comparison similar to the query above only returns zero results. eg. id > 2050, id < 2051 is the same with empty results.

```
{
  "clients": [
    {
      "appointments": [],
      "email": "client1@gmail.com",
      "firstname": "client1",
      "fullname": "client1 test",
      "id": 2049,
      "lastname": "test"
    },
    {
      "appointments": [],
      "email": "client2@gmail.com",
      "firstname": "client2",
      "fullname": "client2 test",
      "id": 2050,
      "lastname": "test"
    },
    {
      "appointments": [],
      "email": "client3@gmail.com",
      "firstname": "client3",
      "fullname": "client3 test",
      "id": 2051,
      "lastname": "test"
    }
}
```

**Comment by nquocnghia** [comment] 2019-08-07 12:55
confirmed, I also got this error when filtering an array with the jsonpath query `$[?(@.name=='name1')]`:
```
bundle.js:24216 [jsonpath] Error:  Error: Line 1: Unexpected token ILLEGAL
    at throwError (/snap/insomnia/31/resources/app.asar/node_modules/jsonpath/lib/aesprim.js:1161)
    at advance (/snap/insomnia/31/resources/app.asar/node_modules/jsonpath/lib/aesprim.js:1089)
    at lookahead (/snap/insomnia/31/resources/app.asar/node_modules/jsonpath/lib/aesprim.js:1118)
    at parseSourceElements (/snap/insomnia/31/resources/app.asar/node_modules/jsonpath/lib/aesprim.js:3070)
    at parseProgram (/snap/insomnia/31/resources/app.asar/node_modules/jsonpath/lib/aesprim.js:3109)
    at Object.parse (/snap/insomnia/31/resources/app.asar/node_modules/jsonpath/lib/aesprim.js:3856)
    at Handlers.subscript-child-filter_expression (/snap/insomnia/31/resources/app.asar/node_modules/jsonpath/lib/handlers.js:116)
    at /snap/insomnia/31/resources/app.asar/node_modules/jsonpath/lib/index.js:137
    at Array.forEach (<anonymous>)
    at /snap/insomnia/31/resources/app.asar/node_modules/jsonpath/lib/index.js:134
```
This error is present in all v6.6.0 artifacts that I downloaded and built myself. I suspect that jsonpath@1.0.2 is the cause because running Insomnia in dev mode with jsonpath@1.0.0 seems to work fine

**Comment by XReaper95** [comment] 2019-08-07 13:05
Yeah same here, it happens with any query using JsonPath, in fact just $.[?(@)] returns nothing.

**Comment by gschier** [comment] 2019-08-07 16:02
It looks like the JSONPath dependency version may have changed by accident in the last release. Taking a look now.

As for your original problem, @jrods. Your response is invalid JSON. The array of clients is missing a closing bracket.

**Closed** 2019-08-07 16:18 UTC
Labels: Accepted 👌, High Priority

**Comment by Ravelman** [comment] 2019-08-08 06:30
Same here, using `$.specificpath.array[(@.length-1)].href `as a JSONpath filter in 
Edit tag -> 
Response - reference values from other request's responses -> 
Body Attribute - value of response body

_Previously, I would get the href of the last element in the array, which is the expected result._
result after upgrading to insomnia 6.6.0:
> Invalid JSONPath query: $.specificpath.array[(@.length-1)].href

**Comment by nquocnghia** [comment] 2019-08-08 07:27
@Ravelman v6.6.2 released yesterday had fixed this error
