### ISSUE TITLE
[Bug] - Unicode characters are not properly displayed in v6.0.1

### ISSUE THREAD

**Issue by Jinsung-L** [getinsomnia/insomnia#1092] opened 2018-07-31 06:47 UTC
- Insomnia Version: v6.0.1
- Operating System: macOS High Sierra 10.13.6

## Details

I tested this issue using an echo server which had no problem on the requests made from browsers.

Request:
```
{
	"testA": "가 나다 라마바 사아자차",
	"testB": "가_나다_라마바_사아자차",
	"testC": "가☆나다☆라마바☆사아자차",
	"testD": "가☆나다☆라마바☆사아자차",
	"testE": "☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆"
}
```

Raw Data:
```
{
  "testA": "\uac00 \ub098\ub2e4 \ub77c\ub9c8\ubc14 \uc0ac\uc544\uc790\ucc28", 
  "testB": "\uac00_\ub098\ub2e4_\ub77c\ub9c8\ubc14_\uc0ac\uc544\uc790\ucc28", 
  "testC": "\uac00\u2606\ub098\ub2e4\u2606\ub77c\ub9c8\ubc14\u2606\uc0ac\uc544\uc790\ucc28", 
  "testD": "\uac00\u2606\ub098\ub2e4\u2606\ub77c\ub9c8\ubc14\u2606\uc0ac\uc544\uc790\ucc28", 
  "testE": "\u2606\u2606\u2606\u2606\u2606\u2606\u2606\u2606\u2606\u2606\u2606\u2606\u2606\u2606\u2606\u2606\u2606"
}
```

Visual Preview:
```
{
	"testA": "가 나\ub2e4 라\ub9c8바 사\uc544자\ucc28",
	"testB": "가_나\ub2e4_라\ub9c8바_사\uc544자\ucc28",
	"testC": "가\u2606나\ub2e4☆\ub77c마\ubc14☆\uc0ac아\uc790차",
	"testD": "가\u2606나\ub2e4☆\ub77c마\ubc14☆\uc0ac아\uc790차",
	"testE": "☆\u2606☆\u2606☆\u2606☆\u2606☆\u2606☆\u2606☆\u2606☆\u2606☆"
}
```

As you can see, all consecutive unicode characters right next to the other unicode character are not properly displayed.

By the way, the language used here is Korean, though it seems unrelated.
I tested this for other languages too, including emoji, the issue appears the same.

**Comment by isabekyan** [comment] 2018-07-31 19:35
Have the same issue.
Version 6.0.1
Shell 1.8.7
Node 8.2.1
V8 5.9.211.38
Architecture x64
OS: Windows 10 Pro 1803.

**Comment by gschier** [comment] 2018-07-31 21:09
Duplicate of #1088

**Closed by gschier** 2018-07-31 21:09 UTC
