### ISSUE TITLE
Sort endpoints / group endpoints

### ISSUE THREAD

**Issue by sbrattla** [getinsomnia/insomnia#2693] opened 2020-10-06 12:12 UTC
I'm a happy user of Insomnia, but there's one thing which I believe Insomnia lacks.

When you have a growing list of endpoints for an API, it becomes harder and harder to locate a specific request. It is not possible to sort the list of endpoints. It's possible to drag and drop / arrange endpoints, but it's cumbersome when you have a long list of endpoints - and you need to make sure you arrange new endpoints correctly as well.

If I would be able to sort endpoints - and maybe also group endpoints (and label the groups) - then that would truly make it awesome!

**Comment by codeasashu** [comment] 2020-10-06 18:27
Doesn't request groups (folder) solves your grouping problem? naming that folder is same as folder name IMO.

I too like to have the sort option

**Comment by develohpanda** [comment] 2020-10-06 20:38
Thanks for requesting this, there is an open issue with some conversation so I will close this as duplicate of https://github.com/Kong/insomnia/issues/2594.

**Closed as completed by develohpanda** 2020-10-06 20:38 UTC
Labels: M-duplicate
