### ISSUE TITLE
Uable to launch 2022.7.1 on Ubuntu 

### ISSUE THREAD

**Issue by manbeing** [getinsomnia/insomnia#5644] opened 2023-01-10 15:49 UTC
### Expected Behavior

After 2022.7.1 version is installed on Ubuntu, users should be able to launch it successfully. 

### Actual Behavior

Unable to launch it.
I have to run the command `sudo snap revert insomnia` to revert the insomnia to 2022.5.1 version to launch the insomnia.
The pain is snap automatically update insomnia every time to the latest version, which I cannot stop it. 

### Reproduction Steps

No steps to reproduce. 
Snap on Linux Ubuntu 20.4 automatically update insomnia to 2022.7.1 version

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.4

### Installation method

snap

### Last Known Working Insomnia version

2022.5.1

**Comment by filfreire** [comment] 2023-01-10 16:11
Duplicate of #5637

**Closed as completed by filfreire** 2023-01-10 16:11 UTC
Labels: B-bug, S-unverified
