### ISSUE TITLE
Can't move requests into folders (or folders into folders)

### ISSUE THREAD

**Issue by vetterj73** [getinsomnia/insomnia#5380] opened 2022-11-03 22:01 UTC
### Expected Behavior

When I drag a request on a folder it should move there.

### Actual Behavior

It doesn't go there.

### Reproduction Steps

This is exactly the same as 5182 which was closed since you said the fix would be in 2022.6.0 but it still doesn't work in that version.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise Version 10.0.22621

### Installation method

Downloaded exe

**Comment by filfreire** [comment] 2022-11-04 10:06
Hi @vetterj73 thanks for reporting this!

Can you confirm that this only happens to you when the folder is "unwrapped" / "closed"?

I was trying to reproduce what you mention, and the only case where I can't move a request or a folder into another folder is if the destination folder is not expanded.

cc @Samuelfaure @izzat-sq

**Comment by Samuelfaure** [comment] 2022-11-04 10:07
@filfreire Negative, I cannot move a request to the folder in any situation (expanded or closed)

**Comment by filfreire** [comment] 2022-11-04 10:18
@Samuelfaure can you double check the version that you are running (Check in the Help tab):

![Screenshot 2022-11-04 101411](https://user-images.githubusercontent.com/11976836/199949297-8fb9be3d-9dab-4b45-ae57-5ffa4aa35b32.png)


Also would you be able to share the logs after trying to move a request or a folder:

![Screenshot 2022-11-04 101648](https://user-images.githubusercontent.com/11976836/199949321-351cdd8f-5c2a-4131-9d13-b1093bacfe8e.png)

**Comment by Samuelfaure** [comment] 2022-11-04 10:31
Here are my whole specs
![image](https://user-images.githubusercontent.com/14159757/199951740-12a5b14b-8b74-4a47-8c23-fb2012b80e17.png)

Nothing happens in the log when I try to move the request to the folder :/ neither in `main` nor `renderer` (however if I do other actions I do see something happening in the logs)

**Comment by vetterj73** [comment] 2022-11-04 15:32
Here are my Insomnia specs

Version: Insomnia 2022.6.0
Build date: 9/26/2022
OS: Windows_NT x64 10.0.22621
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64

The video show me trying to move a request to a folder.

https://user-images.githubusercontent.com/9198450/200014653-476359eb-2ddf-40d9-83d9-31da2d9aa477.mp4

**Comment by izzat-sq** [comment] 2022-11-07 02:32
This is my version. In my case, i cannot drag and drop at all. Not just into folders (both expanded and closed), but also cannot drag and drop to change the position of the request.
![2022-11-07 10-08-29](https://user-images.githubusercontent.com/108707382/200213694-5fecf1ef-ac6a-4a80-8c39-afe36e833ecc.png)

**Comment by darcyrush** [comment] 2022-11-08 08:32
This was reported before and has been broken since 2022-5.1.
2022.7.0-beta.4 finally fixes it

https://github.com/Kong/insomnia/issues/5101

**Comment by Samuelfaure** [comment] 2022-11-08 08:55
@darcyrush I am certain I had the problem in 2022-4.2 (see my original issue https://github.com/Kong/insomnia/issues/5182)

Edit: I confirm, 2022.7.0-beta.4 fixes it :1st_place_medal:

**Comment by vetterj73** [comment] 2022-11-08 15:59
How can I download the beta?

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 8, 2022 at 2:32 AM, ***@***.***> wrote:   


This was reported before and has been broken since 2022-5.1.
2022.7.0-beta.4 finally fixes it

#5101

**Comment by Samuelfaure** [comment] 2022-11-08 16:11
@vetterj73 Available in the release section: https://github.com/Kong/insomnia/releases

**Comment by vetterj73** [comment] 2022-11-08 18:05
I installed the beta and it wiped out my previous project.  I know that is probably my issue since I didn't have it sync'd to the cloud.
Jeremy Vetter (612) 910 - 4225 

    On Tuesday, November 8, 2022 at 10:11:45 AM CST, Samuel FAURE ***@***.***> wrote:  
 
 


@vetterj73 Available in the release section: https://github.com/Kong/insomnia/releases

**Comment by filfreire** [comment] 2022-11-10 11:25
Closing since as fixed since [beta.4](https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.4)

**Closed as completed by filfreire** 2022-11-10 11:25 UTC
Labels: B-bug, S-unverified

**Comment by vetterj73** [comment] 2022-11-11 02:13
This still doesn't work with this version

Version: Insomnia 2022.7.0-beta.4
Build date: 11/2/2022
OS: Windows_NT x64 10.0.22621
Electron: 21.2.0
Node: 16.16.0
V8: 10.6.194.18-electron.0
Architecture: x64


https://user-images.githubusercontent.com/9198450/201247474-412bade8-c2eb-4c55-8868-532db25a912f.mp4

**Comment by darcyrush** [comment] 2022-11-11 08:14
@vetterj73, you need to release your mouse click when you see the dotted lines. It also helps if you drag to the right first

**Comment by vetterj73** [comment] 2022-11-11 09:26
That works it is a little confusing because most moves like this you release the mouse when you are over the folder.
Thanks
Jeremy Vetter (612) 910 - 4225 

    On Friday, November 11, 2022 at 02:14:15 AM CST, darcyrush ***@***.***> wrote:  
 
 


@vetterj73, you need to release your mouse click when you see the dotted lines. It also helps if you drag to the right first
