### ISSUE TITLE
2022.7.0 snap wont start on ubuntu

### ISSUE THREAD

**Issue by seangarner** [getinsomnia/insomnia#5531] opened 2022-12-15 16:08 UTC
### Expected Behavior

For insomnia to start.

### Actual Behavior

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /run/user/1000/snap.insomnia/.org.chromium.Chromium.DdJT13)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snap/insomnia/184/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
```

### Reproduction Steps

1. install insomnia using the snap
2. run insomnia

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Ubuntu 22.04.1 LTS

snap info
```
  latest/stable:    2022.7.0 2022-12-15 (184) 117MB -
```

### Insomnia Version

2022.7.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.1 LTS

### Installation method

snap

### Last Known Working Insomnia version

the one that was installed this morning

**Comment by filfreire** [comment] 2022-12-15 16:11
Hi @seangarner do you get the same issue if you use the `.deb` installation?

**Comment by filfreire** [comment] 2022-12-15 16:13
Also you might be missing some `gcc` libraries locally. Try to follow [this suggestion](https://stackoverflow.com/a/66465559) for a similar issue:

```
sudo apt update
sudo apt install wget gcc-8 unzip libssl1.0.0 software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt-get install --only-upgrade libstdc++6
```

**Comment by seangarner** [comment] 2022-12-15 16:34
`.deb` installation works fine.

**Comment by seangarner** [comment] 2022-12-15 16:40
On the apt install:
```
E: Package 'gcc-8' has no installation candidate
E: Unable to locate package libssl1.0.0
E: Couldn't find any package by glob 'libssl1.0.0'
```

I would go further, but I'm reluctant to add a ppa without looking at it properly first, and I was under the impression that one of the points of snaps was to remove those types of library deps because they have to be shipped in the snap.  I admit that could be a misconception on my part though.  Let me know if you need me to take it further.

**Comment by seangarner** [comment] 2022-12-15 16:43
For others hitting this, the temporary workaround for snap is to downgrade:
```
sudo snap revert insomnia
```

Or to uninstall & switch to the [deb installer](https://insomnia.rest/download).

**Comment by thedomeffm** [comment] 2022-12-16 08:23
I have the same issue with my `Ubuntu 20.04.4 LTS` and `Ubuntu 22.04.01 LTS`!

**Comment by kachar** [comment] 2022-12-16 08:39
Same problem on `Kubuntu 22.04.1 LTS`

Few more log lines:

```
(insomnia:7884): Gtk-WARNING **: 10:35:52.543: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
Gtk-Message: 10:35:52.559: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:35:52.559: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 10:35:52.560: Failed to load module "appmenu-gtk-module"
```

**Comment by arkhi31** [comment] 2022-12-16 08:47
Same issue on `Ubuntu 22.04.01 LTS`, thanks for suggesting downgrade

**Comment by Laerte** [comment] 2022-12-16 09:39
+1 on Ubuntu 20.04.5 LTS

Downgrading worked!

**Comment by Deimos308** [comment] 2022-12-16 11:23
Same issue on `5.15.81-1-MANJARO`
And it's a bit strange because I have required version of lib on my machine.

## Snap: 
![image](https://user-images.githubusercontent.com/18260548/208088328-c720dcf3-4409-42ab-a1e6-2f9b5410072b.png)

## Errors on startup:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /run/user/1000/snap.insomnia/.org.chromium.Chromium.hEUrZp)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snap/insomnia/184/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
```

## ENV:
![image](https://user-images.githubusercontent.com/18260548/208088287-2e372c4e-0224-4c8a-84be-a11024b73392.png)

**Comment by Moraesofia** [comment] 2022-12-16 11:36
I switched to deb but does anyone know how can I recover my workspaces and requests from the snap version?

**Comment by Mateuszry** [comment] 2022-12-16 12:51
> I switched to deb but does anyone know how can I recover my workspaces and requests from the snap version?

Revert snap version as mentioned [here](https://github.com/Kong/insomnia/issues/5531#issuecomment-1353379038), export data and import in deb

**Comment by pesasa** [comment] 2022-12-16 12:51
Idea of snap is that it is a self contained package. It doesn't matter, which Linux OS version you have (Ubuntu/Kubuntu/?buntu/Manjaro/...). It doesn't matter, which libraries your base system has installed, since the program should use the ones inside snap. (Or statically linked inside binary.)

So, the snap package is broken.

**Comment by HiagoW** [comment] 2022-12-16 13:03
Facing same issue on RHEL 8 using RPM

**Comment by danfercf1** [comment] 2022-12-16 14:55
Same issue on Manjaro 5.15.81-1-MANJARO

**Comment by octaviobarbosa** [comment] 2022-12-16 15:04
some in Fedora 37

**Comment by roskee** [comment] 2022-12-16 17:31
Same issue on Ubuntu 22

**Comment by Moraesofia** [comment] 2022-12-16 18:16
> 


> > I switched to deb but does anyone know how can I recover my workspaces and requests from the snap version?
> 
> Revert snap version as mentioned [here](https://github.com/Kong/insomnia/issues/5531#issuecomment-1353379038), export data and import in deb

Revert didnt work for me

**Comment by robertoarruda** [comment] 2022-12-16 18:29
Same issue here, and revert didn't work for me.

```
erro: cannot revert "insomnia": no revision to revert to
```

**Comment by dhitchcock** [comment] 2022-12-16 18:55
revert only works if you had a previous version installed, if this is a fresh install you won't have anything to revert to.  Ideally you could switch channels but the author does not use any of the other channels (candidate,beta,edge) new releases just get pushed straight to stable.  If you switch to the deb version, copy the folder from the sandbox to your home folder, /home/you/snap/insomnia/current/.config/Insomnia/  -> /home/you/.config/Insomnia/

**Comment by dhitchcock** [comment] 2022-12-16 19:05
or you could 
```
sudo snap remove insomnia
wget https://github.com/Kong/insomnia/releases/download/core%402022.6.0/Insomnia.Core-2022.6.0.snap
sudo snap install Insomnia.Core-2022.6.0.snap --dangerous
```

it's not that dangerous :)  It won't update after that it will stay 2022.6, so maybe watch this bug and when it's fixed you can remove that version and install the latest the proper way again.

**Comment by danfercf1** [comment] 2022-12-16 20:26
> or you could
> 
> ```
> sudo snap remove insomnia
> wget https://github.com/Kong/insomnia/releases/download/core%402022.6.0/Insomnia.Core-2022.6.0.snap
> sudo snap install Insomnia.Core-2022.6.0.snap --dangerous
> ```
> 
> it's not that dangerous :) It won't update after that it will stay 2022.6, so maybe watch this bug and when it's fixed you can remove that version and install the latest the proper way again.

Thank you Sir, this is working

**Comment by filfreire** [comment] 2022-12-17 00:37
@Kong/team-insomnia leaving some "stream of consciousness/tap into the force" notes here to help with follow-up investigation.

First, I think this has to do with how the `.snap` is being built by `electron-builder`. VS Code folks have slightly similar issues - see https://github.com/microsoft/vscode/pull/127320 - and they're building snap packages without using electron-builder but relying on old snap base image same as us.

It could explain why we don't have issues with the `.deb` build since it'll use the `/usr/lib/x86_64-linux-gnu/libstdc++.so.6` of the users' machine instead of the older one inside the snap being built (that uses an older ubuntu base).

In our case we are relying on [this template](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/snap/snapcraft.yaml) for the `snapcraft.yaml`. We might be able to solve some of the weirdness folks get on `.snap` by trying to use a more recent snap base version.

There might be extra config we can set on [electron-builder.js](https://github.com/Kong/insomnia/blob/81bc0576a32c02096a413f6c72f172ca4ff32981/packages/insomnia/electron-builder.config.js) to help deal with these issues and other similar issues on `AppImage` and `rpm` builds - and a path for a better fix for #5088 as well.

**Comment by filfreire** [comment] 2022-12-17 01:15
Hey folks, Update to https://github.com/Kong/insomnia/issues/5531#issuecomment-1355879270 - We might have a possible fix 🎸 🎉 

Took inspiration from folks that use electron-builder and bumped into similar issues (see https://github.com/electron-userland/electron-builder/issues/5257#issuecomment-941660681).  Managed to get it working by forcing the `base` of the [snapcraft.yaml](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/snap/snapcraft.yaml) template to latest `core22`.

Steps:
- Run `npm run bootstrap`
- Change the `base` from `core18` to `core22` on `packages/insomnia/node_modules/app-builder-lib/templates/snap/snapcraft.yaml` 
- Run `BUILD_TARGETS='snap' npm run app-package` on a linux host machine (works on WSL)
- Installed the resulting `packages/insomnia/dist/Insomnia<...>.snap` package (e.g. `sudo snap install fixed-insomnia.snap --dangerous`)

And it seems to work okay-ish:
![image](https://user-images.githubusercontent.com/11976836/208215361-807d573a-07dc-4154-bf28-9629e6cd8623.png)


@Kong/team-insomnia fix will be applying these steps to the build pipeline in a proper/sane way which might be tricky. But not impossible.

**Comment by dhernandezgt** [comment] 2022-12-17 18:45
> or you could
> 
> ```
> sudo snap remove insomnia
> wget https://github.com/Kong/insomnia/releases/download/core%402022.6.0/Insomnia.Core-2022.6.0.snap
> sudo snap install Insomnia.Core-2022.6.0.snap --dangerous
> ```
> 
> it's not that dangerous :) It won't update after that it will stay 2022.6, so maybe watch this bug and when it's fixed you can remove that version and install the latest the proper way again.

Thanks is working for me too!!!

**Comment by ciekals11** [comment] 2022-12-19 09:25
> revert only works if you had a previous version installed, if this is a fresh install you won't have anything to revert to. Ideally you could switch channels but the author does not use any of the other channels (candidate,beta,edge) new releases just get pushed straight to stable. If you switch to the deb version, copy the folder from the sandbox to your home folder, /home/you/snap/insomnia/current/.config/Insomnia/ -> /home/you/.config/Insomnia/

I'm 100% sure that I had previous versions (I'm using insomnia for at least a year) but when I try revert I get `no revision to revert to` so for some even reverting isn't an option

**Comment by carloshssouza** [comment] 2022-12-19 13:39
> or you could
> 
> ```
> sudo snap remove insomnia
> wget https://github.com/Kong/insomnia/releases/download/core%402022.6.0/Insomnia.Core-2022.6.0.snap
> sudo snap install Insomnia.Core-2022.6.0.snap --dangerous
> ```
> 
> it's not that dangerous :) It won't update after that it will stay 2022.6, so maybe watch this bug and when it's fixed you can remove that version and install the latest the proper way again.

I'm using Ubuntu 18.04.6 LTS and and Insomnia simply stopped opening and when trying to run it through the terminal, it generates the reported Javascript error. I followed these steps and this is what worked for me. Thanks!!

**Comment by mcallaghan-geotab** [comment] 2022-12-19 14:22
[Snap ](https://snapcraft.io/insomnia) shouldn't be relying on any local libraries ... `snap revert insomnia` fixed for me as well for now.

**Comment by TibebeJS** [comment] 2022-12-20 08:53
> > revert only works if you had a previous version installed, if this is a fresh install you won't have anything to revert to. Ideally you could switch channels but the author does not use any of the other channels (candidate,beta,edge) new releases just get pushed straight to stable. If you switch to the deb version, copy the folder from the sandbox to your home folder, /home/you/snap/insomnia/current/.config/Insomnia/ -> /home/you/.config/Insomnia/
> 
> I'm 100% sure that I had previous versions (I'm using insomnia for at least a year) but when I try revert I get `no revision to revert to` so for some even reverting isn't an option

I think that might be because you had run `snap remove` before - which cleared out the locally retained versions?

**Comment by AlexanderArgyriou** [comment] 2022-12-21 09:49
snap is crap, change my mind, deb works fine

**Comment by marcosnils** [comment] 2022-12-21 13:31
reason why this is not working is because snap core in ubuntu 22.04 and 22.10 don't have the correct `libstdc++.so.6` installed: 

```shell
sudo strings /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

As you can see `GLIBCXX_3.4.26` is not there. 

The correct fix is the one described by @filfreire [here](https://github.com/Kong/insomnia/issues/5531#issuecomment-1355900285) and bump the core base.

**Comment by pogster** [comment] 2022-12-21 14:18
Because of the described problems I uninstalled and reinstalled Insomnia and now all settings are gone, is that intended?

**Comment by marcosnils** [comment] 2022-12-21 14:36
> Because of the described problems I uninstalled and reinstalled Insomnia and now all settings are gone, is that intended?

you can use `snap saved` and `snap restore` to restore removed snap configs. 

ref: https://snapcraft.io/docs/snapshots#heading--automatic-snapshots

**Comment by filfreire** [comment] 2022-12-21 16:02
@marcosnils is correct on [above comment](https://github.com/Kong/insomnia/issues/5531#issuecomment-1361316138) - a fix is ready - https://github.com/Kong/insomnia/pull/5555 - but likely we'll only be able to release it in first week of January due to holidays constraints.

If any other folks bump into this issue in the meantime  - you can either follow [this approach to revert](https://github.com/Kong/insomnia/issues/5531#issuecomment-1355444581)  or install the `.deb` instead. We'll update you here once the above fix PR is merged and likely included in either a patch release or the next beta release.

**Comment by mcallaghan-geotab** [comment] 2022-12-21 16:33
@filfreire  - wouldn't we want to hotpatch / expedite this? (agreed could be difficult timing due to holidays .. but punching out `2022.7.1` seems kind of critical as it is breaking/impacting lots of users (anyone who uses snap anyway);
OR, revoke/revert `2022.7.0` entirely for the time being?

**Comment by dtrckd** [comment] 2022-12-22 00:31
Same error on Debian 5.10.140-1 x86_64 GNU/Linux

The downgrade workaround worked, thanks.

**Closed as completed** 2023-01-04 10:40 UTC
Labels: O-linux, B-bug, O-linux-snap, S-unverified

**Comment by mcallaghan-geotab** [comment] 2023-01-04 14:55
thanks @filfreire !
what's the process / timeline for https://snapcraft.io/insomnia to have the fix?

**Comment by filfreire** [comment] 2023-01-04 16:19
Hey folks merging the PR closed the issue automatically. The fix will go out in a patch release tomorrow morning.

**Comment by kazjote** [comment] 2023-01-09 12:54
Hey, I still can't see the patched version on snapcraft.io. Was it released? :thinking: 

![image](https://user-images.githubusercontent.com/14325/211312689-dcefd920-39ff-4323-bc14-5f3148388c24.png)

**Comment by kazjote** [comment] 2023-01-09 15:40
It still doesn't start for me on Ubuntu 22.04.1 LTS. See full error message: 

```
➜  snap install insomnia
insomnia 2022.7.1 from Insomnia (getinsomnia) installed
➜  snap run insomnia
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /run/user/1000/snap.insomnia/.org.chromium.Chromium.GxeByB)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snap/insomnia/185/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)

(insomnia:30488): Gtk-WARNING **: 16:35:47.604: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(insomnia:30488): Gtk-WARNING **: 16:35:47.607: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(insomnia:30488): Gtk-WARNING **: 16:35:47.607: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
```

**Comment by jlynch1** [comment] 2023-01-09 16:12
> It still doesn't start for me on Ubuntu 22.04.1 LTS. See full error message:

I gave up on the snap version and installed the deb file as documented here : https://docs.insomnia.rest/insomnia/install
this is also build 2022.7.1 and working ok

**Comment by ppazos** [comment] 2023-01-12 01:05
Updated to the latest version and the issue is still happening:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.6P1ZE5)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
```

Only solution is to use a previous version AppImage. Last two updates are broken on Linux.

**Comment by filfreire** [comment] 2023-01-17 15:51
Hey folks, this issue shouldn't be happening any longer for snapcraft packages from [2022.7.2 onwards](https://insomnia.rest/changelog) - the fix was only introduced from that version onwards.

**Comment by djjuhasz** [comment] 2023-01-17 17:14
The 2202.7.3 snap has fixed the start up problem for me. I'm running Ubuntu 22.04.01.

I'm not sure why but snap shows the installed version of Insomnia as 2202.7.4, but when I actually run the app and check Help > About the listed version is 2202.7.3. :shrug:  It's not a big deal, I'm just happy it's working. :)
