### ISSUE TITLE
GraphQL schema docs search

### ISSUE THREAD

**Issue by abdellatifLabr** [getinsomnia/insomnia#3102] opened 2021-02-22 09:15 UTC
This is a feature request and it's not related to any issue.

The feature is search option in graphql schema docs, i'm working on a very large graphql api, and schema docs get very large, so if i want to find a query or a mutation or ...etc i need to scroll through the whole list.

So it would awesome to have a search bar to surf through the docs.

**Comment by nijikokun** [comment] 2021-02-23 08:23
Closing since this seems to be a duplicate of #2720, feel free to re-open if you feel that your request is in some way different. Please also update the OP with any differing mechanisms / requests to ensure it stays open!

**Closed as completed by nijikokun** 2021-02-23 08:23 UTC
Labels: M-duplicate
