### ISSUE TITLE
Insomnia not starting

### ISSUE THREAD

**Issue by NegassaB** [getinsomnia/insomnia#6453] opened 2023-09-06 15:09 UTC
### Expected Behavior

whenever I lauch it from terminal or using gui the expected behavior is for it to start.

### Actual Behavior

With the latest update it doesn't start and when running it from terminal the following error is thrown:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /run/user/1000/app/rest.insomnia.Insomnia/.org.chromium.Chromium.83WdxW)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/main/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
Gtk-Message: 18:03:19.594: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:03:19.595: Failed to load module "pk-gtk-module"
Gtk-Message: 18:03:19.607: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:03:19.607: Failed to load module "pk-gtk-module"
[2:0906/180319.672077:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0906/180319.672374:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0906/180319.793827:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.7

### What operating system are you using?

Other Linux

### Operating System Version

fedora 37

### Installation method

installed using gnome-software-center from fedora flatpak selection

### Last Known Working Insomnia version

2023.1.0

**Comment by Its-treason** [comment] 2023-09-06 17:15
I think this is a duplicate of #6133 #6445

Insomnia was compiled with a version of libc that your system does not have.

You could clone the repo and run Insomnia locally using:
```
npm install
npm run app-package
```

**Comment by joao-jlcm** [comment] 2023-09-06 18:29
Same here using Flatpak app on Fedora 38.

**Comment by joaquinvasquezp** [comment] 2023-09-06 20:33
the .deb package works for me

**Comment by anaximeno** [comment] 2023-09-07 03:14
I am having the same problem on Mint 21.2 (Flatpak)
Reverting to the previous version solved the problem.

**Comment by filfreire** [comment] 2023-09-07 14:18
Duplicate of https://github.com/Kong/insomnia/issues/6133 https://github.com/Kong/insomnia/issues/6445

**Closed as completed by filfreire** 2023-09-07 14:18 UTC
Labels: B-bug, S-unverified

**Comment by anaximeno** [comment] 2023-09-07 15:22
@filfreire Even though this is a duplicate of the other issues, they also seem to be closed as well, and I couldn't find a complete solution for this in any of the other closed issues (nor a commit/merge request referencing the fix on the repository), only workarounds like the one I stated above. Is this something that doesn't depend on your side or won't be fixed, meaning the solution would be to upgrade the system when possible to access a newer version of GLIBC?
