### ISSUE TITLE
[Feature Request] Tabs

### ISSUE THREAD

**Issue by wokes** [getinsomnia/insomnia#1253] opened 2018-11-08 12:52 UTC
- Insomnia Version: 6.0.2
- Operating System: Windows 10

## Details

I recently discovered an issue with Postman that was quite jarring and made me lose confidence (request body appears to be blank, when in fact it's a big JSON response).
This pushed me to - at least partially - add Insomnia to my toolbox. It doesn't have the same problem that Postman does, but it doesn't feel complete enough for me to make a full transition.
Postman has a great tabs feature that lets you open multiple requests at once. To be honest I am shocked that Insomnia doesn't support that - to me it seems like an obvious, ubiquitous feature.
Pretty much all of the API development/testing that I do involves more than one request. Add dozens of saved requests, and you get lost really quick when you have to keep looking for them in the library.

**Comment by sajjadjaved01** [comment] 2018-11-23 06:03
Waiting for this feature ...

**Comment by gschier** [comment] 2018-12-11 23:41
Closing this as duplicate of https://github.com/getinsomnia/insomnia/issues/1003

**Closed by gschier** 2018-12-11 23:41 UTC

**Comment by sebeiron** [comment] 2022-05-25 12:18
I agree with the others, the missing multi-tabs capability is a major hindrance for the adoption of Insomnia in my team.
We often need to compare and switch between the results of several calls and a tabbed interface would be easier for doing so.
There is of course the option to open several instances of Insomnia, but that is not a good workaround.

**Comment by localhosted** [comment] 2023-02-07 16:41
Ever since the update for "projects" I can't open a second Insomnia window

**Comment by roskee** [comment] 2024-06-18 09:31
Opening a second Insomnia window is not that much useful by the way. I had a websocket request. I wanted to connect multiple user instances to the socket and test chatting. but when I opened the request on a second Insomnia window - it says it is connected - it still attaches to the first window request. The windows are like multiple pointers for one variable.
