### ISSUE TITLE
[Feature Request] Tabs and temporary requests

### ISSUE THREAD

**Issue by adrienpayen** [getinsomnia/insomnia#3071] opened 2021-02-10 17:16 UTC
I would like to suggest having two new features that are really missing in Insomnia :
* Tabs
* Temporary requests

## Tabs
**Having tabs helps you working between your different endpoints. It helps you switch from an endpoint to another, then give you the ability to easily compare responses.**

Some of the API I use have a lot of endpoints. To organise all that you have the left menu _(by the way you always need that menu to send a request in Insomnia but I am going to discuss that further)_. 
Now, what if you need to switch from an endpoint that is in the bottom of your menu to another endpoint in the top of your menu and then need a third endpoint in the middle. Let's say you need to subsequently work and test those 3 requests. It is then pretty tricky to navigate between them. Of course you could have your 3 endpoints next to each other in the menu but it would end up being a real mess if you're looking to have a well organised and consistent API. 

## Temporary requests
**As we would have tabs we could considerate having temporary requests in order to not ruin your beautiful list of well documented endpoints (maybe shared with other team members)** 

Sometimes I don't want to save in my collection an endpoint that i created for the only reason that I am testing some random stuff. In order to answer that issue and because it works well with the tab feature I think we could make optional the fact to save the endpoint in your menu. We could still have an history for that endpoint until we close the tab. Of course when quitting the tab we would have a warning inviting us to save this request in the menu. 

> Note : there is a few issues discussing this already but I couldn't find any dedicated topic on this. This feature request isn't to talk about requests history.

**Comment by nijikokun** [comment] 2021-02-11 23:01
Welcome @adrienpayen 👋 

For tabs there is some discussion about leaflets / scratch history, see #1003, this seems to also be something like the temporary requests feature that you mention.

**Comment by adrienpayen** [comment] 2021-02-12 09:47
Hi @nijikokun 👋🏻,
I read and support this feature request but decided to open my own as the main answers were about history and autosave. I wanted to focus on the tab / temporary request part. 

I think history/autosave is compatible with tabs and even temporary requests. 
The way I imagine this is you could have a temporary link in your left menu (maybe written italic to show a difference). If you close this tab without saving it in your collection then this link disappear as well. And history is related to each request anyway.

If we close this issue could we have some answer on https://github.com/Kong/insomnia/issues/1003 ? I'd be happy to take part to the discussion.

**Comment by ThisNoName** [comment] 2021-07-15 19:38
Tabs and no auto save please.  Insomnia is just amazing otherwise

**Comment by filfreire** [comment] 2022-07-25 13:56
Hi @adrienpayen, thanks for reporting this issue! I'm going to close this one as duplicate of #1003.

We'll try to update #1003 as soon as possible. In the meantime feel to report any other issues you come across, or other ideas you have to improve Insomnia!

I'd also like to encourage you and anyone from the community to try to drop by one of our weekly streams (check `#streams` channel on [chat.insomnia.rest](https://chat.insomnia.rest/) for details on how to join, stream happens every Tuesday at around 14:30 UTC).

**Closed as completed by filfreire** 2022-07-25 13:56 UTC
Labels: needs-triage
