### ISSUE TITLE
Require some specific mouse movement when confirming deletions

### ISSUE THREAD

**Issue by teozkr** [getinsomnia/insomnia#184] opened 2017-05-10 22:52 UTC
## Overview

- `Insomnia Version:` 5.0.20
- `Operating System:` Arch Linux amd64

Some mice (I've had several Logitech G600 mice that start doing this after about a year) start interpreting some single-clicks as double-clicks, effectively negating delete confirmation.

## How To Reproduce

- Use a shitty mouse for a few years
- Right-click a request
- Try to click Generate Code
- Miss and accidentally hit delete
- The shitty mouse doesn't debounce correctly, and sends two click events
- The request is gone, oops!

**Comment by dmlittle** [comment] 2017-05-11 01:44
@teozkr what about having a mouse click delay rather than having to move the mouse? I can't reproduce the issue due to lack of a shitty mouse, but I'm guessing the double mouse click happens within 150ms or less from each other. Simply ignoring a second click that happens too quickly after the first one might work without having to change any of the current workflow. 

That being said I'd say, this is not a bug in the software but rather bad UX due to user malfunctioning hardware.

**Comment by gschier** [comment] 2017-05-11 04:53
I agree. @dmlittle's suggestion of adding a delay would _fix_ the problem but will probably cause annoyances for users who want to quickly delete things.

Labeling this issue as a "won't fix", for now.

**Closed by gschier** 2017-05-11 04:53 UTC
