### ISSUE TITLE
Push from Insomnia git is not pushing the unit tests. Only pushes .insomnia/workspace directory with one file

### ISSUE THREAD

**Issue by sajjan10** [getinsomnia/insomnia#4777] opened 2022-05-12 16:55 UTC
### Expected Behavior

In Insomnia after git sync, once user pushes a new git branch then It is not pushing the code related to unit tests into git. However it only pushes one file in .insomnia/workspace directory. 

### Actual Behavior

The complete code related to unit tests should be pushed in git along with .insomnia/workspace folder. 

### Reproduction Steps

Create a new project in insomnia
create a Design document 
create a test suite and a new/multiple test 
sync with git
commit the changes and then push
Expected- All the unit test should be pushed into git.
Actual- Only .insomnia/workspace with one .yml file is pushed and no unit tests are available in git.
[Issue.docx](https://github.com/Kong/insomnia/files/8681153/Issue.docx)
 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.3.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### Installation method

https://github.com/Kong/insomnia/releases/tag/core@2022.3.0

### Last Known Working Insomnia version

2022.3.0

**Comment by filfreire** [comment] 2022-05-13 10:01
Hi @sajjan10, thank you for reporting this!

I wasn't able to reproduce this so far.

For example, I tried for a [brand new repo](https://github.com/filfreire/insomnia-issue-4777), and I'm able to see [the versioned tests there](https://github.com/filfreire/insomnia-issue-4777/tree/master/.insomnia/UnitTest).

Can you kindly double check if you are selecting or able to see the tests when doing a `Commit` on Insomnia, for example:

<img width="778" alt="Screen Shot 2022-05-13 at 10 51 10" src="https://user-images.githubusercontent.com/11976836/168260809-2cc5e9ed-8074-4797-ba89-043fc5dc9f4b.png">

**Comment by filfreire** [comment] 2022-05-13 10:04
Note: I also tried adding new tests to a new branch, and I'm also able to see those:
https://github.com/filfreire/insomnia-issue-4777/commit/120c4089f09214a59b4d9b4815c0607992d122a0

**Comment by sajjan10** [comment] 2022-05-13 11:14
Hi Kong/insomnia,

Can we connect once and I can show it not working in my machine? Please.
I have earlier shared screenshots also.

Regards,
Sajjan

**Comment by filfreire** [comment] 2022-05-16 09:34
Hi @sajjan10,

I would suggest you try and join our Weekly Stream on Tuesdays at 15h30 WEST.

There will be one tomorrow and I believe myself and @dimitropoulos will be there and might be able to help you debug this.

You can find more details about it on our Slack, https://chat.insomnia.rest/, and entering the `#stream` channel.

**Comment by sajjan10** [comment] 2022-05-16 11:55
That would be great help.

I will join. I saw the google calendar and joined the #stream. Where do I
get the meeting/invite URL?

**Comment by filfreire** [comment] 2022-05-23 10:15
Closing this one since it was addressed in the past [Insomnia stream](https://www.youtube.com/watch?v=deNX55AOyyY).

**Closed as completed by filfreire** 2022-05-23 10:15 UTC
Labels: N-author-input, B-bug, S-unverified, insomnia-stream
