### ISSUE TITLE
Support a system wide install on Windows

### ISSUE THREAD

**Issue by hmatt1** [getinsomnia/insomnia#1914] opened 2020-01-28 16:42 UTC
Insomnia currently installs on a per-user basis on Windows. This is a feature request to add the option to install for all users.

This may be related to https://github.com/Kong/insomnia/issues/1756

**Comment by girlpunk** [comment] 2021-05-31 10:26
This is still outstanding

**Comment by filfreire** [comment] 2022-08-12 10:56
Hi @hmatt1 I'm going to go ahead and close this as duplicate of #1756, but I went ahead and marked that one internally as a possible improvement.

**Closed as completed by filfreire** 2022-08-12 10:56 UTC
Labels: needs-triage
