### ISSUE TITLE
Sort order no longer working

### ISSUE THREAD

**Issue by pdfabbro** [getinsomnia/insomnia#6318] opened 2023-08-17 20:55 UTC
### Expected Behavior

When I open my IDE it should show my previous requests in the order I had them in

### Actual Behavior

They opened in a random order and I can't resort them.  The drag and drop as well as the sort button are broken

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Open the IDE and move around some requests/use the sorter and nothing happens

### Insomnia Version

2023.5.3

### What operating system are you using?

Windows

### Operating System Version

windows

### Installation method

windows downloader

### Last Known Working Insomnia version

2023.4.0

**Comment by carlos815** [comment] 2023-08-17 22:04
I'm having that same issue. This might be related, the filter input stopped working as well

**Comment by skipfire** [comment] 2023-08-18 00:14
This is incredibly painful.  All levels of folders and endpoints have had their orders changed and cannot be reordered.

Version: Insomnia 2023.5.3
Build date: 8/16/2023
OS: Windows_NT x64 10.0.22631
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by suchislife801** [comment] 2023-08-18 05:34
Same here. Not only sort order but the Interface font is no longer applying...

All of my ordered API calls are now all.. over.. the place. Documentation missing parts... 

Oh man... I am never turning auto update back on. NEVER. Like.. NEVER. EVER.

Someone please tell me what the last perfectly-fine-should-not-have-been-changed version is.

**Comment by adamrybak** [comment] 2023-08-18 06:25
Same issue for me too.
@suchislife801: bit dramatic don't you think?

**Comment by suchislife801** [comment] 2023-08-18 06:29
No. No I don't think at all. Not at all I don't think. Nope. Not.
I need the version number of the last version that worked.
What is the version number.

**Comment by filfreire** [comment] 2023-08-18 08:31
Duplicate of #6284

**Closed as completed by filfreire** 2023-08-18 08:31 UTC
Labels: B-bug, S-unverified

**Comment by pdfabbro** [comment] 2023-08-18 14:04
Dude, just read the bottom of the issue above - 2023.4.0

**Comment by suchislife801** [comment] 2023-08-18 14:11
## The link. Here is the link to the last working version.

# [2023.4.0](https://github.com/Kong/insomnia/releases/tag/core@2023.4.0)
