### ISSUE TITLE
[Bug] context.app.prompt from workspaceAction

### ISSUE THREAD

**Issue by sesgoe** [getinsomnia/insomnia#2105] opened 2020-05-01 15:26 UTC
I tried to open a prompt from a `workspaceAction`, but no dialog is rendered.

```javascript
module.exports.workspaceActions= [
  {
    label: 'sort-json sort depth',
    icon: 'fa-chevron-right',
    action: async (context, data) => {
      const result = await context.app.prompt('Configure Sort Depth', {
        label: 'sort-json sort depth',
        defaultValue: '1',
        submitName: 'Set',
        cancelable: true
      })
    }
  }
]
```

- Insomnia Version: 7.1.1
- OS: Windows 10

```
{
  "name": "XXXXXXXXXXXXXXXX",
  "version": "1.0.3",
  "main": "index.js",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": ""
  },
  "insomnia": {
    "name": "XXXXXXXXXXXXX",
    "description": "XXXXXXXXXXXXXXXXXX"
  },
  "dependencies": {
    "sort-json": "^2.0.0"
  },
  "devDependencies": {}
}
```

Context: I'm trying to allow a prompt to set a configuration option for my small plugin. Unsure if using API correctly or if actually bug.

`context.app.alert` seems to work with no issues from `workspaceAction`s.

**Comment by gschier** [comment] 2020-05-01 16:54
The prompt api is new and I don't think it's been released yet. Do you see a JS error in the console if you View > Toggle DevTools?

**Comment by sesgoe** [comment] 2020-05-01 17:55
Ah--didn't realize the prompt api was new. I'm assuming you mean new for the `workspaceAction` api? And to answer your question: No, I don't see any errors in the JS Console upon trying to call the `context.app.prompt` function from a `workspaceAction`.

I was looking through issues when I found https://github.com/Kong/insomnia/issues/1520 and figured if it was a year old then the `prompt` api in general was probably pretty well-established by now.

If that's not the case, then no big deal. Was just curious if/why it didn't work.

**Comment by gschier** [comment] 2020-05-01 19:01
My apologies. I was thinking of the `dialog` API, which was just added. It definitely seems like you're using it correctly. Let me try to reproduce it 👍

**Comment by gschier** [comment] 2020-05-01 20:11
Hmm, after testing with the code you posted, I was able to successfully show a prompt in Insomnia 7.1.1. 🤔 

![image](https://user-images.githubusercontent.com/587576/80838162-3dc2c880-8bad-11ea-8a18-96267215e451.png)
![image](https://user-images.githubusercontent.com/587576/80838173-41564f80-8bad-11ea-98ec-25307af1622e.png)

**Comment by gschier** [comment] 2020-05-07 19:14
I'm going to close this for now, as it seems to be working, but please follow up if you continue experiencing problems

**Closed as completed by gschier** 2020-05-07 19:14 UTC
Labels: N-investigation, A-plugin-api, B-bug
