### ISSUE TITLE
[Feature Request] Sub-Sub-"Environments" (for the lack of a better word)

### ISSUE THREAD

**Issue by jostFT** [getinsomnia/insomnia#1906] opened 2020-01-22 18:06 UTC
**Is your feature request related to a problem? Please describe.**
I am using several different keys and ids to fetch tokens. I have always manually added them in through either copy paste or env variables.

**Describe the solution you'd like**
By having a sub-sub-env, I could cycle through private key sub-envs under a public env (say, prod, or dev) - hopefully making the entire process more autonomous. 

**Describe alternatives you've considered**
- to create a key tree in the the base, and then override the id and keys in private prod and dev envs. 
- load them in from a file
- create duplicates of the same function, but use different keys

Thank you so much for this tool, of all the ones I've tried, this is by far the best one :D

**Comment by gschier** [comment] 2020-01-22 19:32
Would you say this is a duplicate of #283?

**Comment by jostFT** [comment] 2020-01-24 14:54
Yes. Specifically, this reply! 😄
https://github.com/Kong/insomnia/issues/283#issuecomment-343169521

**Closed as completed** 2020-01-27 17:18 UTC
