### ISSUE TITLE
VNC on Ubuntu 18.04 get Xlib:  extension "XInputExtension" missing on display

### ISSUE THREAD

**Issue by generatz** [getinsomnia/insomnia#2204] opened 2020-05-20 14:27 UTC
I tried the AppImages version of insomnia and then installed it using apt-get.
In both cases, when launching from command line I get this msg (port omitted):

Xlib:  extension "XInputExtension" missing on display

Workaround:
I discovered that this was a common problem with multiple apps when using VNC.
I found and applied the following solution (thanks @rcarmo):
[https://github.com/microsoft/vscode/issues/3451#issuecomment-227197582](url)
After applying fix, I still see the same warning messages, but insomnia does run.

Ref:
- Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-99-generic x86_64)
- AppImage
- apt-get installed Insomnia 7.1.1

**Comment by kreosus** [comment] 2022-08-09 18:49
Hi @generatz 
Good day and I hope that all is well. Have you tried this on our newest release, available here: https://github.com/Kong/insomnia/releases/tag/core%402022.5.0?

**Comment by wongstein** [comment] 2022-08-17 13:46
Thanks for the workaround!  I'm sure it's helped some people in the past.  I'm going to close this issue for now.  If that stops working, or you feel this issue should be re-opened because it's reproducible with the latest version of Insomnia, please open a new issue.

**Closed as completed by wongstein** 2022-08-17 13:46 UTC
Labels: B-bug, needs-triage
