### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by kamaliamirthalingam1** [getinsomnia/insomnia#5677] opened 2023-01-15 17:56 UTC
### Expected Behavior

Load new request from json

### Actual Behavior

Can't insert key env_4e698cd2df805665c5e3cbbe5f72e9a73be8a233, it violates the unique constraint

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

version 2022.7.2

### Insomnia Version

 2022.7.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise

### Installation method

download from insomnia

**Comment by filfreire** [comment] 2023-01-16 09:55
Hi @kamaliamirthalingam1  thanks for reporting this, closing it as a duplicate of #5617

**Closed as completed by filfreire** 2023-01-16 09:55 UTC
Labels: B-bug, S-unverified
