### ISSUE TITLE
Setup Git Sync for Azure DevOps

### ISSUE THREAD

**Issue by michaelsogos** [getinsomnia/insomnia#2901] opened 2020-12-03 21:49 UTC
Dear,

I tried several ways to configure Git Sync with our company repositories hosted in Azure DevOps, but nothing works.

Insomnia returns always 404 NOT FOUND error.

For testing purpose Azure DevOps offer a free plan with 5 users.
Could i help you in some how to reproduce the error?

Of course i can certify that we don't have any issue with other clients (VS CODE, Visual Studio, SmartGit, Git Kraken, powershell, bash on centos).

**Comment by nijikokun** [comment] 2020-12-03 21:51
What version of Insomnia Designer and Kong Plugin Bundle are you trying to setup sync with?

**Comment by michaelsogos** [comment] 2020-12-04 22:24
Insomnia Designer 2020.4.2
Kong Plugin Bundle i don't how to check it 😄

**Comment by develohpanda** [comment] 2021-02-04 04:46
Closing as duplicate of #2095 as that issue has some more conversation -- thank you for reporting! 🤗

**Closed as completed by develohpanda** 2021-02-04 04:46 UTC
Labels: M-duplicate, A-git-sync
