### ISSUE TITLE
Failed to render error when updating folder via settings

### ISSUE THREAD

**Issue by skipfire** [getinsomnia/insomnia#6340] opened 2023-08-20 19:15 UTC
(Edited by the insomnia team)

When updating a folder, we get the following error:

```
Error: No route matches URL "/organization/org_default-project/project/proj_default-project/workspace/wrk_6960d750243e4e45b7fc0702a527c60e/debug/request-group/fld_07258e4af04146ce84bb9d877cd3a1c0/update"

Error: No route matches URL "/organization/org_default-project/project/proj_default-project/workspace/wrk_6960d750243e4e45b7fc0702a527c60e/debug/request-group/fld_07258e4af04146ce84bb9d877cd3a1c0/update" at Ii 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:31:8269) at Object.Ye [as fetch] 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:30:17838) at Object.submit 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:49:6555) at 
file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:131:22895 at onChange 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/debug-66a2f248.js:35:20580) at Object.Bbe 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:115:9873) at Kbe 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:115:10030) at qbe 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:115:10090) at tA 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:115:31583) at MU 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:115:32001) at 
file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:115:36934 at mk 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:118:36983) at ZB 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:115:9007) at Ay 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:115:33291) at BE 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:115:17414) at sxe 
(file:///C:/Users/{username}/AppData/Local/insomnia/app-2023.5.5/resources/app.asar/index-dc29d08f.js:115:17197) at HTMLBodyElement.sentryWrapped 
(C:\Users\{username}\AppData\Local\insomnia\app-2023.5.5\resources\app.asar\node_modules\@sentry\browser\dist\helpers.js:76:23)
``` 
Version: Insomnia 2023.5.5
Build date: 8/18/2023
OS: Windows_NT x64 10.0.22631
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

### Insomnia Version

2023.5.5

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 22631.2199

### Installation method

Downloaded from Insomnia's website

**Comment by filfreire** [comment] 2023-08-21 09:57
@skipfire check if you have an `L` in the search bar already:

![image](https://github.com/Kong/insomnia/assets/11976836/d28bd89b-60b1-4856-9bac-abccd285b9c7)


As for the other error it's valid bug that seems to happen when we update a folder from its settings.
![image](https://github.com/Kong/insomnia/assets/11976836/b49e800c-641e-48d3-8069-6cb120c14056)

**Comment by filfreire** [comment] 2023-08-21 10:00
Duplicate of #6334

**Closed as completed by filfreire** 2023-08-21 10:00 UTC
Labels: B-bug, S-unverified

**Comment by skipfire** [comment] 2023-08-21 11:41
@filfreire I did have an L in the search bar, not sure when that got there, and I didn't know that the search filter triggered the font, thanks.
