### ISSUE TITLE
Error: URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by unreleased** [getinsomnia/insomnia#4589] opened 2022-03-14 21:12 UTC
### Expected Behavior

Hey, when I have "Automatically encoded special characters in URL" unchecked I seem to be getting an error when using a space " " inside the URL `Error: URL using bad/illegal format or missing URL` - This never used to happen in Insomnia and I've been using it for years, this was the primary reason I've been using insomnia is the ability to easily control and malform requests for my security work. It should still make the request using the unencoded space character.

### Actual Behavior

It returns an error: `Error: URL using bad/illegal format or missing URL`

### Reproduction Steps

Use any URL with a space " " and make sure you have "Automatically encoded special characters in URL" unchecked

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.1

### Installation method

Download via website

**Comment by filfreire** [comment] 2022-03-18 13:17
I'm able to reproduce this issue. @Kong/team-insomnia I'm not entirely sure, but this might be related to the recent changes we did in order to support recent Electron versions.

Here's an example comparison, between `2021.7.2` and `2022.2.0`:
![Screenshot 2022-03-18 at 13 10 57](https://user-images.githubusercontent.com/11976836/159008984-0fd6a1fe-d93c-4763-9621-f04e03e29e00.png)

The version previous to the one @unreleased mentions in the issue description is affected as well, so might be also from the changes we did to bump to Electron 12.




![Screenshot 2022-03-18 at 13 15 52](https://user-images.githubusercontent.com/11976836/159009612-2889dfae-2c08-4d7a-a2f4-e14be49565c1.png)

**Comment by johnwchadwick** [comment] 2022-03-30 18:23
This issue was caused by an update to libcurl. We're working on a workaround for this problem, which should make it into a beta in the near future (#4659)

![screenshot showing whitespace being transferred unencoded to netcat](https://user-images.githubusercontent.com/86682572/160904558-bbf660e9-16ee-4334-a912-5523fb5d5033.png)

**Comment by filfreire** [comment] 2022-03-31 16:35
Hey @unreleased, follow-up to what @johnwchadwick mentioned above, we've released the fix for this issue in our [latest beta (2022.3.0-beta.2)](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0-beta.2).

Thank you for reporting this, feel free to report any other issues you come across 👟 😉

**Closed as completed by filfreire** 2022-03-31 16:35 UTC
Labels: B-bug, S-verified

**Comment by unreleased** [comment] 2022-03-31 16:37
Thanks for the quick response and fix!

**Comment by Rebooting-Me** [comment] 2022-06-26 06:32
It was same for me when I tried to _listen_ to a port on a local node server. Turns out I only did `app.get()` and didn't wrote `app.listen()`. The moment I _listened on the port_, insomnia started working as intended!
Hope that helps!

**Comment by Yoni1984** [comment] 2023-07-14 18:43
fatal: unable to access 'https://github.com:Yoni1984/alx-low_level_programming.git/': URL using bad/illegal format or missing URL  my screen shows me this message what is the problem is there any one who help me
