### ISSUE TITLE
Login using 1Password plugin closes the passphrase modal

### ISSUE THREAD

**Issue by ShadowDaneFoster** [getinsomnia/insomnia#8033] opened 2024-10-01 21:06 UTC
### Expected Behavior

1. Launch the app
2. Login via browser
3. Use the app

### Actual Behavior

Insomnia v10.0.0:
 

1. I launch the app
2. It displays the login UI
3. I select my login option, SSO
4. A browser tab opens that asks for my passphrase
5. The “Authorizing Insomnia” modal displays in the local app
6. I login in the browser
7. Nothing changes in the local app. I’m stuck on the “Authorizing Insomnia” modal
8. In the web app I click on the Organization I want to work with
9. It opens a new tab that once again asks for my passphrase
10. Still stuck on the “Authorizing Insomnia” modal in the local app
11. Rinse/repeat

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.0.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.7

### Installation method

download from Insomnia

### Last Known Working Insomnia version

9.3

**Comment by subnetmarco** [comment] 2024-10-02 00:31
The team is looking into this.

**Comment by robswc** [comment] 2024-10-02 16:13
Have a similar issue.  Attempting to sign up and the email isn't being sent.  I've tried clicking "resend" and checking junk folder.

**Comment by subnetmarco** [comment] 2024-10-03 01:42
This should have been fixed, there were issues with our email provider. Please retry.

**Comment by ShadowDaneFoster** [comment] 2024-10-03 12:59
This has NOT been fixed for me! The bug I'm reporting has nothing to do with email so I have no idea why my issue is being closed when I never reported any email issue. I've included a screen recording that shows that my bug has not been fixed. Thank you.

https://github.com/user-attachments/assets/bec76a30-da0d-43db-9873-e4639170c62b

**Comment by subnetmarco** [comment] 2024-10-08 09:49
Thanks for the video, this makes it clear. I will reopen this issue. You should see this dialog which is clearly not showing:

![Screenshot 2024-10-08 at 3 20 25 PM](https://github.com/user-attachments/assets/4a3a70fb-70d1-4f2f-b542-659f46cd801c)

**Comment by filfreire** [comment] 2024-10-08 09:56
@ShadowDaneFoster would you mind attempting to fill in the passphrase (e.g. copying it from somewhere else) instead of using the 1Password browser plugin - and see if the issue still happens?

**Comment by notjaywu** [comment] 2024-10-08 10:55
Duplicate of #8047

**Comment by pavkout** [comment] 2024-10-08 13:04
@ShadowDaneFoster It should be okay right now, can you please confirm it?

**Comment by ShadowDaneFoster** [comment] 2024-10-08 13:10
@pavkout Confirmed. I got the work-around from @notjaywu on #8047.

**Comment by filfreire** [comment] 2024-10-08 13:14
Checked now and it's fixed, clicking the 1pw icon should no longer close the model.

Closing this issue.

**Closed as completed by filfreire** 2024-10-08 13:14 UTC
Labels: B-bug, S-unverified

**Comment by pavkout** [comment] 2024-10-08 13:17
@ShadowDaneFoster You no longer need to do the workaround, it should be fixed now and you can click the 1password button without closing the modal.
