### ISSUE TITLE
Search Lagging and only highlight

### ISSUE THREAD

**Issue by arifnurdiansyah92** [getinsomnia/insomnia#6339] opened 2023-08-20 14:53 UTC
### Expected Behavior

In the previous version (before 5.2, I believe) the search is fast and only show request that we search.

### Actual Behavior

As you can see here, it's only highligh it
![image](https://github.com/Kong/insomnia/assets/28295027/0b1b3d26-78c7-4673-b22f-aa65a2dac240)

### Reproduction Steps

1. Search something
2. Check the list

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### Installation method

Auto Update

### Last Known Working Insomnia version

2023.5.2 Beta

**Comment by naimmalek** [comment] 2023-08-21 04:53
Same issue [Search is not working]


```
Version: Insomnia 2023.5.5
Build date: 8/19/2023
OS: Darwin arm64 22.5.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64
```

**Comment by CrownTsui** [comment] 2023-08-21 06:21
Same issue，only highlight.

**Comment by namelessone667** [comment] 2023-08-21 06:22
same here, since version 2023.5.0

my current version:
Version: Insomnia 2023.5.5
Build date: 18. 8. 2023
OS: Windows_NT x64 10.0.19045
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by filfreire** [comment] 2023-08-21 06:54
duplicate of https://github.com/Kong/insomnia/issues/6288

**Closed as completed by filfreire** 2023-08-21 06:54 UTC
Labels: B-bug, S-unverified
