### ISSUE TITLE
various problems, preference page and broked fonts

### ISSUE THREAD

**Issue by KinG-InFeT** [getinsomnia/insomnia#2854] opened 2020-11-20 11:08 UTC
**Describe the bug**
click on preference all page white and fonts broked

**To Reproduce**
1. Go to Application
2. Click on Preference
3. See error

**Expected behavior**
Page totally white

**Screenshots**
![image](https://user-images.githubusercontent.com/193969/99793463-03a91c00-2b29-11eb-959e-0ae0e39c0f17.png)
![image](https://user-images.githubusercontent.com/193969/99793504-14599200-2b29-11eb-9eb9-0b673e2feb49.png)

**Desktop (please complete the following information):**
 - OS: Fedora 33 (latest release)
 - Installation Method: snap
 - App Version: 2020.4.2

**Additional context**

**Comment by johanhammar** [comment] 2020-11-20 11:29
Duplicate of https://github.com/Kong/insomnia/issues/2707

**Comment by KinG-InFeT** [comment] 2020-11-26 14:52
i run insomnia in debug mode
```
└─ $ ▶  insomnia --enable-debug
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
15:51:57.978 › Running version 2020.4.2
Error org.freedesktop.DBus.Error.Failed: cannot find snap for connection: not supported
Gtk-Message: 15:51:58.231: Failed to load module "pk-gtk-module"
Gtk-Message: 15:51:58.240: Failed to load module "pk-gtk-module"
15:51:58.473 › [fix] Running database repairs
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
15:51:58.744 › [db] Initialized DB at /home/vluongo/snap/insomnia/109/.config/Insomnia/insomnia.$TYPE.db
15:51:58.745 › Init responses DB
15:51:58.746 › [localstorage] Initialized at /home/vluongo/snap/insomnia/109/.config/Insomnia/localStorage
15:51:59.001 › [main] Loading file:///snap/insomnia/109/resources/app.asar/renderer.html
15:51:59.032 › [ga] Non-interactive General, Launched, 2020.4.2
15:51:59.053 › [ga] Queued event [
  { name: 't', value: 'event' },
  { name: 'ec', value: 'General' },
  { name: 'ea', value: 'Launched' },
  { name: 'ni', value: '1' },
  { name: 'el', value: '2020.4.2' }
]
15:51:59.533 › [updater] Updater not running platform=linux dev=false
(node:60499) Electron: Loading non-context-aware native module in renderer: '/run/user/1000/snap.insomnia/.org.chromium.Chromium.iA8YwK'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:60499) Electron: Loading non-context-aware native module in renderer: '/run/user/1000/snap.insomnia/.org.chromium.Chromium.UuuxBf'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:60499) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Fontconfig warning: FcPattern object weight does not accept value [0 205)


```

**Closed as completed** 2022-12-13 16:48 UTC
Labels: O-linux, needs-triage
