### ISSUE TITLE
[Feature Request] Global Authentication (Workspace level)

### ISSUE THREAD

**Issue by 0xbaadf00d** [getinsomnia/insomnia#507] opened 2017-10-09 08:10 UTC
- Insomnia Version: 5.8.4
- Operating System: Windows 10 Professional 64-bit

## Details

Hello,

It could be nice to have ability to set authentication at the workspace level rather than method level. In our company, we are 1 workspace = 1 API. it's "harassing" to have to manually click on "refresh" button  to get new token for all methods when we use it.

Some API are a lot of method (around 80 - 100), it could be smarter to have a workspace level authentication rather than configure auth for each methods. Of course we can use "variable" but we always have to use it on all methods...

Another option could be to add option to tell to Insomnia to automatically refresh token when something goes wrong...

Sincerely.

**Comment by gschier** [comment] 2017-10-09 19:23
Hi @0xbaadf00d,

Thanks for taking the time to write in! This topic has been discussed broadly in #330 if you want to take a look. 

However, I've also been thinking of adding a `key` parameter to the OAuth settings which would be user-configurable. The idea being that specifying the same `key` between multiple requests would allow them to share the same tokens instead of each request having its own token storage. Let me know if you think this would be a good idea.

_Duplicate of #330_

**Comment by gschier** [comment] 2017-10-10 17:55
Going to close this one for now as a duplicate of #330

**Closed by gschier** 2017-10-10 17:55 UTC
