### ISSUE TITLE
Latest version shows error Render Failure: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by bensmithbdesigned** [getinsomnia/insomnia#6824] opened 2023-11-13 17:45 UTC
On opening the current version (see details):
Version: Insomnia 8.4.1
Build date: 11/13/2023
OS: Darwin arm64 22.2.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64

The app won't load up, instead shows the error:
`Render Failure: Cannot read properties of undefined (reading 'match')`

Screenshow:
![Screenshot 2023-11-13 at 17 43 38](https://github.com/Kong/insomnia-docs/assets/56269341/89fddb16-0d99-44ec-b1c3-853b7f8794cf)

Have tried this after reboot, using a VPN (incase there's a net connection/block issue).

**Comment by jlazo-aptitude** [comment] 2023-11-15 15:52
Also experiencing the same thing
![Screenshot 2023-11-15 at 9 52 19 AM](https://github.com/Kong/insomnia-docs/assets/109173624/62ebb5be-1875-4884-8374-aa006e5d4ba4)

**Comment by filfreire** [comment] 2023-11-16 10:15
closing as duplicate of #6801

**Closed as completed by filfreire** 2023-11-16 10:15 UTC
