### ISSUE TITLE
[FEATURE REQUEST] Save OpenAPI as file in local file system

### ISSUE THREAD

**Issue by prakashm1** [getinsomnia/insomnia#2611] opened 2020-09-14 17:57 UTC
Insomnia needs to work with OpenAPI specs in the local file system. Currently it keeps them in an internal format only.
This has several problems:

1. The specs are not useable outside of Insomnia Designer.
1. One cannot reference definitions from other specs. Each spec has to be entirely self-contained.

It would be much simpler and useful to work with spec yaml's in local file system instead.

**Comment by shortwavedave** [comment] 2020-12-05 00:03
Is there any way to just grab the openapi yaml besides copy pasting from the ui?

**Comment by filfreire** [comment] 2022-10-31 17:42
Closing as duplicate of #1638

**Closed as completed by filfreire** 2022-10-31 17:42 UTC
Labels: C-improvement, S-verified
