### ISSUE TITLE
[Bug] Can't move request inside empty folder

### ISSUE THREAD

**Issue by ddesna** [getinsomnia/insomnia#1487] opened 2019-05-09 07:55 UTC
- Insomnia Version: 6.5.1
- Operating System: Windows 10

## Details

After updating to 6.5.1 version I can't move request inside empty folder. 
Steps to reproduce:
1. Create new empty folder
2. Try to move some request inside folder created on previous step

If some request is already exist in folder, other request could be moved inside.

**Comment by gschier** [comment] 2019-05-09 16:40
Duplicate of #1486

**Closed by gschier** 2019-05-09 16:40 UTC
