### ISSUE TITLE
Have you ever tested Insomnia under Windows?

### ISSUE THREAD

**Issue by wlad** [getinsomnia/insomnia#2384] opened 2020-07-10 14:45 UTC
**What is your question?**
Have you ever tested Insomnia under Windows? 

Usability is a nightmare. Copy & Paste seems to be ignored in all input fields. Can't remember that I had that issue under Linux.

I had to delete the app and install the orange one (although I don't like it at all)

**Comment by DouglasAndre25** [comment] 2020-07-10 15:01
i'm got the same problem

**Comment by Heisenberg87** [comment] 2020-07-10 16:20
I've got the same issue, the issue is to do with the new update(2020.3.0)

**Comment by rharkrader** [comment] 2020-07-10 16:38
I don't think this latest update was tested at all. Same issue on a Mac.

**Comment by nijikokun** [comment] 2020-07-10 17:25
Duplicate of #2377

**Closed as completed by nijikokun** 2020-07-10 17:25 UTC
Labels: C-question
