### ISSUE TITLE
[Feature Request] Publish a windows ZIP version

### ISSUE THREAD

**Issue by jeanmatthieud** [getinsomnia/insomnia#602] opened 2017-11-15 16:11 UTC
Insomnia is a great tool.
Sadly, in corporate environment, it's often impossible to get admin rights to install a software.

Is it possible to build a ZIP version of Insomnia ?

**Comment by gschier** [comment] 2017-11-15 16:14
Closing this as a duplicate of #431 

You can follow that issue and/or leave a comment if you'd like 👍

**Closed by gschier** 2017-11-15 16:14 UTC
