### ISSUE TITLE
Graphql mutation or query selection box will not auto fetch every time click into the file.

### ISSUE THREAD

**Issue by stevelee861** [getinsomnia/insomnia#5536] opened 2022-12-16 05:18 UTC
### Expected Behavior

1. click into a GraphQL file,
2. select mutation or query that need to send,
3. click send
4. preview return.

### Actual Behavior

1. click into a GraphQL file, 
<img width="236" alt="image" src="https://user-images.githubusercontent.com/120702585/208027400-11aa72e8-a884-4010-9312-5d67b1a2c953.png">

2. selection box disable.
<img width="187" alt="image" src="https://user-images.githubusercontent.com/120702585/208027445-12f6118c-020d-4a14-b38c-5fed5d159ace.png">

3. edit the GraphQL file (only enter a whitespace)
4. the selection box active.

5. able to select mutation or query
<img width="225" alt="image" src="https://user-images.githubusercontent.com/120702585/208027521-cee83fca-3727-4a23-80ca-0573d8eb863a.png">

6. click send 
7. preview return

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

demo:

![insomnia-issue-demo](https://user-images.githubusercontent.com/120702585/208028526-e93b5a0c-9ca9-41e4-aa1a-5adcf18290b7.gif)

_No response_

### Insomnia Version

2022.7.0

### What operating system are you using?

macOS

### Operating System Version

macOS 13.0

### Installation method

download from insomnia.rest

**Comment by jackkav** [comment] 2022-12-16 09:20
Thank you for the report, the fix will be in the next beta.

**Closed as completed by jackkav** 2022-12-16 09:20 UTC
Labels: B-bug, S-unverified

**Comment by chabou** [comment] 2022-12-26 10:26
Sorry to hijack this issue, but this is related.

Is it attended to not change the selected query/mutation on focus ?
This is a breaking change behaviour. Due to this I sent some unwanted mutation on production 😱 
Please reconsider this change if this is not a bug.
