### ISSUE TITLE
UI Blocking issue - Unuseable Insomnia

### ISSUE THREAD

**Issue by iqoOopi** [getinsomnia/insomnia#5364] opened 2022-11-01 15:47 UTC
### Expected Behavior

No UI Block

### Actual Behavior

![image](https://user-images.githubusercontent.com/46897552/199276117-456d4f18-cf6c-4f9a-a666-293004a7ac9f.png)
This url prop appears from time to time and won't disappear, have to restart Insomnia, basically makes the software unuseable

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.6.0

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 10 Pro Version	20H2 Installed on	‎7/‎8/‎2021 OS build	19042.1706 Experience	Windows Feature Experience Pack 120.2212.4170.0

### Installation method

download from website

**Comment by jackkav** [comment] 2022-11-01 16:24
Thanks for the issue, and sorry for the inconvenience. We are working on a simplified CodeMirror abstraction to eliminate issues like this one. Please bear with us. 🙏

**Comment by iqoOopi** [comment] 2022-11-01 16:57
> Thanks for the issue, and sorry for the inconvenience. We are working on a simplified CodeMirror abstraction to eliminate issues like this one. Please bear with us. 🙏

Thanks @jackkav , do you know is there a way to disable this prop (is it an autocomplete?)

**Comment by jackkav** [comment] 2022-11-02 08:00
There is no way currently to disable the ctrl+space autocomplete dropdown. In normal cases it is dismissible with Esc, Tab or selecting a value. I hope you will consider joining our beta channel, where this issue should be resolved.

**Comment by filfreire** [comment] 2022-11-02 10:14
Duplicate of #4531

**Closed as completed by filfreire** 2022-11-02 10:14 UTC
Labels: B-bug, S-unverified

**Comment by iqoOopi** [comment] 2022-11-02 14:44
@jackkav Thanks, how can I join the beta channel?

**Comment by jackkav** [comment] 2022-11-02 15:51
<img width="965" alt="image" src="https://user-images.githubusercontent.com/3679927/199537027-61e8a561-36e3-4e4e-840f-073dfbd0dfc2.png">
