### ISSUE TITLE
Unable to Perform manual git clone with Azure Repos

### ISSUE THREAD

**Issue by santitigaga** [getinsomnia/insomnia#6540] opened 2023-09-20 16:29 UTC
### Expected Behavior

The git clone command should clone the repository without any issues.

### Actual Behavior

When attempting to perform a manual git clone operation with Azure Repos, I encountered some difficulties. It seems that the process is not straightforward, and I'm unable to clone the repository successfully.

This is the error.

> HTTP Error: 404 Not Found, TF401019: The Git repository with name or identifier <REPOSITORY_NAME>git does not exist or you do not have permissions for the operation you are attempting.

Whatever, When I create a new collection and try to sync with Git this works correctly.

### Reproduction Steps

1. Open Insomnia
2. Select `Git clone` option
3. Select `Git` Tab
4. Introduce Git URI (https), Author Name, Author Email, username and 
5. Press `Clone` button

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

- Operating System:  macOS
- Git Version: 2.39.1

### Insomnia Version

2023.5.8

### What operating system are you using?

macOS

### Operating System Version

Darwin Kernel Version 21.6.0

### Installation method

insomnia.rest

**Comment by filfreire** [comment] 2023-09-27 09:45
duplicate of #6484

**Closed as completed by filfreire** 2023-09-27 09:45 UTC
Labels: B-bug, S-unverified
