### ISSUE TITLE
Bulk Edit For Headers Not Working

### ISSUE THREAD

**Issue by muratbozkurt35** [getinsomnia/insomnia#2379] opened 2020-07-10 10:44 UTC
When i change something in bulk edit it is not doing anything. Only way the change headers is changing from regular edit. 

**To Reproduce**
1. Open imsomnia
2. Open a request (mine is post) 
3. Change headers from bulk edit.
4. Close insomnia
5. Open insomnia
> change is gone

4. send request
5. look at the headers from webservice
> change is gone

it wasnt like this. what changed?

**Comment by muratbozkurt35** [comment] 2020-07-10 10:52
i did an export and looked at json data.

about:
>(and i found out about now, i cant define a header that name starts with lower character, if you want i can create new issue)

it is not it is. even i deleted those headers. they are still in json file. so you may prevent dublication of headers that not supposed to be exist.

**Comment by muratbozkurt35** [comment] 2020-07-10 11:14
i found it. i cant paste top of a value of a header in bulk edit. 
in default condition headers stay like this 
>header: oldvalue

but after i highlighted the value and paste over it. next what i should do is to make the change applied is deleting the space

>header: newvalue

>header:newvalue

then i change to regular edit and come back it turns into 

>header: newvalue 

 this way its working.

**Comment by develohpanda** [comment] 2020-07-10 11:48
Hi @muratbozkurt35! Looks like you've got a workaround and confirmed it to be the copy-paste bug I mentioned in #2377. I'll close this issue in favor of that, and we'll look to get a fix out ASAP!

**Closed as completed by develohpanda** 2020-07-10 11:48 UTC
