### ISSUE TITLE
Insomnia 2021.2.0 doesn't use local dns server

### ISSUE THREAD

**Issue by xwillq** [getinsomnia/insomnia#3234] opened 2021-03-24 04:53 UTC
**Describe the bug**
Latest version of insomnia doesn't use local dns server if there are any other options

**To Reproduce**
1. Configure local dns server
2. Configure local dns server as preferred and some other server as alternative (for example 1.1.1.1)
3. Make a request to the domain which should be resolved with local dns server
4. See `Error: Couldn't resolve host name`
5. If you capture traffic with wireshark or check logs of local dns server, you can see that it didn't receive any queries

**Expected behavior**
Insomnia uses local dns server for dns lookups

**Screenshots**
DNS lookup when making request with Insomnia 2021.1.1
![image](https://user-images.githubusercontent.com/38136135/112256005-e7afb580-8c95-11eb-95f5-48ec6e1bef50.png)

DNS lookup when making request with Chrome
![image](https://user-images.githubusercontent.com/38136135/112256343-3bba9a00-8c96-11eb-8323-0360c94e1e00.png)

DNS lookup when making request with Insomnia 2021.2.0
![image](https://user-images.githubusercontent.com/38136135/112257432-635e3200-8c97-11eb-8f1e-fc379517e177.png)

**Desktop:**
 - OS: Windows 10
 - Installation Method: Installer from github releases
 - App Version:  2021.2.0

**Additional context**
If you remove all dns servers except the localhost, then insomnia will use localhost.

**Comment by illuz** [comment] 2021-03-24 07:21
The same problem after upgrade to 2021.2.0 today.

**Comment by DMarby** [comment] 2021-03-24 13:03
Hi @xWillQ,

Thank you for reporting this! We have confirmed the issue, and believe it's likely due to our recent upgrade of the `node-libcurl` dependency for the `2021.2.0` release, which changed what DNS resolver backend is being used.

We are looking into ways to address it, and hope to get it fixed as soon as possible.

**Comment by shanegray** [comment] 2021-03-24 14:08
Is there a workaround for the time being? Or a way to downgrade?

**Comment by jogat** [comment] 2021-03-24 14:39
@shanegray
> Is there a workaround for the time being? Or a way to downgrade?

Go to: [https://github.com/Kong/insomnia/releases/tag/core%402021.1.1](https://github.com/Kong/insomnia/releases/tag/core%402021.1.1)

**Comment by nijikokun** [comment] 2021-03-24 17:08
Update: we have identified that it is indeed a regression from the update to `node-libcurl` that impacts all platforms and we are working with the maintainer to get a build out [sometime tonight or tomorrow morning](https://github.com/JCMais/node-libcurl/issues/280#issuecomment-805969502) that doesn't use `c-ares` for DNS to fix the issue.

In the meantime we have pulled 2021.2 from the auto-update api to reduce the impact on users, for those who are impacted please download the previous release mentioned [here](https://github.com/Kong/insomnia/issues/3234#issuecomment-805876205).

**Comment by nijikokun** [comment] 2021-03-24 21:09
Update: new build for `node-libcurl` is up, we are preparing a new patch release for Insomnia which is going into testing and will be released shortly. Thank you to everyone who was a part of making this happen. ❤️

Test build can be [found here](https://github.com/Kong/insomnia/releases/tag/core%402021.2.1).

**Comment by nijikokun** [comment] 2021-03-24 22:29
Patch release is now live! Closing! 🙌 

You can download the latest release [here](https://insomnia.rest/download).

**Closed as completed by nijikokun** 2021-03-24 22:29 UTC
Labels: D-node-libcurl, B-bug, S-verified, P-critical, S-shipped
