### ISSUE TITLE
[Feature Request][Installation]Custom installation path in Windows

### ISSUE THREAD

**Issue by T-One** [getinsomnia/insomnia#998] opened 2018-06-22 10:35 UTC
Hello,

please add the possibility to install Insomnia on windows in a custom path instead of %appdata%
In enterprise environments with binary signation and executable lockdown on paths (like appsense) it's not possible to run software from %appdata%.

Kind Regards
T-One

**Comment by gschier** [comment] 2018-06-22 16:33
Thanks for submitting this @T-One! 

This is a duplicate of an older issue https://github.com/getinsomnia/insomnia/issues/683

**Closed by gschier** 2018-06-22 16:33 UTC
