### ISSUE TITLE
Cannot switch to ok 200 responses from `response history` pane

### ISSUE THREAD

**Issue by javaherisaber** [getinsomnia/insomnia#3969] opened 2021-08-29 09:54 UTC
**Describe the bug**
When we have multiple responses in the response history pane, we're unable to switch to other ok 200 responses
if there is at least one non-ok response there.

**To Reproduce**
1. Send a request with a status code of 200
2. Send another request with a status code of 400
3. Open the response history pane and try to switch to the previous response (200)
4. It is not switching to 200 response, instead just refreshes 400 response in response pane

**Expected behavior**
Open any response from the response history pane, regardless of status code

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: .exe file
 - App Version: 2021.5.0

**Additional context**
Version: Insomnia 2021.5.0
Release date: 8/26/2021
OS: Windows_NT x64 10.0.19042
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0

**Comment by develohpanda** [comment] 2021-08-30 07:16
Thanks for reporting this! It seems similar to the bug fixed by https://github.com/Kong/insomnia/pull/2735 🤔 Will validate when looking at that PR.

**Comment by develohpanda** [comment] 2021-08-31 05:56
@javaherisaber - I was unfortunately not able to reproduce this exact bug. Could you please share a screenshot of your response history dropdown, identifying which items you are clicking for this bug to occur? Please make sure to remove any sensitive information like URLs 😄

**Comment by javaherisaber** [comment] 2021-08-31 09:56
@develohpanda The active response status code is 400 and I want to switch to 200 status code, It just remains at 400 status code!

![image](https://user-images.githubusercontent.com/29440700/131482309-94b32197-ceae-4a2b-b1f0-4610e8d51be8.png)

**Comment by develohpanda** [comment] 2021-08-31 11:06
Awesome! Thanks for sharing the screenshot, that helps! This bug has just been fixed by #2735 merged in today, so I will mark this issue as closed, and it will be published with the next major release (no timeframe yet, but next month or two as a guess) 😊

**Closed as completed** 2021-08-31 11:07 UTC
Labels: B-bug, S-unverified
