### ISSUE TITLE
After atuo-update to 2023.5.0, I cannot execute existing "request".

### ISSUE THREAD

**Issue by g-industrialist** [getinsomnia/insomnia#6281] opened 2023-08-15 06:25 UTC
### Expected Behavior

After atuo-update to 2023.5.0, I cannot execute existing "request".

### Actual Behavior

TypeError: Cannot read properties of undefined (reading 'name') at hde (file:///xxxx/AppData/Local/insomnia/app-2023.5.0/resources/app.asar/index-13ca93ca.js:84:34818) at async X8 (file:///xxxx/AppData/Local/insomnia/app-2023.5.0/resources/app.asar/index-13ca93ca.js:84:33181) at async Module.Ie (file:///xxxx/AppData/Local/insomnia/app-2023.5.0/resources/app.asar/request-7bcb48dc.js:1:7088) at async Sg (file:///xxxx/AppData/Local/insomnia/app-2023.5.0/resources/app.asar/index-13ca93ca.js:31:3691) at async Ke (file:///xxxx/AppData/Local/insomnia/app-2023.5.0/resources/app.asar/index-13ca93ca.js:30:18467)

### Reproduction Steps

1. go to existing request
2. execute request
![230815-1oy-HKIWS173-0821](https://github.com/Kong/insomnia/assets/40657526/52124464-c4a0-4993-a5f8-27a00b259543)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 22H2

### Installation method

download from insomnia

**Comment by jackkav** [comment] 2023-08-15 06:39
Duplicate of #6277

**Closed as completed by jackkav** 2023-08-15 06:39 UTC
Labels: B-bug, S-unverified
