### ISSUE TITLE
Duplicate a request erases the URL in the original request

### ISSUE THREAD

**Issue by ppazos** [getinsomnia/insomnia#4974] opened 2022-07-16 00:20 UTC
### Expected Behavior

It shouldn't erase the URL

### Actual Behavior

When I duplicate a request and change the name of the new request, I go back to the original request and the URL is empty, this happens from time to time but it's annoying.

### Reproduction Steps

Can't  reproduce all the times I duplicate a request. Some times is just:

1. CTRL+D on an existing request
2. set name
3. execute new request
4. go back to original request
5. URL is empty

It happens from time to time, today it happened twice.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Insomnia 2022.4.2

### Insomnia Version

2022.4.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux Mint 19.3

### Installation method

apt

**Comment by endo64** [comment] 2022-07-19 07:59
I just found when it happens!
If you click on the URL bar and then press CTRL-D to duplicate, URL is deleted!

![image](https://user-images.githubusercontent.com/840604/179698513-81b0fa0b-cdf3-431d-b5cc-17cf49d6f55c.png)

If you click on the request on the left panel and then press CTRL-D, URL is not deleted.

Note that when you first click on the request on left panel URL bar will get focus automatically, you need to click the request twice to prevent that.

**Comment by ppazos** [comment] 2022-07-19 13:51
Yes, the issue is when a request is clicked, the URL input gets focused. Then the flow of clicking on a request and doing CTRL+D will always erase the URL.

**Comment by filfreire** [comment] 2022-07-19 16:26
Hi @ppazos (and @endo64), thank you so much for reporting this!

We had found this one internally as well, and @gatzjames has given a shot at fixing it with https://github.com/Kong/insomnia/pull/4917 and https://github.com/Kong/insomnia/pull/4937

We'll update you here once a definitive fix is merge. In the meantime feel free to report any other issues! 🙇

**Comment by hunterwilhelm** [comment] 2022-07-26 16:44
I'm having this issue too
MacOS

**Comment by filfreire** [comment] 2022-08-04 06:42
Heads up closing this one as duplicate of #4766

**Closed as completed by filfreire** 2022-08-04 06:42 UTC
Labels: B-bug, S-verified

**Comment by endo64** [comment] 2022-10-03 10:06
This and related issues are closed, PRs are merged, but the latest version doesn't have the fix yet (v2022.6.0) 🥲
CTRL-D still deletes the URL.

**Comment by filfreire** [comment] 2022-11-02 17:37
Fix for this is available on 2022.7.0 beta versions, you can download latest iteration of beta, [2022.7.0-beta.4](https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.4)
