### ISSUE TITLE
Insomnia reports "Cannot read property 'invoke' of undefined" when issuing a simple request

### ISSUE THREAD

**Issue by brucegodden** [getinsomnia/insomnia#4294] opened 2021-12-09 11:49 UTC
### Expected Behavior

I expect Insomnia to make the request specified. In particular I expect it to prompt me to log in so it can fetch an OAuth2 token.

### Actual Behavior

It reports the error "Cannot read property 'invoke' of undefined". This happens before I get prompted to log in to get the OAuth2 token required to call the API.

### Reproduction Steps

Open Insomnia.
Select a simple request. ({{ _.api }}{{ _.service }}/v1/status)
Select an environment. (It defines the variables in the request above.)
Click send.
The error is reported before I expect to be prompted to log in to get an OAuth2 token.
The OAuth2 token screen uses environment variables like {{ _.keycloakAuthUrl }} in most of its fields. These are defined in the base environment.
This sequence was working yesterday before Insomnia upgraded itself.
Sorry I can't be more specific but it seems to me that Insomnia is just not working at all.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.7.1

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 10 Pro Version	21H1 Installed on	‎07/‎06/‎2021 OS build	19043.1348 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Installation method

It was an upgrade downloaded by Insomnia itself, I believe.

### Last Known Working Insomnia version

I believe the previous version installed was 2021.4.1 (from the contents of my Downloads directory)

**Comment by ghost** [comment] 2021-12-09 11:56
I came here to report this same issue.  I also get it when I submit a request that requires OAuth 2.0 and the token is not present or the token has expired.  I also have a lot of environment variables set in the OAuth tab for the URLs, client ID, etc.

If I request the token manually with the Fetch Tokens or Refresh Token button before I send the request, the request goes through without the error.  

This was also working for me before the 2021.7.1 update.

Let me know if you need me to test anything.

Chris

**Comment by simonrolfmore** [comment] 2021-12-09 18:17
Same issue here: all our endpoints that use OAuth 2.0 fail if the token isn't manually refreshed and up to date. 2021.6.0 works fine. I get a mix of the above error and hangs, so I suspect some internal state breaks when the error occurs.

**Comment by develohpanda** [comment] 2021-12-09 22:04
Hi all, apologies for any inconvenience this has caused. We have just released https://github.com/Kong/insomnia/releases/tag/core%402021.7.2 hopefully addressing these issues. I'll close this issue as resolved, but please report back in case this is not resolved and I will reopen! Thank you for your patience 🙏🏽

**Closed as completed** 2021-12-09 22:04 UTC
Labels: B-bug, S-verified

**Comment by gerald637** [comment] 2021-12-10 14:08
@develohpanda  The same issue existing in Inso CLI 2.4.1.  It working in 2.4.0

**Comment by develohpanda** [comment] 2021-12-13 07:46
Hi @gerald637, thanks for letting us know. What are you doing specifically with inso to hit this issue, could you please share some reproduction steps? Because this issue seems to be related with OAuth 2; is inso running a unit test which invokes a request containing OAuth 2 information?

**Comment by leomarcamargo** [comment] 2021-12-29 21:46
@develohpanda  The problem persists in the 2021.7.2, 2021.7.3 versions. I downgraded to 2021.5.3 version and there was no problem (do not make any changes after this action for everything to work).
