### ISSUE TITLE
CURL parsing is not working as expected

### ISSUE THREAD

**Issue by aabuhijleh** [getinsomnia/insomnia#6766] opened 2023-11-07 16:03 UTC
### Expected Behavior

This curl should be parsed correctly same as Postman

```shell
curl --location 'https://example.com' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxxx' \
--data '{
    "test_prop": true
}'
```

<img width="1011" alt="image" src="https://github.com/Kong/insomnia/assets/42934634/29578960-58e2-431e-af1a-8b4ee28caceb">

With the headers in the Curl being respected, the request body, and method should be POST

### Actual Behavior

Parsed insomnia request has the following issues:
* Method is GET not POST
* No request body
* No headers

### Reproduction Steps

1. Add a new request using "From Curl"
<img width="409" alt="image" src="https://github.com/Kong/insomnia/assets/42934634/8b41755e-faaa-4e1e-8504-cb4330eed518">

2. Use this

```shell
curl --location 'https://example.com' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxxx' \
--data '{
    "test_prop": true
}'
```

3. Notice that parsed insomnia request has the following issues:
* Method is GET not POST
* No request body
* No headers

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

If I change the Curl to this

```shell
curl --request POST \
  --url https://example.com \
  --header 'Authorization: Bearer xxxx' \
  --header 'Content-Type: application/json' \
  --data '{
	"test_prop": true
}'
```

It works as expected now, but I think it would be much better if the parsing was as robust as Postman

### Insomnia Version

8.3.0

### What operating system are you using?

macOS

### Operating System Version

Darwin arm64 23.0.0

### Installation method

https://insomnia.rest

**Comment by TakesTheBiscuit** [comment] 2023-11-08 21:09
This is a dupe of https://github.com/Kong/insomnia/issues/6755
and there's a PR for that here https://github.com/Kong/insomnia/pull/6774
HTH

**Closed as not planned** 2023-11-10 08:48 UTC
Labels: B-bug, S-unverified

**Comment by aabuhijleh** [comment] 2023-11-10 08:58
Working well with the latest version, thanks
