### ISSUE TITLE
MacOS improper icon size in dock

### ISSUE THREAD

**Issue by zutritt** [getinsomnia/insomnia#5939] opened 2023-05-03 10:33 UTC
### Expected Behavior

Properly sized icon in dock

### Actual Behavior

![](https://i.imgur.com/SaNT5Vz.png)

### Reproduction Steps

1. Open Insomnia
2. See this bug

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2023.2.0
Build date: 4/26/2023
OS: Darwin arm64 22.4.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64

### Insomnia Version

2023.2.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.3.1 (22E261)

### Installation method

insomnia.rest

**Comment by filfreire** [comment] 2023-05-03 10:46
duplicate of #5922

**Closed as completed** 2023-05-03 10:47 UTC
Labels: B-bug, S-unverified
