### ISSUE TITLE
NTLM Authentication issue in Insomnia 9.3.2

### ISSUE THREAD

**Issue by ivancho979** [getinsomnia/insomnia#7698] opened 2024-07-10 16:06 UTC
### Expected Behavior

Expected is that:

2. URL preview value is not cleared when disable NTLM auth
3. No Request Failure:  'TypeError: Cannot convert undefined or null to object' when sending a request in case of NTLM is disabled and requested is nested under folders
4. No Render Failure:   Cannot convert undefined or null to object when trying to view folder info. 
![NTLM issue expected](https://github.com/Kong/insomnia/assets/175235225/2858be67-33dd-4f52-b6ef-4dd6045fcfa4)

### Actual Behavior

We are using Insomnia regularly in Rapyd and noticed the issue in the latest version, 9.3.2 when sending request and view folder info when using NTLM authentication that is disabled

From reproduction steps:
2. URL preview gets empty when disabling NTLM auth
![NTLM issue URL preview](https://github.com/Kong/insomnia/assets/175235225/8b847a05-5c7a-4788-bd29-d3ac752ea4ee)

3. TypeError: Cannot convert undefined or null to object

4. This issue has been noticed when using a request that is nested under a folder in a folder. Additionally, when trying to view info about the folders noticed the same error as when sending the request.

![NTLM issue](https://github.com/Kong/insomnia/assets/175235225/bc58a072-cf9c-4ff6-a686-211e2fc67c64)

### Reproduction Steps

1. In a collection open a request that is nested under a folder in a folder 
2. Make sure NTLM authentication is disabled
3. Send request
4. Select folders containing the request to view folder info

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Could not reproduce the issue with Insomnia 9.3.1 (and some previous version)

We needed to update our tests in order to apply workaround however it would be good to investigate the issue and resolve asap.

### Insomnia Version

9.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### Installation method

Download from insomnia

### Last Known Working Insomnia version

9.3.1

**Comment by gatzjames** [comment] 2024-07-17 15:38
Hi @ivancho979 I couldn't reproduce this with a simple example.
I tried using NTLM with empty values, with actual values, in folders, subfolders and the actual request.
Could it be related to another issue?

**Comment by gatzjames** [comment] 2024-07-18 13:53
Could it be related to this https://github.com/Kong/insomnia/issues/7689#issuecomment-2236038039

**Comment by ivancho979** [comment] 2024-07-22 11:59
Hello James,

Cann't be 100% sure however it looks related since there is issue: Render
Failure: Cannot convert undefined or null to object  where we want to see
Auth info on the folder level
[image: image.png]

Hence, if I understood the comment well this should be fixed with 9.3.3,
right?

Thanks,

Ivan

**Comment by gatzjames** [comment] 2024-07-22 13:55
Could you try by disabling your plugins and restarting Insomnia?
If it works it means it's related to the OAuth2 Token Provider plugin

**Comment by subnetmarco** [comment] 2024-07-22 14:50
> Hence, if I understood the comment well this should be fixed with 9.3.3,
right?

@ivancho979 If you could verify this, this would be awesome.

**Comment by gatzjames** [comment] 2024-07-31 14:24
Closing as this should be fixed in 9.3.3
Thanks for the feedback and let us know if it works for you

**Closed as completed by gatzjames** 2024-07-31 14:24 UTC
Labels: B-bug, S-unverified

**Comment by ivancho979** [comment] 2024-08-01 10:57
After upgrading to 9.3.3 the original issue has been resolved. Thanks!
