### ISSUE TITLE
Support Open API 3.1.0-RC

### ISSUE THREAD

**Issue by grimen** [getinsomnia/insomnia#2960] opened 2020-12-18 20:19 UTC
**Is your feature request related to a problem? Please describe.**

I have written API specs using latest versions of JSON Schema and since Open API < 3.1.0 are not 100% compatible with JSON Schema specifications, so now when I try use `openapi: 3.1.0` it seems it is not supported.

**Describe the solution you'd like**

Version 3.1.0 is RC but if not too much work would be useful for API developers to be able to use RC versions of the Open API spec, but maybe too much to ask for.

**Describe alternatives you've considered**

My option now is to use another editor that supports Open API 3.1 RC (Swagger) or give up on latest JSON Schema standard definitions.

**Additional context**

![Image 2020-12-18 at 15 17 25](https://user-images.githubusercontent.com/4783/102657716-29373e80-4144-11eb-9b7a-267f624d410a.jpg)

**Comment by nijikokun** [comment] 2020-12-23 05:11
Would love to have support for 3.1, as it stands [Swagger UI](https://github.com/swagger-api/swagger-ui/issues/5891) and [Swagger Client](https://github.com/swagger-api/swagger-js) support `3.0x`. Since our preview functionality relies on Swagger UI we will have to wait until these libraries support `3.1x`

**Comment by grimen** [comment] 2020-12-25 15:59
I see, that makes sense.

**Comment by wdawson** [comment] 2022-01-18 18:19
Closing as a duplicate of: https://github.com/Kong/insomnia/discussions/3577

**Closed as completed by wdawson** 2022-01-18 18:19 UTC
Labels: M-duplicate, S-blocked, D-swagger-ui, needs-triage
