### ISSUE TITLE
Importing a Postman collection loses almost all information

### ISSUE THREAD

**Issue by kirelagin** [getinsomnia/insomnia#4214] opened 2021-11-14 21:27 UTC
### Expected Behavior

The collection is imported fully and correctly.

### Actual Behavior

All URLs are empty, the body type is always set to “Other” instead of “No body” or “JSON” where appropriate:

![image](https://user-images.githubusercontent.com/451835/141698905-4632b947-eef9-45ea-bab3-00092d7e9c5c.png)

![image](https://user-images.githubusercontent.com/451835/141698933-c75bd7c7-82d7-41a3-9b9e-846625f8c921.png)

No query parameters and authentication set to “No authentication” instead of Bearer (even though the Authorization header is added with `null` value):

![image](https://user-images.githubusercontent.com/451835/141698955-62e94c2d-6756-41e7-b850-a05a8f39db82.png)

### Reproduction Steps

1. Create a new collection (due to #4034).
2. Import from https://web.timingapp.com/docs/collection.json

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.6.0

### What operating system are you using?

Other Linux

### Operating System Version

NixOS 21.05 (Okapi)

### Installation method

Nix

**Comment by develohpanda** [comment] 2021-11-14 21:49
Thanks for reporting this! The issue you linked above should be resolved by #4058, but this particular issue is peculiar and the example is very useful, thank you!

I did a brief investigation into the code for importing a URL given you note that the URL is missing.

When importing a URL, the importer mainly looks for the `$.item[*].request.url.raw` property.

https://github.com/Kong/insomnia/blob/f48cef02bd14c18dcbf3c7e8393081f5d57743c6/packages/insomnia-importers/src/importers/postman.ts#L159-L171

However looking at your example, and the schema docs at https://schema.postman.com/collection/json/v2.0.0/draft-07/docs/index.html, it appears that `url.raw` could be missing and the importer would need to cater for the combination of `url.protocol`, `url.host`, `url.path`. Maybe `raw` was something that was either recently added, or recently removed, from the export file.

I imagine it's a similar story with the query parameters and header (thus Auth) information.

The example Postman file you provided, do you know if that was recently exported or is an older export? Regardless we should handle these cases.

cc: @wdawson

**Comment by develohpanda** [comment] 2021-11-14 22:02
Further notes: I imported https://web.timingapp.com/docs/collection.json into Postman, then exported as V2. Then, after importing into Insomnia, I could see the URLs having imported correctly, but Authentication and Query Parameters still didn't come through.

This indicates to me, at least in the case of the URL, that Postman previously didn't export the `url.raw` property (when https://web.timingapp.com/docs/collection.json was created), but it does now.

As a list of items missing from the Insomnia import, am I missing anything from this list?
- Body type set to "Other" (instead of extracting from the content-type header, for instance)
- Auth not set (instead of extracting from the Authorization header, for instance)
- URLs are empty
- Query parameters don't import
- Environment variables missing (eg. `token` from the Authorization header)

**Comment by kirelagin** [comment] 2021-11-15 02:16
> do you know if that was recently exported or is an older export?

I have no idea. On the one hand, the `last-modified` header in the server’s response says “Fri, 12 Nov 2021 13:33:07 GMT”; on the other, I know that this API was introduced more than a year ago, and all examples in the documentation show year 2019 in timestamps. If that really matters, I guess, I can ask the author.

**Comment by kirelagin** [comment] 2021-11-15 02:21
As for the items you listed, I think your list is complete.

Regarding the body, note that the file has:

```
"body": {
    "mode": "raw",
    "raw": "[]"
},
```

so, I guess, the current behaviour actually makes sense. However, it may be a good idea to have a heuristic that detects this specific case and sets it to “no body”.

Also now that I took a closer look at the format of the file, I think that the `protocol`, `host`, `path` is a nice opportunity to have use environment variables to, e.g. create `baseUrl = protocol + "://" + host`.

When I was creating the issue, I thought there could be some single root cause of all the problems, but now it looks like they all are different. Should I report individual issues and feature requests instead?

**Comment by develohpanda** [comment] 2021-11-16 04:56
> ... all examples in the documentation show year 2019 in timestamps. If that really matters, I guess, I can ask the author.

That's all good, I think we need to handle the case anyway. It was a valid file at some point, and we should handle it to the best of our ability.

I think each change in the list above involves figuring out which properties are _current_ and which are _legacy_ according to the schema, and using that to inform the import hierarchy. Also, I'm not sure which of the items in the list are not yet supported at all, and which are just not supported with this particular file, so that's another thing to be investigated.

> so, I guess, the current behaviour actually makes sense. However, it may be a good idea to have a heuristic that detects this specific case and sets it to “no body”.

Does that actually represent no body, or a body sending an empty array, or just `[]` as text?

> When I was creating the issue, I thought there could be some single root cause of all the problems, but now it looks like they all are different. Should I report individual issues and feature requests instead?

Yes please! Breaking them down would be quite useful, and can be tackled as individual contributions. I'll add some labels once you're done.

**Comment by wdawson** [comment] 2021-11-16 23:38
@kirelagin thanks for reporting this. We definitely want imports to be simple and not be surprising for Postman users that are coming to Insomnia. By my read of this, it seems like there's a workaround for the glaring issues you saw and potentially some feature requests for other areas to import. I can make notes on the specific issues/discussions as they are raised, but these seem like the kinds of things we'd definitely welcome contributions for if you (or any future reader) would be interested.

**Comment by sergiyladnych** [comment] 2022-01-05 21:08
Hello,


> As a list of items missing from the Insomnia import, am I missing anything from this list?
> 
> * Body type set to "Other" (instead of extracting from the content-type header, for instance)
> * Auth not set (instead of extracting from the Authorization header, for instance)
> * URLs are empty
> * Query parameters don't import
> * Environment variables missing (eg. `token` from the Authorization header)

I'm currently working on all of that issues. Soon will provide the fix

**Comment by sergiyladnych** [comment] 2022-01-09 19:11
@develohpanda @wdawson

I have almost finished fixes for all issues except:
> Environment variables missing (eg. token from the Authorization header)

regarding that I want to ask your advise. There is only one possible candidate for that in https://web.timingapp.com/docs/collection.json . It is `token`. But it is not something that has special description in json of imported collection. It is just reference `{{token}}` in few headers without any reference what is the value and type of that variable. There is no section with description of `token` in https://web.timingapp.com/docs/collection.json.  I see that Postman doesn't import token as environment  variable from https://web.timingapp.com/docs/collection.json. Is that really an issue for Insomnia? If you still think that it should be imported please give you opinion:

1. To which level should such variables go? Folder Environment? Sub Environment? Base Environment?
2. What is the type of such Variables?

One additional observation. In order to import `{{token}} `from headers I had idea to look for all values in json of imported collection with pattern `{{ }}` and  artificially put them to section `variables` of that json just before invocation of `importVariable` from postman.ts. But I found that https://schema.postman.com/json/collection/v2.0.0/collection.json does not have description of `variables` and have only `variable` section but https://web.timingapp.com/docs/collection.json has `variables` section

**Comment by develohpanda** [comment] 2022-01-13 05:54
Hi @sergiyladnych! First of all, happy new year and thanks a tonne for working through these! Looking forward to the PR 🎉 

Regarding the `{{token}}` variable, @wdawson and I had a long discussion about this today. Our conclusion was that if Postman does not handle the `{{token}}` variable automatically from the `web.timingapp.com/docs/collection.json` export file, then Insomnia also shouldn't. You mentioned that Postman does not handle the token, and I verified the case as well, so we can ignore it for Insomnia as well and don't need to do any guessing.

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/4312346/149271815-d3f8ef81-02e7-4ed7-bab3-7638af9b3e32.png">

The strange thing is, it seems like this is by design... I noticed that Postman doesn't include environment variables in their collection export at all. Instead, you [export the environment](https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#exporting-environments) from postman as a separate file. Insomnia does have an importer for the postman _environment_ format as well.

For now, let's leave it as-is, leaving the `{{token}}` environment variable unresolved. @wdawson please chime in in case this summary is missing anything we discussed.

---

As another example, when importing an OpenAPI spec, where a header or path contains an environment variable, Insomnia does not generate a stub of keys in the base/sub/folder environment, so this behavior isn't abnormal. It _would_ be nice however, if we could, in a more generic way, identify the environment variable keys that are needed but are missing by a workspace and it's children (requests, folders, etc), and create stubs for them automatically in the base environment. That way any missing variables from any import can automatically be stubbed by Insomnia, not specifically postman! If you'd like to tackle this though, let's do so in another PR! It'd be a fairly involved task I think, but would be incredibly useful.

**Closed as completed** 2022-05-12 11:52 UTC
Labels: PA-importers, B-bug, S-verified
