### ISSUE TITLE
When the parameter value is empty

### ISSUE THREAD

**Issue by antlcl** [getinsomnia/insomnia#7979] opened 2024-09-20 02:04 UTC
### Expected Behavior

Initiate requests normally

### Actual Behavior

Return business error

### Reproduction Steps

This is the address for a get request: http://xxxxxxxxxx?certificateNo=18925491&securityCode=&rechargeAccountId=0

1.It works like this on Postman:
![image](https://github.com/user-attachments/assets/4d41f191-22a6-468d-b459-526d51defac5)

2.It works like this on CURL:
![image](https://github.com/user-attachments/assets/d8d3532b-6416-47ca-9c65-b8bb4e554e1a)

3.It works like this on insomnia:
   (1) new httpRequest   --> Fill in the URL directly(Do not click import from URL button)  --> it`s  ok
![image](https://github.com/user-attachments/assets/cbe0d75b-0b5e-4aaa-b113-7fa1a4dc7799)

   (2) new httpRequest  -->  Fill in the URL directly   ---->  click import from URL button  ---> fail 
![image](https://github.com/user-attachments/assets/fa7aba0b-e0f1-4077-a588-fbeb2ffb1037)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 10.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 14.7

### Installation method

insomnia.rest

### Last Known Working Insomnia version

Insomnia 10.0.0

**Comment by cwangsmv** [comment] 2024-09-20 02:53
Duplicate of https://github.com/Kong/insomnia/issues/7965
It is fixed and will be available in next minor release.

**Closed as completed** 2024-09-20 03:09 UTC
Labels: B-bug, S-unverified
