### ISSUE TITLE
Edit requests programmatically in Unit Tests (e.g. query variables, request body, headers, ...)

### ISSUE THREAD

**Issue by tina-barrett** [getinsomnia/insomnia#4482] opened 2022-02-11 19:26 UTC
in Unit testing  https://docs.insomnia.rest/insomnia/unit-testing.  Would you please add the ability to invoke another API from the Javascript code editor?

const response = await insomnia.send();
const body = JSON.parse(response.data);

expect(body).to.be.an('array');

**Comment by tina-barrett** [comment] 2022-02-13 20:25
I realized I can invoke another API like below, however, is there a way to send in query variables data dynamically?
const response2 = await insomnia.send('req_b733c874b56c477982ac7da149d21ab6');

**Comment by me-nkr** [comment] 2022-06-18 09:53
What is `req_b733c874b56c477982ac7da149d21ab6` ? where can I find it? Also is there a way to find detailed test results, like why it diff between expected and received response?

**Comment by filfreire** [comment] 2022-07-25 12:53
@me-nkr that is an Insomnia `id` for a request that is defined in the document.


<img width="251" alt="Screenshot_2022-07-25_at_13_49_53" src="https://user-images.githubusercontent.com/11976836/180781836-7dd13168-4ce0-425e-b42a-759f1af036f2.png">
<img width="441" alt="Screenshot_2022-07-25_at_13_49_59" src="https://user-images.githubusercontent.com/11976836/180781841-1fffa637-d853-437b-a741-45f536045110.png">


You can call other requests within Unit test code using this id, for example:
<img width="504" alt="Screenshot_2022-07-25_at_13_50_15" src="https://user-images.githubusercontent.com/11976836/180781861-7d4a722a-1227-45a1-af4c-9dee8fa645fe.png">
<img width="777" alt="Screenshot_2022-07-25_at_13_50_25" src="https://user-images.githubusercontent.com/11976836/180781866-129fb0db-8fc5-47b5-b42c-af991ea9e75f.png">
<img width="504" alt="Screenshot_2022-07-25_at_13_50_33" src="https://user-images.githubusercontent.com/11976836/180781870-10e0a19f-4ecd-40ab-9f21-48cd82ad5c2f.png">

EDIT: also regarding your question:

> like why it diff between expected and received response?

there is no way for a diff at the moment, your best option is to try and assert values in the response itself.
```
const body = JSON.parse(response.data);

expect(body).to.be.an('array');
```

Or alternatively, if the response should always be the same, you could try and convert the response to string, and assert it equals  a string you define previously.

**Comment by filfreire** [comment] 2022-07-25 13:00
Hi @tina-barrett-mahana thank you for reporting this issue! There is no way at the moment to edit query variables or other parts of request before sending it within an Insomnia Unit test. 

We are at the moment gathering all this kind of feedback to try and come up with a feasible plan to improve the test feature.

Feel free to report any other issues or improvements you notice 👍

**Comment by filfreire** [comment] 2022-07-25 13:35
Closing this one as a duplicate of #3128

**Closed as completed by filfreire** 2022-07-25 13:35 UTC
Labels: C-improvement, PA-testing, S-verified
