### ISSUE TITLE
[BUG] When following a 302, after a PUT, results in 411 Length Required

### ISSUE THREAD

**Issue by george-ayris** [getinsomnia/insomnia#503] opened 2017-10-05 10:36 UTC
- Insomnia Version: 5.8.4
- Operating System: Windows 10 Enterprise 1703

## Details
Repo:
* make a PUT call that returns a 302
* Insomnia automatically follows the 302 preserving the PUT method
* missing Content-Length header on second PUT results in 411 Length Required response

Here's the timline from the request:
```
* Preparing request to http://api.huddle.local/tasks/3658
* Enable automatic URL encoding
* Disable SSL validation
* Enable cookie sending with jar of 0 cookies
* Connection 4 seems to be dead!
* Closing connection 4
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to api.huddle.local (127.0.0.1) port 80 (#5)
> PUT /tasks/3658 HTTP/1.1
> Host: api.huddle.local
> User-Agent: insomnia/5.8.4
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Type: application/json
> Authorization: OAuth2 {"iss":"login.huddle.local","exp":2465548899,"urn:huddle.claims.userid":17909,"urn:huddle.claims.clientId":"insomnia","urn:huddle.claims.huddleadmin":1}
> Content-Length: 91
| {
|   "title": "Due in 2 days",
|   "status": "Complete",
|   "dueDate": "2017-02-15T00:00:00Z"
| }
* upload completely sent off: 91 out of 91 bytes
< HTTP/1.1 302 Redirect
< Content-Type: text/html; charset=UTF-8
< Location: https://api.huddle.local/tasks/3658
< Server: Microsoft-IIS/10.0
< X-Powered-By: ASP.NET
< Date: Thu, 05 Oct 2017 10:26:35 GMT
< Content-Length: 158

* Ignoring the response-body
* Received 158 B chunk
* Curl_http_done: called premature == 0
* Connection #5 to host api.huddle.local left intact
* Issue another request to this URL: 'https://api.huddle.local/tasks/3658'
* Switch from POST to GET
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to api.huddle.local (127.0.0.1) port 443 (#6)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\Users\GEORGE~1.AYR\AppData\Local\Temp\insomnia\2017-01-18.pem
*   CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.huddle.local
*  start date: Jan 13 10:38:54 2016 GMT
*  expire date: Jan 12 10:38:54 2018 GMT
*  issuer: DC=local; DC=huddle; CN=huddle-UKSCA01-CA-1
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> PUT /tasks/3658 HTTP/1.1
> Host: api.huddle.local
> User-Agent: insomnia/5.8.4
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Type: application/json
> Authorization: OAuth2 {"iss":"login.huddle.local","exp":2465548899,"urn:huddle.claims.userid":17909,"urn:huddle.claims.clientId":"insomnia","urn:huddle.claims.huddleadmin":1}
< HTTP/1.1 411 Length Required
< Content-Type: text/html; charset=us-ascii
< Server: Microsoft-HTTPAPI/2.0
< Date: Thu, 05 Oct 2017 10:26:35 GMT
< Connection: close
< Content-Length: 344

* Received 344 B chunk
* Curl_http_done: called premature == 0
* Closing connection 6
* TLSv1.2 (OUT), TLS alert, Client hello (1):
```

Thanks, hope that's sufficient detail.

**Comment by gschier** [comment] 2017-10-05 13:28
Thanks for the report @george-ayris, but I'm closing this issue as it's a duplicate of #439

**Closed by gschier** 2017-10-05 13:28 UTC

**Comment by george-ayris** [comment] 2017-10-05 16:16
Ah thanks, I wasn't sure whether we expected a method change for PUT on
redirects.

Cheers for all your hard work.

**Comment by gschier** [comment] 2017-10-05 19:06
😄
