### ISSUE TITLE
Copy as cURL broken when URL contains variable/placeholder

### ISSUE THREAD

**Issue by black-snow** [getinsomnia/insomnia#6382] opened 2023-08-24 08:01 UTC
### Expected Behavior

Copy as cURL works as usual and copies the request to the clipboard.

### Actual Behavior

> Could not generate cURL
> Failed to render "<request name>" attempted to output null or undefined value
![grafik](https://github.com/Kong/insomnia/assets/579733/823b594b-15e8-49d4-8988-3a795c7c8131)

### Reproduction Steps

1. create a request
2. create environment and add some variable
3. use variable in request URL
4. hit copy as curl

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

In my case it's just

```json
{
	"host": "localhost"
}
```
and `http://{{ _.host }}:8080`

### Insomnia Version

2023.5.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.22621 x64

### Installation method

installer

### Last Known Working Insomnia version

previoues one, 2023.5.5 I guess

**Comment by DannyHinshaw** [comment] 2023-08-24 14:03
Just wanna add on here that this appears to be a pretty widespread issue with plugins. Pretty much every plugin we use is currently broken. I'm just now diving in to try and debug and see what's going on, but in general it looks like maybe either or both:
- Some updates to React possibly causing issues
- Some changes to the plugin API

I'll try to report back as I find things, but wanted to post this to add some more urgency to what's going on in the latest release.

**Comment by kkmehta03** [comment] 2023-08-28 14:29
same issue

**Comment by tsheaff** [comment] 2023-08-30 19:17
This completely breaks Insomnia for me. It's a critical use-case for me to be able to copy as curl commands.

**Comment by jackkav** [comment] 2023-08-30 21:12
can you please share a reproduction request or curl? does it work with generate code?

**Comment by black-snow** [comment] 2023-09-04 15:18
@jackkav it's as simple as described above:

* create a new HTTP request, `http://{{ _.host }}`
* set up environment with anything as `host` (e.g. example.com)
* click copy as curl

**Comment by jackkav** [comment] 2023-09-08 10:55
Fixed in 2023.5.8

**Closed as completed by jackkav** 2023-09-08 10:55 UTC
Labels: B-bug, S-unverified
