### ISSUE TITLE
Random popup

### ISSUE THREAD

**Issue by wendellestradairely** [getinsomnia/insomnia#5214] opened 2022-09-23 05:43 UTC
### Expected Behavior

Should be able to dismiss this popup.

### Actual Behavior

A popup that shows a list of URLs randomly pops up and can't be dismissed. Tried to hit the ESC key but the popup doesn't disappear.

![image](https://user-images.githubusercontent.com/50942719/191898174-0ed083ab-01f5-4fb3-9b55-7ebc29d12e86.png)

### Reproduction Steps

Unable to replicate because it just randomly pops up.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.5.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

downloaded from insomnia website

**Comment by filfreire** [comment] 2022-09-26 07:18
Hi @wendellestradairely, thanks for reporting this. I've also noticed this behavior as of late. We'll update you here if there are any fixes or work done for this one soon.

**Comment by filfreire** [comment] 2022-10-25 08:50
Closing as duplicate of https://github.com/Kong/insomnia/issues/4531

**Closed as completed by filfreire** 2022-10-25 08:50 UTC
Labels: B-bug, S-verified
