### ISSUE TITLE
[Bug] Body request for application/xml allways send utf-8 when charset is not uft-8

### ISSUE THREAD

**Issue by epelaic** [getinsomnia/insomnia#615] opened 2017-11-21 10:05 UTC
[Bug] – When I send a request with xml body encoded in ISO-8859-15 and setting header Content-Type to application/xml;charset=ISO-8859-15, the request is sent in utf8, resulting in server side with incorrect accents characters.
When using Firefox RESTClient there is not issue.

[Question] – Is it possible to force the resquest to be sent with the correct data encoding ?

Thanks, 

Edo

- Insomnia Version: v5.11.7
- Operating System: Windows 7
Server side : 
- Tomcat Version : 9.0.1
- Jersey 2.25.1
- Java 1.8.0_91

## Details

Add the header : Content-Type: application/xml;charset=ISO-8859-15
Add XML body encoded in ISO-8859-15 with xml prolog : `<?xml version="1.0" encoding="ISO-8859-15"?>`
Add some accents in the data body like : é resulting in : Ã©

**Comment by gschier** [comment] 2017-11-21 17:52
Hey @epelaic. I think this the same (or similar) question as https://github.com/getinsomnia/insomnia/issues/593. Can you take a look and let me know?

**Comment by epelaic** [comment] 2017-11-22 07:45
Hello, yes it's look like to be the same issue.

Thanks,
Edo

**Comment by gschier** [comment] 2017-11-22 11:41
K, going to close this one

Duplicate of #593

**Closed by gschier** 2017-11-22 11:41 UTC
