### ISSUE TITLE
Documentation Browser - Supporting Search

### ISSUE THREAD

**Issue by tomprats** [getinsomnia/insomnia#2720] opened 2020-10-14 02:31 UTC
I'm having a frustrating experience with the documentation browser. I'm working in a large project with a large number of GraphQL queries. The documentation browser shows the queries but there are so many and they don't appear to be ordered in a meaningful way (although I understand it's probably the way the introspection query returns the data).

Adding support for search, ctrl-f or at least listing queries and mutations alphabetically would be a tremendous help

**Comment by l0co** [comment] 2020-10-14 12:29
Exactly the same I've intended to report right now :)

However, if this feature can take some time to develop, please do at least a simple fix to sort queries and mutations in documentation to enable manual search of them. Currently it's not browsable because of the random order.

**Comment by l0co** [comment] 2020-10-14 12:33
@tomprats There's a workaround for that. Open documentation and hit `Alt+Ctrl+I` to toggle dev tools and on Elements tab hit `Ctrl+F` to enable search. Here you can find your query/mutation by name and the documentation will navigate to it.

**Comment by tomprats** [comment] 2020-10-14 16:17
Good idea @l0co, that definitely helps in the meantime

**Comment by nitangle** [comment] 2021-01-06 13:24
Can anybody confirm if the issue is closed or still open?

**Comment by develohpanda** [comment] 2021-01-08 09:42
Hi @nitangle, as it stands the requested feature (search functionality) is still open.

**Comment by Hademumel** [comment] 2021-05-06 19:58
Hi, am I correct that currently nobody is working on this issue? I would like to implement this, since I'm also really missing this feature.

**Comment by develohpanda** [comment] 2021-05-06 21:13
Hi @Hademumel! Not that I know of, feel free to pick it up.

Please note that we do have a big migration to TypeScript about to be merged early next week (week of May 10th), so to avoid setting up Flow and then having merge conflicts, just keep that in mind when you start 🤗

**Closed as completed** 2021-08-26 05:43 UTC
Labels: E-good-first-issue
