### ISSUE TITLE
Support for Environment Variables in the Basic Auth Password Field

### ISSUE THREAD

**Issue by rkrueger11** [getinsomnia/insomnia#2857] opened 2020-11-22 15:47 UTC
Looks like the password field for the Basic Auth works to hide what you type, which is great, but it also seems to lack support for environment variables.

**Comment by Chrno21** [comment] 2021-03-08 14:29
I've installed Insomnia 2020.5.2 again...and disabled updates...

**Comment by cpick** [comment] 2021-03-30 15:40
I found that [this suggestion](https://github.com/Kong/insomnia/issues/229#issuecomment-302170321) still works.
That is: even though the UI doesn't highlight the templated values, you can sill put something like `{{ _.password }}` in the Basic Auth's Password field and it will be evaluated as a template and pull from the environment.

Not intuitive or clear, but it works.

**Comment by bjohnson-va** [comment] 2021-04-27 19:59
You can also do this via the UI entirely. But, again, not super intuitive.


https://user-images.githubusercontent.com/8963131/116305242-bcbaf480-a760-11eb-8fa1-794f94a597a8.mp4

**Comment by czystolowski** [comment] 2022-03-02 08:19
It doesn't seem that environment variables are supported anymore from the Authentication tab.

I've tried all the templates I found Insomnia supports, and all of them get resolved to `{{username}}:{{password}}` (example for Basic Auth) instead of actual values. I hope that I missed something.

**Comment by filfreire** [comment] 2022-08-12 09:39
Hi folks, I'm closing this issue since we do support environment variables on Auth tabs, example with Basic auth:

![Image](https://user-images.githubusercontent.com/11976836/184327589-4f097078-4e4f-4f6b-9df3-fb2e41eeaa40.png)

Feel free to report any other issues you come across!

@czystolowski as for the issue you mentioned, it's likely a different issue. I would suggest you check your Preferences (and maybe the Request Preferences) to see which settings you have enabled that could affect this:

![Image](https://user-images.githubusercontent.com/11976836/184328147-c70dcfd6-6097-4069-a408-eaccc618f5b4.png)

Feel free to open a new issue if you manage to reproduce your problem for example in our [latest beta version (2022.6.0-beta.1)](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.1).

**Closed as completed by filfreire** 2022-08-12 09:39 UTC
