### ISSUE TITLE
[Bug] 7.1.0 slower for each request

### ISSUE THREAD

**Issue by alfreddatakillen** [getinsomnia/insomnia#1943] opened 2020-02-17 01:16 UTC
**Describe the bug**
My insomnia auto updated to 7.1.0 today, and after that, insomnia gets slower and slower for each request.

**To Reproduce**
1. Restart insomnia.
2. Make requests.
3. They are fast in the beginning!
4. Make more requests.
2. Notice that the response in somnia gets slower and slower for each request. After some 50 requests, insomnia takes over 20 seconds from pressing "Send"-button until result is rendered on screen.

**Expected behavior**
No slowdown when making requests.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Installation Method: Downloaded Insomnia-7.0.6.dmg, which got auto updated to 7.1.0.
 - App Version 7.1.0

**Additional context**
"Copy as curl" and running requests in terminal is not affected by the slow down. My response times are 1-5 milliseconds with curl, while being 20 seconds in insomnia. So, the problem is not the server getting slower and slower. It is insomnia getting slower for each request.

Only tested on graphql endpoint. My test endpoints returns maximum 1kb data, so no big payload.

**Comment by garrettjoecox** [comment] 2020-02-17 17:21
This is happening to me as well, thought I was going crazy.

**Comment by alfreddatakillen** [comment] 2020-02-17 17:48
> This is happening to me as well, thought I was going crazy.

Downgrade and uncheck the auto update box! This is clearly an issue with latest version only.

**Comment by gschier** [comment] 2020-02-18 19:40
Thanks for reporting this! Taking a look now 👍

**Comment by gschier** [comment] 2020-02-18 19:58
Looks like this was fixed by this already! https://github.com/Kong/insomnia/pull/1951

Tested locally on old version (was able to reproduce). Then, after pulling that PR, was no longer able to reproduce 😄

**Closed as completed by gschier** 2020-02-18 19:58 UTC
Labels: P-high

**Comment by gschier** [comment] 2020-02-18 21:23
Working on getting this deployed in the next few hours
