### ISSUE TITLE
Fedora 35 crash

### ISSUE THREAD

**Issue by flyhigh-hifi** [getinsomnia/insomnia#4332] opened 2021-12-28 08:00 UTC
### Expected Behavior

App starts successfully

### Actual Behavior

After upgrade to fedora 35 it starts, freezes for a second, and process terminates.

```
10:54:44.846 › Running version 2021.7.2
10:54:44.859 › [electron client protocol] FAILED to set default protocol 'insomnia://'
10:54:44.868 › [electron client protocol] the current executable is not the default protocol for 'insomnia://'
10:54:44.907 › [electron client protocol] the default application set for 'insomnia://' is 'insomnia.desktop
'
10:54:45.059 › [fix] Running database repairs
10:54:45.162 › [db] Initialized DB at /home/mark/.config/Insomnia/insomnia.$TYPE.db
10:54:45.163 › [db] Init responses DB
10:54:45.201 › [localstorage] Initialized at /home/mark/.config/Insomnia/localStorage
10:54:45.239 › [main] Loading file:///opt/Insomnia/resources/app.asar/renderer.html
10:54:45.250 › [ga] Non-interactive General, Launched, 2021.7.2
10:54:45.256 › [ga] Queued event [
  { name: 't', value: 'event' },
  { name: 'ec', value: 'General' },
  { name: 'ea', value: 'Launched' },
  { name: 'ni', value: '1' },
  { name: 'el', value: '2021.7.2' }
]
10:54:45.752 › [updater] Updater not running platform=linux dev=false
[652418:1228/105446.835265:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.7.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux fedora 5.15.10-200.fc35.x86_64 #1 SMP Fri Dec 17 14:46:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

rpm package

### Last Known Working Insomnia version

2021.5.3

**Comment by momega** [comment] 2022-01-01 19:38
The same situation. After installing fedora 35, insomnia 2021.7.2 crashes during start

**Comment by filfreire** [comment] 2022-01-04 16:35
This might be related with an electron and glibc issue:
- https://github.com/LedgerHQ/ledger-live-desktop/issues/4253
- https://github.com/electron/electron/pull/31091
- https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468
- https://github.com/microsoft/vscode/issues/133593


@flyhigh-hifi @momega can you try the following:

- Try to launch `insomnia` with `--no-sandbox` option (not sure if this will work)
- Try to use latest [insomnia beta version (2021.7.3-beta.0)](https://github.com/Kong/insomnia/releases/tag/core%402021.7.3-beta.0)

I've tried reproducing this on both Fedora 35 and ubuntu 21.10, but couldn't, likely due to the fact I'm using virtual machines.

![Screenshot 2022-01-04 at 15 53 59](https://user-images.githubusercontent.com/11976836/148092105-237c0218-0b12-4e3a-a2bd-789aeb0fbf24.png)
![Screenshot 2022-01-04 at 15 48 15](https://user-images.githubusercontent.com/11976836/148092111-c8a1e078-da6a-4fe2-a04c-0577d6cc8930.png)

**Comment by momega** [comment] 2022-01-04 19:22
I can confirm that switch "--no-sandbox" works just fine.

**Comment by vishytk** [comment] 2022-01-05 06:56
For me on Fedora 35

2021.7.2 does not work with and without ``--no-sandbox`` option

2021.7.3-beta.0 works only with ``--no-sandbox`` option

**Comment by flyhigh-hifi** [comment] 2022-01-08 09:34
Thanks, confirming that --no-sandbox works

**Comment by meiremans** [comment] 2022-01-11 11:32
--no-sandbox works just fine indeed.

If it's of any help. It worked for me with nouveau drivers, not with nvidea drivers

**Comment by jprando** [comment] 2022-02-10 22:07
Fedora release 35 (Thirty Five)

`--no-sandbox` works just fine

**Comment by iAmMrinal0** [comment] 2022-05-01 17:01
From NixOS (in case someone comes here for it), `--no-sandbox` works for me.

Crash log:
```
$ insomnia
22:22:38.991 › Running version 2022.1.1
22:22:39.032 › [electron client protocol] FAILED to set default protocol 'insomnia://'
22:22:39.060 › [electron client protocol] the current executable is not the default protocol for 'insomnia://'
22:22:39.188 › [electron client protocol] the default application set for 'insomnia://' is 'insomnia.desktop
'
22:22:39.398 › [fix] Running database repairs
22:22:39.550 › [db] Initialized DB at /home/iammrinal0/.config/Insomnia/insomnia.$TYPE.db
22:22:39.553 › [db] Init responses DB
22:22:39.581 › [localstorage] Initialized at /home/iammrinal0/.config/Insomnia/localStorage
22:22:39.633 › [main] Loading file:///nix/store/pim2g7k3wrl48aj255d0bhnhi58liw9d-insomnia-2022.1.1/share/insomnia/resources/app.asar/renderer.html
22:22:40.172 › [updater] Updater not running platform=linux dev=false
[870861:0501/222240.683653:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[1]    870861 trace trap (core dumped)  insomnia
```

**Comment by filfreire** [comment] 2022-05-13 16:15
Hey folks!

Can you confirm if you still have problems running without the `--no-sandbox` flag for the [latest stable](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0) (or the [latest beta](https://github.com/Kong/insomnia/releases/tag/core%402022.4.0-beta.1)) releases?

If you no longer have problems, I think we can close this issue. Thanks in advance!

(cc @flyhigh-hifi / @momega / @vishytk / @meiremans / @jprando  / @iAmMrinal0 )

**Comment by flyhigh-hifi** [comment] 2022-05-22 12:13
> Hey folks!
> 
> Can you confirm if you still have problems running without the `--no-sandbox` flag for the [latest stable](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0) (or the [latest beta](https://github.com/Kong/insomnia/releases/tag/core%402022.4.0-beta.1)) releases?
> 
> If you no longer have problems, I think we can close this issue. Thanks in advance!
> 
> (cc @flyhigh-hifi / @momega / @vishytk / @meiremans / @jprando / @iAmMrinal0 )

Confirming insomnia works without `--no-sandbox` flag on latest stable release. Thanks!

**Closed as completed** 2022-05-22 12:13 UTC
Labels: O-linux, N-author-input, B-bug, S-verified

**Comment by momega** [comment] 2022-05-22 16:55
Version 2022.3.0 works just fine.

**Comment by meiremans** [comment] 2022-05-23 14:51
> 

can confirm latest version works on fedora 36
