### ISSUE TITLE
[Bug] Certificate input inside workspace settings

### ISSUE THREAD

**Issue by TakesTheBiscuit** [getinsomnia/insomnia#357] opened 2017-07-12 09:43 UTC
## Overview
- `Insomnia Version:` Version 5.5.2 (5.5.2.677)
- `Operating System:`  macOS 10.12.1 (16B2555)
- `Summary: ` Trying to add a certificate has some issues with the popup window on Mac

## How To Reproduce
1. Create request and new environment
2. Click work space settings from top left drop down
3. Click 'Client Certificates' 
4. Click 'Add Cert..'
5. Click 'Choose File'

## Other Notes
Sometimes on Mac there are issues with Window display, not sure if it's a Mac only bug - because it does happen with other apps from time to time where a window may just 'disappear', the reality is that the window is firing/appearing but it's some how hidden under the UI of the parent app.

I just experienced an issue where i had clicked 'choose File' about 10 times, each time i clicked the 'choose file' button the master parent Insomnia window flashed briefly (the toolbar icons for minimise/maximise) went 'colourful' ('enabled'), then back to 'non focussed' colour pallet.

So 'its not working' is what i thought, perhaps because this is very new, that is fair.
Thought i'd quit insomnia to produce this bug report.

Tried to quit, was unable to, this is because windows existed but were not being made focussed/active.

I was then unable to cancel those popups because there were many and i assume the 'connection' between 'choose file' and those modal windows was no longer alive.

So i had to force quit. No big deal.
It seems to me that there is a quick fix here; if a modal window has been fired, do not allow another to be created until the first is dismissed or exited.
The second fix required would be to try and work out how to force that modal window to come to the surface/top most window - which combined with the first fix would be perfect.

This is more of a nuisance bug than anything serious; otherwise great product as ever!

**Comment by gschier** [comment] 2017-07-12 22:42
Hi @TakesTheBiscuit! 

Thanks for the report, that sounds quite annoying. 😟

Since Insomnia uses `electron` for showing dialogs, there isn't really anything _easy_ I can do here, Especially if it's non-trivial to reproduce.

You mentioned that it happens with other apps sometimes. Could it be caused by a setting or other application installed on your system? I haven't ever noticed such a thing on OSX myself.

**Comment by TakesTheBiscuit** [comment] 2017-07-13 07:56
Adding this:
I use an external HDMI powered display 

Is there a way to simply track modal generation from electron?
i.e something like
```
modalHasFired = false;
try {
    if (!modalHasFired) {
        modalHasFired = electron(....);
    }
}
```

**Comment by gschier** [comment] 2017-07-25 22:57
I don't think so, unfortunately. Showing the open dialog is a single command, and is delegated to the OS. 

Since you are experiencing it with other apps as well it seems like an OS-level problem, and I don't think anything can be done from within Insomnia. I wouldn't doubt that this is caused by an external monitor. MacOS is notorious for issues when using external displays.

For reference, here's what showing an open dialog looks like in the codebase:

https://github.com/getinsomnia/insomnia/blob/0ed42bfa906f5096d37c9887ec1cc8ee05cd8f0f/app/ui/components/base/file-input-button.js#L27

```js
remote.dialog.showOpenDialog(options, async paths => {
  // Only change the file if a new file was selected
  if (!paths || paths.length === 0) {
    return;
  }

  const path = paths[0];
  this.props.onChange(path);
});
```

Closing this one for now.

**Closed by gschier** 2017-07-25 22:57 UTC
Labels: MacOS, Needs Verification
