### ISSUE TITLE
Failed to load API definition

### ISSUE THREAD

**Issue by thynquest** [getinsomnia/insomnia#2915] opened 2020-12-06 22:57 UTC
Hello there

I just upgrade insomnia core to version 2020.5.1 and I am working with flask restx trying to use the [swagerui](https://flask-restx.readthedocs.io/en/latest/swagger.html#swagger-ui). the problem is that I have  swaggerui works on the browser but not on insomnia. Instead it displays an error message : 
````
Fetch errorFailed to fetch http://localhost:5000/swagger.json
Fetch errorPossible cross-origin (CORS) issue? The URL origin (http://localhost:5000) does not match the page (null). Check the server returns the correct 'Access-Control-Allow-*' headers.
````

has anyone came across this bug ? I tried many things with no result.

Thank you for your help

**Comment by nijikokun** [comment] 2020-12-08 23:51
Welcome @thynquest, can you add a screenshot of the error occurring and steps to reproduce?

**Comment by thynquest** [comment] 2020-12-12 01:59
yes sure 

here is a simple application written with flask_restx

````python
from flask import Flask
from flask_restx import Resource, Api

app = Flask(__name__)
api = Api(app, doc="/doc/")

@api.route('/hello')
class HelloWorld(Resource):
    def get(self):
        return {'hello': 'world'}

if __name__ == '__main__':
    app.run(debug=True)
````

when I launch the app and go the url http://localhost:port/doc/ I have the swagger ui displayed

<img width="606" alt="Screenshot 2020-12-12 at 02 54 12" src="https://user-images.githubusercontent.com/3199630/101969626-aaaf3e00-3c25-11eb-86ef-cd36d441fe6d.png">

but when I do the same thing with insomnia this is what I have

<img width="685" alt="Screenshot 2020-12-12 at 02 57 39" src="https://user-images.githubusercontent.com/3199630/101969651-dcc0a000-3c25-11eb-8eb2-20174d1aa111.png">

Thank you for your help

**Comment by nijikokun** [comment] 2020-12-14 20:41
@thynquest does the `swagger.json` load as well? I see that the the `/doc` loads but the request in question is the swagger file itself.

**Comment by filfreire** [comment] 2022-08-12 10:00
Closing this one, as I'm also not able to reproduce.



![Image](https://user-images.githubusercontent.com/11976836/184331832-d1328cf0-0c9c-4aaa-9220-5036c0ab9870.png)


@thynquest feel free to open a new issue if you are still facing problems.

**Closed as completed by filfreire** 2022-08-12 10:00 UTC
Labels: N-author-input, needs-triage
