### ISSUE TITLE
version 2023.2 Imports of request collection no longer work

### ISSUE THREAD

**Issue by MarekUrbanUnicorn** [getinsomnia/insomnia#5942] opened 2023-05-04 07:57 UTC
### Expected Behavior

import a file exported from insomnia as insomnia json v 4 containning request directory with three commands one of which has a tag
[Insomnia_2023-05-04.txt](https://github.com/Kong/insomnia/files/11394913/Insomnia_2023-05-04.txt)

expected bahavior is creation of request direcotry
with the command and tag intact

### Actual Behavior

upon importing whis file into insomnia v2023.2. a document is created instead name 'Untitled'
![image](https://user-images.githubusercontent.com/89454288/236142062-a4c8d8eb-7965-491d-a2f8-7273a86a612d.png)
and the Tag becomes disconected
![image](https://user-images.githubusercontent.com/89454288/236142243-733424c2-2f74-4ff9-8c03-3537280e3113.png)

also if insomnia already contains the apropriatly named  request directory import will create duplicate requests.
i think that both tag will point to same request.

### Reproduction Steps

1. export request directory with a tag
2.  import into insomnia
3. request get duplicated
4. delete the request directory
5. import into insomnia
6. Unnamed Document is created and tag is broken 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 10 Pro Version	22H2 Installed on	‎06/‎02/‎2023 OS build	19045.2846 Experience	Windows Feature Experience Pack 120.2212.4190.0

### Installation method

insomnia updated

### Last Known Working Insomnia version

i think the previous version was fine but dont have the nuber on hand since the update

**Comment by MysticFragilist** [comment] 2023-05-04 21:32
Got the same issue as mentionned above

**Comment by juanjoms** [comment] 2023-05-04 22:23
Related to https://github.com/Kong/insomnia/issues/5930

**Comment by itxtoledo** [comment] 2023-05-06 00:04
same here

**Comment by itxtoledo** [comment] 2023-05-06 00:08
> Related to #5930

It's not the same problem as this one. This problem occurs when importing a collection, for some reason in this latest version if you have a template that uses the response from another request everything will break

**Comment by smacktoid** [comment] 2023-06-02 14:14
+1 on this. We're finding request chaining is broken when importing a collection document. 

In our case, we use one request to get a token, and then all subsequent requests retrieve the access token out of the first request's response body.

Recently this seems to have broken, with the request ID failing to match up. It looks like the request ID matches that in the JSON that was imported, so not sure why it's broken.

I've tried "fixing" the reference to the first request, re-exporting, then re-importing, but the collection will be back in a broken state.

Broken reference:
![image](https://github.com/Kong/insomnia/assets/3959288/96cf86f6-d272-4109-aa21-78573531cc1d)

The document that was imported, showing the correct ID:
![image](https://github.com/Kong/insomnia/assets/3959288/413ddd1f-9ad4-43c7-a68e-0413568b95c4)

**Comment by ademlabs** [comment] 2023-06-12 13:01
I would like to add that importing a Collection is imported as a Document instead, which is weird. There is no way to import a Collection, unless you create one first manually and import your data in there. However, you will lose all environments, so yeah import does seem to be very broken.

**Comment by emedbo** [comment] 2023-06-22 11:06
I get the same behavior. For 2023.2, all requests are given a new request id, even the import file contains ids. The solution for me was to downgrade to 2023.1, import the collection then upgrade to 2023.2. This should be a stable workaround.

**Comment by jesseclm** [comment] 2023-06-28 01:45
This is a PIA. I have to go into the `insomnia.Workspace.db` file to change the scope from `design` to `collection` to have it work as a collection.

**Comment by NickRimmer** [comment] 2023-06-28 15:32
Synchronization plugin stop working as well, because of during the import it is always generating new ids for requests/groups )=

**Comment by dyeeye** [comment] 2023-08-11 11:29
I have a similar outcome in the newest version  2023.4.0. Chain requests do not work after import. It works on 2023.1, it does not work on any further version including newest beta version 2023.5

**Comment by KarolinaKL88** [comment] 2023-08-11 13:27
same problem here, with the newest version :( chain requests don't work after import.

**Comment by wojowkik** [comment] 2023-08-11 14:14
I also have problem with import
1. If I imported collection that I previously exported for test purposes (and I have both original and imported collection inside Insomnia even for different projects) values are propagated (still request in GUI empty for imported collection)
![image](https://github.com/Kong/insomnia/assets/53089932/67ec079f-e26e-43f0-b1a5-e87ca6f46f63)
2. If I remove original collection and I try to use imported one I receive error
![image](https://github.com/Kong/insomnia/assets/53089932/812dd42f-6347-4ae8-8d46-d4cf46f3234a)

Looks like elements IDs are propagated between projects and if original collection is unavailable I receiving an error.
Obviously same error if I import collection created by other developers.

**Comment by necessarylion** [comment] 2023-09-11 13:35
Same issue here with latest version.

**Comment by mehr-licht** [comment] 2023-09-25 22:45
Me too.
When I import the collection with tags anywhere else, even though the requests exist because they are imported at the same time, the references don't exist because the ids are new.

**Comment by LuLeRoemer** [comment] 2023-10-19 11:21
Any new development here? Still not working in v8.3.0.

**Comment by lucasvmx** [comment] 2023-11-25 16:08
Still not working in v8.4.0 :(

**Comment by thiagomaia971** [comment] 2023-11-27 15:12
Still not working in v8.4.5 :(

**Comment by filfreire** [comment] 2023-11-27 20:07
Closing as duplicate of https://github.com/Kong/insomnia/issues/5730

**Closed as completed by filfreire** 2023-11-27 20:07 UTC
Labels: B-bug, S-unverified
