### ISSUE TITLE
Add an option to actually disable updates

### ISSUE THREAD

**Issue by cooperfrench95** [getinsomnia/insomnia#6658] opened 2023-10-06 08:53 UTC
### Expected Behavior

There is an option in the settings that allows you to choose whether to "automatically download and install updates". 

I would expect that if I turn this setting off, I can then just use the program without updating it. 

### Actual Behavior

Whether the setting is on or off, I still get pestered constantly to install updates. The app bounces around in my dock on MacOS and tells me an update is available. If I click "later" it reminds me a billion times a day which is distracting enough that I eventually cave. 

GIven how truly awful your recent updates have been (seriously what a cringe decision to force uploading our stuff to your cloud, nobody asked for that) you can understand why I might not be keen to get your latest updates. Who knows what the next update will do? Upload my entire hard drive to S3 with public access?

If this is a feature not a bug (as indicated by the tooltip next to the setting option) then I am not sure why the setting is even available in the first place, since either way I am forced to update

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.2

### What operating system are you using?

macOS

### Operating System Version

macOS something

### Installation method

No clue

### Last Known Working Insomnia version

7.9 probably
```[tasklist]
### Tasks
- [ ] Let me not update this god damn thing
```

**Comment by StephenWetzel** [comment] 2023-10-07 01:33
My work around for this was to add this line to my `/etc/hosts` file.
```
0.0.0.0         updates.insomnia.rest
```

**Comment by suchislife801** [comment] 2023-10-07 14:43
## Last Working Version! Sort Order Fix!
# [2023.4.0](https://github.com/Kong/insomnia/releases/tag/core@2023.4.0)
### ANY version ABOVE 2023.4.0 will absolutely WRECK your sort orders.

**Comment by filfreire** [comment] 2023-10-10 10:25
@cooperfrench95 you can disable auto-updates in the Preferences. What @StephenWetzel posted, although we cannot recommend it, will silence the notifications.

Closing as duplicate of https://github.com/Kong/insomnia/issues/6662

**Closed as completed by filfreire** 2023-10-10 10:25 UTC
Labels: B-bug, S-unverified
