### ISSUE TITLE
Bug - Sort folders and endpoints

### ISSUE THREAD

**Issue by robertocerdasilva** [getinsomnia/insomnia#6330] opened 2023-08-18 13:16 UTC
### Expected Behavior

Sort folders and endpoints

### Actual Behavior

The new update changed the order of all my folders and endpoints. Now as much as I try to move the folders in the order I want, it's impossible.

Am I missing something?

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment] 2023-08-18 13:19
duplicate of #6284

**Closed as completed by filfreire** 2023-08-18 13:19 UTC
Labels: B-bug, S-unverified
