### ISSUE TITLE
Base environment variables are active even though the json is blank

### ISSUE THREAD

**Issue by abhinav202** [getinsomnia/insomnia#6964] opened 2024-01-03 23:35 UTC
### Expected Behavior

If the base enivornment's json is blank {} and does not have any values inside it, then the variable values should be picked up from the sub-environment.

### Actual Behavior

The base enivornment's json is blank, but it still fetches values from it

### Reproduction Steps

Been shifting my work from postman to Insomnia.
I didnt know the concept of base environment earlier. So i must have added some of my variables over there. Later on when i realized that for different environments i need different values, then i started creating multiple sub-environments.
And i deleted the values from the base environment.
So there is a variable named "PO_num" which i must have added in the base environment earlier. And then i added it in the sub-environment too. And now i need to update this value every time for my test, but i am unable to do so because a particular value was put in the base environment initially and it always picks up that value (instead of picking value from the active sub-environment).

1. Start from scratch. Make a new workspace. Add a new collection.
2. Add variables to the base environment.
3. Add a new sub-environment and add values to it.
4. Delete the base environment json.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Attachments:

1. Screenshot of the base environment's json (BaseEnv_json.png)
2. Screenshot showcasing the base environment variable in blue. Blue color means that there is a value for the variable, while the red variables mean that there is no value for it. (BaseEnv_variable.png)
![BaseEnv_json](https://github.com/Kong/insomnia/assets/61115953/c5e102c1-b40c-4adb-9807-7fc161386591)
![BaseEnv_variable](https://github.com/Kong/insomnia/assets/61115953/370ccd2e-ccc3-4df4-80cd-78368f732b17)

### Insomnia Version

8.5.1

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.1.2

### Installation method

homebrew

**Comment by gatzjames** [comment] 2024-01-04 16:21
Hi @abhinav202
When you open the environment modal again is the Base environment empty?
It looks like our validation doesn't allow it to be changed when you clear it out.
Can you try putting an empty object instead of deleting everything `{}`?

**Comment by abhinav202** [comment] 2024-01-04 20:00
Hi @gatzjames thank you for your reply.
The base environment is empty and has {} as shown in the previous screenshot.
I dont clearly understand what you mean by empty object here. But I tried deleteing even the {} and then opened the base enviornment again and it displayed {} by itself.

Sorry if there is a confusion. Let me know if you need more details.

**Comment by gatzjames** [comment] 2024-01-31 19:25
Hey @abhinav202 I can't reproduce this on the latest version. Can you check that this issue is still happening for you?
The only thing I could think of why this is happening is if you have Environment Overrides in the folder that contains the request.
If you open the menu on the folder and select Environment is there perhaps a variable set for PO_num.

**Comment by gatzjames** [comment] 2024-02-06 15:42
Closing as it's not reproducible. Feel free to reopen if you think the issue is still happening!

**Closed as completed by gatzjames** 2024-02-06 15:42 UTC
Labels: B-bug, S-unverified
