### ISSUE TITLE
cannot add grpc directory

### ISSUE THREAD

**Issue by lopezator** [getinsomnia/insomnia#5093] opened 2022-08-18 14:17 UTC
### Expected Behavior

Folder to load correctly, as is does for example in BloomRPC or ezy.

### Actual Behavior

I get this error instead:

Error: duplicate name 'SourceContext' in Namespace .google.protobuf
    at Namespace.add (/opt/Insomnia/resources/app.asar/node_modules/protobufjs/src/namespace.js:239:23)
    at Namespace.add (/opt/Insomnia/resources/app.asar/node_modules/protobufjs/src/namespace.js:232:28)
    at Root.add (/opt/Insomnia/resources/app.asar/node_modules/protobufjs/src/namespace.js:232:28)
    at Root.addJSON (/opt/Insomnia/resources/app.asar/node_modules/protobufjs/src/namespace.js:172:16)
    at process (/opt/Insomnia/resources/app.asar/node_modules/protobufjs/src/root.js:124:49)
    at /opt/Insomnia/resources/app.asar/node_modules/protobufjs/src/root.js:162:21
    at sentryWrapped (/opt/Insomnia/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js:76:23)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.5.1

### What operating system are you using?

Ubuntu

### Operating System Version

18.04

### Installation method

deb package

**Comment by filfreire** [comment] 2022-08-18 14:27
Hi @lopezator thank you for reporting this!

This might be similar problem to a handful of issues we have gRPC related - where Insomnia doesn't properly import folders that have dependencies on "external" protobuf definitions (e.g. https://github.com/Kong/insomnia/issues/4084 and https://github.com/Kong/insomnia/issues/4038).

Any chance you can share an example, like a code snippet or a public facing repository where we would be able to reproduce this?

We need to look into improving the way insomnia loads multiple files and folders for gRPC, and our other [gRPC related issues](https://github.com/Kong/insomnia/issues?q=is%3Aopen+is%3Aissue+label%3AA-grpc), but can't give you an estimate of when that will happen for now.

> Side-note: Heads up to @wongstein and @subnetmarco - this is one of the areas that we might want to look into after the ongoing WebSockets support work.

**Comment by lopezator** [comment] 2022-08-22 07:49
Sure!

Is you use this repo's `third_party` directory along with `Add directory` option in Insomnia you will get the mentioned error:

https://github.com/lopezator/insomnia-grpc-err-repro

Thank you for your quick reply!

P.D. I am also using validate, so it might be the same to #4084 but the err message it's different.

**Comment by filfreire** [comment] 2022-09-12 13:10
Closing as duplicate of #4038

**Closed as not planned by filfreire** 2022-09-12 13:10 UTC
Labels: B-bug, A-grpc, S-unverified
