### ISSUE TITLE
OAuth 2.0 Authorization Window does not respect "Validate certificates" setting

### ISSUE THREAD

**Issue by TCFox** [getinsomnia/insomnia#2778] opened 2020-10-26 04:28 UTC
**Describe the bug**
When fetching a new "authorization code" token with help from the OAuth 2.0 auth helper, if the "Authorization URL" uses a self-signed certificate, the Authorization Window appears, but is blank. This is regardless of the "Validate certificates" setting in the preferences window.

**To Reproduce**
1. Set the "Validate Certificates" setting in the preferences window to "false" (unchecked):
1. In an "OAuth 2.0" mode auth tab, enter valid settings including:
* The "grant type" field with a value of "Authorization Code"
* The "authorization URL" field pointing to an HTTPS URL which does not use a valid HTTPS certificate (such as `localhost` or `127.0.0.1`)
3. Click on 'Fetch Tokens'
1. Note the blank window appearing and no network traffic
1. Note the error in the DevTools console, despite the "Validate certificates" setting from earlier:
```
Uncaught (in promise) Error: ERR_CERT_AUTHORITY_INVALID (-202) loading 'https://127.0.0.1:5001/connect/authorize?response_type=code&client_id=insomnia&redirect_uri=https%3A%2F%2Ffake.url%2Foidc-callback&scope=openid%20profile%20email%20otherscopes&state=820813df-8ca6-4fd3-83c5-45fd3f1a5f7a'
```

**Expected behavior**
Assuming "Validate certificates" is set to false (unchecked), the Authorization Window should correctly send a request to the Authorization URL server and display the HTML response so the user can authenticate.

**Desktop:**
 - OS: macOS 10.15.7 (this might be important as this could be a macOS specific issue)
 - Installation Method: Manual Install (`.dmg` download from website)
 - App Version: Insomnia Core 2020.4.1

**Comment by msanguineti** [comment] 2020-12-04 17:20
This is a problem to me as well.

- OS: Linux (Debian 10)
- Installation method: package (apt)
- App Version: Insomnia Core 2020.5.1

error taken from the DevTools console

```
electron/js2c/renderer_init.js:130 Uncaught (in promise) Error: ERR_CERT_AUTHORITY_INVALID (-202) loading 'https://localhost/oauth2/auth?response_type=code&client_id=2f2f98594a1137e609d88b2138d687957509b4f3&redirect_uri=http%3A%2F%2F127.0.0.1%3A9010%2Fcallback&scope=openid%20offline%20a_data%20b_data&state=some_long_state_string&code_challenge=8L_xG9zVKbSa7JK_fsTlHIxovPO0TbfowYoRDO1vcuA&code_challenge_method=S256'
    at rejectAndCleanup (electron/js2c/browser_init.js:225)
    at WebContents.failListener (electron/js2c/browser_init.js:225)
    at WebContents.emit (events.js:228)
apply @ electron/js2c/renderer_init.js:130
(anonymous) @ electron/js2c/renderer_init.js:82
(anonymous) @ electron/js2c/renderer_init.js:82
emit @ events.js:223
onMessage @ electron/js2c/renderer_init.js:114
19:10:41.624 › [oauth2] did-fail-load: Loaded "https://localhost/oauth2/auth?response_type=code&client_id=2f2f98594a1137e609d88b2138d687957509b4f3&redirect_uri=http%3A%2F%2F127.0.0.1%3A9010%2Fcallback&scope=openid%20offline%20a_data%20b_data&state=some_long_state_string&code_challenge=8L_xG9zVKbSa7JK_fsTlHIxovPO0TbfowYoRDO1vcuA&code_challenge_method=S256"
19:10:41.625 › Unhandled Promise PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: Error: ERR_CERT_AUTHORITY_INVALID (-202) loading 'https://localhost/oauth2/auth?response_type=code&…, type: "unhandledrejection", target: global, …}bubbles: falsecancelBubble: falsecancelable: truecomposed: falsecurrentTarget: global {parent: global, opener: null, top: global, length: 0, frames: global, …}defaultPrevented: falseeventPhase: 0isTrusted: truepath: [global]promise: Promise {<rejected>: Error: ERR_CERT_AUTHORITY_INVALID (-202) loading 'https://localhost/oauth2/auth?response_type=code&…}reason: Error: ERR_CERT_AUTHORITY_INVALID (-202) loading 'https://localhost/oauth2/auth?response_type=code&client_id=2f2f98594a1137e609d88b2138d687957509b4f3&redirect_uri=http%3A%2F%2F127.0.0.1%3A9010%2Fcallback&scope=openid%20offline%20a_data%20b_data&state=some_long_state_string&code_challenge=8L_xG9zVKbSa7JK_fsTlHIxovPO0TbfowYoRDO1vcuA&code_challenge_method=S256'
    at rejectAndCleanup (electron/js2c/browser_init.js:225:1288)
    at WebContents.failListener (electron/js2c/browser_init.js:225:1505)
    at WebContents.emit (events.js:228:7)returnValue: truesrcElement: global {parent: global, opener: null, top: global, length: 0, frames: global, …}target: global {parent: global, opener: null, top: global, length: 0, frames: global, …}timeStamp: 1213952.0249999987type: "unhandledrejection"__proto__: PromiseRejectionEvent
setTimeout (async)
consoleLog @ /opt/Insomnia/resources/app.asar/node_modules/electron-log/src/transports/console.js:93
transport @ /opt/Insomnia/resources/app.asar/node_modules/electron-log/src/transports/console.js:46
runTransport @ /opt/Insomnia/resources/app.asar/node_modules/electron-log/src/log.js:44
runTransports @ /opt/Insomnia/resources/app.asar/node_modules/electron-log/src/log.js:27
log @ /opt/Insomnia/resources/app.asar/node_modules/electron-log/src/log.js:21
(anonymous) @ bundle.js:205778
19:10:41.626 › [ga] Event Error, Uncaught Promise
```

**Comment by judge2020** [comment] 2021-02-11 03:53
Looks like you can temporarily work around this by manually adding your localhost certificate to the trusted root authorities in Windows 10 Pro and on Chrome ([see this for firefox](https://support.mozilla.org/en-US/kb/setting-certificate-authorities-firefox)).

1. press Win+R and enter `certlm.msc`
2. press ctrl+shift+enter to run it (runs it with admin privileges)
3. Go to `Trusted Root Certificate Authorities` -> `Certificates`
4. Click Action (topbar)-> all tasks -> import
5. go through the wizard and find your localhost certificate public key, and don't change the target location

NOTE: the localhost certificate either needs to have its common name or SAN included for the hostname you're using for the browser to not throw the same certificate error.

Then you want to restart Insomnia and try to use the oauth popup. 

This really should be fixed by Kong to avoid having to trust a root certificate.

**Comment by wagner-rebello** [comment] 2021-06-17 14:46
This is SUPER needed for debug purposes.

**Comment by vvidovic** [comment] 2021-06-18 09:04
#1000 - the same issue, closed because of no activity.
There is still no solution for self-signed URLs?

**Comment by nathanjwtx** [comment] 2021-08-08 13:41
Same issue for me as well under Windows 10. Verified that token is returned via Postman.

**Comment by aarro** [comment] 2021-08-27 05:27
Also encountering this issue.

```
Version: Insomnia 2021.5.0
Release date: 8/25/2021
OS: Darwin x64 20.6.0
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0
```

```
electron/js2c/renderer_init.js:107 Uncaught (in promise) Error: ERR_CERT_COMMON_NAME_INVALID (-200) loading 'https://MYDOMAIN/connect/authorize?response_type=code&client_id=insomniaApp&redirect_uri=http%3A%2F%2Finsomnia&scope=openid&code_challenge=eNpPeL1IKGbeZbVwoiy1Idjxf85zrsHTsq8hmRej_nc&code_challenge_method=S256'
    at rejectAndCleanup (electron/js2c/browser_init.js:205)
    at Object.failListener (electron/js2c/browser_init.js:205)
    at Object.emit (events.js:327)
apply @ electron/js2c/renderer_init.js:107
(anonymous) @ electron/js2c/renderer_init.js:83
(anonymous) @ electron/js2c/renderer_init.js:83
(anonymous) @ electron/js2c/renderer_init.js:103
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:91
00:39:19.846 › [oauth2] did-fail-load: Loaded "https://MYDOMAIN/connect/authorize?response_type=code&client_id=insomniaApp&redirect_uri=http%3A%2F%2Finsomnia&scope=openid&code_challenge=eNpPeL1IKGbeZbVwoiy1Idjxf85zrsHTsq8hmRej_nc&code_challenge_method=S256"
00:39:19.847 › Unhandled Promise Error: ERR_CERT_COMMON_NAME_INVALID (-200) loading 'https://MYDOMAIN/connect/authorize?response_type=code&client_id=insomniaApp&redirect_uri=http%3A%2F%2Finsomnia&scope=openid&code_challenge=eNpPeL1IKGbeZbVwoiy1Idjxf85zrsHTsq8hmRej_nc&code_challenge_method=S256'
    at rejectAndCleanup (electron/js2c/browser_init.js:205)
    at Object.failListener (electron/js2c/browser_init.js:205)
    at Object.emit (events.js:327)
```

**Comment by develohpanda** [comment] 2021-08-27 12:58
Seems #3893 is actually a duplicate of this issue, and PR #3894 is in progress to resolve this issue. 🎉

**Comment by nathanjwtx** [comment] 2021-08-27 12:59
This does actually appear to be working for me now. I had an issue with the certificate which, when fixed, seemed to make the login /validation work as expected.

**Closed as completed** 2021-09-01 21:08 UTC
Labels: A-oauth

**Comment by MylesRip** [comment] 2023-05-26 18:49
I'm getting this error with Insomnia 2022.7.5 with build date 1/19/2023.

**Comment by ccampo133** [comment] 2025-04-22 15:04
Looks like this is still an issue even with Insomnia 11.0.2
