### ISSUE TITLE
Execute pre-request script failed: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jayantwaghulde** [getinsomnia/insomnia#8042] opened 2024-10-04 08:20 UTC
### Expected Behavior

I am looking to migrate my postman script to insomnia, but every time insomnia return 'Execute pre-request script failed: TypeError: Cannot convert undefined or null to object"  even for console.log("Hello");

### Actual Behavior

I should be able to write the script in which I can to set the response value of the GET API into the environment variable. 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 10.0.0

### What operating system are you using?

macOS

### Operating System Version

Apple M3 Pro 14.6.1 (23G93)

### Installation method

download insomnia

### Last Known Working Insomnia version

Insomnia 10.0.0

**Comment by subnetmarco** [comment] 2024-10-08 02:29
@ihexxa

**Comment by ihexxa** [comment] 2024-10-08 08:32
This issue seems to be same with #7976 , more information is included for identification.

**Comment by notjaywu** [comment] 2024-10-08 09:15
@jayantwaghulde Can you join our Slack channel https://chat.insomnia.rest, so we can DM you how to reproduce it, thanks.

**Comment by ihexxa** [comment] 2024-10-18 01:20
Hello @jayantwaghulde, would you mind to update to the latest 10.1, which will return more information to help us identify the issue, thank you.

**Comment by ihexxa** [comment] 2024-10-30 10:02
Closing this issue as no further feedback has been received.

**Closed as completed by ihexxa** 2024-10-30 10:02 UTC
Labels: B-bug, S-unverified
