### ISSUE TITLE
Passphrase issue

### ISSUE THREAD

**Issue by slipfly** [getinsomnia/insomnia#7163] opened 2024-03-11 12:33 UTC
### Expected Behavior

When I enter the password, it logs me into the insomnia app.

### Actual Behavior

When I enter the password, the error "Invalid passphrase, please try again" appears, even though the password entered is correct.

### Reproduction Steps

1. Open the app
2. Click on "Continue with google" button
3. Get redirection to "Enter your existing passphrase" window in the browser
4. Enter the passphrase
5. Get "Invalid passphrase, please try again" error

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.1

### What operating system are you using?

Windows

### Operating System Version

Win 10

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

8.6.1

**Comment by sabudilovskiy** [comment] 2024-03-12 09:27
I literally just changed the password on the site, entered it again - I got an error.

**Comment by subnetmarco** [comment] 2024-03-13 14:01
@marckong

**Comment by ElamanBaiguanishev** [comment] 2024-03-19 14:57
The same problem, it seems the developer has blocked access for people from Russia

**Comment by marckong** [comment] 2024-03-20 14:16
@sabudilovskiy @ElamanBaiguanishev @slipfly 
Would you guys like to jump on a call with us and troubleshoot? Please shoot me a DM in our Slack channel.

**Comment by slipfly** [comment] 2024-03-20 14:53
@marckong I guess I can't join your Slack channel due to the fact that I'm from Russia.

**Comment by filfreire** [comment] 2024-03-22 10:16
Hi folks, we are not actively blocking anything, but it might be one of the services we use that might be causing this issue.

Please try to `dig` or similar/relevant command to see if you can reach the IPs that Insomnia "touches" (see [this doc for info](https://docs.insomnia.rest/insomnia/enterprise-ip-whitelist-guide#for-it-administrators))

example
```
dig +short insomnia.rest
dig +short ai.insomnia.rest
dig +short api.insomnia.rest
dig +short docs.insomnia.rest
dig +short updates.insomnia.rest
dig +short auth.insomnia.rest
dig +short insomnia-prod.us.auth0.com
dig +short djvq2ky33rnc.cloudfront.net
dig +short api.segment.io
dig +short o1147619.ingest.sentry.io
```

If one of these fails please let us know 👍 

cc @marckong @subnetmarco  - I suspect it might be what some users mentioned above and also in Support, that it's some sort of geo-block perhaps on Auth0, and want to confirm if it is the case.

**Comment by slipfly** [comment] 2024-03-22 10:37
@filfreire I've tried to ping this and the only one ip I couldn't reach is api.segment.io

**Comment by marckong** [comment] 2024-03-22 12:25
@filfreire at the point the user sees the "Enter Passphrase" means it is already authenticated through the API. The passphrase is something Insomnia Desktop app requires to encrypt and decrypt the Insomnia resource data.

@slipfly we are not doing anything create with your passphrase. In my experience, all the cases that I've jumped on the call turned out that they actually forgot their passphrases. You can alternatively click Forgot Passphrase and reset it. Have you tried it?

**Comment by slipfly** [comment] 2024-03-22 12:40
@marckong I've tried it few times, it doesn't work

**Comment by marckong** [comment] 2024-03-22 14:10
@slipfly I don't know what else to offer than jumping on a call to troubleshoot it.

**Comment by marckong** [comment] 2024-03-22 14:16
Please provide us with an email we can send an invite. Thanks.

**Comment by slipfly** [comment] 2024-03-22 14:51
@marckong slipfly@gmail.com

**Comment by marckong** [comment] 2024-03-22 15:00
@slipfly sent an email invite. Please feel free to propose a new time.

**Comment by slipfly** [comment] 2024-03-22 15:04
@marckong yes, I got your email, and this meeting was yesterday. I guess, today would be more convenient)

**Comment by marckong** [comment] 2024-03-22 15:28
Just jumped on a call with @slipfly. Nothing is wrong with passphrase flow. We will close this issue as there was no issue. 

Going forward, for those who may look into the same issue in the future, it really is the user's end. When users see the "invalid passphrase" error message, it really is a different passphrase the user used to create an encryption with. Please make sure you keep the original passphrase.

There is nothing that we changed in the code in this regards. The code for end-to-end encryption has been always there, and the actual logic was not touched at all with all the paddings and hmac key derivation. Salt value is generated when a user creates encryption passphrase out of the secret that the user has typed. We store that salt value in the database, so we can derive the same value using the same key (that users type). There shouldn't be any issue as long as same salt and key are provided. Salt is static as it's stored in our database, but the key relies on the user's memory.

If you find an issue with the original implementation (I am not the original implementer), please file an issue. Then I will take a look at it. However, I will not be jumping onto another call to troubleshoot passphrase issues. I will re-surface this thread for any future issue about invalid passphrase error message issue and close the issue.

We are also looking to remove the passphrase at all in the near future as this has been significant amount of pain for us, maintainers.

**Closed as completed by marckong** 2024-03-22 15:28 UTC
Labels: B-bug, S-unverified

**Comment by monecchi** [comment] 2024-08-26 01:10
I'm using Insomnia latest version. I've enabled E2EE a few months ago and when authorizing Insomnia on Windows or Mac using my Google account, the E2EE passphrase simply does not work! I always get the "Invalid Passphrase" error. I've tried reseting it a few times with no success. Also, I've tried to disable it but it is not possible, so I'm stuck with its broken functionality.

**Comment by tunahankabakci** [comment] 2024-08-26 09:30
I only use email address to login and the same thing happened to me. I can't log in right now.

**Comment by notjaywu** [comment] 2024-08-26 11:11
@monecchi @tunahankabakci Could you join this Slack channel https://chat.insomnia.rest? So I can DM you for your account email address, it helps us identify the root cause.

**Comment by tcarolan** [comment] 2025-09-09 15:27
Desktop app required authentication, redirected to website, entered email/password, and then asked to enter passphrase. My passphrase was recorded in a password manager app. I'm 100% certain my passphrase is correct but it still says "Email or password invalid" - The error message is misleading - I'm entering the passphrase. But in any case, the flow is not working. There is something wrong, definitely. 

<img width="763" height="415" alt="Image" src="https://github.com/user-attachments/assets/d8c0f4b7-7ba1-4486-813b-7b1f32766c70" />

**Comment by kulor** [comment] 2025-10-20 14:01
Getting the same as [tcarolan](https://github.com/tcarolan). Essentially locked out. I stored my passcode in my password manager as I don't trust my memory so I know it's the correct passphrase. Also getting the invalid email or password error.
All `dig`s mentioned above work for me.
