### ISSUE TITLE
Auto-complete box is all over the place and won't close, and a completely blank UI window

### ISSUE THREAD

**Issue by QAnders** [getinsomnia/insomnia#6992] opened 2024-01-17 07:15 UTC
### Expected Behavior

When typing in a URL I'd expect the auto-complete list/box to pop up under the URL textbox after the set delay (1200 ms) and disappear after I typed the text, leave the textbox or tapping ESC key

### Actual Behavior

The auto-complete box opens over the toolbar, or over the saved request list on the left. The auto-complete box stays open on top of the UI hiding some menus and/or requests and is not being closed even if I switch request in the list.
The only way to close it is to click something in the list, which inserts the clicked URL in the uRL textbox (even though I don't want it there).

Sometimes, after this has happened a few times the whole UI window just becomes blank, nothing there at all, just blank window.

### Reproduction Steps

Open Insomnia Rest, select a request and type in some URL, then keep doing that a while. Sometimes it works for a few hours before it starts acting up.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

 v2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 22631.3007

### Installation method

Insomnia download + auto updates

### Last Known Working Insomnia version

Not sure, maybe 5-6 months ago

**Comment by gatzjames** [comment] 2024-01-31 18:42
👋 @QAnders thanks for the issue. I can't seem to reproduce the issue.
Can you try the latest version and verify that it's still happening for you?
- If it does any logs you could share when this error happens would be great help to figure this issue. You can open the DevTools by opening `View > Toggle DevTools` and find any errors that get logged to the Console.

**Comment by QAnders** [comment] 2024-02-01 14:08
Yes, latest installed and just got this one:
![image](https://github.com/Kong/insomnia/assets/12028885/d5d2768f-200e-45d5-93b4-d2749bf21746)

And a bit later this:
![image](https://github.com/Kong/insomnia/assets/12028885/13f7beb9-e69c-4da7-b391-6211d8b2bcff)

The pop-up is not disappearing unless I click it, and when I click it it always adds the URL in the middle of the already existing URL.

There's no errors in console

**Comment by gatzjames** [comment] 2024-02-06 15:24
Hey @QAnders we just released 8.6.1 containing some updates on how the autocomplete renders on the app.
Can you check if this issue is still happening to you?

**Comment by gatzjames** [comment] 2024-02-23 12:24
Closing as I can't reproduce. If this issue persists feel free to reopen so that we can debug and fix it!

**Closed as completed by gatzjames** 2024-02-23 12:24 UTC
Labels: B-bug, S-unverified
