### ISSUE TITLE
[Bug] Fragments in GraphQL request are always grayed out 

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#1069] opened 2018-07-25 10:11 UTC
- Insomnia Version: 6.0.0
- Operating System: Windows 10

## Details
[Bug] Fragments in GraphQL request are always grayed out: 
![image](https://user-images.githubusercontent.com/38757986/43194860-1a13fc5e-900c-11e8-9683-293efcefb81e.png)

Caused by https://github.com/getinsomnia/insomnia/pull/990.

**Comment by gschier** [comment] 2018-07-25 15:32
I can't reproduce this. Can you send me that example query?

**Comment by gschier** [comment] 2018-07-25 15:32
Ohhh, fragments. Hmm. I should be able to fix that

**Comment by gschier** [comment] 2018-07-25 15:39
Will be released today 😄

**Closed** 2018-07-25 15:38 UTC
