### ISSUE TITLE
Press and Hold not working on Vim keymap (on MacOS)

### ISSUE THREAD

**Issue by alk-mandrianarijaona** [getinsomnia/insomnia#3448] opened 2021-06-04 08:17 UTC
**Describe the bug**
When I enable Vim keymap, long pressing a move key (`j` or `k` for instance) only moves the cursor once.

**To Reproduce**
1. Go to 'Settings', enable Vim keymap in Text Editor Key Map
2. Open a request body and long press `j`
3. The cursor only moves one line down

**Expected behavior**
The cursor should keep moving down until I stop pressing the key

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Installation Method: Download
 - App Version: 2021.3.0

**Additional context**
I tried to run command `defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool true` and restart Insomnia but it did not work

**Comment by dimitropoulos** [comment] 2021-06-04 15:59
are you able to run insomnia locally and give this a try?  I ask because we just updated CodeMirror and some of the notes mentioned updates about vim bindings.

**Comment by alk-mandrianarijaona** [comment] 2021-06-07 07:58
hello @dimitropoulos, you want me to try running Insomnia from this repo instead of release, right? If so, I can try that

**Comment by dimitropoulos** [comment] 2021-06-07 15:52
yes, please.  let me know if you need any help :)

**Comment by alk-mandrianarijaona** [comment] 2021-06-09 07:53
@dimitropoulos I have just launched insomnia from `develop` branch and I have the same behaviour when using Vim keybinding

**Comment by dimitropoulos** [comment] 2021-06-09 12:18
dang.  ok.  thanks for taking a look.

I can confirm that this doesn't happen on the codemirror vimbindings demo https://codemirror.net/demo/vim.html so that means it's something wrong on our side since we're on the latest codemirror (now).

**Comment by dimitropoulos** [comment] 2021-06-09 12:29
https://user-images.githubusercontent.com/15232461/121354208-a9bd4780-c8fc-11eb-8c92-0529c440ec58.mp4

Actually, for me (on linux) this appears to be working as intended.  In the above video I'm holding `j`.

@reynolek or @develohpanda can you please try real quick on mac and see if you have the same results?

**Comment by MrSnix** [comment] 2021-06-14 16:27
Hi @dimitropoulos, this appears to be a bug related to CodeMirror for MacOS.
I did exactly as stated (on my macOS), but it moves only one line; meanwhile, it works as expected on my Windows laptop.

Codemirror website:

![Jun-14-2021 18-12-12](https://user-images.githubusercontent.com/20780192/121925144-e47c1100-cd3c-11eb-9824-0f477be56024.gif)

Latest `develop` branch:

![Jun-14-2021 18-22-46](https://user-images.githubusercontent.com/20780192/121925897-aa5f3f00-cd3d-11eb-90b0-2e9d0803c9e7.gif)

In both video I'm holding `j`


**EDIT**: Same issue with `k`

**Comment by dimitropoulos** [comment] 2021-06-14 18:43
thanks @MrSnix!

well, haha @develohpanda I guess that means you're gonna get this one whenever the time comes.  (I don't have access to a Mac device)

**Comment by develohpanda** [comment] 2021-06-14 20:01
Are there any bug reports on the code mirror repo along these lines?

**Comment by reynolek** [comment] 2021-06-14 20:13
Looks like a bug in code mirror -- Went their vim bindings demo on their website (https://codemirror.net/demo/vim.html) and the same bug happens on mac, but it works on windows

**Comment by dimitropoulos** [comment] 2021-06-14 20:35
ohhh my bad, I misread to be that it _doesn't_ also happen on the codemirror website.  I guess the next step then for us is to file an issue with them if one doesn't already exist and close this ticket.

**Comment by MrSnix** [comment] 2021-06-14 20:52
> ohhh my bad, I misread to be that it _doesn't_ also happen on the codemirror website.  I guess the next step then for us is to file an issue with them if one doesn't already exist and close this ticket.

I think we may remap the k and j button in the meantime to behave like an arrow key (that has the same function of k and j) ... I have seen some api on CodeMirror to remap keys, I think it may work but I gotta give it a shot. It should be possible to make it available only for the Vim mode. 

What do you guys think? As workaround?

**Comment by develohpanda** [comment] 2021-06-14 21:54
@MrSnix because it's not an urgent bug fix needed for Insomnia I think the best approach will be to push this through an official fix on codemirror and only if the fix is no accepted there we think about a workaround through Insomnia. This does seem like a genuine bug so others will benefit from it too!

And I think we shouldn't close this ticket necessarily, since it is a valid bug in Insomnia, but maybe mark as blocked on a dependency. It will still require a code-mirror update to Insomnia, and that update PR can close this issue.

**Comment by develohpanda** [comment] 2021-06-14 22:06
Related issue on codemirror: https://github.com/codemirror/CodeMirror/issues/3678 (which suggests updating the mapping)

**Comment by reynolek** [comment] 2021-06-14 22:23
Changing the OSX level variable mentioned in that PR does in fact fix vim mode in insomnia (after a restart of insomnia)

**Comment by develohpanda** [comment] 2021-06-14 23:24
~~Maybe we do that then, update that config in Insomnia, given it was a known bug in codemirror that has been closed in the past~~ looks like this is setting an OS level variable, which... Seems a bit finicky. I wonder if there is a clean codemirror fix we can contribute downstream

**Comment by MrSnix** [comment] 2021-06-14 23:51
@develohpanda,I have a great news. I think we can handle this through Electron.js itself. 

Just look at their api: [System Preferences](https://www.electronjs.org/docs/api/system-preferences#systempreferencessetuserdefaultkey-type-value-macos)

The flag we need is even mentioned in their doc.

What do you think?

I didn't give an in depth look but it seems cool.

**Comment by develohpanda** [comment] 2021-06-14 23:53
@MrSnix wow nice sleuthing, TIL electron can override variables like that. Let's give it a go!

**Comment by MrSnix** [comment] 2021-06-14 23:56
> @MrSnix wow nice sleuthing, TIL electron can override variables like that. Let's give it a go! 

If okay then, I'd love to pick this up, I'll make a PR to introduce this change.

**Comment by dimitropoulos** [comment] 2021-06-15 12:31
Very exciting stuff.  Not only this fix, but I also love to see all the teamwork and collaboration happening here.  If we do find a fix we should go back to https://github.com/codemirror/CodeMirror/issues/3678 and mention what we did (pointing back to the PR).

**Comment by MrSnix** [comment] 2021-06-15 17:50
@dimitropoulos @develohpanda

Quick update:

The electron interface works like a charm. 

I'll commit the fix in a few hour.
It's a one liner and it works really really well.

Yuppie

**Closed as completed** 2021-06-17 13:32 UTC
Labels: O-macos, B-bug, S-verified

**Comment by develohpanda** [comment] 2021-06-17 16:36
As the PR title suggests, we chose not to automatically override any settings, rather provide a helpful tooltip and link to the documentation [here](https://support.insomnia.rest/article/203-key-maps) to enable key-repeating on macOS.
