### ISSUE TITLE
[Plugins] Add `requestActions` actions support

### ISSUE THREAD

**Issue by devhammed** [getinsomnia/insomnia#2759] opened 2020-10-21 14:43 UTC
**Is your feature request related to a problem? Please describe.**

Currently, the plugin API support adding items to Workspace and Request Groups context menu but it is not supported for Requests and now since there is no builtin support for API testing for Insomnia Core. I am writing a plugin that does just that (almost done actually) but the problem is that I am forced to only hook to Request Groups to register the testing code editor modal.

**Describe the solution you'd like**

There should be `requestActions` just like there is for `requestGroupActions` and `workspaceActions`.

**Describe alternatives you've considered**

Above solution is the only one I can think of.

**Additional context**

Repository: https://github.com/devhammed/insomnia-plugin-api-testing

Plugin in Action:

![deepin-screen-recorder_google-chrome_20201021154200](https://user-images.githubusercontent.com/22827908/96736007-13133900-13b4-11eb-8b6e-fe19aa533cec.gif)

**Comment by jgiovaresco** [comment] 2020-10-21 15:47
I think it is a duplicate of #2119
On the good side, a PR (#2678) is already open to fix that 🎉

**Comment by devhammed** [comment] 2020-10-22 06:19
> I think it is a duplicate of #2119
> On the good side, a PR (#2678) is already open to fix that 🎉 

I can see 😁😁😁

Can you please accelerate work on merging it so my plugin can finally be ready for use because I personally would prefer setting test for each request than on a request group.

**Comment by DMarby** [comment] 2021-01-20 15:36
Closing this as the PR fixing #2119 has now been merged

**Closed as completed by DMarby** 2021-01-20 15:36 UTC
