### ISSUE TITLE
[Bug] Error: Failed writing received data to disk/application

### ISSUE THREAD

**Issue by mxmlnglt** [getinsomnia/insomnia#1476] opened 2019-05-02 09:15 UTC
- Insomnia Version: see below (copy of the About popup)
- Operating System: Windows 10 Pro (64-bit)

[Content]
Version 6.4.2
Shell 3.0.4
Node 10.2.0
V8 6.6.346.32
Architecture x64

libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV

## Details

When issuing a "simple" PUT request on an (internal) API, Insomnia retrieves the response (JSON) but can't display it, just an "Error: Failed writing received data to disk/application", whichever preview mode I select (Visual Preview, Source Code, Raw Data). Also I can't save either Response Body or Full Response, no file is created (in a folder where Insomnia has write access i.e. %UserProfile%\Downloads )
While at the same time, using another REST client, like AdvancedRestClient - https://advancedrestclient.com - I can see the returning data.

Moreover it doesn't appear to be an installation problem (which I thought at first), because targetting the https://swapi.co/ API works (well, it only has GET methods).

By the way, the response is simple as:
```
{"results":{"TypeStructure":[{"IdTypeStructure":6,"TypeStructure":"Réelle"},{"IdTypeStructure":7,"TypeStructure":"Coquille"}]}}
```

Below is the timeline:

```
* Preparing request to http://swrapptal01:8040/services/mdm/querymdm/query/
* Using libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 1 cookie
* Hostname swrapptal01 was found in DNS cache
*   Trying 172.16.136.73...
* TCP_NODELAY set
* Connected to swrapptal01 (172.16.136.73) port 8040 (#14)
* Server auth using Basic with user 'admin@company.com'

> PUT /services/mdm/querymdm/query/ HTTP/1.1
> Host: swrapptal01:8040
> Authorization: Basic YWRtaW5AY29tcGFueS5jb206YWRtaW4=
> User-Agent: insomnia/6.4.2
> Content-Encoding: UTF-8
> Content-Type: application/json
> Accept: */*
> Content-Length: 47

| {
| 	"select": {
| 		"from": ["TypeStructure"]
| 	}
| }

* upload completely sent off: 47 out of 47 bytes

< HTTP/1.1 200 OK
< Content-Encoding: UTF-8
< Content-Type: application/json
< Date: Thu, 02 May 2019 07:52:42 GMT
< Transfer-Encoding: chunked
< Server: Jetty(9.3.24.v20180605)


* Received 138 B chunk
* Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.
* Failed writing data
* Closing connection 14
```

**Comment by gschier** [comment] 2019-05-04 19:19
This is basically a duplicate of #1025 

Insomnia uses `libcurl` to send requests, which is rather strict on content encoding types. Your server is returning a `Content-Encoding` header of `UTF-8` which is not a valid value.

**Closed** 2019-05-04 19:19 UTC

**Comment by tomtheisen** [comment] 2020-01-22 18:16
The same problem also occurs with `Content-Encoding: br`, which *is* valid.  Removing `br` from the `Accept-Encoding` request header solved this problem for me.
