### ISSUE TITLE
Generate Code and Copy as Curl producing the wrong result

### ISSUE THREAD

**Issue by LeeBear35** [getinsomnia/insomnia#1921] opened 2020-01-31 19:36 UTC
**Describe the bug**
When a POST request is duplicated, in this case a Multipart Form, and the file is changed **Generate Code** and **Copy as Curl** both refer back to the original file when the first POST was created not the current values.

**To Reproduce**
1. Go to **New Request**
2. Create a **POST** request 
3. Set Request to Multipart and specify a file to upload
4. Copy the request and change the file to upload
5. Click **Generate Code** and it will show the first file.

**Expected behavior**
**Generate Code** and **Copy as Curl** would both generate based on the current settings not a set of prior setting from a copy.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: Install Package
 - App Version 7.0.6

**Additional context**

**Comment by jgiovaresco** [comment] 2020-10-30 15:06
👋  @LeeBear35 

I can't reproduce the issue on Mac nor Linux.

Besides, there is an open issue related to cUrl & multipart (https://github.com/Kong/insomnia/issues/2282). I've used the [fixed version](https://github.com/Kong/insomnia/pull/2740) to try to reproduce the issue.

Therefore, I suggest to wait for the fix to be released, and hopefully, it should be fixed. 🤞

**Closed as completed** 2022-07-28 11:14 UTC
Labels: needs-triage
