### ISSUE TITLE
Can't rearrange requests

### ISSUE THREAD

**Issue by marko-otasevic-dev22** [getinsomnia/insomnia#6341] opened 2023-08-21 07:02 UTC
### Expected Behavior

User can drag and drop requests in custom order or sort by using the button at the top

### Actual Behavior

Drag and drop doesn't work and sort does not as well

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.5

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.4.1

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment] 2023-08-21 07:03
Duplicate of https://github.com/Kong/insomnia/issues/6284

**Closed as completed by filfreire** 2023-08-21 07:03 UTC
Labels: B-bug, S-unverified
