### ISSUE TITLE
A necessary tool bar is needed for pine endpoints. 

### ISSUE THREAD

**Issue by mattpding11** [getinsomnia/insomnia#7912] opened 2024-09-04 10:10 UTC
### Expected Behavior

Hello Insomnia team, best regards, my name is Mateo and I am writing this message because I have a request or suggestion about the insomnia application for MAC,
**A tool bar is needed to organise the pinned endpoints**

### Actual Behavior

I tell you, when I have several endpoints to which I have indicated the action of “PIN” as shown in the image are added up right, as if they were favorites to access them easily, the problem with this is that when I give PIN to many endpoints then the folders where I have organized the other endpoints of my project are departed, ie the more items I have pineados is becoming less visible and accessible my folders with my endpoints, which apparently is missing a “SCROLL BAR” in this toolbar,

![252a8c2e-7dd2-4be1-8d62-dda48469253c](https://github.com/user-attachments/assets/152e2fdb-5623-4db3-ac6e-9ec5922becda)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.3

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma v.14.5

### Installation method

dmg

**Comment by subnetmarco** [comment] 2024-09-12 11:52
Duplicate of https://github.com/Kong/insomnia/issues/7914

**Closed as completed by subnetmarco** 2024-09-12 11:52 UTC
Labels: B-bug, S-unverified
