### ISSUE TITLE
303 See Other response uses original Method instead of GET

### ISSUE THREAD

**Issue by tilmans** [getinsomnia/insomnia#374] opened 2017-07-24 13:00 UTC
## Overview
- `Insomnia Version:` 5.6.3.750
- `Operating System:`  MacOS 10.12.5 (16F73)
- `Summary: ` I have a REST API which responds to an authentication POST with a 303 to a resource that should be used after successful login to load access tokens. The resource is POSTed to instead of calling GET which causes an error. Postman does a GET which works correctly. I'm not sure if this is according to specification but it makes the login to the API very cumbersome.

## How To Reproduce
Can't provide access to the API unfortunately but below is the Timeline of the request:

```
* Preparing request to https://10.129.156.79:443/api/auth/login
* Enable automatic URL encoding
* Disable SSL validation
* Enable cookie sending with jar of 8 cookies
* Connection 2 seems to be dead!
* Closing connection 2
*   Trying 10.129.156.79...
* TCP_NODELAY set
* Connected to 10.129.156.79 (10.129.156.79) port 443 (#3)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: ...

> POST /api/auth/login HTTP/1.1
> Host: 10.129.156.79
> User-Agent: insomnia/5.6.3
> Accept-Encoding: deflate, gzip
> Cookie: JSESSIONID=1k2xbxexwhuu71tlelhkecvwxi; avidAccessToken=ODAwZWY3OTEtOWMyNy00N2U0LWI1Y2MtOTM1ZmU4N2Q3NDMz
> Content-Type: application/json
> Accept: application/json
> Forwarded: proto=https;host=10.129.156.79:443
> Content-Length: 56
| {
| 	"username": "...",
| 	"password": "..."
| }
* upload completely sent off: 56 out of 56 bytes

< HTTP/1.1 303 See Other
< Server: nginx
< Date: Mon, 24 Jul 2017 12:51:54 GMT
< Content-Length: 0
< Connection: keep-alive
* Replaced cookie JSESSIONID="1py7va91drof5vzxfh5fj0pmo" for domain 10.129.156.79, path /, expire 0
< Set-Cookie: JSESSIONID=1py7va91drof5vzxfh5fj0pmo;Path=/;Secure;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
* Replaced cookie avidAccessToken="MGY4ZjhiZmItMmFiMy00ODY0LTgwN2QtMGFkMTkzMWE2ZmU5" for domain 10.129.156.79, path /, expire 0
< Set-Cookie: avidAccessToken=MGY4ZjhiZmItMmFiMy00ODY0LTgwN2QtMGFkMTkzMWE2ZmU5;Version=0;Path=/
< Location: https://10.129.156.79/auth/tokens/current
< X-Request-URL: /api/auth/login

* Curl_http_done: called premature == 0
* Connection #3 to host 10.129.156.79 left intact
* Issue another request to this URL: 'https://10.129.156.79/auth/tokens/current'
* Disables POST, goes with GET
* Found bundle for host 10.129.156.79: 0x7ffdcc100730 [can pipeline]
* Re-using existing connection! (#3) with host 10.129.156.79
* Connected to 10.129.156.79 (10.129.156.79) port 443 (#3)

> POST /auth/tokens/current HTTP/1.1
> Host: 10.129.156.79
> User-Agent: insomnia/5.6.3
> Accept-Encoding: deflate, gzip
> Cookie: JSESSIONID=1py7va91drof5vzxfh5fj0pmo; avidAccessToken=MGY4ZjhiZmItMmFiMy00ODY0LTgwN2QtMGFkMTkzMWE2ZmU5
> Content-Type: application/json
> Accept: application/json
> Forwarded: proto=https;host=10.129.156.79:443

< HTTP/1.1 405 Method Not Allowed
< Server: nginx
< Date: Mon, 24 Jul 2017 12:51:54 GMT
< Content-Type: application/vnd.avid.problem+json; charset=utf-8
< Content-Length: 199
< Connection: keep-alive
< Allow: GET, DELETE
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache

* Received 199 B chunk
* Curl_http_done: called premature == 0
* Connection #3 to host 10.129.156.79 left intact
* Saved 2 cookies
```

**Comment by gschier** [comment] 2017-07-24 17:29
Thanks for reporting this @tilmans 😄 

Closing this issue, though, as it is a duplicate of #227

**Closed by gschier** 2017-07-24 17:29 UTC
