### ISSUE TITLE
Request summary didn't update when switching design to debug tab

### ISSUE THREAD

**Issue by pebie** [getinsomnia/insomnia#5439] opened 2022-11-18 11:43 UTC
### Expected Behavior

Insomnia document use summary field of an OpenAPI Paths Object to name Requests in the debug tab.

**OpenAPI Spec (design tab)**
```yaml
paths:
  /pet:
    post:
      tags:
        - pet
      summary: Add a new pet to the store
      operationId: addPet
      requestBody:
        $ref: "#/components/requestBodies/Pet"
      responses:
        "405":
          description: Invalid input
```
**Request (debug tab)**
![Capture d’écran 2022-11-18 à 12 20 31](https://user-images.githubusercontent.com/4931752/202694247-c07c72bb-02f4-43ea-837b-02b8b1ae5009.png)

Updating Paths Object summary should always update the Request name in the debug tab when switching design tab to debug tab.

**OpenAPI Spec (design tab)**
```yaml
paths:
  /pet:
    post:
      tags:
        - pet
      summary: Add a new pet to the store (update)
      operationId: addPet
      requestBody:
        $ref: "#/components/requestBodies/Pet"
      responses:
        "405":
          description: Invalid input
```

**Request (debug tab)**
![Capture d’écran 2022-11-18 à 12 25 26](https://user-images.githubusercontent.com/4931752/202694891-a8e211ef-82b4-40d1-8d08-37cfa159c30c.png)

### Actual Behavior

The Request name in debug tab won't update unless I remove it using Insomnia UI, switch back to design tab then switch again to debug tab.

### Reproduction Steps

Assuming you have an existing OpenApi Spec in your design tab and using summary to name your Requests in debug tab.

1. Go to design tab
2. Update the summary of one of your Paths Object 
3. Go to debug tab 

The Request name should have change but it won't.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Notice that I've a [similar problem](https://github.com/Kong/insomnia/issues/3968) before using OpenApi Paths Object summary. Since I use `operationId` I choose to use summary to name Request in debug Insomnia's tab.

I suppose `importRequest` method should be recall when switching between tabs ? 

https://github.com/Kong/insomnia/blob/fb97b17e50675ab1e892cbfe74a50aaa978dfd59/packages/insomnia-importers/src/importers/swagger-2.ts#L135

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

 Darwin x64 21.6.0

### Installation method

Download from insomnia web page

**Comment by filfreire** [comment] 2022-11-18 12:54
Hi @pebie thank you for reporting this. This is a duplicate of #4373

Feel free to report other issues you come across.

**Closed as completed by filfreire** 2022-11-18 12:54 UTC
Labels: B-bug, S-verified

**Comment by pebie** [comment] 2022-11-18 14:28
Hi @filfreire and thanks for answer :)

My point concerne only the update method of Request name. Other [issue](https://github.com/Kong/insomnia/issues/4373) try to sync Tags with folder when an operation move from tag to another tag (name included indeed).

I think updating only Request name with summary will be a good start before trying sync tags and operation with Requests Groups and Requests.

But thank you very much I'll watching @mugi-luffy issue :)

https://github.com/Kong/insomnia/issues/4373
