### ISSUE TITLE
[Feature Request] Refetching the schema doesn't refresh the currently open docs page

### ISSUE THREAD

**Issue by ranjan-purbey** [getinsomnia/insomnia#2014] opened 2020-03-29 19:20 UTC
When a user re-fetches the schema with one of schema docs page already open, the page doesn't refresh after a successful request. The only way to reload the docs is to either close the docs panel and re-open it, or to go back to the root query and navigate to the page again.

It will be really helpful, especially in early prototyping stage of an API to refresh the page automatically.

**Comment by gschier** [comment] 2020-03-30 23:34
Oh, this is actually a duplicate of #1966

**Closed as completed by gschier** 2020-03-30 23:34 UTC
Labels: M-duplicate
