### ISSUE TITLE
[Feature Request] Sortable Sub Environments

### ISSUE THREAD

**Issue by Gabb1995** [getinsomnia/insomnia#630] opened 2017-11-27 11:14 UTC
Really just a small request, can we have sub environments sortable? Meaning that I can move them around in the Manage environments tab just like the requests side bar in the main interface?

![screenshot from 2017-11-27 12 13 59](https://user-images.githubusercontent.com/20728259/33264094-7adafb76-d36c-11e7-994e-efb22f10be65.png)

So in this screenshot I'd be able to push the Staging sub environment under Develop New User.

**Comment by gschier** [comment] 2017-11-27 13:05
Closing this as a duplicate of #162

**Closed by gschier** 2017-11-27 13:05 UTC
