### ISSUE TITLE
[Feature Request] Search function in Schema Explorer

### ISSUE THREAD

**Issue by nora-liza** [getinsomnia/insomnia#1987] opened 2020-03-06 15:59 UTC
It's difficult to scroll and search for specific Graphql requests with the current Schema explorer. It would be great if there's a search function similar to Altair:
![image](https://user-images.githubusercontent.com/42729493/76099719-7b203500-6006-11ea-9f21-9e04e8b3ba38.png)

**Comment by gschier** [comment] 2020-03-09 21:18
Duplicate of #1620

**Closed as completed by gschier** 2020-03-09 21:18 UTC
Labels: M-duplicate
