### ISSUE TITLE
[Bug] URL field and SEND button font size not respect changes

### ISSUE THREAD

**Issue by the-csaba** [getinsomnia/insomnia#2530] opened 2020-08-20 08:13 UTC
**Describe the bug**
Preference changes not applying to the URL text field and the SEND button. Neither the Interface Font Size, neither the Editor Font Size. They always stay the same.

**To Reproduce**
1. Go to Preferences
2. Change Interface Font Size
3. Go back to the main window

**Expected behavior**
The Interface Font Size change the URL field and the SEND button font size.

**Screenshots**
9px:
<img width="278" alt="8px" src="https://user-images.githubusercontent.com/45931795/90733298-ec2a7f00-e2fe-11ea-999c-5d81daf4c3e4.png">
20px:
<img width="596" alt="20px" src="https://user-images.githubusercontent.com/45931795/90733437-1ed47780-e2ff-11ea-96de-54e19e96c0a9.png">

**Desktop:**
 - OS: macOS 10.15.6
 - Installation Method:  homebrew
 - App Version: 2020.3.3

**Comment by develohpanda** [comment] 2020-08-20 08:28
Duplicate of https://github.com/Kong/insomnia/issues/2492, but I will leave it open 👍 Thanks for the report!

**Comment by Innoxious** [comment] 2020-12-09 10:01
@develohpanda this has been fixed 🎉

**Comment by develohpanda** [comment] 2020-12-09 10:37
Closed! Ty @Innoxious ❤️

**Closed as completed by develohpanda** 2020-12-09 10:37 UTC
Labels: M-duplicate, A-accessibility, A-ui-ux, B-bug
