### ISSUE TITLE
Dynamic variables taken from response body usually does not work

### ISSUE THREAD

**Issue by Marcin-Marczak** [getinsomnia/insomnia#8166] opened 2024-11-11 00:13 UTC
### Expected Behavior

Scripts => After response, code like this:

const responseBody = insomnia.response.json();
const campaignUuid = responseBody.uuid;
insomnia.environment.set("campaignUuid", campaignUuid);

should work always when you fetch this variable in next request

### Actual Behavior

(please see first "reproduction steps" below)
====
Request 11 is always failing, due to lack of campaignUuid, 
it is shown in Console:
PUT /api/v2/adops/campaigns//orders/c82ff606-48a1-4c05-b416-4a7097e35e86/line-items/e73f5724-9a09-410c-974c-c4d9c14ae5ca/ HTTP/1.1
(so notice lack of campaignUuid after "campaigns" - it's just empty. no value)

BUT:
a) In environment variable there are both variables:
"campaignUuid": "377270e0-c864-4426-9339-83a3f04f90c1",
“lineItemUuid": "e73f5724-9a09-410c-974c-c4d9c14ae5ca"

b) Log in console, regarding to Pre-request (see reproduction step below)
* ------ Start of request (Update line item) ------
* log: "Campaign uuid taken from env variables is: 377270e0-c864-4426-9339-83a3f04f90c1"
* log: "So if you see uuid in log above- it means that there is campaignUuid in env variables !"

### Reproduction Steps

FOLDER THAT CONTAINS 11 REQUESTS	

Request 6 => Scripts => After response, my code:
const responseBody = insomnia.response.json();
const campaignUuid = responseBody.uuid;
insomnia.environment.set("campaignUuid", campaignUuid);

Request 8 => Scripts => After response, my code:
const responseBody = insomnia.response.json();
const lineItemUuid = responseBody.uuid;
insomnia.environment.set("lineItemUuid", lineItemUuid);

Request 11 – this is request that is using environment variables above
a) request url:
{{baseUrl}}/v2/adops/campaigns/{{campaignUuid}}/orders/{% response 'body', 'req_7cddce9cfe6b405782a59fcacba9a586', 'b64::JC51dWlk::46b', 'never', 60 %}/line-items/{{lineItemUuid}}/

b) Scripts => Pre-request, my code:
const myCampaignUuid = insomnia.environment.get("campaignUuid");
console.log(`Campaign uuid taken from env variables is: ${myCampaignUuid}`);
console.log("So if you see uuid in log above- it means that there is campaignUuid in env variables !")

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This is only one example, it occurs for other data fetched from response body as well.

Of course I am fully aware if feature "variable tag" available when you type "response -> body -> Body Attribute".

But the thing is: If you must duplicate whole folder and use the same requests (plus some new of course) - it's a medieval torture to change manually all "body atrributes" in all places. 

### Insomnia Version

10.1.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.5 LTS

### Installation method

sudo snap install insomnia

**Comment by ihexxa** [comment] 2024-11-12 06:00
Hello @Marcin-Marczak Could you check if `campaignUuid` is defined at the folder-level environment with empty string? As you mentioned "FOLDER THAT CONTAINS 11 REQUESTS".

**Comment by Marcin-Marczak** [comment] 2024-11-12 07:14
> Hello @Marcin-Marczak Could you check if `campaignUuid` is defined at the folder-level environment with empty string? As you mentioned "FOLDER THAT CONTAINS 11 REQUESTS".

Hello. I'm not sure what do you mean. 
If I define BEFORE executing folder smth like this `campaignUuid`  in variable files ? No, I didn't.
I "create campaignUuid" in "After response" script, just like "lineItemUuid".

And as you can see in "actual behaviour": both exist with values in variable file, but campaignUuid is empty in Request 11, lineItemUuid is correct. 

And please notice that like I mentioned in "additionals", this is only example. I had the same problem with other cases, so I report one specific to show full details

**Comment by ihexxa** [comment] 2024-11-12 08:05
Hm, as you mentioned that `lineItemUuid` is correct while `campaignUuid` is not. I suspect that `campaignUuid` is also defined in the folder-level environment so the `campaignUuid`'s value has been overriden.

This could happen if this folder is imported from another product, you can find "folder-level environment" content here:

<img width="767" alt="Screenshot 2024-11-12 at 15 57 51" src="https://github.com/user-attachments/assets/006d9922-ca13-4ef0-9694-398874e97f37">

**Comment by Marcin-Marczak** [comment] 2024-11-12 08:25
> Hm, as you mentioned that `lineItemUuid` is correct while `campaignUuid` is not. I suspect that `campaignUuid` is also defined in the folder-level environment so the `campaignUuid`'s value has been overriden.
> 
> This could happen if this folder is imported from another product, you can find "folder-level environment" content here:
> 
> <img alt="Screenshot 2024-11-12 at 15 57 51" width="767" src="https://private-user-images.githubusercontent.com/24986718/385192364-006d9922-ca13-4ef0-9694-398874e97f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTk3OTIsIm5iZiI6MTczMTM5OTQ5MiwicGF0aCI6Ii8yNDk4NjcxOC8zODUxOTIzNjQtMDA2ZDk5MjItY2ExMy00ZWYwLTk2OTQtMzk4ODc0ZTk3ZjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA4MTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YTllNmJmZTkxMDVlNTk1YjU4ZjVlZGY3MDNkMTZhZmY1ZWFmMWJmOWM0YjlmMTYxMWRmYjk2NTZhOTM1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GwEV1GjnOt0-t7UtUst9hoezTx87TCKMRwCWYay-1Sc">

1. Nope, I didn't import it from anywhere. Only what I did (what I'm doing always) is duplicate folders (folder name => right click => duplicate). 
2. I don't have "Environments" tab in place you shown above, please see my GUI:
![2024-11-12_09-19](https://github.com/user-attachments/assets/eb0761dc-3875-49ca-a83a-7249f3472c61)
Weird, I don't know why your GUI is different than me
3. I have those data in environments here:
![envs_view](https://github.com/user-attachments/assets/ec8017de-f468-44d2-84c0-cca9095228e9)
4. And everything goes to proper "subenv", like Localhost. "Base Environment" is always empty (before execution, after execution): 
![emptyBase](https://github.com/user-attachments/assets/e9f9cf0b-0f36-4642-8334-4a1b0b3d80d5)

**Comment by Marcin-Marczak** [comment] 2024-11-12 08:30
UPDATE:
My mistake, I have  this environment tab, didnt' know that TBH. But it is always empty (before execution - after execution. 
This is screenshot AFTER folder was executed:
![emptyFolderLevel](https://github.com/user-attachments/assets/443286ef-648c-40c6-ba0c-c18939063e3f)

**Comment by ihexxa** [comment] 2024-11-12 08:56
This is weird, but as `lineItemUuid` works, which means the logic works.

So I propose to check it step by step:

- Delete `campaignUuid` in base environment, sub environment and ALL parents folder-level environments.
- Call Request 6, and check if it is generated in the selected (sub) environment like Localhost
- Request 8, and do same thing for `lineItemUuid`.
- If both environment exist, call Request 11, and see what will happen

**Comment by ihexxa** [comment] 2024-11-13 02:34
@Marcin-Marczak Probably you could also try to change a name for `campaignUuid` as `lineItemUuid` works.

**Comment by Marcin-Marczak** [comment] 2024-11-13 05:54
Well, now it works. Since yesterday. Now I have like this:
> PUT /api/v2/adops/campaigns/21b9ee90-04e7-4eb3-a434-416483b4c38a/orders/1c8d3f7a-1820-4335-8655-b4d628e4b561/line-items/014de4f5-d21f-4d30-999b-64ab81ce6ea6/ HTTP/1.1

so dynamic variable "campaignUuid" works. Same for other folder.

What I changed ? Nothing. Literally nothing, so I have no idea why now it works. But now it works, previously didn't as I reported originally with full details.

**Comment by ihexxa** [comment] 2024-11-13 06:40
I'll close this and feel free to reopen it if you detected the cause.

**Closed as completed by ihexxa** 2024-11-13 06:40 UTC
Labels: B-bug, S-unverified
