### ISSUE TITLE
Timer take too long after response to get out of screen

### ISSUE THREAD

**Issue by LeoAlvesBahia** [getinsomnia/insomnia#3955] opened 2021-08-26 16:21 UTC
**Describe the bug**
I send a request (tried only with POST and GET) and within seconds the response show but the timer keeps running indefinitely (200+ seconds) like no response has come. I tried the same request with same parameters and all on postman and it is working properly. Asked some coworkers to test insomnia for me and it is working on their systems (Windows).

**To Reproduce**
1. Go to request
2. Fill body
3. Click on send

**Expected behavior**
When I send the request and receive the response I expect that the timer stops running and get out of my screen so I can read the response body

**Screenshots**
Before click on send:
![Captura de tela_2021-08-26_12-40-09](https://user-images.githubusercontent.com/55108062/130996819-17f3c271-2d67-419a-9177-23e046584bc6.png)

After a while:
![Captura de tela_2021-08-26_12-57-37](https://user-images.githubusercontent.com/55108062/130996850-e66c2384-08c7-42c4-8da1-899d4b6b10df.png)

**Desktop:**
 - OS: Manjaro 21.1.0 Pahvo
 - Installation Method: XFCE
 - App Version 2021.5.0 (but problem was at earlier version (2021.4.1) as well)

**Additional context**
I tryied the flatpak version, the insomnia, insomnia-bin and insomnia-git and all them are with the same problem.
I tried creating a new collection and it works for some time (5~10 requests) and then starts taking too long to remove the timer from screen.

**Comment by MrSnix** [comment] 2021-09-20 11:13
This seems like a duplicate of #3786

**Comment by dimitropoulos** [comment] 2021-09-20 15:10
> I tryied the flatpak version, the insomnia, insomnia-bin and insomnia-git and all them are with the same problem

Ugg.  I'm very sorry that you had to go through all of that.  I greatly appreciate it, though, because it means that it's not the installation method.

Let's go over to #3786 to keep the discussion going, this looks to be the same thing.

**Closed as completed by dimitropoulos** 2021-09-20 15:10 UTC
Labels: B-bug, S-unverified
