### ISSUE TITLE
[BUG] Changing environment colour affects multiple environments

### ISSUE THREAD

**Issue by freost** [getinsomnia/insomnia#811] opened 2018-03-14 09:53 UTC
- Insomnia Version:  5.14.9 (5.14.9.1895)
- Operating System: macOS 10.13.3

Changing the colour of an environment seems to affect multiple environments. As you can see in the gif changing the colour of the `production` environment also affects the `testing` environment (it also nukes the content).

![https://imgur.com/a/isEWC](https://i.imgur.com/ayTZR3p.gif)

Edit: It appears that environments get affected across workspaces as well.

**Comment by gschier** [comment] 2018-03-27 01:21
This is so strange. I'm unable to reproduce it on my end. Does it happen after a fresh launch of the app?

**Comment by gschier** [comment] 2018-03-27 01:23
Also, your colorpicker isn't visible in your video. Are you using the default Mac colorpicker?
![image](https://user-images.githubusercontent.com/587576/37941365-bbf50a16-3122-11e8-91ca-7ae69d591f97.png)

**Comment by gschier** [comment] 2018-03-27 01:25
Oh, I ended up reproducing it after closing and opening the dialog a bunch of times. Fixing now! 😄

**Closed** 2018-03-27 01:40 UTC
