### ISSUE TITLE
OpenAPI JSON crashes Insomnia

### ISSUE THREAD

**Issue by AltayAkkus** [getinsomnia/insomnia#5591] opened 2022-12-27 21:36 UTC
### Expected Behavior

Don't crash

### Actual Behavior

Crash

### Reproduction Steps

1. Try to import [this JSON](https://stoplight.io/api/v1/projects/shopware/admin-api/nodes/adminapi.json?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL3N0b3BsaWdodC5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6IndvcmtzcGFjZV91c2VyIiwieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ3b3Jrc3BhY2VfdXNlciJdLCJ4LWhhc3VyYS11c2VyLWlkIjoiMjA5MjczIiwieC1oYXN1cmEtdXNlci1pcC1hZGRyZXNzIjoiMTMwLjIxMS4xLjkzIiwieC1oYXN1cmEtd29ya3NwYWNlLWlkIjoiMzM5MTQifSwiaWF0IjoxNjcyMTc2Mzc2LCJleHAiOjE2NzIxNzk5NzYsImlzcyI6InN0b3BsaWdodCIsInN1YiI6Ii91c2Vycy8yMDkyNzMifQ.PxMW7LMPjqQsbGaKlP6D0uGUfxgZ7kU6OWgA0YN0Yao&_ga=2.134124174.1452441037.1672175776-949224968.1671309997) file in a project
If the link should break:
https://shopware.stoplight.io/docs/admin-api/YXBpOjEyMjgzNTQ4-shopware-admin-api and go to Export.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19045

### Installation method

Windows installer

**Comment by filfreire** [comment] 2023-01-16 17:43
Hi @AltayAkkus thanks for reporting this, closing it as duplicate of #1843 - the type of issue is the same and is related to how insomnia has trouble handling large openapi specs. We'll be working to improve this soon.

**Closed as completed by filfreire** 2023-01-16 17:43 UTC
Labels: B-bug, S-unverified

**Comment by TheDread-Pirate-Roberts** [comment] 2023-11-22 18:04
@filfreire I know it's been some time but where did y'all land on handling large openapi specs?
