### ISSUE TITLE
Git status on homepage is incorrect when multiple github repositories are cloned

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2364] opened 2020-07-09 01:49 UTC
**Describe the bug**
The branch, and last edited labels on each document of the homepage is incorrect when transitioning between the two.

**To Reproduce**
1. Clone a repository (eg. https://github.com/develohpanda/designer)
2. Make some changes, commit, push - so that there are no more change
3. Clone a different repository
4. Make some changes, commit, push - so that there are no more changes
5. Go to documents home
6. Open one document
7. Go to documents home
8. Open the other document
9. Go to documents home
10. Notice the git sync labels changing on the homepage

**Expected behavior**
Should show the up-to-date status of each document, independently

**Screenshots**
![2020-07-09 13 41 54](https://user-images.githubusercontent.com/4312346/86987813-04c95480-c1eb-11ea-9018-49fb0f2705eb.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Installation Method: DMG
 - App Version v2020.3.0-beta.1

**Comment by filfreire** [comment] 2022-06-23 13:13
We were not able to reproduce this one, so we are closing it for now. cc @wdawson

**Closed as completed by filfreire** 2022-06-23 13:13 UTC
Labels: A-design, B-bug, A-git-sync
