### ISSUE TITLE
Sorry, this new release is just terrible

### ISSUE THREAD

**Issue by popov654** [getinsomnia/insomnia#6809] opened 2023-11-14 12:09 UTC
### Expected Behavior

To react on my actions fast and neatly

### Actual Behavior

Like "wtf is going on"...

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Here is an incomplete list of the problems:

1. Terrible delays: when renaming a request, when switching to another request, when editing a request header, when toggling hidden value of the header, etc. These are sometimes up to 1-1.5 seconds
2. When I click the request name and then click sometimes inside the text, I want to move my text cursor, not to save the changes and finishthe editing >..<
3. When I click th "Untitled request" and start editing, the text is subtle gray, so I expect it to be replaced by the new value (since it's the default placeholder), but... The new value is just getting appended to the right
4. Value of the API key cannot be copied with either Ctrl+C or the context menu
5. When I click and select the API key by dragging, the result sometimes looks weird (like the selection rectangle does not cover all of the text, only 70-75 percent of it)
6. When I open the program, I would like my last collection to be remembered, since it takes at least 2 more mouse clicks to get to the destination now
7. Overall startup time is too slow compared to last major release
8. In fact I accidentally click on the title of the request way too often, because of getting used to the old behavior. Would be nice if rename was triggered only by the context menu as it was before

### Insomnia Version

9.4.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1909

### Installation method

download from website

### Last Known Working Insomnia version

8.x

**Comment by kirantyefun** [comment] 2023-11-14 13:38
+1. Ditto same issue. Terrible update. 
**OS:** 
Mac OS M1 chip

**OS version**
Ventura 13.4.1

**Comment by polderudo** [comment] 2023-11-14 17:31
+1. Ditto same issues. Terrible update.
OS:
Mac OS M1 chip

OS version
Sonoma 14

**Comment by Rafikooo** [comment] 2023-11-14 21:21
I rarely actively participate in GitHub issues, but today is an exception. Indeed, this new update also affects my setup
OS:
Mac OS Ventura on M2 chip

**Comment by subnetmarco** [comment] 2023-11-15 01:47
Will be fixed this week - Preparing 8.4.2 to fix some issues (the single click rename, and more), and 8.4.3 to improve the performance.

**Comment by igor875126** [comment] 2023-11-15 06:18
same issue. Terrible update.

MacOS

downgraded to older Version: Insomnia 2022.7.5 works perfectly

**Comment by subnetmarco** [comment] 2023-11-15 13:51
The rename issue has been fixed this morning in v8.4.2

**Comment by subnetmarco** [comment] 2023-11-15 13:53
@popov654 regarding these issues:

> Value of the API key cannot be copied with either Ctrl+C or the context menu
> When I click and select the API key by dragging, the result sometimes looks weird (like the selection rectangle does not cover all of the text, only 70-75 percent of it)

What do you mean by "API Key"? You mean an environment variable attached to the URL?

**Comment by krstns** [comment] 2023-11-15 22:14
Insomnia on Mac works really slow now, but release 8.4 and 8.4.2 on Windows is a complete disaster. I have a feeling like someone put all user actions execution within a setTimeout with 300ms delay. 
Making changes to environments is close to impossible, switching between configs takes so long that I start to think I have clicked the wrong thing.
Adding a request unfolds all folded folders and moves the focus, folding anything takes time.
Then I tried to change the name... typing a single letter would remove the focus from the input.
wow
How did this pass any tests?

**Comment by LuizPelegrini** [comment] 2023-11-16 02:57
It's super slow now, any user interaction takes 1-1.5s to complete.

Using Mac M1 Chip 32GB Ventura.

Hope this is fixed soon

**Comment by subnetmarco** [comment] 2023-11-16 03:41
Yes we are aware of the slowness. 

It will be fixed next week in 8.4.3. We are iterating rapidly as we are doing some major refactorings, the regressions will reduce dramatically in number once we complete this rough patch of work.

**Comment by priyankvex** [comment] 2023-11-16 12:53
Is there a way to opt out of updates. At this point I just want a stable version that works.

**Comment by krstns** [comment] 2023-11-16 14:26
> Is there a way to opt out of updates. At this point I just want a stable version that works.

try settings->automatically download and install updates option

**Comment by klerpi** [comment] 2023-11-16 18:00
1 to 2 seconds delay on anything I do

**Comment by carloss1989** [comment] 2023-11-16 20:34
Using Mac M1 Chip. 

Terrible release!

**Comment by tss182** [comment] 2023-11-17 03:12
using Mac M1 on Sonomo MAC OS
terrible release

**Comment by klit79** [comment] 2023-11-17 07:19
downgraded to 8.3.0 
i feel alot better

**Comment by PaulXu-cn** [comment] 2023-11-17 09:40
why not ask me before your biggggger update!

**Comment by dunistory** [comment] 2023-11-18 16:35
same issue. Terrible update.
MacOs M2
Sonoma v14.0

**Comment by popov654** [comment] 2023-11-20 01:27
> You mean an environment variable attached to the URL?

I meant Bearer authorization token, IIRC

**Comment by simonmudd** [comment] 2023-11-20 11:24
A few more things I have identified this morning since the latest update:

- Deleting an access token is no longer possible. 
  - If the backspace is pressed the cursor jumps to the end of the token
  - Highlighting the value and pressing backspace has the same outcome
  - Starting at the end of the token and pressing backspace has no effect
- The refresh token is also not deletable with the above behaviour
- Editing a GraphQL request so it has invalid syntax and then switching to a different request will trigger the auto formatting, which returns the request to the last valid syntax. 
  - This behaviour is not reflected in other request types (JSON, XML, etc).

Details of setup:
MAC OS
M1 chip
Insomnia version - 8.4.2

**Comment by alissonpadua** [comment] 2023-11-20 11:43
Same here... it is terrible 

+1. Ditto same issue. Terrible update.
OS:
Mac OS M1 chip

OS version
Ventura 13.4.1

**Comment by subnetmarco** [comment] 2023-11-20 13:29
As an update: we have identified the performance issue and a fix will ship this week in 8.4.3. Besides this issue [here you will find](https://github.com/Kong/insomnia/discussions/6815) more about some of the changes that we are making that are causing these regressions, which will decrease in number very rapidly in the following weeks.

**Comment by subnetmarco** [comment] 2023-11-20 13:31
@simonmudd letting the team know, thanks for reporting.

**Comment by subnetmarco** [comment] 2023-11-22 17:35
Hello 👋 Insomnia 8.4.4 has been shipped with numerous **performance improvements** that brings back a ton of speed in the UI. You can wait for the auto-updater to download it for you, or you can manually download it [here](https://github.com/Kong/insomnia/releases/tag/core%408.4.4).

**Comment by MrRoiz** [comment] 2023-11-22 20:42
@subnetmarco I just updated to v8.4.4 and it still has tons of  UI insane delays.

OS:
Ubuntu 23.10

**Comment by Ryan432** [comment] 2023-11-22 22:41
+1

Guys... come on, cannot agree better then what was said, like "wtf is going on"
You used to have a great product, new versions are just nightmare..

- "Switch Requests (CMD + P on Mac)" shortcut was removed which was super useful for productivity.
- gRPC integration is simply broken - nothing works as expected, saved body are removed, and the list continues.
- The app is working slow in many difference actions.

There are tons of issues that can be mentioned, a complete end to end QA is required.

**Comment by goodalex** [comment] 2023-11-23 15:46
Hi, 

I really like the software. This release has quite some usability issues and issues.

- First it behaves very unexpected when you click double click the name. I don't unterstand the action I have to take to rename
- Then the renaming does not work, when I place the cursor at the start or end of name, and type something, it reverts back to the original name and the "renaming state" is inactive again
- Sometimes when clicking on the requests it will collapse / expand, sometimes not. It's not clear where you want me to click.
- Overall, it takes minutes until you manage to rename the requests.
- All my data was lost after the update installed the first time.  Luckily I had a backup from the day before, but that was already stale so I had to reproduce many changes.
- The method chips are so visually prominent now that it is difficult to visually distinguish requests by request name when you have many requests

**Comment by ches** [comment] 2023-11-23 17:57
> All my data was lost after the update installed the first time. Luckily I had a backup from the day before, but that was already stale so I had to reproduce many changes.

This is at least the second time that an Insomnia update has trashed user data catastrophically or near so, the memory of manually repairing data is still fresh on my mind from #5559.

QA has been really rough on this product since acquisition, doesn't reflect well on Kong as an enterprise vendor… Regression fixes from big changes (#6815) are coming over _months_? Sounds like it should have matured a lot further in the beta updates channel.

**Comment by phen0menon** [comment] 2023-11-24 12:52
Moving to Postman back, it's unusable at this moment. I can't even rename my request name, also I can't even add a new header inside a request - UI terribly lagging on my clean M1 Pro...

**Comment by subnetmarco** [comment] 2023-11-24 13:38
@phen0menon Here is a video to rename a request or adding a header inside a request, isn't this what you are seeing in your local installation? https://www.loom.com/share/6dde9589eaed4f91a803e48619f65804

**Comment by phen0menon** [comment] 2023-11-24 14:08
It works OK for clean collection. My collection is large and when I click on request name (in sidebar), it shows me a text field but when I try to enter anything - the text field disappears and request name replaces with its URL (with variables :D). Shortcuts like Ctrl + C / Ctrl + X don't work at all - it's better not to even try to click them - it's not clear what's going on with the UI - my sidebar will scroll down somewhere

Same behavior for headers tab - when there are more than 10 header items, UI becomes laggy and unusable for fast fingers.

Sometimes it works OK even for bigger collection. But I'm really tired of getting random UI bugs.

**Comment by phen0menon** [comment] 2023-11-24 14:17
But the strange thing comes when I click on a request in sidebar. Seems to me that displaying text field when trying to open a request was a worst UX decision.

If there was an option to downgrade the Insomnia version, I would immediately do that.

**Comment by gatzjames** [comment] 2023-11-24 16:49
Hi @phen0menon we have made a release with a bunch of performance improvements alongside with changing the way renaming a request works to now be a double-click. Is this happening to you on the latest version?

**Comment by subnetmarco** [comment] 2023-11-26 02:31
@phen0menon to ping back on the question above, what version are you using?

**Comment by gatzjames** [comment] 2023-11-27 12:06
Update: Tested with a fairly large collection 550 Requests, many Folders and each request having at least 20-30 headers and everything runs fine. The performance is not affected at all for me.
I'm using an Intel based macbook using the latest version 8.4.5

@phen0menon and others with perf issues, can you verify if that is still an issue on your side?

**Comment by phen0menon** [comment] 2023-11-28 13:43
Yep I'm still having those issues:
```
Version: Insomnia 8.4.5
Build date: 11/23/2023
OS: Darwin arm64 23.1.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64
```

Here's the screencast of what's going on with keylogger attached.

https://github.com/Kong/insomnia/assets/15520523/4fc48e42-01fa-49c7-aee8-f2cdc5943719

**Comment by klit79** [comment] 2023-11-29 05:22
it is not really a bug
it is just terrible UX
one click on http method is alot faster than one click on title
i think because clicking on title need to wait if the second click is registered then you can rename it

there should be an option to disable this double click to rename

**Comment by phen0menon** [comment] 2023-11-29 11:04
UX is terrible you are right but there is really a bug with renaming long-named request. Probably variables inside of an url affect too somehow.

Option to disable this would be good, but I really hope they will remove this feature.

**Comment by daweedco** [comment] 2023-12-01 16:31
Please revert to old version , the software is unusable since the upgrade for big collection !!!

**Comment by brr53** [comment] 2023-12-03 02:42
Just lost all my collections from the new update. 😭

**Comment by subnetmarco** [comment] 2023-12-21 18:41
We are rapidly improving different areas of the product and we just shipped [8.5.1](https://github.com/Kong/insomnia/releases).

When you cannot find your collections after an upgrade, we have introduced this section in the footer to re-assign orphaned projects to your organization:

<img width="432" alt="Screenshot 2023-12-21 at 1 34 31 PM" src="https://github.com/Kong/insomnia/assets/964813/f97c8dc3-4fbb-48cf-8048-36c9933ba36a">

In January we are going to be further looking at other issues/feature requests as [described here](https://github.com/Kong/insomnia/discussions/6815#discussioncomment-7921199).

**Comment by Rafikooo** [comment] 2023-12-22 18:04
I was peacefully waiting for the basic expectations to be met, such as bringing back the most productive features that were removed from Insomnia, specifically the (MacOs bindings):
1. Cmd+P endpoint searcher
2. Control + Tab for easy access to the last request

These two features are crucial for using Insomnia with ease. Currently, searching for the desired endpoint in a large collection is really inefficient. Speaking of searching, it is also broken. For example:

I have a folder named `Product` that contains multiple configured endpoints. If an endpoint doesn't have the word `Product` in its configuration, it is excluded by the search filter, which didn't work like that before "the big release".
Additionally, adding a new endpoint wraps all the folders, and since the quick search doesn't work, I need to search for the new endpoint again.
I had hoped that this would be improved in December, but since it wasn't, I considered moving to Postman. However, I like your product too much, so I finally reverted back to an April release and all my struggles went away.

I wish you good luck with fixing all the regressions

**Comment by subnetmarco** [comment] 2023-12-22 18:16
Hey @Rafikooo - Yes I hoped to have those fixed in December too, but we were too packed for this release. They will ship in January. The good news is that we are doubling our team in the next 6 months, so the velocity on fixing these and other issues will accelerate dramatically. + @gatzjames for visibility on these issues.

**Comment by PavelStefanov** [comment] 2024-01-09 09:41
Sorry guys, but the Insomina team has killed the really good product with an 8+ update 😢

**Comment by JoiGud** [comment] 2024-01-22 15:05
Just to chime in: Love insomnia but, for instance, the ordering for `collections` 
![image](https://github.com/Kong/insomnia/assets/6821202/1aabd666-f0ae-427f-9caf-d831bdadc149)
always resets to `last modified` when you navigate from the `collections` view.

**Comment by subnetmarco** [comment] 2024-01-22 15:28
@JoiGud We are looking at it, thanks.

**Comment by subnetmarco** [comment] 2024-01-22 15:29
@Rafikooo Cmd+P has been re-enabled this month, and is being continuously improved.

**Comment by subnetmarco** [comment] 2024-03-28 02:57
We have fixed all the shortcut problems in the upcoming Insomnia 9.0, for which there is a beta available now in the [releases](https://github.com/Kong/insomnia/releases). Make sure to download Insomnia, not the CLI application.

**Comment by subnetmarco** [comment] 2024-08-01 12:20
We have further improved some issues in the parent ticket, and with the [latest 9.3.3](https://github.com/Kong/insomnia/releases/tag/core%409.3.3) version of Insomnia we were able to improve performance **up to 20x** in some cases.

![Screenshot 2024-08-01 at 7 57 08 AM-modified](https://github.com/user-attachments/assets/0cf46532-b2ea-4ce2-a388-b0e67f9abfce)

We have also significantly improved the **sidebar experience**, removing all the quirkiness that used to affect previous versions:

* You can now double-click anywhere to rename.
* You can now click anywhere to move files around.
* You can right-click to open the contextual menu.
* We have removed the weird inner rectangle when mouse-overing the sidebar items.

Finally, we have also improved the UX of the application and with 9.3.3 we are **remembering the last open file** across application restarts.

https://github.com/user-attachments/assets/f7136723-9d50-42fb-88bd-85a6d490f8f6

With this latest 9.3.3 update and all the other changes in previous versions, we have addressed most of the issues brought up by @popov654, therefore I will close this issue now.

**Closed as completed by subnetmarco** 2024-08-01 12:20 UTC
Labels: B-bug, S-unverified
