### ISSUE TITLE
Small Bug when pasting cURL into the URL field

### ISSUE THREAD

**Issue by Doogiemuc** [getinsomnia/insomnia#5696] opened 2023-01-18 08:07 UTC
When pasting a cURL command with URL encoded form data into the insomnia URL field, then the form parameters are automatically added. But key=values are not correctly parsed:

### How to reproduce

Past the following cURL into the URL field in insomnia client

````
curl --location --request POST 'https://domain.com/exampleDummy' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'response_type=code' \
  --data-urlencode 'state=1234abcd' 
````

### Expected behaviour
The URL is parsed and the --data-urlencode parameters are parsed as key and value and inserted into the correct columns in insomnia Form tab.

### Actual behaviour

Both "key=value" is parsed into the "key" column of the Form tab. The "value" column stays empty. See screenshot:

![image](https://user-images.githubusercontent.com/512835/213116806-6bfaa038-0ac2-4de6-b6bc-ecf7fcf36b61.png)

### Versions
Insomnia Native Client under Windows 2022.7.3
Build date: 16.1.2023
OS: Windows_NT x64 10.0.19044
Electorn: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by jackkav** [comment] 2023-01-18 08:30
Thanks @Doogiemuc 

This appears to be the PR introducing this issue and the assertion proving it.
https://github.com/Kong/insomnia/pull/5006/files#diff-b919cbd6bcbdee3c775a6f8f1b5fe35365991d58059e5bb84c77baa6f8517d54R46

Seems like we need to change the test and perhaps add another case for a second data-urlencode argument.
```
            { name: 'c=&d=4', value: '' },
```
to
```
            { name: 'c', value: '3' },
            { name: 'd', value: '4' },
```

the test can be run with `npm run test --prefix packages/insomnia -- --watch curl.test`

**Comment by filfreire** [comment] 2023-01-24 09:41
@Doogiemuc @jackkav - looks like this is a duplicate of https://github.com/Kong/insomnia/issues/5400 and there's a fix PR up for it https://github.com/Kong/insomnia/pull/5409

**Comment by filfreire** [comment] 2023-01-24 14:37
Reopening, slightly different issue 😅

**Closed as completed** 2023-03-31 11:06 UTC
Labels: E-good-first-issue, S-verified, A-encoding
