### ISSUE TITLE
[Bug] AutoComplete Popup Won't Go Away

### ISSUE THREAD

**Issue by ValorMorgan** [getinsomnia/insomnia#2991] opened 2021-01-08 13:50 UTC
At random times while creating / modifying requests, the auto-fill popup will appear presenting me with options for what I want to add to my URL. It appears in the far top-left (essentially where the URL starts) and will NOT go away until I choose an option forcing data into my URL I don't want or close and reopen the app.

I want to say that this is caused when I'm manually typing in the URL (or editing it) and pause for "nearly" the amount of time needed for the popup to normally appear on it's own in the proper place.  But this is just a theory.

I can still make the normal popup appear elsewhere in the URL while working alongside this random popup. Selecting anything there works as normal but this bugged popup remains.

v2020.5.2 on Windows 10 1909 edition
I'm using the plugin "insomnia-plugin-material-darker-hc-theme" to get this color scheme. No other plugins.

PS. blurred (not so greatly) my image for privacy but the popup in question is in the top-left with all the green on the left side of it.

![Insomnia_Bug](https://user-images.githubusercontent.com/7775950/104022297-1a193e80-518e-11eb-9b8f-c7936c5c1d93.png)

**Comment by apisaint** [comment] 2021-01-09 07:02
There is an open PR to resolve such an issue, perhaps it applies here as well? #2394

**Comment by ValorMorgan** [comment] 2021-01-09 12:26
Reviewing the PR changes, this seems to affect what the autocomplete 
populates. It does not, however, affect what causes the autocomplete to 
appear on screen.

My issue is related to the autocomplete appearing when I don't want it to. 
It also then remains on screen in a sorta frozen state.

I can try reproducing though whenever a new release is available to confirm 
or deny this.

**Comment by apisaint** [comment] 2021-01-11 18:50
@ValorMorgan apologies, I linked the wrong PR, blame lack of coffee. Here is the PR i meant to link https://github.com/Kong/insomnia/pull/2957

**Comment by ValorMorgan** [comment] 2021-01-11 21:34
It definitely looks related but I believe the PR addresses a cleanup operation to occur on unmount of the editor itself.

In my case, the editor remains on-screen.  I’m simply operating within the URL textbox and can trigger the `completionActive` state via a similar “…get the timing right” situation.  Essentially somehow pausing or otherwise causing delays on input within the URL textbox causes the popup to appear just as more input comes in.  Thus the popup hits a confused state as it begins to render causing it to appear to default it’s own state yet stay rendered.

Switching requests does not remove it much the same as this PR describes.

P.S. Never enough coffee ☕☕☕

Sincerely,

Joshua Morgan
Software Engineer II
Scriptcoded@hotmail.com<mailto:Scriptcoded@hotmail.com>
(616) 914-9719

**Comment by develohpanda** [comment] 2021-01-12 23:52
Hi @ValorMorgan, I don't _think_ #2957 will fix this issue, but I haven't been able to reproduce your behavior so I can't check for certain. It's definitely strange behavior, though, and the code-editor is fairly feature-rich so I wouldn't be surprised of an edge case existing there.

Would you have any additional information/steps that might help me to reproduce this? If it definitely is a timing issue, we could try to reproduce it via a scripted smoke test as well.

**Comment by ValorMorgan** [comment] 2021-01-13 00:36
I too am having a hard time reproducing this on my home desktop which is on the latest WIndows update.  Possibly related to the sheer number of saved APIs I have on my work laptop along with a fairly extensive Environment Configuration.

It's just interesting to me that I could reproduce this fairly easily on my laptop.  Seemingly being triggered by the timing of my input combined with the hint system considering my input matches something in my environment config.  Can't put a finger on the exact cause though 🤷‍♂️ 

Worst case, let's chalk it up as #WorksOnMyMachine and maybe a future update to either Insomnia or my Windows machine may address it.

**Comment by develohpanda** [comment] 2021-01-13 05:18
You raise a good point with the number of APIs and an extensive environment configuration. The delay could be the result of a performance bottleneck (I am aware of some of these), which only becomes evident when you have a _lot_ of data. It might be worth exploring this route, even just as a method to discount it. ([Here](https://github.com/Kong/insomnia/issues/2457) is an example of another bug of this nature).

Could you please test something on your laptop for me? If you were to create a fresh workspace, add a few requests and environment variables (~3 each), are you able to reproduce this? Notice that your extensive data will still exist, but it will be linked to a different workspace.

Also, as an _approximation_, how many requests do you have and how large is your environment variable setup (number of env variables)? I can try to reach a similar complexity of my workspace to try and reproduce.

Lastly, if you are able to do so, you can share your workspace _privately_ with us by emailing support@insomnia.rest. This is an inbox that only maintainers have access to.

**Comment by ValorMorgan** [comment] 2021-01-13 13:47
>
>
> Could you please test something on your laptop for me? If you were to create a fresh workspace, add a few requests and environment variables (~3 each), are you able to reproduce this? Notice that your extensive data will still exist, but it will be linked to a different workspace.
> 

Doing a new workspace is proving to be much more performant.  I don't even see lag on the popup like I see in my main workspace.

In my main workspace, even purposefully opening the popup can sometimes feel delayed by a few ms.  Usually not that bad but it could prove your performance theory if I somehow switch the editor's context in some manner causing the popup to bug out.

>
>
> Also, as an approximation, how many requests do you have and how large is your environment variable setup (number of env variables)? I can try to reach a similar complexity of my workspace to try and reproduce.
> 

Base Environment Configuration # of Lines: 13
Sub Environment Configuration # of Lines: 265
- I could probably do with some cleanup here as it does cover a few scopes

Number of Requests Saved: 351

>
>
> Lastly, if you are able to do so, you can share your workspace privately with us by emailing support@insomnia.rest. This is an inbox that only maintainers have access to.
>

I cannot share my workspace as it does have a lot of information specific to the product I work on.  Honestly, my use of Insomnia has grown so much that I've been trying to convince my team to upgrade our use to a paid tier and start sharing the requests 😉

**Comment by develohpanda** [comment] 2021-01-13 22:23
Alright, I created a workspace with that many env variables and requests and _have_ seen it is noticeably slower and a little buggy. Although I still can't reproduce what you are seeing on my MacBook Pro, I can imagine that a lower spec'd machine might exhibit strange(r) behavior. Perhaps this is why you can't reproduce it on your desktop, but can on your laptop?

I don't have access to a Windows _laptop_ to test with but I wonder if a VM might be able to simulate it, something to explore...

Would you please help me validate if the following workspace I generated causes similar behavior? If so, this will become the workspace to validate a fix with. 😄 

[![Run in Insomnia}](https://insomnia.rest/images/run.svg)](https://insomnia.rest/run/?label=GH-2991&uri=https%3A%2F%2Fgist.githubusercontent.com%2Fdevelohpanda%2F9c2d536f0e78c0914e22d300e559d97e%2Fraw%2Ff36478851547743c0bea553a0a1e704b560ec80e%2Fgh-2991.yaml)

I appreciate your time in helping us narrow this down 🙏🏽

**Comment by ValorMorgan** [comment] 2021-01-15 14:56
So lately my issue has not been cropping up.  I'm starting to wonder if I received a Windows update (or driver?) which somehow addressed a memory performance concern on my machine thus fixing this issue?

I've now tried again with my own environment and no luck forcing it to break.  Previously it didn't take much effort but now I'm even hitting an API that produces a response >5MB which causes my app to crawl but the popup doesn't break.

I also used your environment with no luck there either.  It still felt relatively snappy for me (some delay but not bad).

Confirmed my app version has not changed too.

I guess worst case here, the popup maybe could use a sanity check "If I opened but user is providing more input, close me".  I know the normal popup does something like this but perhaps all of them need to somehow bind to key input across the app.

**Comment by develohpanda** [comment] 2021-01-17 21:40
May have been a Windows update (or even just a restart) that resolved some performance bottleneck. Thanks for reporting back!

> I guess worst case here, the popup maybe could use a sanity check "If I opened but user is providing more input, close me". I know the normal popup does something like this but perhaps all of them need to somehow bind to key input across the app.

I would probably hold off on making any changes right now, since the bug cannot be reproduced, and any fix (even a sanity check) will need to be validated. As such, I will close this issue for now but feel free to re-open if it comes back again! 🤗

**Closed as completed by develohpanda** 2021-01-17 21:40 UTC
Labels: N-investigation, B-performance, M-cannot-reproduce

**Comment by ValorMorgan** [comment] 2021-01-22 21:21
So the same bug just happened again with my personal data set.  Just wanted to record how it happened before I forget:

1. Have 2 requests pre-existing where only one portion of the URL needs to change (i.e. an ID)
2. Change first one and fire
3. Before response, visit second one, change, and fire
4. Before second one responds, visit first one to review result (in my case, was moments before response came through)
5. Popup appeared in top-left corner on visit of first one

In my case, the URL ended like the following:
- FIrst One: api/gridView/count/5
- Second One: api/gridView/alerts/5

Those 5's were 0's before I did my changes on visit.  They match up to a region on the globe is all (i.e. 0 == Global, 5 == Middle East).

**Comment by EdilsonVieira** [comment] 2022-01-04 14:31
I am having the same issue here. 

Please, tell me if I can help some how.

![image](https://user-images.githubusercontent.com/4509826/148074085-7a11b17d-4469-42c7-aeda-63d38959f273.png)

**Comment by mikebridge** [comment] 2022-02-04 17:59
I have this issue too on Linux (Ubuntu 20) with version 2021.7.2.  I get multiple unwanted autocomplete windows popping up and there is no way to close them except by selecting something.  Escape, clicking elsewhere does not close them.  It happens every few minutes, and I can't see what's triggering it --- it seems random.  Sometimes I'm just moving the window and it comes up.

Another weird side-effect is that when I choose something from these random windows, it doesn't insert the text---I have to refresh to see the text inserted. 

Here's a screenshot where I have two at the same time.  

![insomnia-menus](https://user-images.githubusercontent.com/213273/152578940-b7d5e0c5-0f6b-4d2e-b49a-afbd94789996.png)

I'd love to just disable the automatic popup and just have it pop up when I request it.

**Comment by mikebridge** [comment] 2022-02-04 18:03
I see you can [disable the automatic popup](https://github.com/Kong/insomnia/issues/2320#issuecomment-649044612) in the preferences (General) by setting "Autocomplete popup delay" to 0.  I will try that.

**Comment by dimitropoulos** [comment] 2022-02-07 15:13
@filfreire do you have a chance to look into this?

**Comment by Vyoam** [comment] 2022-03-25 09:01
I had created https://github.com/Kong/insomnia/issues/4531 for the same issue. Just now came across this existing one. You can see my observations on the bug, which echo what @ValorMorgan has mentioned here too.

@develohpanda I think this can be re-opened. I'll close mine once that happens. (For my note: [github action premissions](https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github))

**Comment by ValorMorgan** [comment] 2022-03-25 12:51
What did help my situation was to cleanup all my requests into request groups separate from one another. I believe the number of requests and environment variables was causing some issues with the auto-complete popup delay. Likely a problem with how that thing gathers values to determine what to show.

A "fix" would likely be some faster searching of requests and environment variables that populate the popup. Maybe also smarter logic around when to cancel said search if the user moved on.

**Comment by tartur** [comment] 2022-10-08 09:36
I still have this issue, I think what is the most annoying part of this bug is that the popup does not go away when I type esape or I click elsewhere! If this popup could be hidden with an escape it would be great, or like most of the editors appears and disappears with the ctrol+space shortcut

**Comment by djuric** [comment] 2022-10-08 11:09
> I see you can [disable the automatic popup](https://github.com/Kong/insomnia/issues/2320#issuecomment-649044612) in the preferences (General) by setting "Autocomplete popup delay" to 0. I will try that.

This fixed it for me, thanks!
