### ISSUE TITLE
Can't move requests into folders (or folders into folders)

### ISSUE THREAD

**Issue by Samuelfaure** [getinsomnia/insomnia#5182] opened 2022-09-14 09:48 UTC
### Expected Behavior

When drag-and-dropping a request or a folder onto another folder, it should move that request into that folder.

### Actual Behavior

It does not

![insomniabug](https://user-images.githubusercontent.com/14159757/190120991-2253ecad-00c6-4283-b8af-af0d76a1a1da.gif)

### Reproduction Steps

See attached GIF

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Arch linux, using picom as a composer and i3-gaps as a tile manager

### Insomnia Version

2022.5.1

### What operating system are you using?

Other Linux

### Operating System Version

Arch Rolling

### Installation method

yay -S insomnia OR yay -S insomnia-bin => same result

**Comment by filfreire** [comment] 2022-09-14 09:59
Hi @Samuelfaure, thanks for reporting this!

Are you by any chance also able to reproduce this issue with previous [stable version 2022.4.2](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2) and/or with the [latest beta](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4)?

**Comment by Samuelfaure** [comment] 2022-09-14 10:06
@filfreire The issue has been happening for quite some time, I am certain it was present during 2022.4.2 (which is even why I upgraded to 2022.5)

I'll try with the latest beta immediately.

Edit: No dice, beta doesn't solve the issue.

**Comment by izzat-sq** [comment] 2022-09-27 01:40
Having the same problem. I have version 2022.5.1-1

**Comment by filfreire** [comment] 2022-09-27 07:49
@Samuelfaure @izzat-sq  this will be fixed in our upcoming `2022.6.0` release.

Fix for it was introduced in https://github.com/Kong/insomnia/pull/5168

**Closed as completed by filfreire** 2022-09-27 07:49 UTC
Labels: O-linux, B-bug, S-unverified

**Comment by vetterj73** [comment] 2022-11-03 21:55
This was not fixed with 2022.6.0.  I still have the same issue

**Comment by izzat-sq** [comment] 2022-11-04 01:34
I still have the issue despite being on 6.0

**Comment by Samuelfaure** [comment] 2022-11-04 09:20
Can confirm, issue is still there in 2022.6.0, please reopen

**Comment by borjao-dev** [comment] 2023-05-01 16:05
Also confirm: Version 2023.2.0 has the same issue.

**Comment by Studio384** [comment] 2023-05-25 21:09
Can this issue be reopened? This bug still exists in the current 2023.2.2.

**Comment by kventil** [comment] 2023-06-12 06:48
```
Version: Insomnia 2023.2.2
Build date: 5/17/2023
OS: Darwin arm64 22.5.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64
```

Having also this issue.

**Comment by jn-novasol** [comment] 2023-08-08 06:16
Same issue. This is my biggest problem with Insomnia since I have been using it for multiple years.. So annoying

Version: Insomnia 2023.4.0
Build date: 04/07/2023
OS: Linux x64 6.4.8-arch1-1
Electron: 23.3.9
Node: 18.12.1
V8: 11.0.226.20-electron.0
Architecture: x64

**Comment by GoncaloPataca** [comment] 2023-08-10 19:51
As a workaround, create a new folder, inside that folder create two requests using the folder dropdown menu, drag and drop your main request in between the two requests you just created, then just delete the other two requests.

![insomniaDragAndDropSolution](https://github.com/Kong/insomnia/assets/75690156/e23f70d9-f3e4-4e6a-b828-11e5e3947634)

**Comment by vermgit** [comment] 2023-08-17 06:24
My Insomnia updated itself to 2023.5.3 and it reordered all folders and requests and I can't move them around anymore. The current order of them is completely useless.

Also all XPath-references are now broken. I don't know, maybe that's related somehow.

**Comment by philyg** [comment] 2023-08-22 11:54
For me not even this trick works in 2023.5.5.

**Comment by dp81** [comment] 2023-08-22 13:01
I've just updated Insomnia to 2023.5.5 and the moving of requests stopped working.

**Comment by michaelnguyen08** [comment] 2023-08-22 15:13
I have the same issue with 2023.5.5 on windows 10

**Comment by vermgit** [comment] 2023-08-23 07:36
2023.5.6 fixes this 😃  Thanks!

**Comment by ThierrydelCastillo** [comment] 2023-12-07 09:06
Apparently you have to be without any sorting filter for this to work. The tip given means that when you create a query the sort filter is canceled. It looks more like expected behavior than a bug (technical limit of the UI??)

**Comment by Samuelfaure** [comment] 2023-12-07 11:06
@ThierrydelCastillo The issue was fixed for me, plus I switched to Insomnium, so I can't reproduce, but I'm pretty certain I had no filters on

**Comment by JordanReiter** [comment] 2024-07-25 15:20
I thought I had this problem in version 9.3.2. It turns out you have to click on the request, hold, then wait for the request to get highlighted with a purple bar. Then I am able to drag requests around.

Once that happens the first time, I am able to drag the requests around as soon as I click on them.

But initially the interface acts as if the requests are not draggable.

**Comment by telemaxxx** [comment] 2024-08-09 10:25
Dragging requests gets disabled entirely when sort is set to alphabetical. I'd love to see a behaviour similar to vs code's explorer when in that mode, where it's still possible to drag requests to other folders. On that note, being able to cut/paste requests would be really nice. I don't want to have to collapse all my folders or move a request into an intermediate folder if I want to move it from a folder at the top to a folder on the bottom

**Comment by azegas** [comment] 2025-03-25 16:08
Make sure you are on "Manual" sort to be able to drag the requests around(to folders, out of folders).

![Image](https://github.com/user-attachments/assets/864b35fe-2111-42bc-8b0a-fe7b65cfb713)

**Comment by niranjan-differenzsystem** [comment] 2025-06-16 04:42
A keyboard shortcut will be appreciated if added for this so screen reader users who does not rely on mouse can also perform the task efficiently. I cannot use mouse and relying only on keyboard.

**Comment by inglar** [comment] 2025-11-10 15:31
how to move request OUT of the folder? it only works if i move request before folder, but doesn't work if i want to move it after folder.

<img width="297" height="284" alt="Image" src="https://github.com/user-attachments/assets/03d2f2d2-2c48-49d9-9ff3-fd63b90fc134" />

PS. I don't understand why every time someone wants to implement some ui behaviour it trying to invent a wheel instead of getting already implemented excellent/intuitive solutions...
