### ISSUE TITLE
(Bearer)-Variables are not recognized during Schema-Fetch

### ISSUE THREAD

**Issue by ChrisTTian667** [getinsomnia/insomnia#3220] opened 2021-03-22 18:00 UTC
**Describe the bug**
When working with OAuth protected GraphQL APIs, you're able to use the OAuth Token variables in the Request-Header. Thats a nice feature and works as expected while retrieving data. If you try to fetch schema information or documentation using this header from the very same GraphQL API, you'll get an "Not authorized" result, but only when using the OAuth-Token variable. It seems that those variables are not resolved when sending the introspection query. If you manually set the token it works as expected.

**To Reproduce**
1. Create a new GraphQL query to an OAuth protected API
2. Add OAuth 2.0 credentials & fetch Token. 
3. Add "Authorization": "bearer **Request -> OAuth 2.0 Token**".
4. Click "Refresh Schema"

**Expected behavior**
Schema is fetched

**Screenshots**

![insomnia1](https://user-images.githubusercontent.com/13163680/112035125-8a095500-8b3f-11eb-84de-bddb3fa939f1.jpg)
![insomnia2](https://user-images.githubusercontent.com/13163680/112035365-c2109800-8b3f-11eb-9f88-cf853ddf85a6.jpg)
![insomnia3](https://user-images.githubusercontent.com/13163680/112036068-81654e80-8b40-11eb-9d5c-b92ea99952ad.jpg)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3 (but also tested on Windows Machines of my colleagues)
 - App Version: 2021.1.1

**Comment by ChrisTTian667** [comment] 2021-04-07 19:55
Hey guys, were you able to reproduce the issue or can i provider additional information?

**Comment by dimitropoulos** [comment] 2021-04-09 19:09
sorry, we haven't been able to get to it yet, but we're trying! cc: @develohpanda

**Comment by filfreire** [comment] 2022-06-23 13:38
Hi @ChrisTTian667 thank for reporting this issue! Apologies for us not getting back to this in the meantime. We'll try to look at it asap. In the meantime, closing this one as duplicate of https://github.com/Kong/insomnia/issues/3013, since we have a few of these.

**Closed as completed by filfreire** 2022-06-23 13:38 UTC
Labels: N-investigation, M-duplicate, A-graphql
