### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by thedomeffm** [getinsomnia/insomnia#4087] opened 2021-10-08 13:41 UTC
### Insomnia Version

v2021.5.3

### What operating system are you using?

Ubuntu

### Operating System Version

18.04.1-Ubuntu

### Installation method

snap

### Expected Behavior

Import Shopware OpenApi json from [here](https://swagger.docs.fos.gg/version/6.4.5.1/api.json).
[Details](https://swagger.docs.fos.gg/?urls.primaryName=Management%20API%20(6.4.5.1))

### Actual Behavior

**Importing via URL:**

Get error "The URI does not contain a valid specification."
```
RangeError: Maximum call stack size exceeded
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:397:17)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
```

**Importing via clipboard:**
Get error "Your clipboard does not contain a valid specification."
```
RangeError: Maximum call stack size exceeded
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:397:17)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
```

**Importing via file (json):**
Get error "The file does not contain a valid specification."
```
RangeError: Maximum call stack size exceeded
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:397:17)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
    at object (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:402:45)
    at generateParameterExample (/snap/insomnia/153/resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:439:16)
```

### Reproduction Steps

1. Insomnia Preferences
2. Data
3. Import Data
4. ???
5. Profit

**Comment by MrSnix** [comment] 2021-10-10 00:44
This is a duplicate of  #1367. 
(You can find some advice on the thread to manually prevent this issue modifying the specification file)
A pull request (#4015) has already been proposed to address this.

**Comment by filfreire** [comment] 2021-12-16 17:44
Closing this one as a duplicate of #1367 (mentioned above by @MrSnix), nevertheless, thank you @thedomeffm for reporting 🙇

**Closed as completed by filfreire** 2021-12-16 17:44 UTC
Labels: M-duplicate, B-bug, O-linux-snap, S-unverified
