### ISSUE TITLE
[Feature Request] support for path variables

### ISSUE THREAD

**Issue by pklopotowski** [getinsomnia/insomnia#519] opened 2017-10-12 17:58 UTC
Would be nice to have a support for path variables:
`/users/{userId}/numbers`
Currently we can only use an environment variable in that case. But this is a very inconvenient way and inflexible because this parameter may change for each request and is environment independent.

**Comment by gschier** [comment] 2017-10-12 20:31
Thanks for the request @pklopotowski! This is probably a duplicate of #203

**Comment by pklopotowski** [comment] 2017-10-12 21:34
@gschier Definitely, this is the same type of requirements. I was searching for _[Feature Request]_ marker, but #203 is marked as _[Proposal]_, my inattention.
But let's focus on the problem. As you wrote, it may be done by placeholders. This gives us flexibility and shows a changeable/configurable part of a request.

**Comment by gschier** [comment] 2017-10-12 21:42
Exactly, meaning it can work for other things besides URL path variables. 😄

**Comment by gschier** [comment] 2017-10-31 22:02
Closing this one, as #203 seems like an appropriate solution.

**Closed by gschier** 2017-10-31 22:02 UTC

**Comment by pklopotowski** [comment] 2017-11-01 12:30
ok, thx. I will be waiting for this feature

**Comment by mpern** [comment] 2020-04-28 05:48
Any chance that #203 gets added to this roadmap?

It has a lot of upvotes and a glaringly missing feature of Insomnia.

**Comment by phylor** [comment] 2021-01-26 11:47
Note that #203 proposes to use a special kind of template syntax such as `{% my_variable %}` within the URL. When importing Open API specifications, the URL will contain `{my_variable}` (as the OP suggests). So this might not be the exactly same use case.

**Comment by mugi-luffy** [comment] 2022-01-16 11:37
this should not be closed
insomnia should support open api path parameters {my_variable} and allow to set them the same way as query parameters.
Postman does the exact same thing

**Comment by dmitriybraginets** [comment] 2022-03-09 18:15
Hi! Any progress here?

**Comment by quiquelhappy** [comment] 2022-04-17 20:35
why is this closed? lol

**Comment by remy727** [comment] 2023-12-29 18:36
Any update on this?

**Comment by risalfajar** [comment] 2024-01-13 01:40
This is so sad, someone has even [done this for them](https://github.com/Kong/insomnia/issues/203#issuecomment-691710227), and they choose to ignore him.
