### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by newfunk** [getinsomnia/insomnia#6326] opened 2023-08-18 11:26 UTC
Since the last 2 updates my filter function does not work anymore. 

Version: Insomnia 2023.5.4
Build date: 18-8-2023
OS: Windows_NT x64 10.0.19045
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

Am I the only one?

**Comment by filfreire** [comment] 2023-08-18 11:30
Duplicate of #6288

**Closed as completed by filfreire** 2023-08-18 11:30 UTC
