### ISSUE TITLE
searchbar does not filter the results

### ISSUE THREAD

**Issue by DennisGoermannMD** [getinsomnia/insomnia#6327] opened 2023-08-18 11:54 UTC
### Expected Behavior

When i use the searchbar at insomnia, the result should be filtered, so only matching entries will be shown

### Actual Behavior

The matched items are highlighted, but not filtered

### Reproduction Steps

Create a collection with at least two entries with different names. search for one entry. The result is not filtered, only highlighted

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This behavior is new for me, since two versions i think 

### Insomnia Version

2023.5.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### Installation method

download

### Last Known Working Insomnia version

2023.2.1

**Comment by DennisGoermannMD** [comment] 2023-08-18 12:31
With v2023.2.1 all works fine. i have downgraded it now locally to work with

**Comment by filfreire** [comment] 2023-08-18 13:19
duplicate of #6288

**Closed as completed by filfreire** 2023-08-18 13:19 UTC
Labels: B-bug, S-unverified
