### ISSUE TITLE
traps in debian 10

### ISSUE THREAD

**Issue by onovaes** [getinsomnia/insomnia#4007] opened 2021-09-06 15:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.2

### What operating system are you using?

Other Linux

### Operating System Version

Debian GNU/Linux 10 (buster)

### Installation method

download deb file e 2 click to install

### Last Known Working Insomnia version

2021.4.0

### Expected Behavior

Open the insomnia in my linux. 

### Actual Behavior

After the software is updated, it won't start anymore

### Additional Information

dmesg output

[   85.016948] traps: insomnia[3905] trap int3 ip:563988cb4e99 sp:7ffec58192d0 error:0 in insomnia[563986653000+6063000]

**Comment by onovaes** [comment] 2021-09-06 15:09
2021.4.1 - also works
2021.5.0 - trap error

**Comment by reynolek** [comment] 2021-09-07 15:31
Sorry you are having issues @onovaes! Have you tried reinstalling? Maybe try the apt repo rather than downloading the deb file from github ([directions here](https://insomnia.rest/blog/new-insomnia-apt-repository))?

We also recently released 2021.5.2.

**Comment by johnwchadwick** [comment] 2021-09-07 17:20
Could you provide the output of `cat /proc/cpuinfo`? It's a bit of a wild guess, but I'm curious if perhaps the problem is limited to certain CPU steppings.

**Comment by johnwchadwick** [comment] 2021-09-07 19:41
I'm combing the web for related problems. Here's an issue that might be related:

[browser frequently crashing with trap int3](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1898389)

From this Launchpad thread, it has been observed on:

|Chrome Version|Linux Version|
|--|--|
|85.0.4183.83-0ubuntu0.16.04.2|(Unknown Ubuntu 16.04)|
|88.0.4324.96|5.4.0-59-generic x86_64|

[In 2021.4.1, Insomnia used Electron 9.3.5](https://github.com/Kong/insomnia/blob/core%402021.4.1/packages/insomnia-app/package.json#L222), and [in 2021.5.0, Insomnia uses Electron 11.2.3](https://github.com/Kong/insomnia/blob/core%402021.5.0/packages/insomnia-app/package.json#L225). [Electron 9.3.5 is based on Chromium 83.0.4103.122](https://github.com/electron/releases/blob/v3.785.0/lite.json#L10264), whereas [Electron 11.2.3 is based on Chromium 87.0.4280.141](https://github.com/electron/releases/blob/v3.785.0/lite.json#L6772).

This suggests that if the problem was introduced in Chromium (83, 85], then it might be the same issue.

Do you have issues running Chromium on this machine? It may not crash right away even if this is the same bug.

**Comment by onovaes** [comment] 2021-09-08 12:43
> Could you provide the output of `cat /proc/cpuinfo`? It's a bit of a wild guess, but I'm curious if perhaps the problem is limited to certain CPU steppings.

cat /proc/cpuinfo - https://pastebin.com/wEcNng3P

I have the Chromium Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.10 (64-bit). I don't know if this chromium works well, as I rarely use it.

I've tried to reinstall insomnia, with no success. It only works until version 2021.4.1

Guys! Tks for the help

**Comment by johnwchadwick** [comment] 2021-09-08 18:16
@onovaes Apologies, I have found the issue. Regrettably, the package is just broken.

For the time being, please run:

```sh
sudo chmod 4755 /opt/Insomnia/chrome-sandbox
```

after installing the latest version of Insomnia. It should again work properly.

**Comment by johnwchadwick** [comment] 2021-09-08 18:18
(This is the same issue as #4010 and should be fixed when we have a release that doesn't have a buggy version of `electron-builder`.)

**Comment by onovaes** [comment] 2021-09-08 18:41
> @onovaes Apologies, I have found the issue. Regrettably, the package is just broken.
> 
> For the time being, please run:
> 
> ```shell
> sudo chmod 4755 /opt/Insomnia/chrome-sandbox
> ```
> 
> after installing the latest version of Insomnia. It should again work properly.

Tks, now 2021.5.2 version works

**Closed as completed** 2021-09-09 15:17 UTC
Labels: B-bug, S-unverified
