### ISSUE TITLE
Token of bearer authorisation disappears after pasting in version 2020.3.0 for Mac

### ISSUE THREAD

**Issue by UUsmonov** [getinsomnia/insomnia#2377] opened 2020-07-10 03:25 UTC
**Describe the bug**
While sending a request the token disappears in version 2020.3.0 for Mac. Till yesterday it worked correct but today it updated automatically and this bug appeared. I tried also manually download and install from site. The bug is not gone. 

I tried to request to get user information from my secured endpoint. So, I have to provide access token in header as bearer token (JWT).  After sometime time (2-3 seconds) the token that I pasted disappears. Both in Auth and in header section.

![Screenshot 2020-07-10 at 08 12 19](https://user-images.githubusercontent.com/50171681/87112531-81107600-c285-11ea-8f9b-09f97b952d86.png)

In this screenshot we can see that bearer token is sent correct.

![Screenshot 2020-07-10 at 08 12 33](https://user-images.githubusercontent.com/50171681/87112616-bb7a1300-c285-11ea-9aa6-957a8941a04e.png)

This is my problematic case. The token suddenly disappears(

 - OS: macOS 10.15.5
 - Installation Method: Automatic update & manual downloaded from site
 - App Version 2020.3.0

**Comment by develohpanda** [comment] 2020-07-10 06:40
Hi @UUsmonov! This may be related to #2354, there seems to be a bug where paste doesn't persist the text. 

As a workaround, if you paste your code, add a space and remove it (to trigger a save), that should work. Please let me know if that works for you! 

In the meantime, marking this as high priority, we'll aim to get a fix out soon. 🤗

**Comment by andriusvo** [comment] 2020-07-10 07:23
Same on the Ubuntu 18.04

**Comment by tisswb** [comment] 2020-07-10 09:11
Same on Window 10

**Comment by cancng** [comment] 2020-07-10 09:41
Same on Windows 10. header values are disappearing.

**Comment by DasJott** [comment] 2020-07-10 11:13
Same here on Manjaro Linux. Can not use.

**Comment by oscarmeanwell** [comment] 2020-07-10 11:53
Same on Linux mint 18 and macOS Mojave.

**Comment by tammo** [comment] 2020-07-10 14:11
Made a small gif, maybe that helps to understand how to reproduce it. Copy and pasting seems to not work correctly.

![CleanShot 2020-07-10 at 16 07 09](https://user-images.githubusercontent.com/90767/87163644-f735cc80-c2c7-11ea-840c-70e4de70577f.gif)

**Comment by oscarmeanwell** [comment] 2020-07-10 14:49
> Made a small gif, maybe that helps to understand how to reproduce it. Copy and pasting seems to not work correctly.
> 
> ![CleanShot 2020-07-10 at 16 07 09](https://user-images.githubusercontent.com/90767/87163644-f735cc80-c2c7-11ea-840c-70e4de70577f.gif)

Anyone wanting to downgrade because of issues here is a [link](https://github.com/Kong/insomnia/releases/tag/core%402020.2.2).

**Comment by oscarmeanwell** [comment] 2020-07-10 14:50
Anyone wanting to downgrade because of issues here is the [link](https://github.com/Kong/insomnia/releases/tag/core%402020.2.2)

**Comment by RayBB** [comment] 2020-07-10 15:04
@oscarmeanwell thanks for that link!

Don't forget to turn off auto update otherwise you'll be upgraded again as soon as you open it.

**Comment by alexislopes** [comment] 2020-07-10 15:16
for those looking for a workaround:
 
    - click the field and type something;
    - click out of the field;
    - click the field again and paste your content right after the content typed;
    - click out of the field and it should work;
    - then just clean the previosly typed content;

I tried to paste right before the typed chracters, same fail.

**Comment by thomaslevesque** [comment] 2020-07-10 15:19
I'm seeing this as well.
It also happens when I paste in the environment JSON

The workaround suggested by @alexislopes seems to work

**Comment by nijikokun** [comment] 2020-07-10 17:29
We are currently looking into it 🕵️‍♀️

Sorry for any issues this has caused 🙇‍♂️

**Comment by SFBorland** [comment] 2020-07-10 18:00
Similar issue, when pasting anything into the query field, after like 10 seconds it reverts back to the previous value it you sit and stare at it

EDIT: MacOs latest

**Comment by FelipeSSantos1** [comment] 2020-07-10 18:04
Also if we start to type some variable name, e then when the list of variable is showed, if we click on that it doesn’t work

**Comment by EXPEylazzari** [comment] 2020-07-10 18:24
Also having this issue with the latest update that I did today. It was the source of a lot of headaches. Consider this a vote to get this fixed ASAP! Thank you!

**Comment by nijikokun** [comment] 2020-07-10 18:24
Looks like we have found the root cause to be a [recently merged PR](https://github.com/Kong/insomnia/pull/2305), we are currently working on a fix. 🙏

**Comment by KakoF** [comment] 2020-07-10 19:18
Same problem! Token disapear, no store env variables.

**Comment by gschier** [comment] 2020-07-10 19:48
There's now a fix out for this in 2020.3.2
- https://insomnia.rest/changelog/core/2020.3.2
- https://insomnia.rest/changelog/designer/2020.3.2

**Closed as completed by gschier** 2020-07-10 19:48 UTC
Labels: P-high, B-bug

**Comment by UUsmonov** [comment] 2020-07-11 05:02
Hi @develohpanda thank for your fast feedback. 
I'm sorry that I haven't answer immediately. Since it didn't work for me I had to downgrade to version 2020.2.2.
I was in hurry because I had to test my RestApi.

**Comment by develohpanda** [comment] 2020-07-11 07:55
> I'm sorry that I haven't answer immediately. Since it didn't work for me I had to downgrade to version 2020.2.2.

No worries! Thank you for your report! It has been fixed in 2020.3.3 so you should be okay to upgrade now. 😊

**Comment by UUsmonov** [comment] 2020-07-11 16:25
> > I'm sorry that I haven't answer immediately. Since it didn't work for me I had to downgrade to version 2020.2.2.
> 
> No worries! Thank you for your report! It has been fixed in 2020.3.3 so you should be okay to upgrade now. 😊

You welcome) I updated successfully to 2020.3.3 and it works correct.
Thank you guys)
