### ISSUE TITLE
importing swagger deletes requests from collection

### ISSUE THREAD

**Issue by skyhirider** [getinsomnia/insomnia#3453] opened 2021-06-06 15:04 UTC
**Describe the bug**
Collection requests getting deleted if using same swagger file to import into another collection

**To Reproduce**
1. ~Go to https://editor.swagger.io/~ See https://github.com/Kong/insomnia/issues/3453#issuecomment-877886904
2. ~Click on File -> Convert and save as json~
3. Open latest Insomnia
4. Import json file as new new request collection
5. Go into import and import the same json again, but into a new separate collection
6. Bug happens, first collection looses all requests.

**Expected behavior**
Importing same swagger into a new collection does not remove the requests from any other collections. There are cases where I want to import same swagger spec into multiple collections.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Installation Method: via downloading installer from page
 - App Version 2021.3.0
![image](https://user-images.githubusercontent.com/1695005/120929745-8622b300-c6ea-11eb-870e-7551e42ea26f.png)

**Comment by dimitropoulos** [comment] 2021-06-07 16:12
Thank you for the clear reproduction steps.  Can confirm.

**Comment by AGenius** [comment] 2021-06-08 20:42
I spotted this today also

**Comment by skyhirider** [comment] 2021-06-29 19:19
I saw this was assigned to me but presumed it was an automated process. Is there anything else I should do apart from reporting this issue? It seems it was replicated by other people and is indeed a bug, and not a fun one at that.

**Comment by develohpanda** [comment] 2021-07-12 00:20
Note, in order to reproduce this you need a spec which has methods with their `operationId` defined and belonging in a tag. The default spec at https://editor.swagger.io no longer matches the requirements for this bug, use the following spec to reproduce it.

```yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
host: petstore.swagger.io
basePath: /v1
tags:
  - name: pets
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        "200":
          description: OK
```



<details>
<summary>Note, this bug does not exist with an OpenAPI 3 spec</summary>

```yaml
openapi: "3.0.1"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: petstore.swagger.io/v1
tags:
  - name: pets
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        "200":
          description: OK

```

</details>

**Comment by filfreire** [comment] 2022-08-12 09:55
Closing as duplicate of https://github.com/Kong/insomnia/issues/2882

Also related to https://github.com/Kong/insomnia/issues/4283

**Closed as completed by filfreire** 2022-08-12 09:55 UTC
Labels: B-bug, S-verified
