### ISSUE TITLE
[FEATURE REQUEST] Control order in which Unit tests are executed

### ISSUE THREAD

**Issue by Duvel** [getinsomnia/insomnia#2592] opened 2020-09-08 06:30 UTC
**Describe the bug**
I have multiple unit tests in a test suite and these need to be in a certain order, so have information available in the next request. When I execute this with the cli tool, this doesn't follow the order from the GUI.

I know in theory unit tests shouldn't depend on each other, but with the current way of running multiple requests, you have no clear view which requests are bering executed due to the use of the name.

**To Reproduce**
1. Go to 'Test'
2. Create a new test suite
3. Create 4 or 5 tests with a incrementing number in it's name
4. Execute the test-suite
5. See different order of unit tests

**Expected behavior**
The order with the CLI should be the same as in the GUI. 

**Screenshots**

```
  General
    ✓ Returns 200 (1585ms)
    1) Returns 200
    ✓ Returns 201 (305ms)
    2) Returns 200


  2 passing (2s)
  2 failing

  1) General
       Returns 200:
     Error: No responses for request

  2) General
       Returns 200:
     Error: No responses for request
```

The third test (201) should have run second.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Installation Method: dmg and yarn
 - App Version: 2020.3.3 and 2.2.22

**Additional context**

**Comment by develohpanda** [comment] 2020-09-09 10:27
Hi @Duvel, thanks for reporting this!

> but with the current way of running multiple requests, you have no clear view which requests are being executed due to the use of the name.

I'd like to clarify what you mean by this. If you _were_ to set up multiple requests to run in one test, how are you achieving that? A screenshot would be epic!

Ideally, instead of introducing ordering to the tests I would prefer to investigate the solution where we make it nicer to make multiple requests in one test. This way, traditional unit testing concepts will translate as-is to designer. 😄 There _is_ a case for controlling test order as well, but that is likely a more involved fix.

**Comment by Duvel** [comment] 2020-09-11 13:05
I see that I mixed what I needed and what is available. I meant "the use of the id".

```
const response2 = await insomnia.send('req_b733c874b56c477982ac7da149d21ab6');
expect(response2.status).to.equal(201);

const response1 = await insomnia.send();
expect(response1.status).to.equal(200);
```


In my use case response2 sets a few variables for response1.

**Comment by develohpanda** [comment] 2020-09-11 23:54
Cool, that's what I assumed you meant. 😊 It would be nice to explore nunjucks templating in unit tests so that we can show the request name, instead of id, for instance.

**Comment by palevi67** [comment] 2021-11-04 12:34
To me it would be a great if:

1.- Insomnia-cli run tests sequentially and in a known order (as insomnia now do)
2.- Insomnia allows to manually reorder tests

This would make test configuration much simpler, reducing the need to deal with javascript code and obscure request ids.

Maybe what insomnia calls "test" could be renamed to "test step" or "api call" or something similar, and what insomnia calls "test suite" could be renamed simply a "test" ... what do you think?

**Comment by pierreozoux** [comment] 2022-05-18 16:01
I agree that in term of UX this is confusing between the UI that does run them in order, and the CLI that does run them randomly.

**Comment by Sl-Alex** [comment] 2022-08-12 15:31
I'd say, this is quite a critical bug.
Imagine the following test set:

Test case 1: login as admin with the default password
Test case 2: change the password
Test case 3: logout
Test case 4: login as admin with the new password
Test case 5: reset the configuration to the factory default

Executing tests in a different order will never work.
Of course, there are completely stateless APIs, like checking if the server is alive, but those are rather an exclusion.
In the CLI test cases are ordered anyway, the problem is that the order is wrong.

**Comment by Neko-Design** [comment] 2022-08-29 05:46
Hey All, this one is a critical one for my current case as well, where we have an ordered flow to validate each step of an onboarding api, something like:

1. Create Account
2. Send validation email
3. Update Account
4. List account resources
5. Delete account

Where each call needs to be made in sequence as running the steps out of order wouldn’t work, so we need guaranteed ordering in some way.

**Comment by enricojonas** [comment] 2023-03-29 09:13
Hi all,

just stumbled about this and this makes the cli testing unusable for us. In our case we need to call our API to create an ID that we can use to test against.

We could use request chaining for it but it would mean to modify all the requests that are involved in the flow to test. Some simple flows could consist of 3 requests, let's say create a context, modify context, delete context. Obviously this must be done in this order.

So I guess the UI is doing it "correctly" in the order you define, though it is missing basic functionality to re-order requests.

inso cli though doesn't respect any of the given order. I guess there needs to be something introduced so that we can choose whether the tests in a suite should run in serial or randomly and this choice should be consistent when running tests from the UI or CLI.

**Comment by ThanhHuyLe** [comment] 2023-08-18 14:24
@enricojonas 
I want to optimize CLI usage to automatically run tests for all requests, saving time especially with large Test Collections. 
Can we consider using request chaining as a temporary solution for the control order issue? 
If there are updates or better solutions since your March 29 comment, I'd appreciate hearing about them.

**Comment by gatzjames** [comment] 2024-02-01 09:29
Fixed now that tests and test suites can be reordered

**Closed as completed by gatzjames** 2024-02-01 09:29 UTC
Labels: N-discussion, A-design, PA-testing, needs-triage
