### ISSUE TITLE
[Feature Request] Grid / Table view support for JSON/XML content

### ISSUE THREAD

**Issue by ray-qu** [getinsomnia/insomnia#529] opened 2017-10-14 10:06 UTC
- Insomnia Version: 5.9.6
- Operating System: Windows 7

## Details

No doubt Insomnia is a **great tool** as a REST Client, but it needs little more tweaking to make it far better, or say it more **Human friendly** as the tag line says Consider real time scenario: When it comes to handle long request/responses, it becomes bit cumbersome to navigate the JSON content. For example, an customer order detail with 50+ line items or say some config like package.json file, etc. We believe you got the picture. The preview / pretty-print already does a good job, but it's still machine friendly.

The Grid view feature in Altova XML Spy Tool can be taken as reference. There are many Chrome plug-ins also provide formatting of JSON to table / grid view for presenting JSON / XML content in more human readable way.

Reference URL: http://manual.altova.com/xmlspy/spyenterprise/xseditingviews_gridview_tables.htm
or, http://valentin.dasdeck.com/lingo/dml/screenshots/xmlspy_grid_view.png

Cheers,

**Comment by gschier** [comment] 2017-10-14 13:10
Hi @ray-qu. Thanks for the feedback!

This is a duplicate of #284 so please see the discussion there.

**Closed by gschier** 2017-10-14 13:10 UTC

**Comment by ray-qu** [comment] 2017-10-14 19:57
Thank you for looking into this and sorry to comment on a closed request. Would agree #284 is sort of duplicate only for the JSON part. This request is for both JSON & XML in a seamless way. The suggestion out on the other request doesn't seem close enough to the table / grid view (react-json-tree approach). The expand / collapse adds some flexibility, but the viewer still sees curly braces (the phonetics basically). It would be nice to a novice & pro without going much detailed into technical of XML / JSON when viewed in a spreadsheet fashion (for the moment they use the tool). Not sure whether you re-consider, but IMO if this put through well thoughts w/ some creativity, this will put the tool a distinguished of its kind.

**Comment by gschier** [comment] 2017-10-14 20:09
The original question on #284 _was_ for a table view, so I think it's appropriate for you to leave your opinion on _that_ issue. 

The original author of the issue said they would be fine with a tree-view approach, but I think it would be good if you left your opinion there  (basically what you said above) saying why you would still prefer the table view.

**Comment by wonderbeyond** [comment] 2017-10-24 13:04
> The original author of the issue said they would be fine with a tree-view approach

@gschier I am the author of issue#284, but I did not say tree-view is an alternative. You must mismatched me with another one who left a comment.

I didn't post more words to insist on my opinion just because you have expressed your opinion in this reply:

> Since a table view would only work with a very specific data format, I hesitate to include it as a general feature.

**Comment by gschier** [comment] 2017-10-24 15:45
Ah, sorry about that. Yes, the comment was from another user. Also, it's true that there is a lot to do before getting to something like this. However, it may be possible with the plugin system ie the future. I've beee thinking that it might be useful to allow plugins to define their own preview mode for responses.
