### ISSUE TITLE
Insomnia 8.6.1 local API connectivity issues

### ISSUE THREAD

**Issue by exotexot** [getinsomnia/insomnia#7087] opened 2024-02-13 11:15 UTC
### Expected Behavior

The title says it all. And I am so angry, that I let ChatGPT write this post for me:

Dear Insomnia Team,

I am writing this issue with a mix of disbelief and extreme frustration. As a long-time supporter and user of Insomnia, I've always admired your work for its reliability and efficiency. However, the latest update has completely shattered my trust. The update has rendered Insomnia utterly useless for testing local APIs (e.g. http://localhost:1337/api/assets) - a fundamental feature that many of us rely on daily!

Let me be clear: the inability to connect to local APIs is not just a minor inconvenience; it is a catastrophic failure that disrupts the entire development workflow. This is unacceptable for a tool that is supposed to streamline and simplify API testing. 

What baffles me even more is the lack of communication or warning about such a significant change. There was no heads-up, no beta testing invitation, nothing. We were blindsided by this update that seems to have been rolled out without proper testing or consideration for how it would impact your user base.

This isn't just a bug; it's a complete breakdown of functionality. How could such a critical aspect of the software be overlooked? It's as if the needs and use cases of your loyal users have been completely ignored. 

I demand an immediate fix to restore local API connectivity. This is a non-negotiable aspect of the Insomnia tool, and its absence has brought my work to a screeching halt. I also expect a thorough explanation of how such a significant oversight happened and what steps are being taken to ensure it never happens again.

I hope for a swift and effective resolution to this issue. Please remember that your user base depends on the stability and reliability of your software for their daily tasks. Don't let us down.

This shows the request I'm trying within insomnia
![Screenshot 2024-02-13 at 12 13 09](https://github.com/Kong/insomnia/assets/10153413/62f292c2-5020-4cab-853e-62be6bec0b1b)

This is the expected result, shown in browser. It is more useful than using Insomnia for me now.
![Screenshot 2024-02-13 at 12 08 52](https://github.com/Kong/insomnia/assets/10153413/92058f2e-799c-4dd0-9c82-d8b1d61f55e8)

### Actual Behavior

-

### Reproduction Steps

Open insomnia
Try requesting local api
be disappointed

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.1

### What operating system are you using?

macOS

### Operating System Version

macOS 14

### Installation method

FORCED FUCKING UPDATE

**Comment by exotexot** [comment] 2024-02-13 11:17
You forced this update on me. I didn't choose to install it. You decided to force this update and break my developer experience. You don't even give me chance to roll back to a previous version.

Damn, I'm so angry.

**Comment by exotexot** [comment] 2024-02-13 11:21
And just to make clear: I'm only angry because a few years ago, Insomnia was working PERFECTLY Fine. I really loved it. You really had me as a happy user. But since you heavily commercialised the software since a few years, you fucked it up. My personal opinion.

**Comment by filfreire** [comment] 2024-02-13 11:57
Hi @exotexot 

Thank you for taking the time to share your feedback and concerns with us. We understand your frustration and appreciate your long-standing support for Insomnia. We are committed to resolving the issues you've encountered and restoring your trust in our tool.

To help us address the problem more effectively, we recommend the following steps:

1. **Reproduction of Behavior**: Please try to reproduce the unusual behavior by using the "Copy as cURL" option from the request dropdown. This will help us determine if the issue is consistent and not isolated to Insomnia.

2. **Disabling Automatic Updates**: In the Preferences, under the Software Updates section, you have the option to disable automatic updates. This will prevent future updates from being applied automatically, allowing you to control when and how you update Insomnia.

3. **Reverting to an Older Version**: If the latest update is causing significant disruption to your workflow, you can revert to an older version of Insomnia by visiting [our releases page on GitHub](https://github.com/Kong/insomnia/releases). Please ensure you disable automatic updates after installing an older version to avoid the issue reoccurring.

4. **Share More Details**: Since we are not fully aware of the specifics of the local API you are trying to test, sharing a code snippet or clearer reproduction steps would be immensely helpful. It's possible that the API may be blocking third-party API clients in some way, and additional details will aid us in pinpointing the issue.

We take your concerns seriously and are investigating this matter thoroughly to prevent such incidents from happening in the future. Your feedback is invaluable to us as it helps improve Insomnia for all our users.

**Comment by subnetmarco** [comment] 2024-02-13 16:08
@exotexot What is the issue? I don't understand your ChatGPT question.

Is localhost reachable outside of Insomnia? Is Insomnia hanging when you are trying to make a request?

Did ChatGPT also use the F* word in your post? Be polite.

**Closed as completed by subnetmarco** 2024-02-13 16:08 UTC
Labels: N-author-input, B-bug, S-unverified
