### ISSUE TITLE
CMD + P for quick switch does not open window for search Mac M2

### ISSUE THREAD

**Issue by Ivan-Donchenko** [getinsomnia/insomnia#6313] opened 2023-08-17 13:36 UTC
### Expected Behavior

CMD+P  shortcut pressed and Quick Switch window opened

### Actual Behavior

CMD+P  shortcut pressed and Quick Switch window not opened.

### Reproduction Steps

Precondition: Macbook Air m2 macOS Ventura 13.5
Open Insomnia app
Enter the workspace
Press CMD+P for quick switch

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

After few reinstalls of Insomnia app CMD+P shortcut does not work. I dont understand why. Previously I used Insomnia app on Ubuntu 22.04 and everythig was ok, but now when i switched to macOS Quick Switch does not work. I tried to reset settings, reinstall appp, change shortcut but nothing help

### Insomnia Version

2023.5.3

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.5

### Installation method

via official site

**Comment by filfreire** [comment] 2023-08-17 13:38
Duplicate of #6301

**Closed as completed by filfreire** 2023-08-17 13:38 UTC
Labels: B-bug, S-unverified
