### ISSUE TITLE
Chained requests work in desktop client but not via Inso CLI

### ISSUE THREAD

**Issue by coladarci** [getinsomnia/insomnia#3366] opened 2021-05-07 23:27 UTC
**Describe the bug**

Let's say I want to create a request to an endpoint, but I first need an auto token. The way I would do this is:

Create Two Requests:
1) POST Login
2) GET My Request

#2 would set a header that would look something like this:
```
Authorization: Bearer {% response 'body', 'req_dd905edea3924ac8bfac7539f97b427d', 'b64::JC50b2tlbg==::46b', 'never', 60 %}
```

Which is fancy-speak for "pull the `token` key out of the Login request and use it inside an auth header prefixed w/ Bearer.

When I'm in "Debug" mode in my client, I just click on Login, first, then I click on My Request, and all works.

When I'm in "Test" mode, I create a new test suite and then I'm confused at what I"m *supposed* to do; as far as I can tell, there are three options:

1. use the "New Test" option and add each step as a "test" (this feels wrong) 

![image](https://user-images.githubusercontent.com/1004167/117517255-4f714580-af50-11eb-80f3-e95169f81077.png)

2. make a single test and then attempt to hack together a bunch of requests in a single test run:

![image](https://user-images.githubusercontent.com/1004167/117517304-7f204d80-af50-11eb-868a-68d01f816f67.png)

3. Only add My Request and then go through each chained request and select a trigger behavior to tell it to make the dependent request if it needs to.

![image](https://user-images.githubusercontent.com/1004167/117517377-b5f66380-af50-11eb-8c87-d69fc5c1d47e.png)

No matter which option I take above, clicking "Run Tests" works. Yet 1 and 2 don't work when running in `CLI; I always get `Error: No responses for request`.

If I try #3 in CLI, I can get it to work, but only if there is only 1 element in the chain; i.e if Req 1 requires Req2 which requires Req 3, it fails. That said this solution feels terrible, because it's making a ton of extra calls; trying to login each request instead of re-using the token. 

**To Reproduce**
1. Make a request that returns something
2. Make a second request that needs something from the first
3. Make a test suite that contains those two requests, each as "tests"
4. Verify Run Tests works
5. Try and run `inso test` and select that suite

**Expected behavior**
It works

**Desktop (please complete the following information):**
 - OS: 11.3
 - Installation Method: Mac App
```
Version: Insomnia 2021.3.0
Release date: 4/28/2021
OS: Darwin x64 20.4.0
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by joshrl-clearme** [comment] 2021-08-23 12:21
Also very curious about this. The docs don't seem to clarify, but it appears that [chained requests](https://support.insomnia.rest/article/175-chaining-requests) just aren't supported in the CLI as far as I can tell. 

@develohpanda @coladarci -- can you clarify? is this just not supported as of yet? it would be good to know....

**Comment by coladarci** [comment] 2021-08-23 14:44
We weren’t seeing any traction from the team here so we forked the project and bent it to our will (changes were trivial; they are actively BLOCKING it in the code base from what we could tell) 🙃

I think there was a concern of infinite loops of requests chained in an infinite combo.

**Comment by develohpanda** [comment] 2021-08-24 02:54
Hi all, apologies for the delay, issues do slip under our radar and we're trying our best to keep up. Thanks for bringing this to my attention @joshrl-clearme.

I just tested a request chaining scenario using 3 requests in the chain and it seems to be working as intended both within Insomnia v2021.4.1 and with Inso v2.3.0, the stable release for each.

![image](https://user-images.githubusercontent.com/4312346/130547595-0f109057-c179-497f-8d81-533fe7633ee8.png)

Request 3 depends on Request 2, which in turn depends on Request 1. In this chain, the trigger behavior is set to "Always", but any option except for "Never" works fine too.

I used the following workspace to test this:
[![Run in Insomnia}](https://insomnia.rest/images/run.svg)](https://insomnia.rest/run/?label=3366&uri=https%3A%2F%2Fgist.githubusercontent.com%2Fdevelohpanda%2Fd58c110caa6c7cbb2ea6e03dd23b722d%2Fraw%2Fa4e3685679e26e624f1d0922e48386e454428acb%2Ffile.json)

For this to work you'd need to run `npm run serve` from `packages/insomnia-smoke-test`.

@coladarci / @joshrl-clearme, could you please help me understand what is different/specific about your use-case, where this flow doesn't work for you via the Inso CLI?

If there is definitely a case we are missing, @coladarci would you consider opening a PR with the changes from your fork back into this main repo so we can fix the root issue?

> It is worth noting that #3385 was merged recently and will be part of the next release; it improves the behavior for chaining to better cater for multiple requests in a chain, although my reproduction steps above are from the current stable release.

### The finer details

The reason that option 1 and 2 don't work in the CLI environment is because when `insomnia.send()` is called, it initializes a [new in-memory database](https://github.com/Kong/insomnia/blob/706b0f076ae667ea2de7df11510010e20deb3d08/packages/insomnia-app/app/common/send-request.ts#L13-L43) (which is needed for request/response chaining). When running within the app, it does not need to initialize a new database because one already exists, containing the responses for each request.

Because a new db instance is used with each `insomnia.send()` invocation within a unit test while running tests from the CLI (whether or not this sandboxing should happen is a separate conversation), it means that if the trigger behavior in a request chain is set to "never", the response of a dependent request executed within the same unit test is not available for the chain to work.

However, if you set the trigger behavior to send dependent requests as necessary, then one invocation of `insomnia.send()` to the top of the chain (Request 3 in my screenshot above) should execute all dependent requests as they are needed.

**Comment by coladarci** [comment] 2021-08-24 15:43
Thanks it appears it was fixed after we submitted this issue - https://github.com/Kong/insomnia/pull/3385/commits

**Comment by wdawson** [comment] 2021-08-24 16:10
Awesome, thanks for confirming @coladarci ! I'll close this issue then. Feel free to reopen if something's still amiss.

**Closed as completed by wdawson** 2021-08-24 16:10 UTC
Labels: B-bug, PA-inso, PA-testing, S-unverified

**Comment by tkowalski29** [comment] 2024-03-24 15:24
I think is not working now

**Comment by tkowalski29** [comment] 2024-03-24 16:22
On wersion 2.4.0 working on the 8.6.1 is not working

**Comment by 0erty** [comment] 2024-05-26 08:36
We also encountered this problem. This will greatly affect our work with Insomnia, is there a way to fix it?
