### ISSUE TITLE
[Bug] Sub Environments Not Showing When Duplicated (But Still Work)

### ISSUE THREAD

**Issue by eorroe** [getinsomnia/insomnia#591] opened 2017-11-13 01:56 UTC
## Steps to reproduce

1. Make a workspace, with a sub environment.
2. Select the sub environment.
3. Create a request that uses one of the variables in the sub environment
4. Duplicate the workspace, notice the sub environment is still in use and the variables work.

But when you edit the environment the sub environment is missing and can still be used but not deleted

- Insomnia Version: 5.11.5
- Operating System: Windows 10

**Comment by rcrooks** [comment] 2017-11-21 19:25
also seen on MacOS (10.13.1). In my case, I exported a workspace, then deleted it, and them imported it back into Insomnia. The sub environment in it then behaved exactly as described above.

**Comment by gschier** [comment] 2017-11-21 19:26
Currently fixing the cause of this bug now. It's a tricky one :/

**Comment by gschier** [comment] 2017-11-21 19:31
You should be able to fix it manually with the following steps:

1. Export the workspace (be sure to include private environments)
2. Find all environments named "Base Environment"
3. If there are more than 1, delete the others
4. Update the parentId property of each Environment to be the same as the _id property of the "Base Environment"

**Comment by gschier** [comment] 2017-11-22 23:01
Closed by #616

**Closed by gschier** 2017-11-22 23:01 UTC
Labels: Committed, High Priority

**Comment by gschier** [comment] 2017-11-23 01:38
I just pushed an early [beta version](https://insomnia.rest/changelog/5.12.0-beta.1/) that prevents this from happening. It will also automatically fix the messed up environments when the app launches. If you give it a try, be sure to set the "update channel" to "stable and beta" in the settings, or else the app will automatically update to the previous stable release.

**Comment by rcrooks** [comment] 2017-11-23 15:39
Thanks, @gschier -- will give it a try

**Comment by rcrooks** [comment] 2017-11-24 16:42
@gschier all seems well with beta 3 -- thanks!

**Comment by gschier** [comment] 2017-11-24 16:50
Awesome! Good to hear 👍 😄
