### ISSUE TITLE
[Bug] copies only '-' in clipboard when trying to copy a JWT

### ISSUE THREAD

**Issue by SergejKern** [getinsomnia/insomnia#433] opened 2017-08-14 17:24 UTC
## Overview
- `Insomnia Version:` 5.7.11
- `Operating System:`  Win 7
- `Summary: ` 

I am getting a JSON containing a JWT from a POST, a try to copy a part of it into the clipboard. When trying to paste into some editor, all I get is one character '-'. However, when I switch to RAW, then I can copy successfully. And, in Preview or Source, when I doubleclick on some string part´, and some part gets selected, it also works fine. Just when I select with my mouse by pressing, holding, moving and letting go - it dows not work.

## How To Reproduce
I try to get a token from keycloak, but I suppose this behaviour is not dependent on keycloak at all.
1. Create new request to keycloak or something that gives a JSON with an JWT in it.
In my case its a POST to http://server/auth/realms/MyRealm/protocol/openid-connect/token
2. Perform a request which returns a valid JSON
3. try to copy a access_token data to clipboard
4. paste it in any editor

**Comment by gschier** [comment] 2017-08-14 17:25
This is a duplicate of #430

**Comment by gschier** [comment] 2017-08-14 17:26
@SergejKern will try to deploy the fix for this today.

**Closed by gschier** 2017-08-14 17:25 UTC
