### ISSUE TITLE
Insomnia Designer Install Error

### ISSUE THREAD

**Issue by aniq-pirzada** [getinsomnia/insomnia#2078] opened 2020-04-29 17:17 UTC
**Describe the bug**
Unable to install Insomnia Designer

**To Reproduce**
1. Download Insomnia Designer for Windows
2. Try to install Insomnia Designer (as Admin)
3. Error when isntalling.

**Expected behavior**
Insomnia Designer to be installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/11415321/80625727-87909f00-8a45-11ea-826f-d47710b8842b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: Insomnia.Designer-2020.1.0.exe
 - App Version Designer 1.0

**Additional context**
[squirrellog.txt](https://github.com/Kong/insomnia/files/4553227/squirrellog.txt)

**Comment by reynolek** [comment] 2020-04-29 18:33
Duplicate of #2073 

Thanks for reporting! We are actively investigating the issue. I am going to close this in favor of the other one for easier tracking purposes.

**Closed as completed by reynolek** 2020-04-29 18:33 UTC
Labels: O-windows, N-investigation
