### ISSUE TITLE
GraphQL fetch schema not able to use the `f` Request

### ISSUE THREAD

**Issue by nico-arianto** [getinsomnia/insomnia#3464] opened 2021-06-11 09:24 UTC
**Describe the bug**
We set the Header like below
![image](https://user-images.githubusercontent.com/6427889/121662510-0163da80-cad8-11eb-9ad5-3a4cdb433f11.png)

While the Authentication Token is fetched
![image](https://user-images.githubusercontent.com/6427889/121662658-3112e280-cad8-11eb-88f7-14ec8154c9d6.png)

But the GraphQL fetch schema is failed
![image](https://user-images.githubusercontent.com/6427889/121662329-ca8dc480-cad7-11eb-970c-c96366c00998.png)

While it did works correctly for `Send`
![image](https://user-images.githubusercontent.com/6427889/121663073-9bc41e00-cad8-11eb-9176-308972bf4b65.png)

**To Reproduce**
1. Create New Request with `GraphQL` body
2. Enable the Authentication (In my case is `OAuth2`)
3. Set the `Authorization` in `Header` with value something like `Bearer [Request -> OAuth 2.0 Identity Token]`
4. In `GraphQL` tab > schema > `Refresh Schema`
5. See the failed notification said `Failed to fetch schema: No OAuth 2.0 identity tokens found for request`

**Expected behavior**

Able to fetch the Schema and pass the `Header` information as `Send` process

**Screenshots**

Attached as above in the description

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Installation Method: dmg
 - App Version: v2021.3.0

**Additional context**

**Comment by filfreire** [comment] 2022-06-23 13:40
Hi @nico-arianto thank for reporting this issue!

Closing this one as duplicate of https://github.com/Kong/insomnia/issues/3013, since we have a few of these. We'll look into this soon.

Feel free to report any other issues you come across.

**Closed as completed by filfreire** 2022-06-23 13:40 UTC
Labels: N-investigation, M-duplicate, B-bug, A-graphql, S-unverified
