### ISSUE TITLE
Command + Enter to send now not work

### ISSUE THREAD

**Issue by locnguyen-teq** [getinsomnia/insomnia#6406] opened 2023-08-29 07:38 UTC
### Expected Behavior

When selecting a request and pressing command + enter, the request should be sent successfully
<img width="295" alt="image" src="https://github.com/Kong/insomnia/assets/39117386/973e94ad-a27c-4439-bfde-5544ec826c52">

### Actual Behavior

When selecting a request and pressing command + enter, the request is not sent and the software starts having errors. If I select another request and re-select the original request that I pressed command + enter on, it will not work anymore. The workaround is to select a different project, then go back to the original project.

### Reproduction Steps

1. Open the software
2. Select a request 
3. Press command + enter on the request
4. The request is not sent
5. Select another request 
6. Re-select the original request
7. Pressing command + enter no longer works for the original request
8. Select a different project
9. Go back to the original project
10. The issue persists

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

if click on list item below and press command + enter and then button can't click again
<img width="565" alt="image" src="https://github.com/Kong/insomnia/assets/39117386/24295258-cf3d-4846-80eb-24f47ae2fe4f">

### Insomnia Version

2023.5.6

### What operating system are you using?

macOS

### Operating System Version

macOS 13.1

### Installation method

https://insomnia.rest

**Comment by jackkav** [comment] 2023-08-30 09:41
This is currently happening only when the request sidebar was the last thing clicked as its swallowing the cmd+enter event because our component library is using it for selection. 
There should be a workaround for this but we haven't found it yet, need to dig into react-aria.
In the meantime tabbing away from the request sidebar will allow you to cmd+enter without using the mouse.

**Comment by ClementJ-PW** [comment] 2023-09-05 09:25
I had the same issue but I found that the alternate shortcut Ctrl + R seems to still work. This is not as comfortable of a shortcut as Ctrl + Enter but it will have to do until this bug is fixed.

**Comment by subnetmarco** [comment] 2023-10-23 11:39
This regression will be fixed in the next 8.4 release.

**Comment by subnetmarco** [comment] 2023-11-21 20:40
This regression has been resolved in 8.4.x.

**Closed as completed by subnetmarco** 2023-11-21 20:40 UTC
Labels: B-bug, S-unverified
