### ISSUE TITLE
Schema explorer

### ISSUE THREAD

**Issue by hzawawi12** [getinsomnia/insomnia#1106] opened 2018-08-08 20:15 UTC
- Insomnia Version: ___Version 6.0.1 (6.0.1.2298)
- Operating System: ___ macOs High Sierra

## Details

Would be nice to have a schema explorer that show different mutations/queries available for a particular service.
Schema will include the different input/output types expected and help in writing the different queries/mutations in the client.

**Comment by gschier** [comment] 2018-08-08 21:40
Closing this as it's a duplicate of #451

**Closed by gschier** 2018-08-08 21:40 UTC
