### ISSUE TITLE
[Bug] GraphQL Query Variables pane hides query string pane

### ISSUE THREAD

**Issue by SN9NV** [getinsomnia/insomnia#858] opened 2018-04-11 13:08 UTC
- Insomnia Version: v5.12.3
- Operating System: Ubuntu 17.10 (Linux 4.13.0-38-generic x86_64) Gnome on Wayland

## Details

With the GraphQL layout, the Query Variables pane can take up the full height of the main pane, and you cannot access the query string pane above it.

A solution could be to limit the Query Variables pane to 50% of the height of the parent. Or maybe a scroll bar for both of the panes?

### Can access the query string section
![image](https://user-images.githubusercontent.com/10219618/38618364-b90fbec6-3d99-11e8-8020-0eb7774b35e6.png)

### Cannot access the query string section
![image](https://user-images.githubusercontent.com/10219618/38618450-01f25cac-3d9a-11e8-83d5-f49cbdf903c3.png)

**Comment by gschier** [comment] 2018-04-11 13:29
Hi @SN9NV!

Please update to the latest version v5.15.0, as this was fixed a while ago. 
Duplicate of #700

**Closed by gschier** 2018-04-11 13:29 UTC

**Comment by SN9NV** [comment] 2018-04-11 14:51
:man_facepalming: I feel so stupid. I did an apt upgrade, but I had installed it from the deb package and assumed that it was added to my sources. :disappointed:

**Comment by gschier** [comment] 2018-04-11 15:10
Oh no! Glad you figured it out though 😄
