### ISSUE TITLE
Reponse Lookup for different Environments broke with 2022.7.2

### ISSUE THREAD

**Issue by deckdom** [getinsomnia/insomnia#5682] opened 2023-01-16 16:08 UTC
### Expected Behavior

The latest response should be displayed and should be appended to the environment history.

### Actual Behavior

Performed requests do not show up

### Reproduction Steps

1. Create a new HTTP Request/Use an existing HTTP Request
2. Be sure to enable the Option "Request / Response" -> "Filter reponses by environment"
3. Send the request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It seems like sent requests are not assigned to any environment and therefore are filtered out.
Disabling the Option "Request / Response" -> "Filter reponses by environment" makes responses visible again.

Seems to be broken since the Update, as it was working before (Not sure which version I had installed before however)

### Insomnia Version

2022.7.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 (Enterprise), v10.0.19044

### Installation method

Download from Insomnia.rest

### Last Known Working Insomnia version

2022.7.1

**Comment by filfreire** [comment] 2023-01-16 17:14
@deckdom thanks for reporting this, this is a duplicate of https://github.com/Kong/insomnia/issues/5664 - fix for it will go out today

**Closed as completed by filfreire** 2023-01-16 17:14 UTC
Labels: B-bug, S-unverified
