### ISSUE TITLE
Sorting / Searching - Slow on Larger Collections

### ISSUE THREAD

**Issue by lincolnpjames** [getinsomnia/insomnia#6404] opened 2023-08-29 00:48 UTC
### Expected Behavior

I expect the sorting/searching to be almost instantaneous similar to previous versions.

### Actual Behavior

Sorting takes ~3s and searching ~6s

![Screen Recording 2023-08-29 at 9 43 53 am](https://github.com/Kong/insomnia/assets/919524/ceb6d08e-4904-44bf-8569-0197ff9cbef3)
![Screen Recording 2023-08-29 at 9 44 55 am](https://github.com/Kong/insomnia/assets/919524/3ed82bbe-b73d-474a-93c7-4ba256474730)

### Reproduction Steps

1. Open Collection
2. Sort an Item
3. Search for the Item

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Current Version
```
Version: Insomnia 2023.5.6
Build date: 8/23/2023
OS: Darwin arm64 22.5.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64
```

This behavior was not present on `2023.4.0`, only once #6349 was resolved and sorting/searching was fixed is it now present.

### Insomnia Version

2023.5.6

### What operating system are you using?

macOS

### Operating System Version

Darwin Not-a-MBP.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### Installation method

insomnia.rest

### Last Known Working Insomnia version

2023.4.0

**Comment by joshua-wheeler** [comment] 2023-08-30 14:45
I can reproduce this issue. I discovered when searching existing issues for performance issues I've had since last update release so I don't enter duplicate issues.

**Comment by jcurlier** [comment] 2023-09-07 17:35
+1

**Comment by vvivanloc** [comment] 2023-09-07 22:21
would it be fixed by #6461 ?

**Comment by itsc-Hohmann** [comment] 2023-10-19 11:18
I also find it slow for a few versions now. Already considering going for the alternative :(
Just typing into the filter bar takes long to show the results. I have only like a hundred request entries.

**Comment by subnetmarco** [comment] 2024-08-01 12:28
We made some significant improvements in the [latest 9.3.3](https://github.com/Kong/insomnia/releases/tag/core%409.3.3) (up to 20x in some cases). Can you please verify that this issue is solved?

**Comment by lincolnpjames** [comment] 2024-08-01 22:31
I'm happy for this to be closed however, I am unable to confirm as I've pinned myself to a version prior to the feature enforcing an account to use this application.

**Comment by subnetmarco** [comment] 2024-08-02 13:46
@lincolnpjames understandable. You can also try this in Scratch Pad without creating an account. I will close this issue for now, but I will re-open it if we determine it has not been resolved.

**Closed as completed by subnetmarco** 2024-08-02 13:46 UTC
Labels: B-performance, B-bug, S-unverified
