### ISSUE TITLE
Support SSO login (e.g. SAML, with Okta)

### ISSUE THREAD

**Issue by guidotrueb** [getinsomnia/insomnia#2877] opened 2020-11-27 08:28 UTC
**Describe the solution you'd like**

One key feature for teams would be to support SSO login in your paid subscription.

**Describe alternatives you've considered**

A reasonable alternative would be to support login with Google/GitHub/GitLab accounts.

**Additional context**

I believe many companies would consider migrating from Postman if this was available on your platform.

_Thanks and keep the great work!_

**Comment by nijikokun** [comment] 2020-12-03 22:04
It's on the roadmap! 🎉

**Comment by ericbach** [comment] 2021-01-21 18:40
@nijikokun Do you have an ETA on this feature? Would you expect something in the next Q1/2 or further down the road?

**Comment by csotiriou** [comment] 2021-07-05 09:44
This would be a major and very useful feature.

**Comment by iuvalk** [comment] 2022-02-13 11:59
Any ETA for the SSO feature?

**Comment by manali-bhosale** [comment] 2022-06-27 20:15
Any links we can follow for the SSO feature updates?

**Comment by filfreire** [comment] 2022-08-25 15:59
Hi @guidotrueb, I'm closing this as duplicate of #1999
SSO feature is at the moment being worked on by the team, with initial support of GitHub.
Soon other platforms will be added.

**Closed as completed by filfreire** 2022-08-25 15:59 UTC
Labels: needs-triage
