### ISSUE TITLE
App not launching, error: libX11.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by veritas1** [getinsomnia/insomnia#3814] opened 2021-07-14 07:26 UTC
**Describe the bug**
Application does not launch. Instead returns the following error:
>/snap/insomnia/144/insomnia: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory

**Desktop**
 - OS: Pop OS 21.04
 - Installation Method: Snap
 - App Version: 2021.4.1 (latest/stable channel)

**Additional context**
I just upgraded from Pop OS 20.10, where it was working.

**Comment by filfreire** [comment] 2022-05-10 09:54
Hi @veritas1, we have since upgraded some dependencies that helped with similar issues of folks using Insomnia on linux. Are you still able to reproduce this issue with our [latest release (2022.3.0)](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?

**Comment by filfreire** [comment] 2022-07-27 10:24
Hello again @veritas1, I'm going to close this issue in the meantime. Feel free to reopen it or create a new one if you still face this issue with our latest [stable](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2) or [beta](https://github.com/Kong/insomnia/releases/tag/core%402022.5.0-beta.5) releases.

**Closed as completed by filfreire** 2022-07-27 10:24 UTC
Labels: N-author-input, B-bug, O-linux-snap, S-unverified
