### ISSUE TITLE
[Bug] Issue in new update ,json path validations not working properly

### ISSUE THREAD

**Issue by parasuramln** [getinsomnia/insomnia#1629] opened 2019-08-08 09:20 UTC
- Insomnia Version: 6.6.2
- Operating System: WINDOWS 10

## Details

json path query working in previous version ,now it is not working .

tested in https://jsonpath.com/ also .
![image](https://user-images.githubusercontent.com/22343548/62691154-b5334500-b9eb-11e9-967c-2f8902d9b248.png)
but in insomnia i am getting error.
![image](https://user-images.githubusercontent.com/22343548/62691212-d6943100-b9eb-11e9-8eb7-5e223a1fec52.png)

for sample data & query please check https://stackoverflow.com/questions/56071136/json-path-expression-to-find-a-value-corresponding-to-a-particular-name

**Comment by michaelrommel** [comment] 2019-08-08 12:27
I have the same problems since yesterday. A path like
`$.arrayname[?(@.createdBy=="user1")]`
does no longer work...

**Comment by gschier** [comment] 2019-08-08 15:48
Hmm, there was a JSONPath bug in 6.6.0 but it _should_ be fixed now. 

Here is Insomnia running that exact query in 6.6.2

In the Response tag

![image](https://user-images.githubusercontent.com/587576/62717648-4695bd80-b9d2-11e9-9b19-85bac2224e99.png)

And in the regular response filter

![image](https://user-images.githubusercontent.com/587576/62717673-51e8e900-b9d2-11e9-88b1-d0db893bf3f0.png)

Can you try it in both places to see if it's just one of them that's not working?

**Comment by michaelrommel** [comment] 2019-08-12 20:09
Hello, today the update was available for me to install (when I commented on this issue, I was not aware of a .2 version, because pressing the "check now" button on the update preferences returned with "up to date")

I can confirm, that the update fixed the issue for me!

**Closed** 2019-08-13 13:46 UTC
Labels: Needs More Info ℹ️
