### ISSUE TITLE
[Bug] Sidebar drag and drop freeze

### ISSUE THREAD

**Issue by nkkollaw** [getinsomnia/insomnia#1443] opened 2019-04-21 11:01 UTC
- Insomnia Version: 6.3.2
- Operating System: Xubuntu 18.04

## Details

When I try to sort request groups in the sidebar, the app completely freezes and I have to kill it and restart it.

This was a problem connected to Electron actually (https://github.com/electron/electron/issues/14430 I believe), but it had been solved. Now it appeared again.

**Comment by gschier** [comment] 2019-04-22 18:32
Does this still happen in 6.4.0? I'm not able to reproduce it on my Mac unfortunately. I've heard of it happening on Mac too though but it seems to only happen on certain setups.

**Comment by nkkollaw** [comment] 2019-04-22 18:40
@gschier yup, just installed 6.4 and it's still happening.

Also, I don't know if there's a switch that I can use, but even if I launch it from the command line there is no error.

**Comment by gschier** [comment] 2019-04-22 19:13
There probably isn't an error message if it's hanging. 

Also going to close this one as a duplicate of #1373 
Please move further discussion there

**Closed by gschier** 2019-04-22 19:13 UTC
