### ISSUE TITLE
[Bug] Prompt storage key not clearing on restart

### ISSUE THREAD

**Issue by julian-sf** [getinsomnia/insomnia#1976] opened 2020-03-02 18:07 UTC
**Describe the bug**
Prompts with storage keys do not re-prompt when the application is restarted.  If I change the storage key, the prompt fires as expected on the next request.

**To Reproduce**
1. Build a prompt like so:
    ![image](https://user-images.githubusercontent.com/50758144/75702636-d3aca680-5c83-11ea-8993-684ca1a9a672.png)
2. Run the Request
3. Fill in the prompt with some value (let's use `2`)
4. Restart Insomnia (close and open it)
5. Run the Request

**Actual behavior**
The Request is run with the old values for the prompt

**Expected behavior**
A prompt should appear asking for a new value

**Screenshots**

Request:
![image](https://user-images.githubusercontent.com/50758144/75703655-dc9e7780-5c85-11ea-90c5-9a6d1c529d9f.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Installation Method: DMG installer
 - App Version: Version 7.1.1 (7.1.1.3350)

**Additional context**
I hope this isn't a user error, but from what I've seen I haven't been able to discern the proper way to use this feature.  If this is not a bug, I think at the very least some clear documentation around usage that is easy to find would be a good by-product.

I have checked through the other bugs and don't seem to see anything similar to this one.  The closest was #1063, but that seems resolved.

**Comment by etauker** [comment] 2020-03-05 18:31
I was looking into using this feature today and based on the documentation it looks like a bug to me too.

In addition, I was wondering if there is a similar feature that keeps the input in memory only, without persisting it anywhere. I am looking to use it for caching credentials for the current session only and need them to be cleared after closing (or in the even of a crash). I though maybe this would be suitable but looks like it persists the input.

**Comment by gschier** [comment] 2020-03-09 23:15
@etauker the best way to go about this would be to fork the prompt plugin and modify it to your needs. It is not meant for storing sensitive information.

As for the original issue. Values are not meant to reset after restarting Insomnia. What you're seeing is expected behavior. To reset a prompt that uses a storage key, you need to change the storage key.

**Closed as completed by gschier** 2020-03-09 23:15 UTC

**Comment by bennyrw** [comment] 2020-08-18 11:19
Sorry to comment on a closed issue but I also found myself here after finding the actual behaviour (version 2020.3.3) doesn't match the tooltip that appears for 'Storage key': 'If this is set, the value will be stored in memory under this key until the app is closed'. Perhaps the tooltip could be corrected if this is working as you intend? Thanks
