### ISSUE TITLE
Grpc request does not import path with dependency of another proto

### ISSUE THREAD

**Issue by lfkimura** [getinsomnia/insomnia#3238] opened 2021-03-24 17:44 UTC
**Describe the bug**
Grpc request does not import path with dependency of another proto

**To Reproduce**
1. Go to 'New Request'
2. Click on 'GET'
3. Scroll down to grpc.'
4. Click on 'CREATE'
5. Click Import proto file import file of dependency of another proto 
like import "google/protobuf/timestamp.proto";
4. Click on 'SAVE'
4. Click on 'Send'

**Expected behavior**
Have some feature to import path of proto dependecies

**Comment by haswalt** [comment] 2021-03-25 11:02
I have a similar issue. Looks like this is because the includeDirs option is not being passed to proto-loader so it tried to parse the proto file in isolation.

I'll try and put a PR together to resolve this.

**Comment by filfreire** [comment] 2022-07-26 16:24
Thank you for reporting this @lfkimura. Sorry for not replying sooner!

We're going through some gRPC issues, and noticed there's some of them that point to a common trend (e.g. not being able to properly load a proto file that depends on another one). I'm going to go ahead and close this one as a duplicate of #3316 

Feel free to report any other issues you come across, we'll try to look into this issue asap.

**Closed as completed by filfreire** 2022-07-26 16:24 UTC
Labels: N-investigation, A-grpc, S-unverified
