### ISSUE TITLE
Filter Response Body Failed to Render dc

### ISSUE THREAD

**Issue by dwwitter** [getinsomnia/insomnia#7044] opened 2024-02-01 01:43 UTC
### Expected Behavior

Attempting to select a previously used filter in the Filter Response Body

### Actual Behavior

When choosing a previously used filter in the Filter Response Body, the program crashes with an error that says:

Failed to Render dc 

The Stack Trace is:

Error: Failed to execute 'querySelector' on 'Element': '[data-key="$.json.published."year""]' is not a valid selector.
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-417d832f.js:44:79232
    at Xh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-417d832f.js:44:24296)
    at j6 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-417d832f.js:44:42448)
    at mve (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-417d832f.js:44:41270)
    at gc (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-417d832f.js:44:40309)
    at DA (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-417d832f.js:44:36912)
    at Bs (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-417d832f.js:42:3288)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-417d832f.js:44:34286
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.2.1

### Installation method

download and install

**Comment by gatzjames** [comment] 2024-02-01 09:18
Thanks for the issue. A fix is coming on the next patch release.
Closing as duplicate of #6977

**Closed as completed by gatzjames** 2024-02-01 09:18 UTC
Labels: B-bug, S-unverified
