### ISSUE TITLE
URI not updated when copying from clipboard

### ISSUE THREAD

**Issue by Cera06** [getinsomnia/insomnia#2382] opened 2020-07-10 14:28 UTC
**Description**
When sending a GET request on a page the first request work.
If I update the same URI but copy-paste something at the end, the URI is not updated and the request is sent to the previous URI.

**To Reproduce**
Steps to reproduce the behaviour:
1. Send a GET request to URI path
2. Update the URI to a sub-path and send a new request

**Expected behavior**
The request should be sent to the new URI

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 x64
 - Installation Method: deb package
 - App Version : insomnia/2020.3.0

**Additional context**
The issue should be easy to reproduce, I attached a simple flask server to help understant the context.
[simple_flask.py.txt](https://github.com/Kong/insomnia/files/4903608/simple_flask.py.txt)
The steps are :
1- Open Insomnia
2- Send GET http://127.0.0.1:5000/
3- Copy paste "list1/" at the end
4- Send GET http://127.0.0.1:5000/list1/
5- Check in Timeline, it clearly show the issue "Preparing request to http://127.0.0.1:5000/"

**Comment by Necrontyrr** [comment] 2020-07-10 14:37
Not just the url. Also pasting something in the headers doesn't update the request. I have to type everything.
Version 2020.3.0 on Windows 10.

And yes, I just broke stuff on production because of this.

Edit: Pasting in the body also doesn't work. All the clipboard functionality is broken.

**Comment by marcellorvalle** [comment] 2020-07-10 14:45
Just opened a similar issue about the environment variables. Seems to be a application wide problem.

**Comment by RayBB** [comment] 2020-07-10 15:01
Yes seems related to #2377 
If you want to downgrade:
https://github.com/Kong/insomnia/releases/tag/core%402020.2.2

Don't forget to turn off auto update otherwise you'll be upgraded again as soon as you open it.

**Comment by nijikokun** [comment] 2020-07-10 17:24
Duplicate of #2377

**Closed as completed by nijikokun** 2020-07-10 17:24 UTC
