### ISSUE TITLE
pressing tab inserts a tab character instead of focusing the next field

### ISSUE THREAD

**Issue by rburgst** [getinsomnia/insomnia#4267] opened 2021-12-03 08:14 UTC
when editing the query params of a request, pressing tab will insert a tab (or 4 chars, dont remember), rather than moving the focus to the next field.
```
Version: Insomnia 2021.6.0
Release date: 27/10/2021
OS: Darwin x64 21.1.0
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0
```
not sure when this was broken, but it used to work as expected

**Comment by filfreire** [comment] 2021-12-03 11:00
@rburgst thank you for reporting this!

It turns out it had already been reported and is a duplicate of https://github.com/Kong/insomnia/issues/4206

It has been solved in https://github.com/Kong/insomnia/pull/4215 and the fix should be available in the next upcoming release.

**Closed as completed** 2021-12-03 11:00 UTC
Labels: M-duplicate
