### ISSUE TITLE
[Bug] Insomnia doesn't respect system proxy

### ISSUE THREAD

**Issue by shravan2x** [getinsomnia/insomnia#2046] opened 2020-04-23 07:31 UTC
**Describe the bug**
Insomnia doesn't respect the currently set system proxy, so network trace tools like Fiddler don't catch its traffic. This is difficult in cases where Fiddler is being used to compare requests from different sources.

**To Reproduce**
1. Run Fiddler
2. Send a request through Insomnia

**Expected behavior**
Insomnia respects the system proxy.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: Setup exe
 - App Version: 7.1.1

**Comment by nijikokun** [comment] 2020-04-30 20:15
Hi @shravan2x! Thanks for using Insomnia 😊 

I think we did some work for proxies in Core for the Designer application. @gschier would this happen to be fixed by that proxy work we did, or is there more that we would need to do to support things like this?

**Comment by gschier** [comment] 2020-05-02 18:40
We don't support automatic detection of system proxies but perhaps we could handle this better in the future.

For now, you can manually set the proxy settings from within the application preferences. https://support.insomnia.rest/article/53-http-s-proxy

Going to close this one, as it's not a bug. Feel free so open another issue if you still feel that automatic detection is necessary 😄

**Closed as completed by gschier** 2020-05-02 18:40 UTC
Labels: N-investigation

**Comment by shravan2x** [comment] 2020-05-02 19:18
@gschier I think this is a reasonable default so Insomnia plays well with other applications. Manually setting the proxy works but is a chore to set/remove on each use.

Could we reopen this issue and treat it as a feature request? I see the appropriate tag has been added already.

**Comment by FabioNevesRezende** [comment] 2023-04-30 14:27
Is it already been added? Insomnia currently not working with proxychains and in the menu preferences there is only support for HTTP proxy, which cannot work  with tor that is a Socks5 proxy
