### ISSUE TITLE
[Bug] 6.4.0 unable to change OAuth2 values

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#1452] opened 2019-04-23 20:03 UTC
- Insomnia Version: 6.4.0
- Operating System: Arch Linux 5.0.7

## Details

When changing some values at the OAuth2 tab Insomnia throws some erros on the console, and the changed value is reverted to the previously state. For example, when changing some of these credentials:

![image](https://user-images.githubusercontent.com/12160864/56611886-55a25c80-65e9-11e9-8a70-00ca1d0ffd72.png)

Insomnia throws the following:

![image](https://user-images.githubusercontent.com/12160864/56611923-694dc300-65e9-11e9-8985-769daf5e77fb.png)

So I changed the auth mode to `No Authentication` and back to `OAuth 2` to get a clear form, and even the `Grant Type` got stuck and unable to change.

**Comment by gschier** [comment] 2019-04-23 21:56
Duplicate of #1449

**Closed by gschier** 2019-04-23 21:56 UTC
