### ISSUE TITLE
MacOS Icon is oversize

### ISSUE THREAD

**Issue by Nemesis19** [getinsomnia/insomnia#5938] opened 2023-05-03 08:23 UTC
### Expected Behavior

Icon of same size of every other icons on MacOS

### Actual Behavior

It's oversize, please see the screenshot
<img width="254" alt="Screenshot 2023-05-03 alle 10 22 42" src="https://user-images.githubusercontent.com/5808262/235865568-fde84029-77a2-48ba-9649-cc23e8ac132e.png">

<img width="287" alt="Screenshot 2023-05-03 alle 10 22 55" src="https://user-images.githubusercontent.com/5808262/235865625-f66860d6-e05e-4895-855a-b3b9f04b377c.png">

### Reproduction Steps

Just install the latest Insomnia version.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

latest

### What operating system are you using?

macOS

### Operating System Version

MacOS from bigsur and up (Monterey and Ventura)

### Installation method

download insomnia rest for macos

### Last Known Working Insomnia version

2023.1.0

**Comment by filfreire** [comment] 2023-05-03 08:28
duplicate of #5922

**Closed as completed by filfreire** 2023-05-03 08:28 UTC
Labels: B-bug, S-unverified

**Comment by Nemesis19** [comment] 2023-05-03 08:44
thanks, never expected to search for "logo" among the other requests 🤦‍♂️...considering it's technically and "icon".

I apologize for the duplicate
