### ISSUE TITLE
[Bug] Cannot reference numeric Environment Variable values in GraphQL query variables

### ISSUE THREAD

**Issue by jgeth** [getinsomnia/insomnia#1937] opened 2020-02-12 18:00 UTC
**Describe the bug**
When referencing an environment variable in GraphQL query variables, an environment variable that contains a JSON number both reports a JSON parse error in the query variables pane and results in a GraphQL error for invalid expected type of Int due to rendering as a string value.

**To Reproduce**
1. Create an environment variable with a numeric value
2. Create a GraphQL query using query variables
3. Reference numeric environment variable in query variables
4. See JSON parse error in Query Variables pane
5. Send Query and (likely) receive type error

**Expected behavior**
Expect support for numeric JSON values in (Insomnia) environment variables. This may require the JSON parsing to interpret Nunjucks template markup before parsing to resolve parse error and to pass a numeric value when given one.

**Screenshots**
<img width="1410" alt="Screen Shot 2020-02-12 at 9 48 59 AM" src="https://user-images.githubusercontent.com/21069919/74362533-b61fa780-4d7d-11ea-9b28-9c8ff23fb96d.png">
<img width="1324" alt="Screen Shot 2020-02-12 at 9 51 52 AM" src="https://user-images.githubusercontent.com/21069919/74362554-bf107900-4d7d-11ea-8cca-a43e77b586bc.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.2
 - Installation Method: homebrew
 - App Version: v7.0.6

**Comment by jostFT** [comment] 2020-05-05 13:00
any update on this?

**Comment by afterdigital** [comment] 2020-05-11 09:18
I'm hitting this problem as well I'm having to hardcode the value in, which defeats the purpose.

**Comment by jkamleh** [comment] 2020-05-14 01:15
Getting the same issue with standard JSON POST request while evaluating this product.

Am i missing something or is this an issue with _numeric_ Environment Variables throughout Insomnia?

testIntEnvVar is defined in a Sub Environment:
`"testIntEnvVar": 1234`

![image](https://user-images.githubusercontent.com/14323780/81881632-d0ad2b00-95cf-11ea-85ca-7d8b4f7ab462.png)

EDIT:
Although this is just a linting error, the request POST's successfully and returns the desired result in this case.

**Comment by jostFT** [comment] 2020-05-18 12:56
@jkamleh , if you don't mind me asking, but what platform are you on?

What you wrote works fine for me. I'm on **Mac OS 10.14**
**However**, a coworker runs **Windows 10**, and it **doesn't work** for him.

We're both running **Insomnia 7.1.1**.

**EDIT:** 
It doesn't actually work for me, it turned out that it was simply caching the previous query variables due to the linting error

**Comment by jkamleh** [comment] 2020-05-18 13:36
@jostFT I’m running Windows 10 and encountered the issue on the latest downloadable release (unsure  of the version number as I’m away from my workstation).

**Comment by panchalkalpesh** [comment] 2020-05-18 15:45
+1 👍 

Getting the following errors: 
<img width="467" alt="Screen Shot 2020-05-18 at 11 43 32 AM" src="https://user-images.githubusercontent.com/1808686/82232689-f2265380-98fc-11ea-9e47-4ab0b830bace.png">
<img width="466" alt="Screen Shot 2020-05-18 at 11 44 58 AM" src="https://user-images.githubusercontent.com/1808686/82232755-0702e700-98fd-11ea-8e41-f40716b6973c.png">
<img width="469" alt="Screen Shot 2020-05-18 at 11 43 42 AM" src="https://user-images.githubusercontent.com/1808686/82232694-f2beea00-98fc-11ea-968a-748e6d1130ea.png">



Confirmed on: 
- OS: macOS Mojave 10.14.6
- Installation Method: [Official Installer](https://insomnia.rest/download/#mac)
- App Version: 7.1.1 (7.1.1.3350)

**Comment by Rogn** [comment] 2020-06-03 07:34
The issue still persists in the latest version, 2020.2.1.
Insomnia can't handle numeric query variables correctly.
![image](https://user-images.githubusercontent.com/3670768/83608222-766f0c80-a574-11ea-8deb-8d7941069699.png)

Previewing the User variable:
![image](https://user-images.githubusercontent.com/3670768/83608344-ad452280-a574-11ea-9a62-dbefc20b990a.png)

**Comment by krithigagupta** [comment] 2020-06-08 16:46
Any update on this?

**Comment by krithigagupta** [comment] 2020-06-08 16:49
Is this only specific to environment variables? Can Insomnia handle numeric variables coming from Request Body attribute?

**Comment by vino-jasuba** [comment] 2020-08-11 06:46
If the data you're referencing comes from the result of another request, you can pull it out of the response body object as below.
The only downside to this that I noticed is that insomnia can't parse the JSON body correctly. However, the request is handled just as expected.

Using insomnia core 2020.3.3 on ubuntu 20.04 

![insomnia crop](https://user-images.githubusercontent.com/30801697/89865765-00f86b80-dbb7-11ea-9d9a-419082a276e7.png)

**Comment by jostFT** [comment] 2020-08-21 13:29
@vino-jasuba Are you certain that it is not using your previous json body that had no parsing errors? That's what happened to me. I thought it worked, but it turned out that due to the parsing error, it simply referred to a previous json body that had no parsing errors.

**Comment by Pimentoso** [comment] 2020-10-06 08:47
+1 same issue, Macos Catalina 10.15.7
Version: Insomnia Core 2020.4.1

**Comment by dhoelzgen** [comment] 2020-10-12 13:33
Same issue here. Adding a numeric environment variable / response variable to the query variables leads to invalid json, and it seems it does not really re-evaluate it.

Problem seems to be the way Insomnia handles the references:

`{
	"id": {% response 'body', 'req_fa61b45b7eeb4643ae0a4ce424d72abe', 'b64::JC5kYXRhLmFkZENhc2VEYXRhR3JvdXBUb0Nhc2UuY2FzZURhdGFHcm91cC5pZA==::46b', 'never', 60 %}
}`

**Comment by almerindo** [comment] 2021-02-22 23:47
Any update about it?

I have been tryied many diferent ways and it did'nt works fine.

![image](https://user-images.githubusercontent.com/554495/108784627-973a2080-754e-11eb-807f-b036ca8ea5a8.png)

![image](https://user-images.githubusercontent.com/554495/108784684-b33dc200-754e-11eb-9260-9b2091ea04c6.png)

![image](https://user-images.githubusercontent.com/554495/108784933-32cb9100-754f-11eb-9951-6989a9b89fc6.png)

**Comment by abbasegbeyemi** [comment] 2021-04-15 14:16
Still running into the same issue. Any fix on the horizon?

**Comment by kevinjalbert** [comment] 2021-10-20 20:19
Just commenting here that this is still an issue.

While you can still send the request even with the lint error. The underlying issue of Nunjucks templating in code mirror editor not being valid JSON seems to be the problem. In the 'manage environment' modal though a lint error actually prevents you from saving it -- which is pretty broken.

**Comment by jostFT** [comment] 2022-01-12 15:38
Just to emphasise that this is **still** an issue.
And yet, not even one developer has as much as commented on the issue.

**Comment by taboadakt** [comment] 2022-01-26 21:59
Any updates on this issue? Is any clarification needed to get a solution started?

**Comment by aBOBination** [comment] 2022-01-27 00:16
Any update on this issue?  I am running into this same error when trying to use ints.

**Comment by dleurs** [comment] 2022-02-01 16:03
Any update ?

![image](https://user-images.githubusercontent.com/58068925/152004434-15da3b19-fb2b-4780-b766-165b5164e551.png)

![image](https://user-images.githubusercontent.com/58068925/152004501-fe7fac44-fd37-4225-9192-1d6aef88e64a.png)

Putting double quotes modify the requests and it fails

**Comment by benlester** [comment] 2022-02-08 15:38
I too have this issue, it's a real show stopper for GraphQL chaining work.

**Comment by wildermuthn** [comment] 2022-03-01 21:37
Insomnia is a great product, but this is a show-stopper for using GraphQL with it.

**Comment by jostFT** [comment] 2022-03-16 10:34
@wildermuthn, if I remember correctly, it works perfectly fine in Postman. That is a very powerful alternative at least.
The industry price is just pretty steep 😬

**Comment by jmckinney** [comment] 2022-03-22 14:43
So this is a 2 year old open issue with no updates? This is an absolute blocker for me getting my team switched over to Insomnia

**Comment by iErik** [comment] 2022-03-22 20:42
There's really no workaround for this? It's pretty basic functionality

**Comment by jostFT** [comment] 2022-03-23 09:59
@iErik @jmckinney, I'll have a bit more free time from Monday and onwards, so I'm planning on taking a stab at it myself 😄 
I have no idea how the project is built or where the issue lies, so it might take a while. I will keep you posted 🤞 
any help is much appreciated 😄

**Comment by fabriziotrenti** [comment] 2022-10-25 11:13
Any news on this issue? It is still present in version 2022.6.0

**Comment by justswoosh** [comment] 2023-03-01 17:42
Any update?  This is limiting our ability to use this more wide spread.

**Comment by suuunly** [comment] 2023-03-02 10:03
@justswoosh, the issue has been active for 1114 days - and the devs have not noticed it yet. So I doubt it will ever get fixed.

So I've found 3 possible solutions to the problem:

1. Create a wrapper GraphQL request that takes in only strings, and parses them over to your actual request
2. Switch to Postman (since this issue does not exist on Postman)
3. Or submit your own PR with a solution to this problem.

I wanted to go for option 3 myself, however I haven't really had the time to delve into it.
Since then, we have also slowly moved away from GraphQL.
And finally, I've found other old annoying bugs in Insomnia, that they don't have time to look at either.

So all in all, I will most likely go with option 2.

**Comment by tnovau** [comment] 2023-04-12 21:32
Are there any news?

**Comment by subnetmarco** [comment] 2023-10-23 11:44
+ @ihexxa

**Comment by subnetmarco** [comment] 2023-11-16 12:36
This is being worked on in https://github.com/Kong/insomnia/pull/6823

**Comment by subnetmarco** [comment] 2023-11-22 18:20
This has been fixed in 8.4.4, available for download today.

**Closed as completed by subnetmarco** 2023-11-22 18:20 UTC
Labels: N-help
