### ISSUE TITLE
404 when working with a Bitbucket server

### ISSUE THREAD

**Issue by DrMetallius** [getinsomnia/insomnia#2220] opened 2020-05-27 16:25 UTC
**Describe the bug**
When trying to push changes in git to a Bitbucket server, a 404 response is returned.

**To Reproduce**
1. Set up git integration for a repository with a Bitbucket server (we have the version 6.2.0)
2. Make a commit
3. Push the changes
4. An error with the following stack trace appears:
```
HTTPError: HTTP Error: 404 
    at Function.discover (/Applications/Insomnia Designer 2.app/Contents/Resources/app.asar/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:6481:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Expected behavior**
Changes are pushed successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/5721128/83045549-6627d080-a04e-11ea-861f-6dfcc99d3d45.png)

**Desktop:**
 - OS: Mac OS X 10.15.4
 - Installation Method: GitHub releases
 - App Version: 2020.1.4-alpha.1

**Additional context**
The issue happens during the request `/info/refs?service=git-receive-pack`. The `Accept` header contains `application/json`, which trips the server up for some reason. If the header doesn't contain `application/json` or is even absent altogether, everything works.

This header comes from axios defaults. There is a workaround for this, the problem goes away if I type something like this in DevTools:
```
require("axios").defaults.headers.common["Accept"] =  "*/*"
```
Obviously, it's rather annoying to type it in all the time, so I would appreciate if this gets fixed.

**Comment by 4n70w4** [comment] 2020-09-01 15:25
The same issue

**Comment by sahinyanlik** [comment] 2020-10-20 09:18
Hello,

I am having same problem 

```
HTTPError: HTTP Error: 404 
    at Function.discover (C:\XXX\AppData\Local\insomnia-designer\app-2020.4.1\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:6481:13)
    at async fetchPackfile (C:\XXX\AppData\Local\insomnia-designer\app-2020.4.1\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:7296:22)
    at async fetch (C:\Users\XXX\Local\insomnia-designer\app-2020.4.1\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:7157:22)
    at async Object.pull (C:\XXX\AppData\Local\insomnia-designer\app-2020.4.1\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:9895:49)
    at async GitSyncDropdown._handlePull (file:///C:/XXX/AppData/Local/insomnia-designer/app-2020.4.1/resources/app.asar/bundle.js:193810:7)
```

I am able to clone through console however when I use my token and username in the Insomnia Designer V2 I cannot pull. If I try wrong username then I get 401 response so I am sure username and token is true.

I cloned from console such as git clone https://usename:token@bitbucketserver.com 

I am using bitbucket server in local. 

Thanks.

**Comment by sallendbug** [comment] 2021-07-30 14:44
Confirmed problem still exist with BB server 6.10.0 and with  both Mac and Windows clients of Insomnia.

**Comment by eldon111** [comment] 2021-09-30 16:14
I'm having the same issue with Bitbucket v7.6.3

**Comment by isaacjlivingston** [comment] 2022-01-11 09:51
I'm having the same issue on the Windows Insomnia client, and workaround that DrMetallius mentioned works for me.

**Comment by mattdillon100** [comment] 2022-03-15 01:04
This is still occurring.

I have fixed it locally by unpacking the `app.asar` file into `/opt/Insomnia/app/` and adding the following line:
```
headers['Accept'] = "*/*";
```
to `/opt/Insomnia/resources/app/node_modules/isomorphic-git/index.cjs:6571`

This is a terrible workaround but works nonetheless.

It would be great if you guys could just update your dependencies.

**Comment by gsigmund** [comment] 2022-05-24 07:06
same issue here, please fix it in next version

**Comment by filfreire** [comment] 2022-05-25 10:57
Hi @DrMetallius, thanks for reporting this, and apologies for not getting back sooner.

I've been trying to reproduce this in our [latest beta build](https://github.com/Kong/insomnia/releases/tag/core%402022.4.0-beta.1), but so far haven't been able to get back the error with the 404 response.

On the other hand, I'm observing a lot of weird behavior and problems when using Bitbucket + Insomnia:

- When creating a new branch - the branch isn't created remotely
<img width="827" alt="Screen Shot 2022-05-25 at 11 41 42" src="https://user-images.githubusercontent.com/11976836/170246510-457b17ed-89d7-4bfd-85aa-b1bd3df572b5.png">


- When creating a new branch - we're don't seem to be carrying over the changes up to that point in the newly created branch, everything up to that moment becomes unversioned in the new branch.
- When cloning an existing repository, we're not picking up any of the history on the default branch we checkout, it's as if I just cloned an empty repository and I can introduce again the same changes.

<img width="1010" alt="Screen Shot 2022-05-25 at 11 43 29" src="https://user-images.githubusercontent.com/11976836/170246654-c87e8f13-baf1-4ba4-b914-94f21c5be99f.png">



Are you folks still able to get the 404 error page with [latest beta](https://github.com/Kong/insomnia/releases/tag/core%402022.4.0-beta.1) or even with [latest stable build](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?



cc @gsigmund @mattdillon100 @isaacjlivingston @eldon111 @sallendbug @sahinyanlik @4n70w4 


EDIT: 

If it helps, I'm using the following settings for the "App password" which I use in Insomnia as a personal access token:

![Screenshot 2022-05-24 at 17 09 53](https://user-images.githubusercontent.com/11976836/170248025-6f49ea93-aa20-4c6d-9204-ae2984d381e8.png)
 
BTW, are you folks using the [cloud bitbucket](https://bitbucket.org/), or your own private cloud/on-premises instances?

**Comment by rschwedasi** [comment] 2022-06-10 07:35
@filfreire The issue still exists with the latest builds. In my case it is a self hosted Bitbucket server instance. Setting the Accept-Header like described by @DrMetallius seems to work fine.

**Comment by bosnian** [comment] 2022-06-13 12:18
Is there any approximation, when we could have this fixed in official version?

**Comment by OriginalMHV** [comment] 2022-08-16 06:41
Any further details when this might get fixed? Still got the issue with Bitbucket server v7.21.2.

**Closed as completed** 2022-08-30 12:16 UTC
Labels: N-investigation, B-bug, A-git-sync

**Comment by filfreire** [comment] 2022-08-30 14:04
Hi folks, quick update, the PR that @nHuebner contributed is now merged, it should be picked up for the upcoming Beta release this Thursday 👍 

Stay tuned on https://github.com/Kong/insomnia/releases for release `2022.6.0-beta.4`
