### ISSUE TITLE
[Improvement] To add a feature to work with RAML, Swagger, Paw, Postman…

### ISSUE THREAD

**Issue by IlyaBelitser** [getinsomnia/insomnia#367] opened 2017-07-21 02:50 UTC
To add a feature to work (import/export) with RAML, Swagger, Paw, Postman…

**Comment by gschier** [comment] 2017-07-25 20:53
Closing as a duplicate of #281

**Closed by gschier** 2017-07-25 20:53 UTC

**Comment by JayAndCatchFire** [comment] 2017-10-18 21:16
https://github.com/getinsomnia/importers/issues/13
https://github.com/getinsomnia/importers/issues/14
