### ISSUE TITLE
Insomnia Designer installation fails

### ISSUE THREAD

**Issue by TheProgrammer21** [getinsomnia/insomnia#2079] opened 2020-04-29 17:48 UTC
**Describe the bug**
The installation of insomnia designer 2020.1.1 fails. The logs can be found here: https://pastebin.com/JM8b45R7

**To Reproduce**
1. Execute the exe file as administrator.

**Expected behavior**
The installation is successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/52009814/80628865-4d79ca00-8a52-11ea-9dee-73b5081337a6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1909 Build 18363.815
 - App Version 2020.1.1

**Comment by reynolek** [comment] 2020-04-29 18:26
Duplicate of #2073

Thanks for reporting! We are actively investigating the issue. I am going to close this in favor of the other one for easier tracking purposes.

**Closed as completed by reynolek** 2020-04-29 18:26 UTC
Labels: M-duplicate
