### ISSUE TITLE
[Bug] Unicode characters not displayed properly

### ISSUE THREAD

**Issue by TR3MIC** [getinsomnia/insomnia#1075] opened 2018-07-25 18:18 UTC
- Insomnia Version: 6.0.0
- Operating System: Windows 10 x64 v1709

## Details

In the response preview panel, Unicode characters are not displayed properly. For one character, it remove the one preceding it. For example, __arrivée__ become __arriée__. And if multiple Unicode character are written, it bugs and show some part of the Unicode code (example: __arrivéééée__ become __arrié\u00eé\u00e9e__).

The response is correctly received from the server (as shown by the Raw data panel). It only appear when the response is viewed in the Preview panel and the Source code panel.

The issues wasn't there in older version (my colleague still has the 5.16.6 version and doesn't have this problem).

**Comment by TR3MIC** [comment] 2018-07-25 18:19
Same as #1071

**Comment by gschier** [comment] 2018-07-25 18:20
Duplicate of #1071 and #1071

**Closed by gschier** 2018-07-25 18:20 UTC
