### ISSUE TITLE
No longer possible to sort Sub-Environments

### ISSUE THREAD

**Issue by rkonopka** [getinsomnia/insomnia#5639] opened 2023-01-09 21:01 UTC
### Expected Behavior

In previous versions of Insomnia, it was possible to drag sub-environments in the Manage Environments list to create a custom sort order. 

### Actual Behavior

In the latest version, this is no longer possible in 2022.7.1. That is, you cannot click a sub-environment name and drag it to a new location in the list. I am unable to find any way to change the order the sub-environments are displayed. This new behavior affects both Windows and Mac versions.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 and macOS Ventura

### Installation method

installer

**Comment by filfreire** [comment] 2023-01-11 09:04
Closing as duplicate of #5410

**Closed as completed by filfreire** 2023-01-11 09:04 UTC
Labels: B-bug, S-unverified
