### ISSUE TITLE
Publish Flathub Package

### ISSUE THREAD

**Issue by ldelossa** [getinsomnia/insomnia#2104] opened 2020-05-01 14:07 UTC
**Is your feature request related to a problem? Please.

While appimage is a viable installation option for non ubuntu distributions, flathub is becoming the defacto "enterprise application" hub for all platofrms.  

**Describe the solution you'd like**
Instead of providing app images which are clunky to work with, make efforts toward providing a flathub driven installation.

**Describe alternatives you've considered**
Appimage - installation is clunky, daemon must run to integrate appimage into gnome. Not many distros run this daemon.

**Comment by nijikokun** [comment] 2020-05-01 18:34
Hi @ldelossa! Thank you for raising this.

Did some digging and found out there was originally a PR to make Insomnia support flatpak but it seems it never got merged, wonder if that could be reopened: https://github.com/Kong/insomnia/issues/939

**Comment by ldelossa** [comment] 2020-05-01 21:13
Would be awesome. I know most of my colleagues use flatpak to install Drobox, Slack, Signal, etc... it's becoming a hot spot for desktop applications.

**Comment by ldelossa** [comment] 2020-05-01 21:15
it looks like github actions supply a flatpak builder: 

https://github.com/bilelmoussaoui/flatpak-github-actions

maybe it can be used almost in a drop in fashion?

**Comment by gschier** [comment] 2020-05-02 02:49
Thanks for the suggestion @ldelossa!

While I would love it if we could support all the various Linux distribution formats, it quickly becomes a maintenance headache. It seems like Flatpak is very similar to Snap, which we [already support](https://snapcraft.io/insomnia
) (and supported OOTB by `electron-builder`) so I'd be curious to understand the benefits that Flatpak offers.

_Note: we're working on getting a Snap up for the new Insomnia Designer shortly._

**Comment by ldelossa** [comment] 2020-05-02 13:44
I seems like youre catering to one linux community (ubuntu) where almost all others (fedora, arch, clear linux, manjaro, etc...) Utilize flatpak. Its not very likely other distros will use snap, but rather likely ubuntu users will use flatpak. 

I believe a flatpak install would actually make it so you DONT have to handle a deployment for each type of linux.

**Comment by gschier** [comment] 2020-05-02 17:04
Thanks for the info @ldelossa! To be honest, none of us are full-time Linux users (anymore) so we've really just been going with whatever `electron-builder` supports out of the box. It looks like Flatpak is actually very-highly requested over there too so that's a good sign https://github.com/electron-userland/electron-builder/issues/512

**Comment by aadityabhatia** [comment] 2020-05-02 20:05
Related #1812

**Comment by ghost** [comment] 2020-06-11 19:28
FYI you can treat the Flatpak build as you were using a closed source release.

https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.yaml#L45
https://github.com/flathub/com.dropbox.Client/blob/master/com.dropbox.Client.json#L92
https://github.com/flathub/shared-modules

I've been running insomnia in a flatpak for months without any issues, using this terrible code since I haven't bothered reading their docs

    {
      "name": "insomnia",
      "buildsystem": "simple",
      "build-commands": [
        "install -d /app/bin",
        "tar xvf insomnia*.tar.gz",
        "rm insomnia*.tar.gz",
        "cp -rf insomnia-*/* /app/bin",
        "rm -rf insomnia-*",
        "ls -la /app/bin",
        "chmod -R 0755 /app/bin"
      ],
      "sources": [
        {
          "type": "file",
          "url": "https://github.com/Kong/insomnia/releases/download/v9.9.9.9.9/insomnia-9.9.9.9.9.tar.gz",
          "sha256": "9999999999999999999999999999999999999999999999999999999999999999"
        }
      ]
    }

**Comment by blackva** [comment] 2020-07-21 05:44
@nijikokun Any updates? Using Flatpak is a much better user experience compared to Appimages. Would be amazing to have it as option.

**Comment by surendrajat** [comment] 2020-10-02 08:20
Any updates on this? I see many electron apps on flathub but insomnia is still missing. I guess it's easier than snapcraft(except that canonical guys approach for snap but flatpak is a community endeavor). Snap store being proprietary(**like** windows store, as you might be aware) is not being very well received by the open-source community and only a few outside Ubuntu use it while flatpak is vendor-neutral and completely open-source.

flathub/flathub#504 was closed after waiting for the upstream response. Could you please accept write access to the repo if the community adds it?

**Comment by ceisserer** [comment] 2020-11-17 07:04
too bad there is no progress in uploading insomnia to flathub - I am so used to installing stuff with flatpack, I don't want to go back to the days of downloading tarballs and/or manually adding distribution-specific repos to my package manager configuration.

**Comment by ldelossa** [comment] 2020-11-17 13:30
TBH i just moved to Postman which has a flathub deployment.

**Comment by doums** [comment] 2020-11-21 02:16
It really sucks that insomnia is still not present in flatpak after all this time.
Moving to Postman too..

**Comment by rcauquil-pycom** [comment] 2020-12-11 10:31
I'm looking for this also, it would be great
snap was my goto under ubuntu, but I'm under tumbleweed now and use flatpak

**Comment by KevinAtSesam** [comment] 2021-02-01 12:17
Count me in as interested.

> Thanks for the suggestion @ldelossa!
> 
> While I would love it if we could support all the various Linux distribution formats, it quickly becomes a maintenance headache. It seems like Flatpak is very similar to Snap, which we [already support](https://snapcraft.io/insomnia) (and supported OOTB by `electron-builder`) so I'd be curious to understand the benefits that Flatpak offers.
> 
> _Note: we're working on getting a Snap up for the new Insomnia Designer shortly._

As a Flathub volunteer and package maintainer, I wish to comment on that. Snapcraft is universal in a sense that it's technically possible to run almost everywhere, but in practice most distributions discourage it, or outright block it. The fundamental core of the problem is that Snap is a Canonical product, where Canonical is in total control. Flatpak is designed as a distributed network, where not a single party controls everybody. As a response, Snap is now essentially a Ubuntu-only format and Flatpak is the community darling.

As a company, you should care about that a lot. With Flathub, you have the technical certainty that nobody can force a 30% revenue split on you, while Snap is only as reliable as its parent company. If maintaining a Snap, a .deb and a flatpak is to much, then I would recommend using Flatpak only.

**Comment by WhyNotHugo** [comment] 2021-05-27 20:44
Please see the previous thread: https://github.com/Kong/insomnia/issues/1812#issuecomment-849766586

Discussion has continued there, and we're working on a community-maintained Flatpak package.

**Closed as completed** 2021-07-01 00:40 UTC
Labels: O-linux, needs-triage
