### ISSUE TITLE
[Bug] npm error when trying to install plugin

### ISSUE THREAD

**Issue by BlueberryKing** [getinsomnia/insomnia#1202] opened 2018-10-07 20:06 UTC
- Insomnia Version: 6.0.2
- Operating System: Windows 10

## Details

I'm trying to install a plugin, `insomnia-plugin-jwtdecode` to be specific, but I get the following error when trying to install via Preferences -> Plugins:

```
insomnia-plugin-jwtdecode npm error: Command failed: C:\Users\username\AppData\Local\insomnia\app-6.0.2\Insomnia.exe --no-deprecation C:\Users\username\AppData\Local\insomnia\app-6.0.2\resources\bin\yarn-standalone.js info insomnia-plugin-jwtdecode --json
```

I opened DevTools, but I don't see an error, I only see: `[plugins] Fetching module info from npm`

Please let me know if you want me to provide more information. Thank you.

**Comment by gschier** [comment] 2018-10-11 17:50
Hmm, I can't reproduce this on Mac. Maybe try running the command manually from the command line and see if you get more of an error message?

**Comment by gschier** [comment] 2018-10-11 19:45
Sorry, after `Command failed: ` it shows the command that it tried to run. Can you try running that manually?

```C:\Users\username\AppData\Local\insomnia\app-6.0.2\Insomnia.exe --no-deprecation C:\Users\username\AppData\Local\insomnia\app-6.0.2\resources\bin\yarn-standalone.js info insomnia-plugin-jwtdecode --json```

Insomnia does not use your system version of Node or NPM. It uses a bundled version of Yarn instead.

**Comment by BlueberryKing** [comment] 2018-10-11 20:13
Gotcha. I actually tried that, but it just launches Insomnia. The console shows this output:

```
[fix] Running database repairs
[db] Initialized DB at C:\Users\valen\AppData\Roaming\Insomnia\insomnia.$TYPE.db
[localstorage] Initialized at C:\Users\valen\AppData\Roaming\Insomnia\localStorage
[main] Loading file://C:\Users\valen\AppData\Local\insomnia\app-6.0.2\resources\app.asar/renderer.html
[updater] Using url https://updates.insomnia.rest/updates/win?v=6.0.2&channel=stable
[updater] Checking for updates url=https://updates.insomnia.rest/updates/win?v=6.0.2&channel=stable
[updater] Not Available
```

**Comment by aduvoisin13** [comment] 2018-10-23 21:11
I'm seeing this exact same problem, same output and results. 6.0.2 / Windows 10. Workaround was to go into the plugins folder and `npm install insomnia-plugin-default-headers`.

**Comment by gschier** [comment] 2018-10-25 00:53
@BlueberryKing Perhaps try running this instead (assuming you have NodeJS installed)

```
node --no-deprecation C:\Users\username\AppData\Local\insomnia\app-6.0.2\resources\bin\yarn-standalone.js info insomnia-plugin-jwtdecode --json
```

**Comment by goddard82** [comment] 2018-11-14 09:54
I'm still seeing the "no-deprecation" error when I try every set of steps above (windows 10, Insomnia 6.2). Is there anything else that might work?

**Comment by gschier** [comment] 2018-11-14 18:36
Can you paste the error here?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ghost99cze** [comment] 2018-11-15 06:42
I have the same problem in Insomnia 6.2 (Windows 10).
When I try to install any plugin in app. It just says:

> insomnia-plugin-jwtdecode npm error: Command failed: "C:\Users\Michal\AppData\Local\insomnia\app-6.2.0\Insomnia.exe" --no-deprecation C:\Users\Michal\AppData\Local\insomnia\app-6.2.0\resources\bin\yarn-standalone.js info insomnia-plugin-jwtdecode --json

When I try suggestion above:

> {"type":"inspect","data":{"name":"insomnia-plugin-jwtdecode","description":"JWT (JSON Web Token) decoder for Insomnia REST Client","dist-tags":{"latest":"1.0.2"},"versions":["1.0.0","1.0.1","1.0.2"],"maintainers":[{"name":"siebesysmans","email":"siebe.sysmans@gmail.com"}],"time":{"modified":"2018-11-03T10:42:56.049Z","created":"2017-11-04T15:12:29.654Z","1.0.0":"2017-11-04T15:12:29.654Z","1.0.1":"2017-11-04T15:22:21.285Z","1.0.2":"2018-11-03T10:42:53.589Z"},"author":{"name":"Siebe Sysmans","email":"siebe.sysmans@gmail.com"},"license":"MIT","readmeFilename":"README.md","homepage":"https://github.com/SiebeSysmans/insomnia-plugin-jwtdecode#readme","repository":{"type":"git","url":"git+https://github.com/SiebeSysmans/insomnia-plugin-jwtdecode.git"},"bugs":{"url":"https://github.com/SiebeSysmans/insomnia-plugin-jwtdecode/issues"},"version":"1.0.2","main":"./src/plugin.js","insomnia":{"name":"jwtdecode","description":"Decode a JWT (JSON Web Token) andreturn a claim"},"dependencies":{"base-64":"0.1.0"},"gitHead":"676e3aa345263bb5e9821a889082b92cbf93bc7c","dist":{"integrity":"sha512-QD6TUHiohv1Irg66RccxNv18kQ5NI/lLuu2sDnH9aGZlquPFCn9zdxGAdcfknsGa1bztE666OHQ7sfDTY8Tirw==","shasum":"d2aa2b0960070245584af3711c2b8d72b1209981","tarball":"https://registry.npmjs.org/insomnia-plugin-jwtdecode/-/insomnia-plugin-jwtdecode-1.0.2.tgz","fileCount":10,"unpackedSize":2171131,"npm-signature":"-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.4\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJb3XuuCRA9TVsSAnZWagAAlqsP/2ktvn646pc9+vC9buKb\nJ7kor5Kiahs5WWhCgK483TiqBW+t4ofafcld77fr5KqCwl5WrqwCJ/7uEQnR\n7MWcjBUq4tkWC/4UMq5rOnnfqQ1k1jr6y3CyRqxkiMAtd4wZB8z42JaF6RqL\npQKCNNFsAkwNthDuoLZL1M4R7WrlTe4cIpD+6dC7r0wNCGJXQDkE+wFmGTqp\ncU7DzsNG3gWjA+YTauq8QSWViMZzvKmddWgauOv/M/VbUVBbMF3lavQ4kxbY\ngYqIWUtDzPEtCocYPLM8JRz7lBEnuXabks9xfVDosqeLDYwvkZ+v1PT+YMiB\ntbJj367mPLUVOGdy8l74zzplD2yoWQJukb9EHjxib+pSKagpMDiNykDi2Zg9\nS01ikhuOAdJibcj8ORss5HJdhFdo03kjKfSGsKzcx/XgdQ3ZOIn5sE2pF3QA\ncj76EbiYnwWZ9+lovrmifhaPbmyBEfLe0uKnZrmvOXWNOgE1MgqtT9HvyFCD\nh8Oe7md6hGvSd+uOOfYLficrTTUu3NmkX4PWV8rDsJU6ysa4vzrIYoxt3M7w\nxT0NRteFYLVY5n0e9d88aPktMUuSj3RtbxolLgegzzjqcLcQsumNle2Uhbt+\nfTw0vg29OMcXZO9ronPA9biXtH/O6I26pFPU47RQ0qqW/WG4Q45Y76N50Int\nbxZW\r\n=6OaO\r\n-----END PGP SIGNATURE-----\r\n"},"directories":{}}}

In both attempts plugin is not installed.

The only way right now is to go to the plugins folder and install it by hand (npm install insomnia-plugin-jwtdecode)

**Comment by gigouni** [comment] 2018-11-27 10:47
Hi,

I succeed to install `insomnia-plugin-jwtencode` plugin with the following commands

```shell
C:\Users\ngigou\AppData\Roaming\Insomnia\plugins
λ yarn add insomnia-plugin-jwtdecode
yarn add v1.6.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ insomnia-plugin-jwtdecode@1.0.2
info All dependencies
├─ base-64@0.1.0
└─ insomnia-plugin-jwtdecode@1.0.2
Done in 0.38s.

C:\Users\ngigou\AppData\Roaming\Insomnia\plugins
λ ll
total 6
drwxr-xr-x 1 ngigou 1049089    0 Nov 27 11:35 node_modules
-rw-r--r-- 1 ngigou 1049089   75 Nov 27 11:35 package.json
-rw-r--r-- 1 ngigou 1049089 2779 Nov 27 11:35 yarn-error.log
-rw-r--r-- 1 ngigou 1049089  479 Nov 27 11:35 yarn.lock
```

Was such a hard time to found out how to do it, even with docs when you're a new Insomnia user. Hope it could help some of you until it's "fixed". 👍 

@gschier @ghost99cze

**Comment by ctcampbell** [comment] 2018-12-04 17:18
Same issue on multiple Windows machines

**Comment by gschier** [comment] 2018-12-12 00:37
Okay so it looks like Node's `execFile` command is returning an `err` object but ALSO returning all the correct data in `stdout` (`stderr`) is empty. I have no idea why that would be. Any Windows folks have any idea?

![image](https://user-images.githubusercontent.com/587576/49839187-0404de00-fd7c-11e8-9db2-bbd49a3ee3ce.png)

Code that runs it is here: 
https://github.com/getinsomnia/insomnia/blob/develop/packages/insomnia-app/app/plugins/install.js#L62

**Comment by senoctar** [comment] 2019-01-17 00:07
To run the command from Windows prompt we need to set the same environment variables, otherwise the command will just start Insomnia again.
I did that and it runs successfully (the exit code / error level is 0), so there's no issue with the command itself.
![image](https://user-images.githubusercontent.com/970918/51285446-8a55b500-19f7-11e9-86e0-55eb233c3dc8.png)

Node execFile as it returns exit code 3221226356 in the error object.
![image](https://user-images.githubusercontent.com/970918/51286177-89725280-19fa-11e9-8c38-a1c01b6bbf66.png)
The same can be seen in your screenshot gschier. This is corroborated by Windows audit log:
![image](https://user-images.githubusercontent.com/970918/51286220-b0308900-19fa-11e9-8474-faa585e2995c.png)
0xC0000374 is hex for 3221226356
So the process actually fails when running from within node. That particular error code is common in heap corruption which makes this issue quite odd. Might be a bug in node or electron.

**Comment by Wazbat** [comment] 2019-02-26 10:13
I'm not able to offer much help, but I'm getting the same issue when trying to install insomnia-plugin-faker

**Comment by 4n70w4** [comment] 2019-04-02 09:25
Any news? I'd like to start using plugins!

Maybe there is some other way to install plugins in Windows?

**Comment by Wazbat** [comment] 2019-04-02 10:45
It is possible to install some things manually as a workaround, but the main install remains broken.

For example, to install insomnia-plugin-faker I had to:
Create a new npm project
Install insomnia-plugin-faker via npm install insomnia-plugin-faker, which included dependencies
Create a node_modules folder inside the insomnia-plugin-faker folder, and move every dependency that was downloaded into that folder
Move the final insomnia-plugin-faker folder, which contains the plugin as well as the dependencies inside, into the insomnia plugins folder.
Final structure is as follows:
![image](https://user-images.githubusercontent.com/6253896/55396832-1e3e1400-5545-11e9-86ba-7ec523575d62.png)

It should then show in your plugins list
![image](https://user-images.githubusercontent.com/6253896/55396866-2dbd5d00-5545-11e9-9cbc-c0b16e19d38c.png)

I'm still a novice at this, so the dependencies might not need to be in a folder titled node_modules, but it works

**Comment by senoctar** [comment] 2019-04-03 01:01
The root cause is not likely to be solved, it seems to be a reoccurring issue randomly affecting projects:
https://github.com/sass/node-sass/issues/2168
https://github.com/symfony/webpack-encore/issues/281

I created a PR for a fix that tries to go around the problem: https://github.com/getinsomnia/insomnia/pull/1425

**Comment by gschier** [comment] 2019-04-26 22:47
Can someone verify whether or not PR #1425 fixed this issue?

**Comment by ghost99cze** [comment] 2019-04-29 08:57
It seems that it is working in v6.4.1. Tested on Windows 10.

**Comment by ghost99cze** [comment] 2019-04-29 09:15
At least it is working for `insomnia-plugin-jwtdecode` but it is not working for example for `insomnia-plugin-plus4u-oidc`. But it looks like there is a problem in this plugin. (But when i install it manually - everything works fine)

**Comment by gschier** [comment] 2019-04-30 01:39
What error do you get with the oidc plugin? Insomnia was able to install it correctly on Mac

**Comment by senoctar** [comment] 2019-05-01 15:28
The issue with `insomnia-plugin-plus4u-oidc` does not seem related. When running the command manually yarn stops at `[3/4] Linking dependencies...` with no message (`--verbose` doesn't help either).
Using `yarn-1.15.2.js` instead of `yarn-standalone.js` bundled with insomnia fixes the issue.

You can even make insomnia work (until a version with a newer yarn is available). Download [yarn-1.15.2.js](https://github.com/yarnpkg/yarn/releases/download/v1.15.2/yarn-1.15.2.js) rename it to `yarn-standalone.js` and overwrite / copy to `c:\\Users\\<your-user-name>\\AppData\\Local\insomnia\app-<insomnia-version>\resources\bin\`. Then just install using the insomnia UI.

**Comment by ghost99cze** [comment] 2019-05-09 11:59
I also think it is not related. For now i'm using npm install in the plugin folder which is working fine as well.
Maybe yarn-standalone has some problems with dependencies or something like that.

Either way. Original problem seems fixed.

**Comment by gschier** [comment] 2019-05-09 17:42
I'll get an update to `yarn-standalone.js` into the next release. Thanks for testing that out @senoctar! ❤️

**Comment by gschier** [comment] 2019-05-09 18:27
Going to close this one for now actually and can reopen it if the problem still occurs after the next release.

**Closed by gschier** 2019-05-09 18:27 UTC
Labels: OS: Windows

**Comment by Wazbat** [comment] 2019-11-13 12:54
Just coming back to say that I'm still getting what I think is a similar error on ubuntu when trying to install plugins. My old fix still worked for faker

![image](https://user-images.githubusercontent.com/6253896/68765439-12f3b080-061d-11ea-863d-8497531712c0.png)
