### ISSUE TITLE
[Bug] Variable uncovering returns "undefined" for nested variables

### ISSUE THREAD

**Issue by bbbco** [getinsomnia/insomnia#1288] opened 2018-11-30 19:52 UTC
- Insomnia Version: 6.2.3
- Operating System: Linux Mint

## Details

https://github.com/getinsomnia/insomnia/pull/1274 introduces variable uncovering (helpful), but it seems that nested variable references returns `{undefined}:<variable>`

For example use the following environment:

````
{
  "foo": {
    "bar": "foobar"
  },
  "fu": {
    "baz": "{{ foo.bar  }}"
  },
  "foobar": "foobar2",
  "fubaz": "{{foobar}}"
}
````
- Hover over the `fu.baz` value ( `{{ foo.bar }}` ), and notice it shows `{undefined}:foobar`
- Hover over the `fubaz` value ( `{{ foobar }}` ), and notice it shows `{root}:foobar2`

Expectations:

- Hovering over the value shows `{{root}}:foobar` like a non-nested value does.

Other thoughts:
 - Should the `root` reference instead say "Base Environment" to correspond to the Base Environment?

**Comment by gschier** [comment] 2018-12-05 03:52
I can confirm this is a bug. Going to ping @dhruv944, as they were the one who worked on this.

**Comment by dhruv944** [comment] 2018-12-05 15:09
Thanks for reporting this. I'll pick it up ASAP.

**Comment by bbbco** [comment] 2019-04-29 16:39
Any updates?

**Comment by gschier** [comment] 2019-04-30 02:31
Looks like the lookup logic does not account for nested properties at all:

https://github.com/getinsomnia/insomnia/blob/0d333b008bba19422618c8e85808def1678b5d9b/packages/insomnia-app/app/common/render.js#L216-L240

**Comment by Gabrz** [comment] 2019-08-11 17:43
I think a quick fix for this bug is a change in
 https://github.com/getinsomnia/insomnia/blob/0d333b008bba19422618c8e85808def1678b5d9b/packages/insomnia-app/app/ui/components/codemirror/extensions/nunjucks-tags.js#L279

to
`// Check if property is nested, if so strip to topmost Parent property`
      `const propSource = cleanedStr.includes('.') ? cleanedStr.substring(0, cleanedStr.indexOf('.')) : cleanedStr;`
      `title = '{' + con.keyContext[propSource] + '}: ' + title;`

I've created a Pull Request #1637, but it failed during the CIT AppVeyor, not sure why tho. I have no errors in my insomnia development environment and the change seems to be working.

**Closed** 2019-08-16 20:54 UTC
Labels: Accepted 👌
