### ISSUE TITLE
App Icon too big

### ISSUE THREAD

**Issue by PawelNiedzwiecki** [getinsomnia/insomnia#5936] opened 2023-05-02 11:50 UTC
### Expected Behavior

App icon looks too big compared to other MacOS icons.
MacOS Ventura 13.3.1 (22E261)
![image](https://user-images.githubusercontent.com/66324097/235657251-6d007d92-966a-4cee-a12f-653507f3a6d0.png)

### Actual Behavior

App Icon should be the same size as general MacOS icons

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.3.1 (22E261)

### Installation method

homebrew

**Comment by filfreire** [comment] 2023-05-02 12:21
Duplicate of #5922

**Closed as completed by filfreire** 2023-05-02 12:21 UTC
Labels: B-bug, S-unverified
