### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by thirstyfish** [getinsomnia/insomnia#3011] opened 2021-01-19 02:22 UTC
We're experiencing performance issues with Insomnia Core 2020.5.2 on MacOs Mojave (previous Insomnia versions exhibited the same issues) with the Quick Switch modal and environment variables.

We have around 200 GraphQL requests organised into around 80 folders (3 to 4 levels deep).

The Quick Switch modal frequently (but not every time) freezes the application (app needs to be force closed) when trying to search for and switch to another request.

We have around 35 environment variables that are resolved from response body attributes that we use in GraphQL queries and mutations. 
Even though the trigger behaviour is set to "When expired - resend when existing response has expired" with a max age of 60 seconds, Insomnia seems to be resolving every variable for every request on Send, even if the given request doesn't use the given environment variable. 
This makes all of our GraphQL requests very very slow when issued from Insomnia.

**Environment:**
 - OS: macOS 10.14.6
 - Installation Method: dmg from website
 - App Version: Insomnia Core 2020.5.2

**Comment by AndreMaz** [comment] 2021-11-30 05:56
Hi @dimitropoulos What is the status on this? Can this issue be solved in near future?

**Comment by andrasore** [comment] 2021-12-03 11:24
Hi there,
Any update on this?

**Comment by AndreMaz** [comment] 2021-12-03 13:42
I'm glad to see that I'm not the only one who wants this to be solved. @develohpanda @DMarby sorry to tag you but can you take a look at this?

**Comment by oliverjanik** [comment] 2022-01-19 02:02
I experience similar issue on Win 11 when I flick between windows. When I get back to insomnia 50% of the time I get a freeze that lasts 5 seconds or so.

**Comment by dimitropoulos** [comment] 2022-01-31 14:05
apologies for the radio silence.  this is something we care about, for sure!  we have a few things in the queue ahead of it that are fairly critical, for example upgrading electron and node (which then means big architecture changes such has potentially removing node-libcurl, etc.).

I did, though, just now add a triage ticket to our team's board linking to this issue.  I realize that this may sound disingenuous considering this (quite serious!) issue went a full year without being commented on from the team, but _this feedback does not fall upon deaf ears_ -> just _busy_ ears.

The information you provided here is very very helpful, but the absolute best thing would be if you can provide an export of a workspace.  I realize it may not be possible to do if there's private information and therefore would require some time to redact any private info from the JSON export: but just wanted to mention it.  We'll be trying to recreate something like this, all the same, with the information you provided.

**Comment by Vyoam** [comment] 2022-03-28 08:48
I have a reproducible observation specifically regarding delay due to chained requests in base environments. I'm not sure if it can be called a bug or not, but definitely needs to be documented. It is somewhat related to this thread (but I'm not sure how much).

Basically, as a user, I had expected the chained requests (even if defined in base env.) to get triggered only if the request I'm hitting actually needs it. But, the chained requests in base env. run irrespective of whether they are relevant or not.
I don't think there's any documentation which highlights this behavior and the timeline tab doesn't give any clue either. So, a user might assume a deeper performance issue with Insomnia.

Obviously, as a user one can try to be meticulous and segregate chained flows to different workspaces. But improvement wise, these are some of my thoughts (all might not be needed)...
- Call out this current behavior in some documentation. Here: https://docs.insomnia.rest/insomnia/chaining-requests ... Or as a warning in the env. var. dialog.
- Include the env. var. flows in timeline tab
- Ideally, just NOT trigger chained requests unless it is actually relevant for the selected request

For reproducing, use the attached collection (within zip). The base env. has a 'test_delay' variable. And it depends on one of the requests which has an in-built 15sec delay, and is configured as always-resend (Even with that config, intuitively, an average user still wouldn't expect it to trigger for irrelevant cases IMHO). As long as the base env. var. is present, you will have the unnecessary delay when using 'DummyAPI' call. And the delay goes away once you remove the env. var. And as you'd see, that env. var. isn't at all needed by 'DummyAPI'.
[Insomnia_2022-03-28.zip](https://github.com/Kong/insomnia/files/8361128/Insomnia_2022-03-28.zip)

**Comment by LunaticoCR** [comment] 2023-03-10 15:38
I'm also plagued by performance issues. I think it's definitely related to big collections. I currently have 844 requests, with around 60 variables in the base environment and 19 sub environments with between 2 and 10 variables each.
Every time I go into one of the requests it takes several seconds for the request to render variables and tags, and recently if I navigate the UI too quickly the main window goes blank and I would have to restart the app.
I really hope this gets looked at soon because I'm at a point where I would soon have to make the hard decision to move to another app, which would be a huge pain, and I really like Insomnia. @dimitropoulos

**Comment by dimitropoulos** [comment] 2023-03-15 16:59
hey @LunaticoCR, sorry about your trouble with this.  I no longer work for Kong, but the team that does is filled with some great developers and I'm sure they'll take a look at this (performance is one of those things that never really goes away as a concern, you know?).

**Comment by cwangsmv** [comment] 2024-09-05 02:09
@thirstyfish since you have 35 environment variables that are resolved from response body attributes that use in GraphQL queries and mutations, can you try to use [After-Response Script](https://docs.insomnia.rest/insomnia/after-response-script) to save environment variables from the response which will greatly reduce the request render time.

**Comment by cwangsmv** [comment] 2024-09-05 03:30
@LunaticoCR we've done some performance improve recently, could you please try the latest version? Besides, if you are also saving a lot of environment variable from response, I suggest to use the  [After-Response Script](https://docs.insomnia.rest/insomnia/after-response-script) to save response body as environment variable which will have great performance improve.

**Comment by LunaticoCR** [comment] 2024-09-05 08:16
@cwangsmv I'm currently on version 9.3.3 and I can confirm the performance issues have greatly improved in recent builds. When I started using the app years ago the after-response scripting wasn't available, but I'll absolutely be using it from now on! Thank you!

**Comment by cwangsmv** [comment] 2024-09-05 08:33
> @cwangsmv I'm currently on version 9.3.3 and I can confirm the performance issues have greatly improved in recent builds. When I started using the app years ago the after-response scripting wasn't available, but I'll absolutely be using it from now on! Thank you!

Thanks for the feedback. Close the issue since it is improved now.

**Closed as completed by cwangsmv** 2024-09-05 08:33 UTC
Labels: B-performance, needs-triage
