### ISSUE TITLE
Unnecessary connections

### ISSUE THREAD

**Issue by SynapseScribe** [getinsomnia/insomnia#3246] opened 2021-03-26 20:02 UTC
Unnecessary connections at startup, even if updates and data sharing is disabled:
redirector.gvt1.com
api.insomnia.rest

**Comment by dimitropoulos** [comment] 2021-03-29 14:44
Thanks for letting us know!  Could you please provide some steps to reproduce/confirm this.  For example, did you use wireshark to determine this?  Were you logged in?

**Comment by SynapseScribe** [comment] 2021-03-29 14:46
I wasn't logged in. it was fresh install. I saw them in firewall

**Comment by reynolek** [comment] 2021-03-29 17:16
Hi @fusionneur -- The calls to `api.insomnia.rest` are used to display notifications in the application, such as when a new version is available.

As for the `gvt1.com` callout, that is a google controlled domain, which is used by Chromium iirc. Electron is powered by Chromium.

**Comment by SynapseScribe** [comment] 2021-03-29 18:23
I understand but the app should be clean of connections if updates and analytics are turned off.

**Comment by SynapseScribe** [comment] 2021-05-30 08:15
keep alive

**Comment by wdawson** [comment] 2021-07-01 19:15
Hi @fusionneur , sorry for the confusion. We are moving feature requests to GitHub discussions to offer a better experience for the community for those ideas. However, it looks like you've reported a bug so I'm moving this back to Issues and reopening.

If possible, can you show us which requests you're seeing? It might save us time when we try to reproduce.

**Comment by SynapseScribe** [comment] 2021-07-01 21:03
see first comment with the 2 endpoints

**Comment by wdawson** [comment] 2021-07-01 22:17
Ok thanks. As @reynolek mentioned, those two calls are made at startup regardless. If you choose to opt out of updates and analytics, the app should not send requests like that in the future. I'm going to close this out as expected.

**Closed as completed by wdawson** 2021-07-01 22:17 UTC
Labels: needs-triage, waiting-for-team

**Comment by SynapseScribe** [comment] 2021-07-01 23:42
i just downloaded v2021.4.0 portable and with 'Do not notify of new releases' it still tries to connect to api.insomnia.rest.

The google's domain redirector.gvt1.com however is not contacted anymore with analytics turned off.

**Comment by wdawson** [comment] 2021-07-02 00:59
That's expected behavior consistent with our ToS for notification purposes.
