### ISSUE TITLE
Color picker doesn't show when changing environment color

### ISSUE THREAD

**Issue by tauinger-de** [getinsomnia/insomnia#2741] opened 2020-10-19 08:42 UTC
**Describe the bug**
For a sub-env for which I want to change the color the color picker just briefly flashes and disappears again.

**To Reproduce**
1. Go to Manage Evnrionments
2. Duplicate existing environment with a color
3. Click "Color" to change color
4. See color picker disappearing instantly

**Expected behavior**
Picker should remain visible

**Desktop (please complete the following information):**
Version: Insomnia Core 2020.4.1
Release date: 9/23/2020
OS: Linux x64 5.4.0-51-generic
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libssh2/1.9.0 nghttp2/1.41.0

**Additional context**
Removing the sub-env color makes the picker show. Setting a color and then trying to change it produces bug again

**Comment by jgiovaresco** [comment] 2020-10-19 09:18
Duplicate of #2647

A [fix](https://github.com/Kong/insomnia/pull/2711) is waiting for a review it should be fixed soon ;)

**Comment by tauinger-de** [comment] 2020-10-19 09:21
Oh, yeah, ok. I did a search before posting but got misled by "MacOS" part ;)

**Comment by nijikokun** [comment] 2020-10-19 19:26
Closing since it's a duplicate and there is a fix in progress 👍 

Even though it's a duplicate, better late than never!

**Closed as completed by nijikokun** 2020-10-19 19:26 UTC
Labels: M-duplicate
