### ISSUE TITLE
HTTP request result is not showing with "Filter responses by environment" option

### ISSUE THREAD

**Issue by avdotius** [getinsomnia/insomnia#5678] opened 2023-01-16 08:35 UTC
### Expected Behavior

Response is shown in the Preview and Timeline area

### Actual Behavior

Response area is empty

### Reproduction Steps

1. Turn on "Filter responses by environment" option
2. Select an http post request
3. Clear History
4. Press "Send"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Problem apperead after update to v2022.7.2

Nothing is shown in the history after I press Send with "Filter responses by environment" option = true
![screenshot](https://user-images.githubusercontent.com/1001060/212632887-03eb48d6-28f3-4e42-9fe6-e6e1758b9a0c.png)

If I set "Filter responses by environment" option in preferences to false then everything seems working.

### Insomnia Version

2022.7.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2 build 19045.2364

### Installation method

Downloaded from insomnia.rest/download some time ago and then automatically updated to 2022.7.2

### Last Known Working Insomnia version

prvious version worked fine

**Comment by filfreire** [comment] 2023-01-16 11:27
Hi @Alterant-zz thanks for reporting this, this is a duplicate of #5664 - fix for it will go out today

**Closed as completed by filfreire** 2023-01-16 11:27 UTC
Labels: B-bug, S-unverified
