### ISSUE TITLE
Render Failure e.include is not function

### ISSUE THREAD

**Issue by dexterns88** [getinsomnia/insomnia#6867] opened 2023-11-23 15:00 UTC
### Expected Behavior

load query editor

### Actual Behavior

error on screen for query editor
<img width="1066" alt="Screenshot 2023-11-23 at 15 58 32" src="https://github.com/Kong/insomnia/assets/1290174/a26e92f5-30ea-49a6-9f90-195d76e4c451">

### Reproduction Steps

open project

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

TypeError: e.includes is not a function
    at KVe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:470:868)
    at _l (file:///Applications/Insomnia.app/Contents/Resources/app.asar/debug-672b1df6.js:53:34237)
    at FS (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:42:19553)
    at aF (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:44101)
    at tF (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:39819)
    at qpe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:39745)
    at Fd (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:39596)
    at Px (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:35959)
    at QO (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:34906)
    at N (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:29:1615)
    at Immediate.me [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:29:1987)
    at process.processImmediate (node:internal/timers:476:21)

### Insomnia Version

8.4.4

### What operating system are you using?

macOS

### Operating System Version

13.2.1 (22D68)

### Installation method

Update old working version

**Comment by filfreire** [comment] 2023-11-23 16:15
Hey folks, we will launch a new release with a fix for this today, 8.4.5.

Closing this as a duplicate of #6857

**Closed as not planned by filfreire** 2023-11-23 16:15 UTC
Labels: B-bug, S-unverified

**Comment by filfreire** [comment] 2023-11-23 17:22
Update [here](https://github.com/Kong/insomnia/issues/6857#issuecomment-1824752852)
