### ISSUE TITLE
"Send" button unresponsive in grpc request

### ISSUE THREAD

**Issue by andrewwylde** [getinsomnia/insomnia#5095] opened 2022-08-18 18:14 UTC
### Expected Behavior

When sending a grpc request with a body, I expect that the send button (and UI) will give some sort of feedback as to whether the request is sent, failed, or succeeded

### Actual Behavior

Please see [video](https://www.loom.com/share/c2459d2f3b374683b707cb393891d52b) for demonstration, but essentially the button depresses but nothing happens in the UI as far as I can tell.

### Reproduction Steps

1. I added several directories to account for the relative import problem seen above (please see below image)
![image](https://user-images.githubusercontent.com/2126677/185464287-d98a3c17-1e84-418f-94c4-8e1ff410ae55.png)
2. I selected a local server
3. I selected a grpc method
4. I enter a payload
5. I click send
6. Nothing happens

Please see video, it may help?

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I took a look at [3316](https://github.com/Kong/insomnia/issues/3316) to make sure this wasn't a duplicate.

```
Version: Insomnia 2022.5.1
Build date: 8/17/2022
OS: Darwin x64 21.6.0
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64
```

### Insomnia Version

2022.5.1

### What operating system are you using?

macOS

### Operating System Version

12.5 (Monterey)

### Installation method

insomnia.rest

**Comment by filfreire** [comment] 2022-08-19 13:23
Hi @codelemur, thanks for reporting this! And thank you for the video showing the issue!

We couldn't reproduce this with a simpler example. Can you by any chance share with us a similar complex environment/project structure that we can use locally as example where we may reproduce this?

Or maybe sync this into a Insomnia collection that you could share with us (e.g using [Sync](https://docs.insomnia.rest/insomnia/version-control-sync#sync) or [Git Sync](https://docs.insomnia.rest/insomnia/git-sync).

**Comment by andrewwylde** [comment] 2022-08-19 20:15
OK, shared via Sync!

**Comment by wongstein** [comment] 2022-08-30 13:30
With the synced setup, I am able to reproduce the send button not working but just on the /RGConfigAPI/... endpoints and not on /HealthCheck.  There's nothing immediately obvious in the logs as to what could cause this, nor am I seeing anything in the setup.

**Comment by filfreire** [comment] 2022-09-12 13:08
@codelemur we could reproduce this, and it seems it touches two other similar problems:

- https://github.com/Kong/insomnia/issues/4038
- https://github.com/Kong/insomnia/issues/5093

We have problems dealing with folder structures in gRPC requests, which in this cases causes us to have an error pressing send button like:

```
14:03:05.206 › Error: ENOENT: no such file or directory, open '/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong/irma/rgconfig/v1/validate/validate.proto'
```

```
Warning: validate/validate.proto not found in any of the include paths /var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto,/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong,/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong/irma,/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong/irma/entities,/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong/irma/entities/v1,/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong/irma/health,/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong/irma/health/v1,/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong/irma/notifications,/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong/irma/notifications/v1,/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong/irma/rgconfig,/var/folders/q1/bfpq4bc51vq9fwc7h75l8kb80000gq/T/insomnia-grpc/pd_b80b11d5a38840d8b126965987ae5cb9.1662987766182/proto/kong/irma/rgconfig/v1
```

**Comment by filfreire** [comment] 2022-09-12 13:10
Closing as duplicate of #4038

**Closed as not planned by filfreire** 2022-09-12 13:10 UTC
Labels: B-bug, S-unverified
