### ISSUE TITLE
Collapse/Expand folder took very long time to done.

### ISSUE THREAD

**Issue by adithyaharun** [getinsomnia/insomnia#6296] opened 2023-08-16 04:33 UTC
### Expected Behavior

Collapsing/expanding any folders done in a blink of eye. Like the earlier versions.

### Actual Behavior

It took a very long time to collapse/expand any folders, or even not working at all. So I need to re-click on the folder.

### Reproduction Steps

1. Create collection or use existing collections
2. Create New Folder
3. Create New Request inside the recently created folder
4. Click on the folder to collapse/expand it.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 (Build 22631.2191)

### Installation method

Download from insomnia.rest, auto update since first install.

### Last Known Working Insomnia version

Didn't check, but before 2023.5.2 works well.

**Comment by jackkav** [comment] 2023-08-16 13:45
Duplicate of #6297

**Closed as completed by jackkav** 2023-08-16 13:45 UTC
Labels: B-bug, S-unverified
