### ISSUE TITLE
GraphQL field autocompletion context menu doesn't show up on Ctrl+Space keyboard shortcut

### ISSUE THREAD

**Issue by prcdpr** [getinsomnia/insomnia#5796] opened 2023-02-22 16:47 UTC
### Expected Behavior

In GraphQL query input, I usually use Ctrl+Space to show available fields.

![image](https://user-images.githubusercontent.com/43776797/220696533-3745a2e9-770b-4b08-bc36-859129b5b0dd.png)

This works perfectly in Insomnia 2022.6.0 but on latest 2022.7.5 it most of the times doesn't work at all.
Currently I rolled back to older version because it's very difficult to work on GraphQL without autocompletion.

### Actual Behavior

Context menu with available fields selection doesn't show when Ctrl+Space is pressed.

### Reproduction Steps

1. Create GraphQL query.
2. Start entering query
3. Use Ctrl+Space shortcut to open autocompletion for fields
4. It doesn't show up

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### Installation method

.EXE

### Last Known Working Insomnia version

2022.6.0

**Comment by itsfabijano** [comment] 2023-03-20 12:31
Seems to be a duplicate of [!5692](https://github.com/Kong/insomnia/issues/5692)

**Comment by filfreire** [comment] 2023-07-14 10:23
closing as duplicate of #5692

**Closed as completed by filfreire** 2023-07-14 10:23 UTC
Labels: E-good-first-issue, B-bug, S-unverified
