### ISSUE TITLE
no support for collection running like post man

### ISSUE THREAD

**Issue by parasuramln** [getinsomnia/insomnia#1493] opened 2019-05-10 05:37 UTC
- Insomnia Version: ___
- Operating System: ___

**Comment by gschier** [comment] 2019-05-10 14:00
Duplicate of #774

**Closed by gschier** 2019-05-10 14:00 UTC
Labels: Duplicate

**Comment by Krazybug** [comment] 2019-07-06 15:18
Hello,

Now you've closed this issue and the other in reference and you only proposed a plugin as a hack.

I think the request is :
"Do you plan to integrate this as a core feature ?"

This req is probably the last one that curbs a larger adoption of Insomnia against its main concurrent.

See: 
https://itnext.io/postman-vs-insomnia-comparing-the-api-testing-tools-4f12099275c1
or 
https://youtu.be/ErDCN_oU9a8


And you have proved with your plugin that it will be easy to add it.

Please, please re-open this issue  :)
