### ISSUE TITLE
Project folders (and requests within) are all out of sort. Cannot re-order the folders (or requests) using drag/drop method. Additionally, I am noticing the filter option no longer works. 

### ISSUE THREAD

**Issue by rpalmer1768** [getinsomnia/insomnia#6335] opened 2023-08-18 17:43 UTC
### Expected Behavior

1) I should be able to drag and drop folders and the requests within them to whatever location I choose. 

2) Using the filter to search for requests should return searched results...

### Actual Behavior

1) Folders and requests within them are unable to be moved. Dragging and dropping looks like it will work, but does not.  

2) Typing a value into the Filter search no longer works. 

### Reproduction Steps

1. Open Insomnia
2. Observe that all folders and the requests within them are not ordered as desired. 
3. Mouse over a folder, click to select then drag it to a desired location and drop. 
4. Result is the folder does not move. 
5. Also, type value into Filter Search. 
6. Observe that search is not working as expected.
7. Bang head against desk in frustration...

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I have more than 80 project folders with over 1K total requests. The preset sort that I had them in somehow changed by itself and I cannot rearrange / reorder them. It's now very challenging to find anything. 

### Insomnia Version

2023.5.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 22H2 (OS Build 19045.3208)

### Installation method

Download

### Last Known Working Insomnia version

2023.5.2

**Comment by ROG3R-DEV** [comment] 2023-08-19 03:11
I can confirm that this issue is occurring.

**Comment by joeydash** [comment] 2023-08-19 09:33
[Insomnia 2023.4.0](https://github.com/Kong/insomnia/releases/tag/core%402023.4.0)

Install this and turn off auto-update from settings/preference menu

**Comment by rpalmer1768** [comment] 2023-08-19 13:21
@ROG3R-DEV, @joeydash - Okay, so this just kind of blew my mind, but after spending literally half my day yesterday trying to fix this issue with no luck (hence this GitHub ticket), I literally just fixed it in a matter of seconds. All I did was mess around with the Zoom settings. 

View>>> Zoom In / Zoom Out. I also used the "Specific Zoom Level" option and set it to like 250% and then switched it back to 100%. After doing that I noticed all my folders were again sorted alphabetically. I tested reordering them by dragging and dropping and that works now. Also, the filter search option is working again. So weird...

**Comment by masukomi** [comment] 2023-08-19 16:06
can confirm bug
- filtering highlights matching text in names but doesn't filter
- can't drag and drop to reorder things
- sorting doesn't work
- mucking with zoom as @rpalmer1768  did, did not fix it. 

macOS: 13.4.1 (c)

Version: Insomnia 2023.5.5
Build date: 8/18/2023
OS: Darwin arm64 22.5.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64

**Comment by filfreire** [comment] 2023-08-21 06:58
duplicate of https://github.com/Kong/insomnia/issues/6288 and https://github.com/Kong/insomnia/issues/6284

**Closed as completed by filfreire** 2023-08-21 06:58 UTC
Labels: B-bug, S-unverified
