### ISSUE TITLE
Unclickable "Base Environment" in "Manage Environments" Dialog

### ISSUE THREAD

**Issue by nsankaranarayanan** [getinsomnia/insomnia#267] opened 2017-05-29 20:52 UTC
## Overview
- `Insomnia Version:` v5.1.0
- `Operating System:`  Windows 10 Professional
- `Summary: ` When I deleted the entire "Base Environment", I can no longer select the "Base Environment" any more.

## How To Reproduce
I am not sure whether this is a reproduceable bug. You might have to try. The below is what happened to me.
I clicked on the "Activate Environment" and selected the "Manage Environments" then I selected the "Base Environment" and entered some JSON. At some point in time I deleted the entire JSON (including the curly brackets) and clicked done. At that point onwards I could not select the "Base Environment" node.

Thanks

**Comment by gschier** [comment] 2017-05-29 20:55
This is a duplicate of #249. The _fix_ has been merged into the `develop` branch, but has yet to be included in an official release. I will make sure it gets deployed in the next one (hopefully today).

**Closed by gschier** 2017-05-29 20:55 UTC
