### ISSUE TITLE
GRPC: "Select method" is disabled

### ISSUE THREAD

**Issue by Haarolean** [getinsomnia/insomnia#7440] opened 2024-05-22 12:13 UTC
### Expected Behavior

"Select method" dropdown for GRPC requests is enabled and represents a list of available methods

### Actual Behavior

"Select method" dropdown for GRPC requests is disabled despite importing proto files.

### Reproduction Steps

1. Install
2. Open scratch pad
3. Create a grpc request
4. Import proto files
5. ???
6. profit

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 9.2.0

### What operating system are you using?

macOS

### Operating System Version

12.7.2

### Installation method

download from insomnia.rest

**Comment by ihexxa** [comment] 2024-06-11 07:33
Hello @Haarolean , is it possible to share a proto file to reproduce the issue? Currently we are not able to reproduce it on our side, thanks for the feedback.

**Comment by subnetmarco** [comment] 2024-10-21 11:35
We can reproduce it, @CurryYangxx is on it.

**Comment by JalinWang** [comment] 2024-10-25 06:17
> We can reproduce it, @CurryYangxx is on it.

@CurryYangxx hello~ Is there any update? New to Insomnia and stuck here :(

After "Add Directory" and confirm, the 'Save' button isn't responsible, as well as the disabled "Selected Method" dropdown after closing the modal.

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/fb1fc6b8-d30c-4d4f-b2ba-0ccf32676be9">


Update:

from log file:
> [2024-10-25 14:15:26.249] [error] (node:91461) Warning: proto/centaur.proto not found in any of the include paths /var/folders/d1/r1cqgqfd4c9048t7n56nptg80000gp/T/insomnia-grpc/pd_c00d69e9510d440a8f86fd660384797a.1729835936740/proto
[2024-10-25 14:15:26.250] [error] Error occurred in handler for 'grpc.loadMethods': Error: ENOENT: no such file or directory, open '/var/folders/d1/r1cqgqfd4c9048t7n56nptg80000gp/T/insomnia-grpc/pd_c00d69e9510d440a8f86fd660384797a.1729835936740/proto/proto/centaur.proto'

It seems to be caused by the relative import in my proto files.
```
/project
    /proto
        /to_include.proto
        /test.proto.  # import "proto/to_include.proto";
```
I think is better to show the error message instead of becoming not responsible:(

Update 2:
Selecting the parent folder still doesn't help. This time no log printed :(
<img width="826" alt="image" src="https://github.com/user-attachments/assets/6ac3b4b1-dd0b-4be5-bf63-bd67f087d692">

But after return to the request view, console shows some errors:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/3be77b3d-1481-47a6-8e23-534cb7e18455">
```
node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: Error invoking remote method 'grpc.loadMethods': Error: Proto file pf_82866a59fbef43e88cf69af192b6820e not found
    at IpcRenderer.invoke (node:electron/js2c/renderer_init:2:6995)
    at async grpc-request-pane.tsx:62:23
```

**Comment by CurryYangxx** [comment] 2024-10-28 09:31
@Haarolean Have you uploaded all proto files, including files introduced in the import statement? We found that when a file is missing, no error is reported, and it fails silently, which causes the parsing to fail and the corresponding method cannot be obtained.

**Comment by CurryYangxx** [comment] 2024-10-28 09:55
@JalinWang Hi, thanks for your feedback.

> After "Add Directory" and confirm, the 'Save' button isn't responsible, as well as the disabled "Selected Method" dropdown after closing the modal.

After you upload a directory, you need to click a file to select which proto you want to parse, and then the save button will enable.
Now it seems that the file is not a clickable node. We will optimize the UI later, such as adding a checkbox.

https://github.com/user-attachments/assets/a460a228-4779-42b0-92fc-da6bc87917f5


> It seems to be caused by the relative import in my proto files. I think is better to show the error message instead of becoming not responsible.

Now when user click the save button, we can get an error message. We will display the error in a modal instead of closing it directly.

**Comment by JalinWang** [comment] 2024-10-28 11:13
@CurryYangxx Thanks for the reply! Finally got it running😊 The error modal and clickable fix will definitely be helpful improvements~

**Closed as completed** 2024-10-30 03:57 UTC
Labels: B-bug, S-unverified

**Comment by Haarolean** [comment] 2024-10-30 15:00
> @Haarolean Have you uploaded all proto files, including files introduced in the import statement? We found that when a file is missing, no error is reported, and it fails silently, which causes the parsing to fail and the corresponding method cannot be obtained.

not sure, but it has worked in other tools. Perhaps it might've been related to missing 'well-known' imports like google's proto?
