### ISSUE TITLE
[BUG] Export to YAML contains mixed spaces with tabs

### ISSUE THREAD

**Issue by jankosecki** [getinsomnia/insomnia#1527] opened 2019-05-28 10:11 UTC
- Insomnia Version: 6.5.3
- Operating System: macOS Mojave 10.14.3

## Details

Exported workspace that contains a request with JSON body mixes spaces with tabs.

## Steps to reproduce

1. Create a POST request with JSON body
2. Export workspace to YAML
3. Open exported YAML in any editor that can show whitespaces
4. Fragment defining body of the request uses tabs for indentation

<img width="604" alt="Screenshot 2019-05-28 at 11 05 28" src="https://user-images.githubusercontent.com/41573247/58470064-ce408f80-8138-11e9-9cd1-00ba4276f310.png">

**Comment by gschier** [comment] 2019-05-28 19:52
It looks like that's because the request body contained tabs. The first two indents use spaces because the YAML document it indented with spaces, and the JSON body intents with tabs because that's what's in the request body within Insomnia. We can't convert those tabs to spaces or we would be modifying the contents of the request.

Going to close this issue as this is expected behavior.

Note, you can change Insomnia's default indent from tabs to spaces in the app preferences if you'd like your bodies to be indented with spaces.

**Closed by gschier** 2019-05-28 19:52 UTC
