### ISSUE TITLE
Upgraded to 10 and all old request are gon

### ISSUE THREAD

**Issue by stocks81** [getinsomnia/insomnia#7997] opened 2024-09-23 17:45 UTC
### Expected Behavior

I would have thought upgrading all my old request would be there in the new version.

### Actual Behavior

Non of my old request carried over. 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

the installer

**Comment by BukhariH** [comment] 2024-09-23 20:40
So I had the same heart attack.

The requests are there but side menu is hidden for some reason. 

<img width="457" alt="Screenshot 2024-09-23 at 21 39 24" src="https://github.com/user-attachments/assets/e22c62b7-0d65-4268-96d1-99f33a78d905">

**Comment by notjaywu** [comment] 2024-09-24 01:15
@stocks81 Which version did you use before upgrading? If it is a version before 8.0, you should be able to see a project named `Insomnia` in v10.0. Do you see your collections in this project?

![image](https://github.com/user-attachments/assets/5ad83eab-064e-4507-b561-7ef6664c9e46)

**Comment by remixer-dec** [comment] 2024-09-27 13:05
<img width="1328" alt="screenshot" src="https://github.com/user-attachments/assets/0b9c80ed-443f-45ac-9ae1-02e6efda8ce4">
Same issue, all requests gone, 1 "orphaned" project that cannot be transferred anywhere, at least with fully local experience.    

I guess taking user data as hostage and forcing people into making accounts is by design, instead of offering extra features for logged users. Yikes, it was a good software, downgrade is the only option.

**Comment by subnetmarco** [comment] 2024-09-27 22:02
The requests are always on the file system, when creating an account they appear in the "Insomnia" project or personal workspace (depending the original version that you are upgrading from). 

@BukhariH you are bringing up a valid point, we should not allow that menu to be fully hidden perhaps.

@remixer-dec Insomnia's development is being supported by those accounts, more information [here](https://github.com/Kong/insomnia?tab=readme-ov-file#why-does-insomnia-require-an-account).

Unless there are more information from @stocks81 I will close this issue now.

**Closed as completed by subnetmarco** 2024-09-27 22:02 UTC
Labels: B-bug, S-unverified

**Comment by ydcool** [comment] 2024-09-29 09:21
So user have to login to see those local data of old version?  If a user is in a restricted network environment with no access to a insomnia server, this is a usability issue.

**Comment by subnetmarco** [comment] 2024-09-30 01:17
For versions of Insomnia >= 8.0, we require a login to use the full application experience. We still provide the Scratch Pad without needing to login, but it doesn't have all the product capabilities.

> If a user is in a restricted network environment with no access to a insomnia server, this is a usability issue.

Yes, this could be the case if you are initiating the login for the first time, but it is not always the case. 

This is how it works:

1. **Login once and use everywhere**: you can login once and the session will be stored locally, so that you can use the application in an air-gapped environment down the road. You will need connectivity for the first login, but then it's not needed afterwards.
2. **Work offline or with poor connectivity**: The application will keep working normally without an internet connection (you can simulate this by turning off your wifi, and using the application) as long as you have a user session (see previous point).
3. **Still be able to have Local, Git or Cloud projects**: Finally, the login requirement doesn't mean your data must be in the cloud, you can choose to have it local (or Git, or partially in the Cloud for those projects where collaboration is needed). And even for cloud projects (the ones you decide to store in the Insomnia cloud), we support offline working but of course you won't be able to push your changes until your connectivity is back.

**Comment by DawTaylor** [comment] 2025-03-06 14:31
I had auto updates turned off because of older issues, now I decided to upgrade and test it out and I'm locked out of my data.

What a bad decision. Forcing people to give out data is not the way to go. You literally trashed out the existing software making it barely usable.

**Comment by subnetmarco** [comment] 2025-03-06 14:47
@DawTaylor You can still store your files locally, we simply require an account to use the product but your data locality can be local (or Git, or cloud). The new version of Insomnia are significantly more capable and powerful than the older ones.

![Image](https://github.com/user-attachments/assets/b4999f06-46fc-4cd8-bab5-be7ab4eb049a)

**Comment by DawTaylor** [comment] 2025-03-06 14:51
> we simply require an account to use the product

You're literally requiring me to give out personal data in exchange for using the product...

I understand the product development needs support, but forcing people to give out data in advance is a bad decision. I already managed to find and export my data, that's not an issue for me, I can also find a better option. I just wanted to leave my feedback, this is NOT the way, and the fact that many people doesn't give a sh** about their personal data does not mean you're in a good path.

**Comment by subnetmarco** [comment] 2025-03-06 15:00
Yes, we require an account but it's not at gun point: you can simply stay on an older version of Insomnia if you are against creating one, you can also use Scratch Pad on the latest versions which also doesn't require an account. We only require an account to use the greatest and latest version of Insomnia, and the account is used to run the product and its features (many were developed that required an account, many more will come in the future).

With that said I understand and respect why you may not want to create an account, just sharing my perspective.

**Comment by DawTaylor** [comment] 2025-03-06 15:24
> you can also use Scratch Pad on the latest versions which also doesn't require an account.

That would be fine IF you allowed people to keep using their existing collections with the Scratch Pad, which you do not. That would be fine IF you didn't make the product worse to those who do not have an account.

Don't get me wrong, I would create an account to gain access to new features. But I would not create an account to use the old features.

The fact that it's now being force feed into us leads people to think their data will de sold at some point, and they are not wrong.

> you can simply stay on an older version of Insomnia if you are against creating one

It would be interesting from you to keep older versions easily accessible. From home brew you can only install the latest one.

I'm also just sharing my perspective which is, making the product worse would not do any good to the product. People need to use something before they start to actually like the product before they give out personal data. When someone wants to share their collections with their teammates, making the account is a natural step.

**Comment by subnetmarco** [comment] 2025-03-06 17:29
> That would be fine IF you allowed people to keep using their existing collections with the Scratch Pad, which you do not.

You can probably reimport your files in Scratch Pad and re-use without an account. You are going to miss all the other capabilities though, so that's the tradeoff.

> Don't get me wrong, I would create an account to gain access to new features. But I would not create an account to use the old features.

You are getting access to a state of the art product, with 100s of capabilities that are being continuously developed, a product that is trying to grow in a sustainable way while still delivering 99% of features for free without having to pay a dime. We needed to rip the band aid off a couple of years ago and move on to a more sustainable model or we were simply not going to invest into the product at all any longer: it all consumes times, money and resources. I know that none of this is your business, but it is mine and I have responsibility in making sure we are on a good path.

Yes we introduced a login dialog to still use all the capabilities for free, and still being able to store them locally. It's not unusual for developer tools to have a login, think of Cursor, or even think of GitHub: Git per-se doesn't require an account, and yet here we are. Millions of developers on a daily basis create accounts for all sorts of tooling, I respect the ideological opposition to creating an account, but we couldn't run this project on ideology anymore.

So another way to think about it is: consider Insomnia 8.x as a divergence point, you can keep using the older Insomnia version pre v8.x without a login dialog, but effectively that product development has stalled as it was not sustainable anymore. Every version above v8+ to today has been developed with a new direction (and resources) that has allowed us to accelerate the development of Insomnia to this day.

> It would be interesting from you to keep older versions easily accessible.

We are keeping all releases available on GitHub.

> The fact that it's now being force feed into us leads people to think their data will de sold at some point, and they are not wrong.

We are not in the business of reselling account data, we are a product company.

**Comment by DawTaylor** [comment] 2025-03-06 19:22
You intentionally made the product **worse** to collect user data. There's no other reason for that other than reselling it at some point.

Github is a service as opposed to Git, this is why you need an account for it. A rest client is not a service and, as such, should not require an account.

This is going nowhere. I wish you best of luck.

**Comment by subnetmarco** [comment] 2025-03-06 19:31
> There's no other reason for that other than reselling it at some point.

This is baseless speculation and not true. We are providing a service too with our collaboration and sharing features, AI features (and a lot more) that require an account to work. Insomnia has evolved a lot since 2019, it is not just a GUI on top of curl anymore.
