### ISSUE TITLE
When data is pasted into address field, old request is sent

### ISSUE THREAD

**Issue by funkflute** [getinsomnia/insomnia#2385] opened 2020-07-10 15:16 UTC
**Describe the bug**
When altering an existing URL by pasting data, the url is updated, but the request sent is the old

**To Reproduce**
On a Mac
Have an existing request setup
Run that request
Copy part of new url to replace part of the existing request (like changing an id /something/123, copy 345 from somewhere, select 123 and paste to replace 123 with 345)
run the request
the response will be the same as the last request
the query panel does not show the url in the address field

**Expected behavior**
the response should use the new pasted URL
the query panel should show the url in the address field

**Screenshots**
![image](https://user-images.githubusercontent.com/7559852/87169920-a78edb00-c29e-11ea-84dd-65f06b36a5d6.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Installation Method: DMG
 - App Version 2020.3.0

**Comment by rodionbykov** [comment] 2020-07-10 15:50
Windows 2020.3.0: paste (Ctrl+V) a param value into Query field. In 2-3 seconds param value is cleared without interaction from user. To avoid the problem, right after pasting in new param value, type something and immediately delete, then pasted value is saved and used in request.

**Comment by bodegafresh** [comment] 2020-07-10 16:04
I have the same problem on linux and when some part of the response collapsed and then I clicked outside the application, returns to its original state alone.

Yesterday I updated to the latest version. Before it did not happen.

uname -a
Linux  4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

Sorry my english (Google translator)

**Comment by mattburton** [comment] 2020-07-10 16:21
Same on macOS 2020.3.0

**Comment by Brunopoliveira** [comment] 2020-07-10 17:22
When pasting new endpoint parameters and make a new GET it makes the call with the previous parameters value. No matter how many times i try to change the values, it keeps making the request with the previous parameters. This started after updating to the last version V2020.3.0 (7/9/2020).

**Comment by nijikokun** [comment] 2020-07-10 17:25
Duplicate of #2377

**Closed as completed by nijikokun** 2020-07-10 17:25 UTC
