### ISSUE TITLE
Insomnia Designer - operations in the Debug section are lost when switch to the Design section

### ISSUE THREAD

**Issue by projser** [getinsomnia/insomnia#2442] opened 2020-07-25 11:56 UTC
I have added folders to organize operations in the Debug section when I changed to the Design section  and return to the Debug section, the operations are removed from the folders.

Steps to Reproduce

Create a Folder in the Debug section, add operations in it. Change to the Design section and return to the Debug section.

I have even commit the changes and tried to imported later on, but the operations and folders have been lost in the debug section too.

macOS 10.15.5
Insomnia version 2020.3.3

**Comment by filfreire** [comment] 2022-08-12 10:32
Hi @projser thanks for reporting this!

I'm going to go ahead and close this issue as duplicate of #2882 and #4283.

Internally we are aware that there's a handful of problems when switching between Debug and Design tabs, and we'll be addressing these soon.

Feel free to create new issues and report any other problems or improvements you come across!

**Closed as completed by filfreire** 2022-08-12 10:32 UTC
Labels: needs-triage
