### ISSUE TITLE
Active/selected environment not visible

### ISSUE THREAD

**Issue by adrianmiles** [getinsomnia/insomnia#7615] opened 2024-06-28 13:00 UTC
### Expected Behavior

For the active base environment (e.g. staging, dev, prod) to be visible from the main UI (on the left-hand side) so I know which environmnent I'm running queries against. 

### Actual Behavior

No environment shown on left hand panel.
<img width="451" alt="image" src="https://github.com/Kong/insomnia/assets/44703855/a7f9a15a-e4c2-4897-8975-a736440df08d">

### Reproduction Steps

Install version 9.3.0 and it won't be visible

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 9.3.0

### What operating system are you using?

macOS

### Operating System Version

14.4.1 (23E224)

### Installation method

Download from GH

**Comment by drc-bsvee** [comment] 2024-06-28 14:34
This is a terrible bug and a deal breaker. It is imperative that I don't make post/put requests to production by accident.

**Comment by mbombonato** [comment] 2024-06-28 16:26
I have to say... I love Insomnia, but 9.3 was one of the worst releases so far. The whole UI is glitch and don't work properly and besides that we have this kind of weird decision of hiding one of the most important information from our sight.

**Comment by subnetmarco** [comment] 2024-06-29 12:17
> This is a terrible bug and a deal breaker. It is imperative that I don't make post/put requests to production by accident.

Yes, makes sense. We will bring this back, as it shouldn't have been removed from a product standpoint. This is a regression introduced with the creation of global environment variables, we will make a release by EoW next week to re-introduce it.

**Comment by binarythistle** [comment] 2024-06-30 23:35
I really want to stay on Insomina as the alternatives are not great, but bugs/ releases like this make it very hard... It just seems to get progressively worse.

**Comment by qury** [comment] 2024-07-01 08:10
I can confirm, that this issue is present in the linux appimage as well.
![image](https://github.com/Kong/insomnia/assets/1764676/187b8b08-2c6c-4609-8856-5b966c245095)

As you can see from the above there is no visible indicator about which environment is used, you have to click on the "Manage Environments" button to find that out.

It is frustrating to say the least.

I would like to see the environment name at least on the button or next to it!

**Comment by subnetmarco** [comment] 2024-07-01 08:17
> but 9.3 was one of the worst releases so far

> It just seems to get progressively worse.

Insomnia is objectively getting better every day, we are shipping new capabilities every month.

Regressions/mistakes happen, Insomnia is a large project at this point, and this one will be fixed this week. I understand the value of seeing immediately the environment variable that's been selected, and we are bringing it back this week.

**Comment by subnetmarco** [comment] 2024-07-01 09:05
This is how it will look like in 9.3.2 when both a global environment, and a collection env, are selected.

We also added counters for cookies and certificates, so it's easier to see if they are being valued or not:

<img width="400" alt="image" src="https://github.com/Kong/insomnia/assets/964813/b77f5001-0ad3-4d38-84c4-7e112c5f986e">

**Comment by Agomezdelamo** [comment] 2024-07-01 09:46
> > but 9.3 was one of the worst releases so far
> 
> > It just seems to get progressively worse.
> 
> Insomnia is objectively getting better every day, we are shipping new capabilities every month.
> 
> Regressions/mistakes happen, Insomnia is a large project at this point, and this one will be fixed this week. I understand the value of seeing immediately the environment variable that's been selected, and we are bringing it back this week.

I love Insomnia, thx for try to fix this one. As you said, mistakes happen.

**Comment by DusanLesan** [comment] 2024-07-01 23:47
> Insomnia is objectively getting better every day, we are shipping new capabilities every month.

That is debatable. I cannot really remember any new feature that was relevant to me. That would be fine if previous/core functionality wasn't removed or broken every release more and more. I used to be very enthusiastic about this app but now the only thing keeping me here are the people I converted into the ecosystem while I was happy with the app. The app used to be simple (which is a huge benefit IMO) alternative to Postman that offered everything I needed to interact with APIs. But then you forced us to create accounts (I don't think it is even possible to import exports from other people without them and even if they have accounts, data import is partially broken for over a year), and you now keep working on shrinking important parts of UI and call it a improvement. There are several people in my team alone who reverted to versions prior to V8 disaster and will never attempt to downgrade to 8 or 9

**Comment by subnetmarco** [comment] 2024-07-02 00:00
In the past releases we have stabilized the application significantly although when we build major features (like the new global environments) there is a risk of introducing regressions like the one discussed here, that we promptly fixed and we will ship it soon in 9.3.2 this week. We would rather avoid introducing regressions, but yes it can happen and we will try to fix them asap when it does.

In what ways Insomnia is not simple anymore? You can still go straight into a collection and start debugging as usual. Yes, we require a login because we are running a business, but the usability of the app hasn't changed much over the years and most of the capabilities are free.

**Comment by DusanLesan** [comment] 2024-07-02 00:43
> In what ways Insomnia is not simple anymore?

Bunch of actions now require some additional click or workaround: 
- You want a new request - you must go to headers and delete "default" entries
- You want to import data - you must go through hundreds of requests to fix broken tags
- You want to see docs - make sure to to switch between sections after selecting request
- You want to delete request - hunt down a dialog to confirm
- Wanna continue where you have left of? - nope
- Wanna update - pray to have app usable after relaunch

> In the past releases we have stabilized the application significantly although when we build major features (like the new global environments) there is a risk of introducing regressions like the one discussed here

I am aware that unintentional regressions happen as well, but it is curious how fast I bump into them. I saw this issue less than a minute after starting this version.

> Yes, we require a login because we are running a business

I get that you need to farm data these days to be profitable. I have payed for a lot less needed software than this, but not after losing my data after attempting to work after update or being forced to create an account

**Comment by subnetmarco** [comment] 2024-07-02 08:56
Thanks for the feedback, answers below:

> You want a new request - you must go to headers and delete "default" entries

We are adding the ability in the Preferences to remove the automatically generated `User-Agent` header. This header was also added in previous versions of Insomnia since a very long time, but simply we didn't show it in the Headers section (but now we do).

> You want to import data - you must go through hundreds of requests to fix broken tags

Let me ask the team if we are aware of this issue.

> You want to see docs - make sure to to switch between sections after selecting request

I can replicate, we can fix this for upcoming 9.3.2

> You want to delete request - hunt down a dialog to confirm

The confirmation dialog was introduced because - on the other end - many users complained that they lost data by accidentally deleting an entire request. So we decided to prioritize for not losing data, but perhaps we can introduce a "Do not ask again" checkbox so that after the first time we don't ask it again for users that don't mind deleting without a confirmation.

> Wanna continue where you have left of?

You mean after restarting the application, the ability to be redirected directly into the last collection that you were working on?

**Comment by DusanLesan** [comment] 2024-07-02 09:49
> Let me ask the team if we are aware of this issue

https://github.com/Kong/insomnia/issues/6070

> You mean after restarting the application, the ability to be redirected directly into the last collection that you were working on?

Exactly: https://github.com/Kong/insomnia/issues/6928

> but perhaps we can introduce a "Do not ask again" checkbox so that after the first time we don't ask it again for users that don't mind deleting without a confirmation

It was a nitpick I bumped in that day. I do not mind it much. Only an example how app requires more clicks and takes up more space but probably not something I would complain about otherwise.

**Comment by subnetmarco** [comment] 2024-07-04 15:42
Insomnia v9.3.2 [has been released](https://github.com/Kong/insomnia/releases/tag/core%409.3.2) fixing this issue.

**Closed as completed** 2024-07-04 15:42 UTC
Labels: B-bug, S-unverified
