### ISSUE TITLE
XPath query does not work at all

### ISSUE THREAD

**Issue by miagg** [getinsomnia/insomnia#5808] opened 2023-02-28 09:26 UTC
### Expected Behavior

If I try to filter a XML response using XPath query I always get empty result.

`<result></result>`

For example in the following XML response
```XML
<?xml version="1.0" encoding="UTF-8"?>
<store>
    <created_at>27.02.2023 08:19:45</created_at>
    <products>
        <product>
            <UniqueID>20656</UniqueID>
            <Name>Deux Dieux 750ml</Name>
            <Link>https://someurl/</Link>
            <Category>Wine</Category>
            <Vendor>Some Vendor</Vendor>
            <Color>Red</Color>
            <Year></Year>
            <Size>750</Size>
            <Price>33</Price>
            <Availability>Instant Delivery</Availability>
        </product>
    </products>
</store>
```

Quering for `/store` or `//Name` does not return any results

If I query the response using an external tool I get the required results.

I am 100% positive it worked fine previously but I cannot remember when and how it stopped working for me.

### Actual Behavior

To get results

### Reproduction Steps

1. Send a GET request to an endpoint returning a XML response.
2. Perform a XPath query

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Things I already tried:

- Install an older version
- Install the latest beta (2023.1.0.beta-4)
- Run the app using Rosetta (M1 sillicon)
- Disable all plugins
- Try different API endpoints with alternate responses
- Validate XML structure using external tool
- Check if `jsonpath-plus` is not working as weel (it works for JSON responses)
- Check DevTools for any errors (No Errors)
- Download Insomnia from website instead of homebrew
- Clean application caches (`~/Library/Application Support/Insomnia, ~/Library/Preferences/.com.insomnia.*`)

### Insomnia Version

2023.1.0.beta-4

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.2.1

### Installation method

homebrew

**Comment by sb-relaxt-at** [comment] 2023-03-06 09:17
Same issue here, running 2022.7.5. It definitely has worked before.

**Comment by av603** [comment] 2023-04-21 20:12
Same issue on Ubuntu.

**Comment by kerivdw** [comment] 2023-05-15 08:18
Hi,

Is this is still an issue?  When I run against this api http://restapi.adequateshop.com/api/Traveler?page=1 in the latest develop branch I then filter by `//id` it filters the list of nodes I would expect to see.

If I repeat the same in the latest released version, it doesn't seem to work.  I am wondering is it fixed but not released yet?

![image](https://github.com/Kong/insomnia/assets/75972814/9397bb09-1ac3-4a8a-911e-fad53fda9a52)

**Comment by patriciomg** [comment] 2023-08-16 14:20
Any news on this? 
I have the same issue using OSX Ventura 13.5, here the full info of the build:
```
Version: Insomnia 2023.4.0
Build date: 7/4/2023
OS: Darwin arm64 22.6.0
Electron: 23.3.9
Node: 18.12.1
V8: 11.0.226.20-electron.0
Architecture: arm64
```

and taking this example: 
```
<?xml version="1.0" encoding="UTF-8"?>
<offices>
    <office>
        <supplier>
            <name>
                <![CDATA[Acme Company]]>
            </name>
        </supplier>
        <referencenumber>
            <![CDATA[1f2e1bc7-0004348901-009314728]]>
        </referencenumber>
        <date>
            <![CDATA[12.08.2023]]>
        </date>
        <title>
            <![CDATA[Lorem ipsum dolor sit amet...]]>
        </title>
    </office>
</offices>
```    
    
I would expect to see **12.08.2023** when doing **//offices/office/date**  but I only get  ```<result></result>```

if I try **//offices/office/date/text()** same result.

**Comment by vermgit** [comment] 2023-08-17 06:17
I'm on Windows using version 2023.5.3 (it updated itself) and all my XPath-references are now broken.

Also the ordering of the folders and requests are now fixed and I can't reorder them to something useful, so there's something completely wrong with the latest version(s).

**Comment by joshymcd** [comment] 2023-08-17 11:37
Im also on 2023.5.3 and i am having the same issue

**Comment by vermgit** [comment] 2023-08-18 17:29
There was an update to 2023.5.4, which doesn't change anything. Same blocking behaviour.

**Comment by vermgit** [comment] 2023-08-18 22:33
There was an update to 2023.5.5, which doesn't change anything. Same blocking behaviour.

**Comment by johanhendrikehlers** [comment] 2023-08-22 12:11
Yes, also ran into this issue, from my perspective it seems to be happening from 2023.5.x onwards. If need be I am going to try and send a pull request for this one. I recently introduced insomnia rest into my company (from postman) and with the plugins I managed to do things you simply can't do in postman. Loving it, but still trying to convice fellow developers! Where is that Bounty button github!

Because of namespaces I had to use a bit of a different XPATH query, worked up to 2023.4.x:

`//*[local-name()='Token']`

 I see the following in the dev console:

![image](https://github.com/Kong/insomnia/assets/1751638/2d0e3998-a8d3-425f-b982-7e0b8bac5f67)

**Comment by vermgit** [comment] 2023-08-23 07:49
> Also the ordering of the folders and requests are now fixed and I can't reorder them to something useful, so there's something completely wrong with the latest version(s).

In case anyone sees this here and not in the other issues: 2023.5.6 fixes this

XPath is still broken.

**Comment by ybarrantes** [comment] 2023-08-24 12:55
Version 2023.5.6 does not yet fix this issue. XPath is still broken.

**Comment by patriciomg** [comment] 2023-08-29 06:33
I update from 
````
Version: Insomnia 2023.4.0
Build date: 7/4/2023
OS: Darwin arm64 22.6.0
Electron: 23.3.9
Node: 18.12.1
V8: 11.0.226.20-electron.0
Architecture: arm64
````
to 
```
Version: Insomnia 2023.5.6
Build date: 8/22/2023
OS: Darwin arm64 22.6.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64
```

and the issue is still there. I get an empty result:   <result></result>
(my prior post: https://github.com/Kong/insomnia/issues/5808#issuecomment-1680711128)

**Comment by featherbear** [comment] 2023-08-30 04:59
<img width="1179" alt="image" src="https://github.com/Kong/insomnia/assets/1159091/09765e59-76a2-4370-8867-6044184ceaff">

I did a bit of digging, seems to be because of the library minification of `xmldom`
@stevenp2

**Closed as completed** 2023-08-30 07:56 UTC
Labels: E-good-first-issue, B-bug, S-unverified

**Comment by patriciomg** [comment] 2023-08-30 12:32
it is working now! 👍 
With the new update **2023.5.7**
I am finally getting results :) 

//offices/office/date 

```
<result>
	<date>
		<![CDATA[17.08.2023]]>
	</date>
	<date>
		<![CDATA[17.08.2023]]>
	</date>
	<date>
		<![CDATA[15.08.2023]]>
	</date>
</result>
```

**Comment by ybarrantes** [comment] 2023-08-30 12:55
I have upgraded to:

```
Version: Insomnia 2023.5.7
Build date: 8/30/2023
OS: Windows_NT x64 10.0.22621
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64
``` 

This version fixes the XmlPath issue in this section as you can see in the following screenshots:

![image](https://github.com/Kong/insomnia/assets/39712885/f0ba198b-d2b7-42ad-8b5d-d667847f8341)

![image](https://github.com/Kong/insomnia/assets/39712885/e3d4c1f0-a172-47b2-a80d-8bc8b32a02ba)


However this issue persist in the 'Manage Environments' -> 'Edit Tag' window

![image](https://github.com/Kong/insomnia/assets/39712885/db8ca2b9-1772-4fec-b36f-758b2bf16c67)

![image](https://github.com/Kong/insomnia/assets/39712885/d5c841c9-490a-40f7-a60c-3a3817246a3d)

**Comment by vermgit** [comment] 2023-08-30 13:44
For me 2023.5.7 didn't improve any of my XPath-references.

**Comment by greenewk** [comment] 2023-08-30 14:01
2023.5.7 does not fix the issue. It now works in the preview window: 
![image](https://github.com/Kong/insomnia/assets/42468194/105990ca-4577-4444-92cf-74fd28c2f4e5)

but not when actually using it in a Tag:
![image](https://github.com/Kong/insomnia/assets/42468194/92517f71-f209-4b87-92ed-fd1974cff174)

**Comment by featherbear** [comment] 2023-08-30 14:32
Ahh... I'm new to using Insomnia, didn't know about the use of XPath in templating..

@jackkav looks like https://github.com/Kong/insomnia/blob/develop/packages/insomnia/src/ui/components/templating/local-template-tags.ts#L721-L758 needs to be modified similarly to #6419

**Comment by jackkav** [comment] 2023-08-30 14:44
Ah I knew I'd seen similar code somewhere, thanks for the catch PR up here #6428

**Comment by vermgit** [comment] 2023-09-05 12:43
Here's a screenshot of what used to work for me with a regular mpd-file:

![image](https://github.com/Kong/insomnia/assets/7654880/b2ee832e-3e7e-4be6-b9ae-1824cb324e43)

If I need to use a different syntax now, feel free to let me know.

**Comment by vermgit** [comment] 2023-09-11 06:06
2023.5.8 didn't fix this

**Comment by featherbear** [comment] 2023-09-11 08:26
@vermgit Can you share the MPD file you're using?

Seems to be working for template tags on [this](https://gist.githubusercontent.com/shankardevy/cfe77acd9fe7bded116c/raw/6168390c9d0aae247c5de0cfd02e6f6680a19ce3/gistfile1.xml) file I found 

<img width="799" alt="image" src="https://github.com/Kong/insomnia/assets/1159091/dddce004-64dd-42dd-9245-72aaf2ceca45">

**Comment by vermgit** [comment] 2023-09-11 14:44
@featherbear Interesting, it now also works on my end. I think I had to modify the "Filter" maybe?

Very good, thanks :)
