### ISSUE TITLE
Environment dropdown is gone after update

### ISSUE THREAD

**Issue by amustaine** [getinsomnia/insomnia#7660] opened 2024-07-03 21:22 UTC
### Expected Behavior

It would be nice to get the dropdown back

### Actual Behavior

I have to click on "</> Manage Environments" each time I send requests, because I need to be sure which environment I'm using. It makes it difficult to work

### Reproduction Steps

Install latest version (9.3.1)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 24.04 abd Ubuntu 23.10

### Installation method

from snap

### Last Known Working Insomnia version

9.3.0

**Comment by subnetmarco** [comment] 2024-07-03 21:29
This has already been fixed in 9.3.2 beta, due to be released tomorrow.

**Comment by neverfan** [comment] 2024-07-04 09:16
Thank you that the issue is in the process of being resolved

**Comment by justinian-tomegea** [comment] 2024-07-04 10:26
Bug confirmed on Mac OS Sonoma as well.

**Comment by subnetmarco** [comment] 2024-07-04 15:44
Insomnia v9.3.2 [has been released](https://github.com/Kong/insomnia/releases/tag/core%409.3.2) fixing this issue.

**Closed as completed by subnetmarco** 2024-07-04 15:44 UTC
Labels: B-bug, S-unverified
