### ISSUE TITLE
[Bug] Curl import does not work after switching to bulk editing

### ISSUE THREAD

**Issue by Euphorbium** [getinsomnia/insomnia#381] opened 2017-07-27 10:11 UTC
## Overview
- `Insomnia Version:` 5.5.2.677
- `Operating System:`  _MacOS 10.12.5_
- `Summary: ` If you make a new request, switch to bulk editing and then back (or stay in bulk editing mode) and then paste a curl command in url field, nothing gets populated and the command stays in url field. At this point there is no way to import a curl command.

## How To Reproduce
1. _Create new request_
2. _Switch to bulk editing_
3. _Switch back to regular editing_
4. _Paste a curl command in url field_

**Comment by gschier** [comment] 2017-07-27 22:58
@Euphorbium, I am not able to reproduce this one with the steps you've provided. 

I used the following Curl command:

```
curl -X POST https://insomnia.rest -H 'Foo: Bar'
```

Would you be able to provide the exact curl command you used to reproduce this?

**Comment by gschier** [comment] 2017-08-03 22:53
Can you confirm that this is still happening in 5.7.0?

**Comment by gschier** [comment] 2017-08-14 17:56
Closing this for now. Can re-open if you can confirm it's still happening.

**Closed by gschier** 2017-08-14 17:56 UTC
Labels: Needs Verification
