### ISSUE TITLE
Cannot run npm bootstrap on Linux ARM64

### ISSUE THREAD

**Issue by rpsteiger** [getinsomnia/insomnia#5957] opened 2023-05-11 17:15 UTC
### Expected Behavior

I would like to use Insomnia on Kali Linux. I am on ARM64. Since there is no arm64 build I wanted to build the code myself.
I get the following errors during `npm run bootstrap`. Unfortunately, I cannot make sense of the error. Can someone help me out?
[insomnia-build-error.txt](https://github.com/Kong/insomnia/files/11454733/insomnia-build-error.txt)

Expected Behavior:
I would like the program to build and start when I execute `npm run bootstrap` in the project directory. Btw I am using Node V.16.

### Actual Behavior

The build process stops with an error message during the lerna info installing external dependencies.
![Screenshot 2023-05-11 at 19 13 31](https://github.com/Kong/insomnia/assets/1891583/0c2ec537-87ca-4c93-ae74-2873c2a94a58)

### Reproduction Steps

1. git clone <insomnia>
2. nvm use 16
3. npm run bootstrap

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

the current version from main

### What operating system are you using?

Other Linux

### Operating System Version

Kali Linux

### Installation method

cloned the sources

**Comment by filfreire** [comment] 2023-05-17 10:47
Hi @rpsteiger thanks for reporting. We don't have official Linux ARM64 support for now.

If you can share the error log we might be able to give a few hints of what it is and attempt to help.

**Comment by filfreire** [comment] 2023-07-17 15:56
Duplicate of #5777

**Closed as completed by filfreire** 2023-07-17 15:56 UTC
Labels: B-bug, S-unverified
