### ISSUE TITLE
Insomnia uses tabs to indent YAML by default

### ISSUE THREAD

**Issue by arnu515** [getinsomnia/insomnia#4313] opened 2021-12-16 05:51 UTC
### Expected Behavior

By default, tabs are used to indent YAML documents, which is not allowed in YAML, causing unhelpful errors to show up. The below screenshot shows the errors that are very unhelpful.

![Step-2-errors](https://user-images.githubusercontent.com/52203828/146315504-29e36335-1fa6-4490-94e1-db502adebed5.png)

### Actual Behavior

YAML should be indented with spaces. Maybe a warning on top that says "YAML should be indented with spaces", with an option to change the indent type, or automatically indenting with spaces in Insomnia Designer documents can fix this issue.

### Reproduction Steps

1. Get a clean install of insomnia (preferences reset)
2. Create a new insomnia designer document
3. Add some OAPI stuff with indentation
4. The document is indented with tabs, and the errors are not helpful.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.7.1

### What operating system are you using?

Ubuntu

### Operating System Version

Pop!_OS 21.04 (based on Ubuntu)

### Installation method

Using flatpaks on the Pop!_Shop

### Last Known Working Insomnia version

N/A

**Comment by develohpanda** [comment] 2021-12-16 06:22
Thanks for reporting this! I confirmed this is a regression from 2021.6.0. For the time being this can be resolved by going into Preferences > General > Font and unchecking "Indent with Tabs".

<img width="157" alt="image" src="https://user-images.githubusercontent.com/4312346/146318649-f89dd298-dc3b-45a9-a608-d525990dc79b.png">

--- 

Investigation notes: curiously, we have some checks in place to make sure that that setting is disregarded if using YAML, however the editor in the Design tab sets the mode to `openapi` (which could be YAML or JSON) and not `yaml` specifically.

https://github.com/Kong/insomnia/blob/80d5dd1ec3bbabc9fd632e362190bc367229923f/packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx#L802-L804

This wasn't an issue in 2021.6 because that one ignored the `indentWithTabs` setting entirely when used by the code editor in the design tab, but after we moved to remove the prop drilling, the `indentWithTabs` setting is automatically read from Redux. We might want to put a safety net in if the mode is openapi.

https://github.com/Kong/insomnia/commit/f3c6ae19a59c9e583d49da1be6a2c7abc4519a2a#diff-0c3351d2098a07898def22b80d1048527b61d4a902c4b7bb607f607f8bc87847L162-L165

**Comment by arnu515** [comment] 2021-12-16 06:40
Thanks for the quick reply @develohpanda 

Can you give me an estimated time when I can see this pull request merged? Thanks.

**Comment by develohpanda** [comment] 2021-12-16 06:42
No worries @arnu515! We should be able to get it merged quickly, but because of the holiday period we likely don't have a quick release planned (though I will confirm tomorrow).

We are aiming to launch some beta builds between now and January however, so it'll be a part of that, and then a stable release mid-late January.

**Comment by arnu515** [comment] 2021-12-16 06:55
Thanks

**Closed as completed** 2021-12-16 10:48 UTC
Labels: B-bug, S-verified
