### ISSUE TITLE
App crashes when trying to import from file

### ISSUE THREAD

**Issue by erwinetchart** [getinsomnia/insomnia#5012] opened 2022-07-27 16:48 UTC
Hi,

I had to reopen the issue since still happens 

Thanks

Erwin

PD - Ubuntu 22.04 with GNOME

Here the reference to the error not fixed but yet present --->

Thanks
                                                                    
---------------------
Same error happened to me , looks like an error with Yaru theme.

Here the logs (in image format)

![image](https://user-images.githubusercontent.com/8241652/181064222-91674c36-fbc5-4bb6-a2f0-92ce77869535.png)

_Originally posted by @erwinetchart in https://github.com/Kong/insomnia/issues/2638#issuecomment-1195729929_

**Comment by filfreire** [comment] 2022-07-27 17:43
Hi @erwinetchart thanks for reporting this!

Looking at the error message, indeed seems related to what you mentioned on https://github.com/Kong/insomnia/issues/2638#issuecomment-1195729929.

Just to double-check, are you able to reproduce the crash locally if for example you reinstall Insomnia using an alternative to snap, like [the AppImage or the .deb package](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2)?

**Comment by erwinetchart** [comment] 2022-07-27 17:47
Hi Filipe, in fact this is a fresh new installation, from snap.
The image pasted in the closed ticket , from my local machine is.

Thanks!
Obrigado!

![insomnia](https://user-images.githubusercontent.com/8241652/181319368-8cb305e6-aa10-4ffa-a7cd-ded5c33b2a48.png)

**Comment by erwinetchart** [comment] 2022-07-27 17:53
Will check now.

**Comment by erwinetchart** [comment] 2022-07-27 17:58
Deb package  works fine for the import , thanks, obrigado.

Here the version installed:
![image](https://user-images.githubusercontent.com/8241652/181340588-464f409d-73c2-4f26-a430-444581fef65e.png)

 
Here the repository used.
echo "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all" \
    | sudo tee -a /etc/apt/sources.list.d/insomnia.list

**Comment by erwinetchart** [comment] 2022-08-04 21:07
@filfreire  Should i close the issue? The app installed from apt works fine, but no from snap, not sure the actions to take.

Thanks

**Comment by wongstein** [comment] 2022-08-08 17:43
Let's close this issue, since apt works.  We can reopen this issue again later if all forms of download stop working.

**Closed as completed by wongstein** 2022-08-08 17:43 UTC
