### ISSUE TITLE
My entire project just disappeared

### ISSUE THREAD

**Issue by ghost** [getinsomnia/insomnia#5167] opened 2022-09-12 00:28 UTC
### Expected Behavior

Work

### Actual Behavior

There were 4 folders of 10-12 requests each. After I closed and opened the program, most of the requests and folders were gone...

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I was disapponted after my entire project just disappeared. There were 4 folders of 10-12 requests each. After I closed and opened the program, most of the requests and folders were gone! I was very angry, very angry. All my hard work had gone to waste. Before that, I sometimes noticed that something was wrong with the program, or some requests were deleted, or the address bar deleted its content, this happened after closing the program. And here came this terrible bug!

### Insomnia Version

2022.5.1

### What operating system are you using?

Other (specify below)

### Operating System Version

Linux 5.15.0-47-generic #51-Ubuntu x86_64 GNU/Linux

### Installation method

download

### Last Known Working Insomnia version

same

**Comment by filfreire** [comment] 2022-09-12 12:58
Hi @pheianox thanks for reporting this! This sounds like it could be a bug.

Please reply with the following information:

- How did you install Insomnia?
- Did you create your folders and requests manually, or by importing anything (e.g. like a Postman collection or OpenApi spec)
- Also can you share with us what does your project structure/dashboard look like? (e.g.

![image](https://user-images.githubusercontent.com/11976836/189659672-f020a995-3c84-4916-a337-397437cf40b2.png)


You can also sharing here a screenshot of your [application data](https://docs.insomnia.rest/insomnia/application-data) folder. And you can also try moving it, and see if that affects anything. Moving the folder instead of deleting it means you can restore it later. App Data on Linux: `$XDG_CONFIG_HOME/Insomnia` or `~/.config/Insomnia`

**Comment by ghost** [comment] 2022-09-17 17:29
Hello @filfreire! Thank you for response. 

1. I downloaded file (Insomnia.Core-2022.5.1.deb) and installed via GUI 
2. I created requests manually, I've never used import
4. Here's dashboard screenshot (empty, but there were only one collection with folders and each folder had requests + global env vars)
![image](https://user-images.githubusercontent.com/77569421/190868883-bda03989-289b-48e7-8e3a-ff93256ac008.png)

**Additinal details:**
Also when you duplicate loaded with env vars requests (e.g.`{{_.baseUrl}}/products`) the address bar clears itlsef (not always, but you feel it sometime)

**Comment by ghost** [comment] 2022-09-17 17:36
I had this structure 

(collection)
```
myproject/
  authentication/
    [POST] {{_.baseUrl}}/sessions
    [DELETE] {{_.baseUrl}}/sessions/{{_.authentication.refreshToken}}
    [GET] {{_.baseUrl}}/sessions/{{_.authentication.refreshToken}}/token
    ...
  account/
    ...
  product/
    ...
  category/
    ...
```

(global env)
```ts
{
  "baseUrl": "...",
  "authentication": {
     "accessToken": "...",
     "refreshToken": "...",
      ...
  },
  ...
}
```

So after I closed and came back folders `product`, `account`, ..., were deleted, but some were not. It looked like unsaved version, but maybe it's bug. I never actually thought about saving project, it would save it automatically every time, so it's mostly bug. Maybe something wrong with the state managment, you guys know it better how it works

**Comment by dunhamjared** [comment] 2022-11-14 16:49
Also have this issue on my Windows 11 environment.

**Comment by kguskov** [comment] 2022-11-15 11:46
I have the same issue on Mac OS. Version: Insomnia 2022.7.0-beta.4

**Comment by filfreire** [comment] 2022-11-16 17:46
Hi folks, this might be the same problem that was reported on https://github.com/Kong/insomnia/issues/5384 and then fixed on https://github.com/Kong/insomnia/pull/5397. The fix should go out in an upcoming beta release.

@pheianox @dunhamjared @kguskov if you feel comfortable in trying a workaround until then, I would recommend the following steps in the meantime to debug if it's the same issue that got fixed:

1. First, check in your Data folder (see first screenshot) on the `insomnia.Workspace.db` file (you can open with text editor like VS Code) 

![image](https://user-images.githubusercontent.com/11976836/202253974-51ab0038-8ede-47c9-a5d3-515fcc460229.png)

2. Inside the `insomnia.Workspace.db`, please confirm if there any of the entries show up with the field `parentId` as null ?

![image](https://user-images.githubusercontent.com/11976836/202254044-a06611ab-812f-4a04-a812-758cccca6676.png)

3. If there are entries in that file that the `parentId` is `null` then:
- Make sure you closed Insomnia
- Replace the `null` with the string `"proj_default-project"`
- Reopen Insomnia and see if you now are able to see your data

Another user from has tried these steps and it worked for them ([link](https://getinsomnia.slack.com/archives/C3BBF236C/p1667792749381689))

**Comment by dunhamjared** [comment] 2022-11-16 19:32
@filfreire 

I can confirm that my issue is related to the null value for the parent ID. 

Thank you for the workaround!

**Comment by filfreire** [comment] 2022-11-17 09:23
Thank you for the confirmation @dunhamjared 

We will keep this issue open until we release `2022.7.0-beta.5` that has the fix for this.

**Comment by kguskov** [comment] 2022-11-17 09:43
> @filfreire
> 
> I can confirm that my issue is related to the null value for the parent ID.
> 
> Thank you for the workaround!

It worked for me too! Thank you!

**Comment by filfreire** [comment] 2022-11-17 16:09
2022.7.0-beta.5 is out now, https://github.com/kong/insomnia/releases

Marking this issue as closed. If you folks notice the behavior again, please feel free to reopen a new ticket. Hopefully after updating to this one it shouldn't happen though 🙏

**Closed as completed by filfreire** 2022-11-17 16:09 UTC
Labels: O-linux, N-author-input, B-bug, S-unverified, B-data-issues

**Comment by tmerten** [comment] 2022-12-16 10:29
That did not not work for me but then I switched from snap to deb install because of this issue #5531 . Aren't both versions using the same folder for storage?

**Comment by ghost** [comment] 2022-12-16 16:39
I also have this issue. All my stuff just disapeared when Insomnia updated itself. No clue where it is if it still exists. 

Using windows 11.

Im unhappy and thinking about writing my own curl scripts in a git instead. Both postman and insomnia now come with bloat and problems it seems.

**Comment by MaestroJurko** [comment] 2022-12-18 11:16
Deleting my Insomnia because of this issue. I lost all my requests and collections.

**Comment by alittlebitweird** [comment] 2022-12-20 00:33
wow. this just happened to me at the most mission-critical time imaginable 👎🏻

**Comment by jmrobbins13** [comment] 2022-12-20 19:19
Yeah, data is gone from the ui. Going to extract what I need from the requests file and move my requests to a new app.

**Comment by TomCosta** [comment] 2022-12-20 20:37
I lost everything without notice after update... 😳

**Comment by reyqn** [comment] 2022-12-21 08:34
Just in case, your issues seem to be related to #5559, [here](https://github.com/Kong/insomnia/issues/5559#issuecomment-1360095833) is what fixed it for me.

**Comment by bredwrd** [comment] 2022-12-22 15:49
I restored my environments by manually creating new environments, then copying the values of the `data` field from `insomnia.Environment.db` into the text editor in Manage Environments.

My requests were initially present in the Debug tab (top centre, just below the title bar) after opening or creating a new file, but then they disappeared after restoring the environment data as described above. I created a new request in the now-empty request panel, and then exited Insomnia and opened `insomnia.Request.db`. I copied the value of the `parentID` field of the new request over the value of the `parentID` field for all of my actual requests, and then saved and re-opened Insomnia.

I lost all my folder structure, but at least I don't have to create my requests from scratch. If I had a more complex folder structure that would have been painful to recreate, I may have tinkered in `insomnia.RequestGroup.db` and `insomnia.RequestGroupMeta.db` instead.

**Comment by IamMayankThakur** [comment] 2022-12-28 13:42
Had the same issue after the latest update. Lost all requests, `parentID` is not null.

**Comment by wollkind** [comment] 2022-12-28 15:02
Same here, just restarted my machine and everything in Insomnia is gone.  I think it auto-updated to 2022.6 when I restarted and I'm guessing that had something to do with it.  No one reading this needs me to point out that this is beyond frustrating and, honestly, a pretty mind-blowing bug.  "The software just deleted all my work" is about as bad as it gets.

**Comment by dusinof** [comment] 2023-01-02 11:44
My solution: 
Create new : `Request Collection`
<img width="1350" alt="Screenshot 2023-01-02 at 12 40 29" src="https://user-images.githubusercontent.com/34308289/210226560-9c56f16c-d14a-4d4f-9f99-78f7ed330298.png">

close insomnia.

open in the editor: 
`insomnia.workspace.db` and copy the `_id` of the newly created collection.
then open `insomnia.request.db` and replace the `parent_id` with the one you've just copied. 
Start insomnia. In my case, all request was back. Give it the try.

**Comment by lukasz-dobek** [comment] 2023-01-02 12:36
Can confirm @dusinof fix is working for requests - however, the same thing happened to my Environments and replacing `parent_id` of `insomnia.Environment.db` rows isn't enough (I guess some of them get deleted through `{"$$deleted":true,"_id":"..."}` mechanism on every Insomnia restart).

**Comment by kasperfp** [comment] 2023-01-03 13:23
Hi all. I had the same issue. For me it helped to choose the "DEBUG" tab inside the Document:
![image](https://user-images.githubusercontent.com/14122465/210365509-a3dcc81f-402b-42ca-b945-1ed221ba34a2.png)

**Comment by mikebm** [comment] 2023-01-03 17:07
Also lost everything. I came back from the holidays with an updated insomnia and a blank collection.
![image](https://user-images.githubusercontent.com/11326655/210405727-f97c50c2-d82e-4bea-841c-75a1afeafa8d.png)

As you can see, I don't have a Design/Debug/Test section at the top of mine.

I was lucky enough to snag a copy of my insomnia.Request.db before the app blew it away, but now no matter what I do trying to restore it (adjusting parentId), Insomnia empties the file out everytime I start the app.

Update - Deleting the Deleted entries like lukasz-dobek pointed out works. However, I don't trust Insomnia anymore. 
Back to postman I go. Unfortunately, I wasn't quick enough to copy other things like environment before it purged them too. Now I have hundreds of requests all without environment variables and folder structure. Gah.

**Comment by ghost** [comment] 2023-01-04 08:47
https://github.com/Kong/insomnia/issues/5600

**Comment by agencia3w** [comment] 2023-01-16 13:27
@dusinof, thanks, worked for me.

**Comment by R13e** [comment] 2023-02-02 08:03
I just stumbled across this. I haven't used Insomnia since 10/2022, but I regularly keep it updated via brew. All queries gone. A no-go for not-so-technical users. Sorry, but I'll switch to another app after all.

`brew remove insomnia`

**Comment by pheianox** [comment] 2023-02-02 15:02
This unstable behaviors make me swtich back to postman

```
nala remove isomnia
```

**Comment by janmonterrubio** [comment] 2023-02-03 22:31
Also ran into this as a surprise after closing the app today (finally updated I guess). 

I followed the tip of attaching everything to one workspace (RIP MY FOLDERS). I had about 400 requests to go through, so I was able to use this regex:
```
"parentId": "(\w+)"
```
To replace it with the new workspace id. Save file, quit, restart app. At least all my requests aren't gone...

**Comment by ls-philippe-khodara** [comment] 2023-02-09 10:29
> Deleting my Insomnia because of this issue. I lost all my requests and collections.

Same here, honestly I can't fathom how something like that can happen. Hours of work have been lost.

I suggest renaming the product from Insomnia to Nightmare.

**Comment by r2inlondon** [comment] 2023-02-12 18:08
Restarted my computer today and all my projects and data are gone !

Can't believe this just happened and that ticket for this issue is closed !

I am going back to Postman

**Comment by fdimauro** [comment] 2023-02-14 16:49
WTF This also just happened to me? Why would you release a product that destroys everyone's projects!!! You are going to lose most of your users including me!!! Duh!!

**Comment by ldevoco** [comment] 2023-02-24 22:03
I came here because I thought all my requests were deleted. But, I just clicked the Debug tab, and they were all in there?

Doesn't seem intuitive to me honestly. The reason I like Insomnia is because it was intuitive and clean. Design/Debug/Test... could probably be named something else, or they could be colored instead of slightly darker gray... or it could just go to the tab automatically instead of going to the Design tab, which didn't have anything in it.

I'd think Debug would be named Requests, since it contains all of my requests. I'm not debugging anything.

Anyway, thanks for your work.

**Comment by igorshandrov** [comment] 2023-03-13 11:49
Same happened to me! WTF???! I've lost all my projects, I'm removing this app right now and for good.

**Comment by stevevets** [comment] 2023-03-15 21:02
This is how I restored my Insomnia and hope it helps

1. Go to app data folder 
<img width="435" alt="image" src="https://user-images.githubusercontent.com/75004826/225437664-8067e2ee-ef9e-4a79-b594-d988c6dcf249.png">

You should be able to find these 2 folders
<img width="302" alt="image" src="https://user-images.githubusercontent.com/75004826/225438163-28d27b77-9661-4964-8271-082c0ce70a12.png">

2. Open **insomnia.Request.db** with text editor. This file stores all requests created. If this file is empty, I am sorry this method cannot help you :(

3. Lookup `"parentId":"wrk_` from the files. This is the workspace id your requests have been put under it. If you have multiple workspaces created before, make sure you have captured them all.

4. Open **insomnia.Workspace.db**. We need to recreate those missing workspaces here. 

Find the dummy workspace with `"type":"Workspace","parentId":"proj_default-project"`, and set parentId to null `"type":"Workspace","parentId":null`. This prevents the dummy default project from showing up. Do not remove it here since there are many relations binding to this id. Remove it through the UI later.

Add all new workspaces like this
`{"_id":"[[your workspace id]]","type":"Workspace","parentId":"proj_default-project","modified":1678912448235,"created":1678911590955,"name":"Restore collection","description":"","scope":"collection"}`

5. Save the file, restart Insomnia. You should be able to see there is a collection "Restore collection" in the dashboard.

**Comment by SeanBracksDev** [comment] 2023-03-30 14:09
How is this still an issue?
I'm uninstalling Insomnia, as I've met this issue multiple times, losing all requests and collections. What a joke.

**Comment by lovedisaster** [comment] 2023-04-28 04:19
I lost everything today, and found this ...

**Comment by MikeNGarrett** [comment] 2023-05-02 21:53
@stevevets Thank you!

**Comment by yair-rodriguez** [comment] 2023-05-18 15:46
This happened to me yesterday after clicking the home icon. Fortunately, I found my collections in the "Debug" tab, as @kasperfp mentioned.

**Comment by gethari** [comment] 2023-05-30 12:45
> in

Amazing thank you

**Comment by gethari** [comment] 2023-05-30 12:46
> This happened to me yesterday after clicking the home icon. Fortunately, I found my collections in the "Debug" tab, as @kasperfp mentioned.

Yes same happened with me as well @dusinof solution worked for me

**Comment by timgavin** [comment] 2023-05-31 17:26
This happened to me as well. I don't even have a debug tab, in fact I don't have any tabs across the top; even the GitHub badge is gone. This app is an unintuitive mess. And no, @dusinof 's solution did not work for me. The only thing that works is a Time Machine restore.

**Comment by errob37** [comment] 2023-06-13 15:35
Happened to me this morning... few hours before a demo..... Nightmare:(

**Comment by danilopeixoto** [comment] 2023-06-20 16:19
Seems everything I create disappears after closing the application.

```
Version: Insomnia 2023.2.2
Build date: 5/17/2023
OS: Windows_NT x64 10.0.22000
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64
```

**Comment by jifernandezv** [comment] 2023-06-21 17:01
Happened to me as well, and I was able to access my requests under the "Debug" tab, as @kasperfp pointed out.

Note that you will not see a "Debug" tab here:

![imagen](https://github.com/Kong/insomnia/assets/134718128/f6e1a19c-b7ea-495c-a4d7-fce84620a09f)

Instead, you need to open a Document in order for the tab to appear:

![imagen](https://github.com/Kong/insomnia/assets/134718128/4762b918-8915-43ef-bd29-39bdc4ce4b45)

**Comment by ellamurii** [comment] 2023-07-28 02:12
Happened to me today. after relaunching Insomnia, it says it was updated successfully. And all my requests are gone. Tried all suggested fixes here, nothing works. Instead, I imported from Insomnia backup folder, though it is outdated. Last backup was from March. this is sad.

**Comment by tmanley1985** [comment] 2023-07-28 15:12
Just adding to the pile at this point, but all of my requests are gone. It's been a few months since I opened it last and everything's gone. All of my requests are dust in the wind.

**Comment by timgavin** [comment] 2023-07-28 15:38
@ellamurii  @tmanley1985  It's sad. However, if a project has over 500 open issues I think it's safe to say we shouldn't use the product because the developers either don't care about it, or they are too lazy to fix it. I went back to Postman and haven't had a single issue since :)

**Comment by AnEmortalKid** [comment] 2023-07-28 17:04
> It's sad. However, if a project has over 500 open issues I think it's safe to say we shouldn't use the product because the developers either don't care about it, or they are too lazy to fix it. I went back to Postman and haven't had a single issue since :)

This is a pretty terrible attitude to have @timgavin . The last commit was 30 minutes ago which doesn’t show a lack of care or laziness. I understand this issue is frustrating, but anyone who cares enough to fix it can go fix it and submit a PR. 

In fact, work like #6184 shows that the developers care about their product.

**Comment by camilotorron** [comment] 2023-08-10 07:51
Same thing happened to me. I created a collection because i have some requests with no collections i suddenly all my requests disappeared. Trying to fix it using all the tricks explained before, but non worked. Very sad to loose my work. Hopefully we can solve it soon but i guess our deleted work is gone.

**Comment by ingemoody** [comment] 2023-08-15 12:56
Experienced this today. After an auto update all my data is lost. Extremely frustrating experience! I opened the application and discovered all my projects were gone on my desktop and I was logged out. No biggie I thougt so I tried to log in. This resulted to the deletion of my projects on my laptop which was already logged in. So now all the `.db` files are at default/empty. I fail to see how this issue is closed?
As you can see on the photo every single files was created after the update. This is unacceptable behaviour from an application.
<img width="466" alt="image" src="https://github.com/Kong/insomnia/assets/98735197/35772481-17d7-40ae-9291-19627f2c89ee">

**Comment by paulohliima** [comment] 2023-08-29 15:26
Hope this walkthrough helps too.
In my case, I updated my insomnia through the ubuntu snap, and I lost all the collections I had. The solution was:

1 - Go to the personal folder, enable see hidden files.
2- Enter .config/Insomnia, and copy everything inside.
3 - Go to the newly installed insomnia, and in the help tab - show app data folder.
4 - Enter insomnia, and paste everything, overwrite.
5 - Close and open insomnia and that's it.

I hope it helped you. =)

**Comment by oribens** [comment] 2023-09-26 15:44
I fixed the issue by creating a new workspace, and then I copied the wrk_xxxx id from insomnia.Workspace.db and  then replaced this ID with the old wrk_old in all files that start with insomnia*

**Comment by vhscom** [comment] 2023-09-27 21:25
Just upgraded to Insomnia 8 and boom it's all gone. But there are lots of new features! Only I can't use them now until I figure out how to restore my work and settings. Is there an official guide for this for the Insomnia 8 upgrade? There certainly was no warning before the upgrade.

**Comment by vhscom** [comment] 2023-09-27 21:26
Just upgraded to Insomnia 8 and boom it's all gone. :( But there are lots of new features! Only I can't use them now until I figure out how to restore my work and settings. Is there an official guide for this for the Insomnia 8 upgrade?

**Comment by vhscom** [comment] 2023-09-27 21:26
Just upgraded to Insomnia 8 and boom it's all gone. 😞 But there are lots of new features! Only I can't use them now until I figure out how to restore my work and settings. Is there an official guide for this for the Insomnia 8 upgrade?

**Comment by vhscom** [comment] 2023-09-27 21:36
Just upgraded to Insomnia 8 which I'd been using offline. When the app restarted it appeared as if all my data was gone. I was only able to access my existing project data after signing-in to my account and setting an E2EE password.

**Comment by vhscom** [comment] 2023-09-27 21:38
Just upgraded to Insomnia 8. When the app restarted after the upgrade it appeared as if all my data was gone. I'd kept all data offline. I was only able to access my existing data after setting an E2EE password and signing-in to the app.

**Comment by Boztown** [comment] 2023-09-27 22:44
I also upgraded to Insomnia 8. At first I didn't want to sign in so I chose "Use Scratchpad". When I did none of my data was there. I figured I was being forced to sign up now, so I did. And now still I'm back to an empty slate. I just had local data, offline. Probably about 200 requests. I didn't really ever try to back it up because it was a bit messy had a lot of endpoint stuff for old projects of mine that are defunct. But, still... there might be a nasty bug here...

**Comment by shaders** [comment] 2023-09-28 01:54
All my requests has been deleted after update to 8. All of them... gone in instant. Why did you do this? This is NOT how you do the update. This is NOT how you do the app. Time to move back to Postman.

**Comment by apeisa** [comment] 2023-09-28 08:08
~~Same happened to me. Updated insomnia (it was autoupdate of some sort), had to login (didn't like it, but whatever), created account using GitHub login, added E2EE passphrase and then - all data gone (happily used Insomnia for a year before that). Can those old requests be somewhere to be saved?~~

Ok, right after writing this I found out those under "New Document" name.

**Comment by namiwa** [comment] 2023-09-28 08:20
comment from @filfreire https://github.com/Kong/insomnia/issues/5167#issuecomment-1317415546 solves this for v8.0.0 on m2 mac

**Comment by afavieres** [comment] 2023-09-28 13:27
The version 8.0 wiped out all my requests and signing up is not an option for me. Do you have any solution for this? Once I get my data back I am never going back to Insomnia, I prefer an application that have my data in a better regards, thanks.

**Comment by NikhithVasa** [comment] 2023-09-28 15:02
> Hope this walkthrough helps too. In my case, I updated my insomnia through the ubuntu snap, and I lost all the collections I had. The solution was:
> 
> 1 - Go to the personal folder, enable see hidden files. 2- Enter .config/Insomnia, and copy everything inside. 3 - Go to the newly installed insomnia, and in the help tab - show app data folder. 4 - Enter insomnia, and paste everything, overwrite. 5 - Close and open insomnia and that's it.
> 
> I hope it helped you. =)

I dont have .config/Insomnia folder, can you help navigate to this folder? TY

**Comment by itsa-sh** [comment] 2023-09-28 15:25
I literally received a popup 20 times requesting me to "Restart and Update" or "Skip Update" so Skip doesn't work.

Post update i'm forced to create an account and login, or use local scratch pad which doesn't work, doesn't seem compatible with my older projects. This product was cleaner and simpler than Postman, now it's much worse.

**Comment by lance-nesn** [comment] 2023-09-28 15:29
Yo Kong, where are all of my env and collection settings after upgrading to 8.0?  Is it time to switch back to Postman?

**Comment by hvitoi** [comment] 2023-09-28 17:46
+1 that got all my collections wiped after a refusal to log-in. That is really nasty.

**Comment by afavieres** [comment] 2023-09-29 06:39
I have found an install for an older version. I copied the db files there and removed the scratch one with an editor as explained before in this thread. That gave me back my requests. Now I am trying to export my collection to a format that could work in other programs, but the plugins and the Har option are failing.

**Comment by josdirksen** [comment] 2023-09-29 06:41
Same for me, but apparently there was a backups folder in the `App Data` folder which contained a backup from a couple of days ago. Imported that one, and at least only lost a couple of days of work.

Moving away from Insomnia, since this product doesn't seem to be the simple REST client I liked anymore.

**Comment by egingir** [comment] 2023-09-29 13:58
I work for one of the biggest silicon valley companies. We were thinking about moving to insomnia enterprise. We all lost our saved requests in one update. We are lucky to have this disaster just before joining as a company.

**Comment by mryanprice** [comment] 2023-09-29 22:18
Forced to upgrade, lost everything.  Worst experience I've had with a dev tool in my career.  Will never use insomnia again unless there's absolutely no other option.  If I do use, my primary overriding concern will be making sure I never upgrade under any circumstances.

**Comment by bb-nik** [comment] 2023-10-02 05:22
This is a horrible experience!

Lost everything and wasted almost 2 hours trying to find new info!

How hard is it to consolidate prior work into new version!  

Here's how I fixed it...

1) Uninstall version 8 or above!  Be sure to only remove the app and not the support files.  I use use Cleanmymac which has an uninstall feature.  I left the support files which I figured has prior DB.

2) Downloaded the last update before version 8

https://github.com/Kong/insomnia/releases/tag/core%402023.5.8

3) Install

4) Everything came back. 

5) Turn off automatic updates...

<img width="781" alt="image" src="https://github.com/Kong/insomnia/assets/1457083/6fd21024-4c37-49f3-b345-8b2f3fbc13ef">

**Comment by pfleischer-intelycare** [comment] 2023-10-03 14:02
+ 1 , terrible upgrade experience, don't do it.

**Comment by benmotyka2** [comment] 2023-10-03 14:45
> https://github.com/Kong/insomnia/releases/tag/core%402023.5.8

Thank you!

**Comment by KerickHowlett** [comment] 2023-10-03 16:16
@bb-nik I applied your recommendation yesterday, which worked (despite me having installed the app through Homebrew), but when I went to use it the next day, I tried running an API call, but it didn't work for some strange reason, so I hard closed it to boot it back up, it updated itself without my permission.

And yes, I had the "Automatically download and install updated" option unchecked.

**Comment by chennighan** [comment] 2023-10-12 01:22
Just got ultra burned by this. Absolute trashware. Back to postman I go.

**Comment by sampart** [comment] 2023-10-16 14:11
I've just moved to https://www.usebruno.com which doesn't require an account and can import collections (but not environments) from Insomnia. And you can manage your Bruno collections with git!

**Comment by nathan-mill** [comment] 2023-10-19 00:03
Another "me too" post. Had to reboot and when Insomnia re-launched it updated itself and deleted absolutely everything in the process. Project data is clearly still there in Application Support but Insomnia doesn't load any of it and refuses to show me anything but the (empty) scratchpad and the nagging upsell modals. Gonna be deleting Insomnia once I figure out how to fish what I need out of the backups.

**Comment by nathan-mill** [comment] 2023-10-23 22:55
https://github.com/ArchGPT/insomnium

**Comment by kkroening** [comment] 2023-10-24 18:57
> I've just moved to https://www.usebruno.com which doesn't require an account and can import collections (but not environments) from Insomnia. And you can manage your Bruno collections with git!

Thanks for sharing that, @sampart - I just tried Bruno and it's _awesome_! Good find.

**Comment by fullheart** [comment] 2023-11-07 11:33
I too lost all requests after upgrading to Version 8.x.

I restored the requests in an other app: https://github.com/Kong/insomnia/issues/5559#issuecomment-1798326290

**Comment by ChristianEscobar** [comment] 2023-11-25 07:14
I was able to restore my lost workspace by clicking on Insomnia > Preferences then in the Data tab, under `Untracked projects` clicking on the `Select an organization` drop down, selecting my `Personal Workspace` and then clicking on the `Move` button

<img width="869" alt="image" src="https://github.com/Kong/insomnia/assets/46496129/36682f3d-78a0-4559-8134-953fbdc87c58">

**Comment by nikhiljain12** [comment] 2023-11-28 00:00
What an absolute disaster! I've been trying to recover my lost data for the last 2 hours. There was a backup file with `insomnia.Requests.db` but that seems to have been corrupted now. Insomnia is writing to all the copies of this backup file as well, I have no idea how it is doing that. The workspace/project/folder/collection organization is so confusing and messed up.

And lastly, I created a brand new collection with 1 request in it, and Insomnia created 5000 new Request records in `Requests.db`. Absolutely insane

**Comment by nathan-mill** [comment] 2023-11-29 05:57
Dig through the past issues, count the number of times the CEO has done this exact same thing over the past few years and make an educated decision.

**Comment by copiri-six** [comment] 2023-11-30 18:55
> This is a horrible experience!

+1 For that!!  What a wreck of an upgrade process.

Just chiming in to say that [this response](https://github.com/Kong/insomnia/issues/5167#issuecomment-1742415192) worked for me.  Be sure to make sure that automatic updates are turned OFF so that this dumpster fire of a program doesn't trash your data again.

I really liked Insomnia before Kong took over... but I'm really considering moving to Postman after all these "create an account so we can monetize your data" issues.

**Comment by dustinkeeton-ign** [comment] 2023-12-04 20:11
> I was able to restore my lost workspace by clicking on Insomnia > Preferences then in the Data tab, under `Untracked projects` clicking on the `Select an organization` drop down, selecting my `Personal Workspace` and then clicking on the `Move` button
> 
> <img alt="image" width="869" src="https://private-user-images.githubusercontent.com/46496129/285570889-36682f3d-78a0-4559-8134-953fbdc87c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTk3MjIsIm5iZiI6MTcwMTcxOTQyMiwicGF0aCI6Ii80NjQ5NjEyOS8yODU1NzA4ODktMzY2ODJmM2QtNzhhMC00NTU5LTgxMzQtOTUzZmJkYzg3YzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE5NTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMmYxOWYwMzY4N2ZkMmMzMTQyYjBmMTgyMzE4MjQyYjRmM2ViZTg5MTMwMTJhMzQyZDQ3ZTY5MThiOTg0ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KDYMZgH1pjKMFObyxzoF7llr1FIEKY0IbrzsnIprmZk">

This worked for me. Thanks!

**Comment by sovetski** [comment] 2024-03-18 18:01
> My solution: Create new : `Request Collection` <img alt="Screenshot 2023-01-02 at 12 40 29" width="1350" src="https://user-images.githubusercontent.com/34308289/210226560-9c56f16c-d14a-4d4f-9f99-78f7ed330298.png">
> 
> close insomnia.
> 
> open in the editor: `insomnia.workspace.db` and copy the `_id` of the newly created collection. then open `insomnia.request.db` and replace the `parent_id` with the one you've just copied. Start insomnia. In my case, all request was back. Give it the try.

Thank you man, you saved my day!!! Insomnia should fix this issue, just after login to my account, I lost everything created locally, it is a very strange and enoying experience

**Comment by OctStrike** [comment] 2024-03-28 19:10
Looks like this is still an issue today. The first time it almost happened, I found my folders and requests again. Over six months of API requests and many folders are gone due to the forced login and passphrase creation. Who thought this was a good idea? I would like to talk to them. Hundreds if not hundreds of thousands of lost hours of work when you consider how many people this happened to.

Please send times you are available to fix this issue of your own creation, Insomnia team. Thanks.

**Comment by micoraweb** [comment] 2024-07-27 12:33
Today I lost all of the requests that I was so meticulously saving for the last year. I'm a developer and I had a ton of important API requests stored for various applications, services, etc. All gone. Insomnia.. the name totally makes sense ;)

**Comment by sideeffffect** [comment] 2024-08-22 22:17
It's happened again. For the second time already. All my library has disappeared. Again. I'm moving to a different app
https://alternativeto.net/software/insomnia-rest-client/?license=opensource

**Comment by thansk** [comment] 2024-08-31 15:34
Where are my requests??? Why is moving my "untracked" project disabled?

![image](https://github.com/user-attachments/assets/26000c5c-d7cb-47e1-bc86-ca73841049a9)

**Comment by micoraweb** [comment] 2025-01-14 19:41
Everything disappeared again. By now, this product has caused me more harm than good to be honest. It's too bad, actually because I do like it and instead of deleting it, I will keep it for some quick tests that don't need a long term persistence. Otherwise be warned, all the saved requests will be gone!

**Comment by fullheart** [comment] 2025-01-14 21:35
I lost also all saved requests. Therefore I left Insomnia and switched to Bruno: https://github.com/usebruno/bruno

**Comment by tmanley1985** [comment] 2025-01-14 21:47
> I lost also all saved requests. Therefore I left Insomnia and switched to Bruno: https://github.com/usebruno/bruno

I moved to Bruno too. It's a shame because I really liked the UI and overall experience of Insomnia.

**Comment by robclancy** [comment] 2025-03-07 01:26
> > I lost also all saved requests. Therefore I left Insomnia and switched to Bruno: https://github.com/usebruno/bruno
> 
> I moved to Bruno too. It's a shame because I really liked the UI and overall experience of Insomnia.

The original insomnia creator made something new because they ruined what he made. This comment is probably going to be deleted like others today that mentioned it so I won't say it or link it.

**Comment by Arborescent** [comment] 2025-09-25 03:53
Another solution:

1. Open `insomnia.Request.db`
2. Paste the contents into ChatGPT, Claude, etc.
3. Ask it to convert it into an OpenAPI specification
4. Import it into Insomnia or your tool of choice (example: Bruno, Postman, IntelliJ)
5. Always keep a backup in OpenAPI specification format in the future
