### ISSUE TITLE
MY COOKIE I NOT WORKING CAUSING ALL MY API FAILED IT WAS  WORKING FINE PREVIOUSLY BUT TODAY NOT WORKING 

### ISSUE THREAD

**Issue by Nimraa01** [getinsomnia/insomnia#7616] opened 2024-06-28 13:54 UTC
### Expected Behavior

Error: [object Object] at Object.validate (C:\Users\DELL\AppData\Local\insomnia\app-9.3.0\resources\app.asar\node_modules\tough-cookie\lib\validators.js:91:13) at formatDate (C:\Users\DELL\AppData\Local\insomnia\app-9.3.0\resources\app.asar\node_modules\tough-cookie\lib\cookie.js:322:14) at Cookie.toString (C:\Users\DELL\AppData\Local\insomnia\app-9.3.0\resources\app.asar\node_modules\tough-cookie\lib\cookie.js:952:29) at wS1 (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:110:16004) at Ze (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/workspace-environments-edit-modal-Bf0HPEMW.js:1:16292) at Ok (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:43:17033) at NK (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:44104) at kK (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:39822) at Z9e (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:39748) at Yh (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:39598) at ME (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:35960) at EK (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:34907) at L (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:30:1594) at Immediate.oe [as _onImmediate] (file:///C:/Users/DELL/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:30:1965) at process.processImmediate (node:internal/timers:478:21)I WANT TO FIX IT PLEASE

### Actual Behavior

..

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

NO

### Insomnia Version

9.3

### What operating system are you using?

Windows

### Operating System Version

WINDOW

### Installation method

DOWNLOAD FROM WEBSITE

### Last Known Working Insomnia version

3.9

**Comment by IfWeCodeGregory** [comment] 2024-06-28 14:14
+1

**Comment by IfWeCode-EtienneCandat** [comment] 2024-06-28 14:21
Same problem for us, the application crashes when we click on "Manage cookies" and the cookies are no longer sent. After closing the application and reopening it, I can access the "Manage cookies" window, but as soon as I send a request, the behavior returns to the same level. This is very annoying, as we can no longer request our API from Insomnia.

**Comment by redbaran** [comment] 2024-06-28 14:32
This is a duplicate of #7604

**Comment by Nimraa01** [comment] 2024-06-28 14:57
Please tell me how to solve this problem my uni project is pending

**Comment by redbaran** [comment] 2024-06-28 15:25
1. Turn off automatic updates (Application>Preferences)
2. Install the 9.2 version: 
https://github.com/Kong/insomnia/releases/tag/core%409.2.0
https://github.com/Kong/insomnia/releases/download/core%409.2.0/Insomnia.Core-9.2.0.exe

**Comment by gatzjames** [comment] 2024-06-28 16:31
Thanks for the feedback. Closing as this was fixed in 9.3.1

**Closed as completed by gatzjames** 2024-06-28 16:31 UTC
Labels: B-bug, S-unverified
