### ISSUE TITLE
Request filter does not show requests present in the resulted folder 

### ISSUE THREAD

**Issue by Deepika-Malik** [getinsomnia/insomnia#6588] opened 2023-09-28 11:01 UTC
### Expected Behavior

All the requests that are part of the folder that we is filtered by keyword appear in the results. It was happening earlier but with releases in Sept, it stopped showing the requests inside the folder. It only shows folder. 

This beats the purpose of adding a group requests in a folder.

### Actual Behavior

Only the folder appears in the results when filtered by typing in request filer.
For example : Following are the screenshots of filtering - there is a user folder that contains its CRUD API requests but they are not shown in the filter.
<img width="367" alt="Screenshot 2023-09-28 at 4 22 05 PM" src="https://github.com/Kong/insomnia/assets/13562804/ab51af4b-2832-48cb-a020-2bdf63851cfb">
<img width="367" alt="Screenshot 2023-09-28 at 4 22 32 PM" src="https://github.com/Kong/insomnia/assets/13562804/2c4ffd93-c263-48ff-9a21-5111ac900f58">
Following are the requests that are part of user folder.
<img width="364" alt="Screenshot 2023-09-28 at 4 23 29 PM" src="https://github.com/Kong/insomnia/assets/13562804/744b0a11-94bf-44a2-b811-a4198137d2a4">

Earlier all the requests in a folder would be displayed in filter results but no longer. It has become a pain for such requests that were grouped in folders. There is no point in grouping requests in folder anymore.

### Reproduction Steps

Check the actual behaviour section

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 8.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey version 12.7

### Installation method

Download from Insomnia website.

### Last Known Working Insomnia version

Insomnia 2023.5.5

**Comment by filfreire** [comment] 2023-09-28 11:05
@Deepika-Malik thanks for reporting this, marking it as a duplicate of #6494, we'll be fixing it as soon as possible.

**Closed as completed by filfreire** 2023-09-28 11:05 UTC
Labels: B-bug, S-unverified
