### ISSUE TITLE
Sub-environment variables don't work with gRPC

### ISSUE THREAD

**Issue by dpclark4** [getinsomnia/insomnia#3221] opened 2021-03-22 22:29 UTC
**Describe the bug**
I recently discovered that the latest version of Insomnia supports environment variables; however I am unable to get this to work. When I put in an environment variable of `127.0.0.1:6565` and attempt to use this, nothing happens in the UI (there are errors in the dev console). If I directly paste `127.0.0.1:6565` in, it works as expected (old behavior). I have tried downgrading to 2020.1.0 but that doesn't fix the issue either. 

**To Reproduce**
In the environment tab, add a new variable. Fill that variable in and make a gRPC request.

**Expected behavior**
The request should be successful, but it is not

**Screenshots**
(These are intentionally cropped)
![image](https://user-images.githubusercontent.com/3443935/112065748-97bcdb80-8b3b-11eb-8655-6fca05afadf5.png)
![image](https://user-images.githubusercontent.com/3443935/112065781-a905e800-8b3b-11eb-8d35-29272feac8b7.png)
![image](https://user-images.githubusercontent.com/3443935/112066092-24679980-8b3c-11eb-93e8-ec1155e50bd9.png)

![image](https://user-images.githubusercontent.com/3443935/112066053-144fba00-8b3c-11eb-9b1f-a85899e1ff57.png)

**Desktop (please complete the following information):**
Version: Insomnia 2021.1.1
Release date: 3/9/2021
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0

**Additional context**
Error message:
```
18:24:20.309 › Unhandled Promise PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: Error: attempted to output null or undefined value
    at file:///Applications/Insomnia.app/Content…, type: "unhandledrejection", target: global, …}bubbles: falsecancelBubble: falsecancelable: truecomposed: falsecurrentTarget: global {parent: global, opener: null, top: global, length: 0, frames: global, …}defaultPrevented: falseeventPhase: 0isTrusted: truepath: [global]promise: Promise__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: Error: attempted to output null or undefined value
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:37548:26
    at /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nunjucks/src/environment.js:41:5
    at RawTask.call (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/asap/asap.js:40:19)
    at flush (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)location: {line: 1, column: 1}path: "url"reason: "undefined"type: "render"message: "attempted to output null or undefined value"stack: "Error: attempted to output null or undefined value↵    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:37548:26↵    at /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nunjucks/src/environment.js:41:5↵    at RawTask.call (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/asap/asap.js:40:19)↵    at flush (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/asap/raw.js:50:29)↵    at processTicksAndRejections (internal/process/task_queues.js:76:11)"__proto__: Errorreason: Error: attempted to output null or undefined value
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:37548:26
    at /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nunjucks/src/environment.js:41:5
    at RawTask.call (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/asap/asap.js:40:19)
    at flush (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)returnValue: truesrcElement: global {parent: global, opener: null, top: global, length: 0, frames: global, …}target: global {parent: global, opener: null, top: global, length: 0, frames: global, …}timeStamp: 595062.414999993type: "unhandledrejection"__proto__: PromiseRejectionEvent
setTimeout (async)
consoleLog @ /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/electron-log/src/transports/console.js:93
transport @ /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/electron-log/src/transports/console.js:46
runTransport @ /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/electron-log/src/log.js:44
runTransports @ /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/electron-log/src/log.js:27
log @ /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/electron-log/src/log.js:21
```

**Comment by develohpanda** [comment] 2021-03-22 23:04
Thank you for reporting this! I am able to reproduce it. 

There are three places an environment variable can be defined - the base environment, a sub environment, or a folder environment. gRPC seems to resolve variables from both the base environment and folder environments correctly, but I see strange behavior with sub-environments.

While testing it I see two interesting (and I think related) behaviors:
- if my `grpcHost` variable exists in both the base environment and the sub environment, and the sub environment is selected, the request works but the actual request execution resolves the variable from the base env, it should resolve from the sub env.
- if my `grpcHost` variable exists only in the sub environment, regardless of which environment is selected, the request fails in the above manner.

It seems like when resolving variables for actually executing a request, it's not consuming the sub environment correctly.

**Comment by dpclark4** [comment] 2021-03-22 23:08
@develohpanda thanks for helping me with a work around! I can confirm that this workaround works on 2020.1.alpha2 (I have tried all of the recent versions including 2020.2 alpha).

**Comment by develohpanda** [comment] 2021-03-22 23:09
No worries! We will certainly look to resolve this though, it's not working as intended. 🤗

**Comment by dpclark4** [comment] 2021-03-22 23:12
I misread your post. It seems that this isn't a work around (always resolves the base). Hopefully this is not too hard of an issue to address. I'm a big fan of the recent gRPC support nonetheless!

**Comment by cwscott246** [comment] 2021-04-07 21:27
I've also noticed this and was wondering when it might be fixed? Love using the tool!!

**Comment by jamesmazur** [comment] 2021-06-10 15:20
@develohpanda I'm also encountering this issue - any updates?

**Comment by develohpanda** [comment] 2021-06-10 19:16
Hi @jamesmazur, sorry no timeline as yet, but we have disabled statelbot for the time being so it won't close this ticket, as it is valid.

**Comment by naturetime10** [comment] 2021-06-11 02:50
I have faced the same issue with Insomnia regarding env

**Closed as completed** 2021-07-26 00:49 UTC
Labels: B-bug, A-grpc
