### ISSUE TITLE
[Bug] Unable to copy large strings from request and response body

### ISSUE THREAD

**Issue by jetauriello** [getinsomnia/insomnia#442] opened 2017-08-16 22:58 UTC
- Insomnia Version: 5.7.11
- Operating System: Windows 10

## Details
If you attempt to copy a large string of content from the main request/response windows and then paste the contents to another location or application the result is a single hyphen "-" character.

**Comment by gschier** [comment] 2017-08-16 23:03
This is a duplicate of #430 and was fixed in 5.7.12
https://insomnia.rest/changelog/5.7.12/

**Closed** 2017-08-16 23:03 UTC
