### ISSUE TITLE
[Question] Use Custom curl?

### ISSUE THREAD

**Issue by kzap** [getinsomnia/insomnia#302] opened 2017-06-12 06:54 UTC
## Overview
- `Insomnia Version:` 5.2.0.434
- `Operating System:` MacOS 10.12.3 (16D32)
- `Summary: ` Developing locally I am unable to cURL a local HTTPS address because of the certificate. I installed cURL from brew to solve this and put it in my PATH but Insomnia still uses the default cURL from OSX, is there any way to get Insomnia to use a different path for cURL?

## How To Reproduce
_Please list all pertinent information and steps needed to reproduce the issue. For example:_
1. cURL from terminal: ```
$ curl --request GET   --url https://api.local.dev/endpoint -k
curl: (56) SSLRead() return error -9841```
2. Install curl via brew and put into path `brew install --with-openssl curl`
3. Try it again via terminal and it works.
4. Try via Insomnia and it still gets the `curl: (56) SSLRead() return error -9841` error

**Comment by gschier** [comment] 2017-06-12 20:23
@kzap first off. Have you tried toggling the "Validate SSL certificates" setting?

I'm not an expert with brew, but I'm guessing that it installs `curl` and it's dependencies (`libcurl`, `zlib`, etc) in a brew-specific directory. In order for it to be picked up by Insomnia, you will have to overwrite the global version of Curl and all of its libraries with the one from brew.

**Comment by kzap** [comment] 2017-06-16 04:39
Hi @gschier Yes I am not validating SSL certs. I know I can fix the problem by overwriting the global curl but I prefer not to do this and break Apple's OSX, same as why brew does not do this.

A simple path to curl setting could help this, you may need to assume not all cURLs are created equal and some person on some system maybe want to use a different cURL from the one on their system.

I will try to make a PR :)

**Comment by gschier** [comment] 2017-06-16 04:43
There is probably an environment variable you can set to tell NodeJS to load native add-on libraries from a different location. I'd be happy to take a look at a PR if you figure it out. I agree that it would be awesome if users could override the curl version. 👍

**Comment by kzap** [comment] 2017-06-21 02:09
I've looked at the code, its not using native curl...

You use node-libcurl which uses node-pre-gyp which can either build curl from source or use a prebuilt binary and has node binding which allow you to use the C++ binary with nodejs.

The prebuilt binaries are taken from https://github.com/JCMais/node-libcurl/releases
and bundled into the electron binary when built....

so basically its not about changing the path to curl, the app uses a builtin nodeilbcurl binary which is built using curl from source or from the local libs on the build machine...

**Comment by gschier** [comment] 2017-06-21 02:47
Thanks for the info @kzap. However, I don't think it's entirely correct.

node-libcurl only bundles its own copy of the library for Windows (static linking) because most Windows users don't typically have Curl installed. For Linux and Mac, node-libcurl builds curl using dynamic linking, which requires the user to have the library (and dependency libraries) available. I've had to explicitly add `libcurl` as a package dependency for Insomnia to work on Arch Linux as well as some Ubuntu variants. I've also heard from users on older versions of OSX have the app crash because their libcurl version was too old.

I'm not sure if that helps at all, but I'm 98% sure that Insomnia _is_ using the curl library from `/usr/lib/libcurl.dylib`. After a bit of searching, I don't think it's easy to force OSX to look somewhere else for dynamic libraries.

**Comment by LouisStAmour** [comment] 2017-06-24 06:57
You can hack operating systems when launching apps to look for dynamic libraries elsewhere, but looking at how the build process works, one of the easiest ways might be to override the `curl-config` command by ensuring that the version Homebrew installs, at `/usr/local/opt/curl/bin/curl-config` is available for this script to find: https://github.com/JCMais/node-libcurl/blob/master/tools/curl-config.js

Edit: Never mind, that won't work. Well, you could use `brew link curl` to force curl to be linked by homebrew into the standard paths under /usr/local. Otherwise the supported method appears to be to modify your path to add `/usr/local/opt/curl/bin/` to the start of it, while running the node install for the libcurl bindings.

**Comment by LouisStAmour** [comment] 2017-06-24 17:35
In regards to compiling node-libcurl against custom locations, having tried multiple ways of setting the ENV PATH variable for this compilation, I’ve discovered electron-rebuild isn’t flexible enough and node-pre-gyp is confusing. So the easiest way to get the job done is to continue maintaining a fork of libcurl as you’re doing now, adding the option to change the location of curl-config? Alternatively, second easiest is to reproduce the behaviour of node-pre-gyp and node-gyp as invoked by electron-rebuild, or to fork electron-rebuild and add PATH next to the HOME env. Last option (perhaps least preferable), save PATH, then export a new copy of PATH with homebrew curl added, do the rebuild, then reset path as it was...

**Comment by gschier** [comment] 2017-06-26 18:55
@LouisStAmour you are correct. A custom curl version can be used during the build process by making sure the `curl-config` command of the version you want is in your PATH. I've done this successfully in the past. More info on the [`node-libcurl`](https://github.com/JCMais/node-libcurl/#linux) repo. Note that the version of curl you want still has to be built with shared libraries enabled (not static libraries) because `node-libcurl` expects that.

Another thought... I think the Mac version of Insomnia is really the only one that users may want to swap out (because of some restrictions with Apple's Secure Transport). Maybe we could provide an OpenSSL-built version of Insomnia in addition to the Secure Transport version for Mac users to download?

**Comment by gschier** [comment] 2017-06-30 03:35
Closing this issue for now, but feel free to keep the discussion going if you'd like

**Closed by gschier** 2017-06-30 03:35 UTC
