### ISSUE TITLE
Failed to install because "No license field"

### ISSUE THREAD

**Issue by Miuler** [getinsomnia/insomnia#4041] opened 2021-09-20 14:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.3

### What operating system are you using?

Other Linux

### Operating System Version

LSB Version:    1.4 Distributor ID: Garuda Description:    Garuda Linux Release:        Soaring Codename:       Bateleur

### Installation method

paru -S  aur/insomnia-bin

### Expected Behavior

Install a plugin insomnia-plugin-kong-bundle from insomnia hub.

### Actual Behavior

But when I try to install insomnia-plugin-kong-bundle or any another plugin, show the message the error: "No license field"

![imagen](https://user-images.githubusercontent.com/9974/134022435-855b1d1f-3881-4ee9-a940-fa7748ce8501.png)

**Comment by dimitropoulos** [comment] 2021-09-20 15:03
Thanks for the report -> I was unable to reproduce on Kubuntu 21.04.

![Screenshot_20210920_110149](https://user-images.githubusercontent.com/15232461/134025257-bc08068c-8658-4d3e-a13e-03b589b27dd7.png)


This is strange because this plugin does indeed have a license field https://github.com/Kong/insomnia/blob/develop/plugins/insomnia-plugin-kong-bundle/package.json#L6.

I've never run Garuda before, but my next steps would be to open it up in virtualbox and go through the steps.  Any things I might like to know before I do that?  Any tips on how to replicate your environment?

And that aside, could you say a little more about what the specific reproduction steps are so I can take those exact steps?  Thanks!

**Comment by develohpanda** [comment] 2021-09-21 21:26
Hi @Miuler! This plugin bundle is pre-installed within Insomnia now, so you shouldn't need to install it manually from the plugins tab 😄 We also have an open-source PR in the works (https://github.com/Kong/insomnia/pull/4039) to allow for unsafe plugin installation as sometimes it fails on a warning as well.

I'll go ahead and close this issue for now, but please ask if you have any other questions!

**Closed as completed by develohpanda** 2021-09-21 21:26 UTC
Labels: B-bug, S-unverified

**Comment by hockeymikey** [comment] 2022-04-14 22:24
I too am dealing with this bug and on any plugin install it fails out with the message.

**Comment by hockeymikey** [comment] 2022-04-15 17:17
![Screenshot_20220415_121641](https://user-images.githubusercontent.com/1435185/163600789-e565be43-8642-4f38-8cfd-11cefb2f9a6c.png)

**Comment by JorgeSanzS** [comment] 2022-04-29 10:01
I have the same problem. Happens with all plugins

**Comment by TheAnarchoX** [comment] 2022-05-11 08:10
same here, can't install any plugins on Windows 10 running the Free edition

**Comment by mattburdumy** [comment] 2022-11-07 22:37
I'm getting this bug now on Ubuntu 20.04 -- installing any plugin at all.

**Comment by remoharsono** [comment] 2022-12-24 08:26
I've got similar message, it turns out that I have package.json on my home directory (yes, I mistakenly create a temporary project at my home directory), after deleting package.json then the message dissapeared. A friend of mine got similar problem and he successfully fix it by adding private:true to package.json

**Comment by enias-oliveira** [comment] 2023-03-02 02:43
@remoharsono Just saved me a bunch of headaches

**Comment by Geromo94** [comment] 2023-03-13 03:03
> У меня похожее сообщение, оказывается, у меня есть package.json в моем домашнем каталоге (да, я по ошибке создал временный проект в своем домашнем каталоге), после удаления package.json сообщение исчезло. У моего друга возникла аналогичная проблема, и он успешно решил ее, добавив private:true в package.json.

hello, how fix that on Windows 10? :(

**Comment by gribanoveu** [comment] 2023-10-23 07:44
> hello, how fix that on Windows 10? :(

delete package.json and package-lock from C:\Users\\{you windows username}
