### ISSUE TITLE
New macOS icon too big

### ISSUE THREAD

**Issue by SpicySpaceman** [getinsomnia/insomnia#5928] opened 2023-04-28 14:20 UTC
### Expected Behavior

It should have the same size as the other native Apple icons

### Actual Behavior

The icon is bigger than the native Apple icons:

![image](https://user-images.githubusercontent.com/10995998/235173036-002c88e7-a65c-4d46-903a-aab70c705bd7.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Related to #5867

### Insomnia Version

2023.2

### What operating system are you using?

macOS

### Operating System Version

macOS 13.3.1

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment] 2023-04-28 15:24
duplicate of #5922

**Closed as completed by filfreire** 2023-04-28 15:24 UTC
Labels: B-bug, S-unverified
