### ISSUE TITLE
[Feature Request] Individual contextual environments

### ISSUE THREAD

**Issue by SiebeSysmans** [getinsomnia/insomnia#579] opened 2017-11-09 09:05 UTC
It would be nice to be able to not only switch an environment, but also user, version, ... or other configurable contexts you wish to switch.

Right now, if I have an environment _x_ and _y_, and user _a_ and _b_. I have to create environments _xa_, _ya_, _xb_ and _yb_. This solution gets worse if you also have to switch version, platform, ...

Here is an example of how Paw handles these environment switches.
<img width="230" alt="screen shot 2017-11-09 at 10 02 04" src="https://user-images.githubusercontent.com/1453276/32596885-1bec2df0-c535-11e7-95e3-d16ba225236e.png">

Hope I explained this clearly.

**Comment by gschier** [comment] 2017-11-09 09:42
Yep, that makes sense. This is actually a duplicate of #283

**Closed by gschier** 2017-11-09 09:42 UTC
