### ISSUE TITLE
Variables not clickable in OSX

### ISSUE THREAD

**Issue by jamesgkong** [getinsomnia/insomnia#8140] opened 2024-10-29 15:52 UTC
### Expected Behavior

In the Collections view when a variable is inserted into a URL or elsewhere in the UI this should be a clickable element which presents a pop-up dialog allowing for variable selection or edits as per screen-shots below:

1. Variable is clickable:
![image](https://github.com/user-attachments/assets/1cd78ba3-1079-4943-ad1e-bf79e2dbe75d)

2. when clicked a dialog is presented to edit key and values: 
![image](https://github.com/user-attachments/assets/03064c82-c940-4926-80a6-08d5a9f1c579)

### Actual Behavior

This seems to be working fine in Windows:
![image](https://github.com/user-attachments/assets/fc764925-9645-4421-a4a9-25be68d9b761)

and Ubuntu 22.04:
![image](https://github.com/user-attachments/assets/4b7cc562-aaf6-4d2c-8dbe-a1ec9485c1c1)

However the variables are not a clickable area in OSX and display differently:
![image](https://github.com/user-attachments/assets/7ab5db26-226c-4564-ad26-21b3b39adf86)

### Reproduction Steps

1. Create a Collection on OSX machine.
2. Add Environment variables.
3. Populate some data into a Request and insert a variable.
4. Variable is not clickable element.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.1.1

### What operating system are you using?

macOS

### Operating System Version

OS: Darwin arm64 23.6.0

### Installation method

Downloaded installer

**Comment by cwangsmv** [comment] 2024-10-30 02:18
@jamesgkong Could you please check If you have enabled "Raw template syntax" option in Insomnia Preferences?
<img width="429" alt="Screenshot 2024-10-30 at 10 16 29" src="https://github.com/user-attachments/assets/adb75ba6-2342-4af0-ba94-4c75bb93236b">
The variables should be clickable if you disable this option.

**Comment by notjaywu** [comment] 2024-10-30 03:41
Duplicate of #7787

**Closed as completed by notjaywu** 2024-10-30 03:41 UTC
Labels: B-bug, S-unverified
