### ISSUE TITLE
Use Vertical Layout not working

### ISSUE THREAD

**Issue by josueal1** [getinsomnia/insomnia#5835] opened 2023-03-10 16:58 UTC
### Expected Behavior

trying enable the checkbox "use vertical layout"  so Response section to the right of Request section

### Actual Behavior

Request section is horizontal  above the the response section (this is the default view after download)

### Reproduction Steps

1.  download insomnia 2023.1.0
2. open a collection
3. notice the image like so: 
![B78E33CA-E266-4115-B91E-EA1FE1E5A26F](https://user-images.githubusercontent.com/30352270/224376145-834a4787-00d6-49ce-88ae-9e7ce2c552d7.jpeg)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Mar 10, 2023 i downgraded to v2022.7.5 and this checkbox toggle works instantly

### Insomnia Version

2023.1.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.1

### Installation method

insomnia.rest

### Last Known Working Insomnia version

2022.7.5

**Comment by merc1er** [comment] 2023-03-17 06:37
I have the exact same issue. Seems like it is a regression in version `2023.1.0`.

**Comment by 0x524c** [comment] 2023-03-18 17:23
The same here. I need to downgrade for now.
Running on MacOs Ventura.

**Comment by robwent** [comment] 2023-03-21 14:52
A few days ago I was stuck with horizontal layout.

Testing again today, it seems that the checkbox is the opposite of the label.
When 'use vertical layout' is checked it's horizontal, when unchecked it's vertical.

**Comment by 0x524c** [comment] 2023-03-21 17:55
I also thought that was it. But with a checkbox checked or not, the result doesn't change. I needed to go back to an old version, 2022.7.5.

**Comment by robwent** [comment] 2023-03-21 19:54
@524c  That was my experience at first as well. I just tried updating my laptop and I'm seeing the same there.

![orient](https://user-images.githubusercontent.com/411678/226725638-9e806a7a-62bf-4b76-b34d-f40c2043489c.gif)

![about](https://user-images.githubusercontent.com/411678/226725703-d55588a9-2f09-4f06-b4ba-e2c266bf1dde.PNG)

**Comment by merc1er** [comment] 2023-03-22 02:11
> @524c  That was my experience at first as well. I just tried updating my laptop and I'm seeing the same there.
> 
> 
> 
> ![orient](https://user-images.githubusercontent.com/411678/226725638-9e806a7a-62bf-4b76-b34d-f40c2043489c.gif)
> 
> 
> 
> ![about](https://user-images.githubusercontent.com/411678/226725703-d55588a9-2f09-4f06-b4ba-e2c266bf1dde.PNG)
> 
> 
> 
> 
> 
> 

The issue only happens on small window sizes. Try reducing the width of your window and you will see it is stuck on vertical layout.

**Comment by robwent** [comment] 2023-03-22 11:18
@merc1er That's true. Reducing the width forces the horizontal layout.

The checkbox option is still the opposite of the expected behaviour though.

**Comment by joaohenriquearaujo** [comment] 2023-03-23 21:28
Just updated to the latest version and noticed the same behavior.
The option "user vertical layout" doesn't work as expected.

**Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Darwin arm64 22.3.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64**

**Comment by joaohenriquearaujo** [comment] 2023-03-23 21:30
Just updated to the latest version and noticed the same behavior.
The option "user vertical layout" doesn't work as expected.

Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Darwin arm64 22.3.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64

**Comment by joaohenriquearaujo** [comment] 2023-03-23 21:31
Just updated to the latest version and noticed the same behavior.
The option "user vertical layout" doesn't work as expected.

**Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Darwin arm64 22.3.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64**

**Comment by CorbyC** [comment] 2023-03-30 15:35
Also experiencing the layout not changing when the vertical layout checkbox is checked or unchecked.

Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Darwin arm64 21.6.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64

**Comment by Foohx** [comment] 2023-04-18 09:50
Same for me : 

Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Darwin x64 22.2.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by 0x524c** [comment] 2023-04-27 12:54
It still doesn't work in the latest version.

Impossible to use on notebooks with small screens (13"). 

Version: Insomnia 2023.2.0
Build date: 4/26/2023
OS: Darwin x64 22.1.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by Foohx** [comment] 2023-04-27 13:04
The problem seems to come from the beakpoint for layout switching. They must have changed the value.

Start by checking that "Use vertical layout" is not checked in your preferences.

Then you can correct the problem by simply zooming out a bit your UI.
- Windows/Linux: `Ctrl` + `-` (not sure about the shortcut)
- Mac: `Cmd` + `-`

**Comment by CorbyC** [comment] 2023-04-27 14:49
Foohx you're my hero! That did work for me.

**Comment by merc1er** [comment] 2023-04-27 16:09
> Then you can correct the problem by simply zooming out a bit your UI.

The issue with that is that the text becomes too small and barely legible. But I guess that's a valid workaround on some screen types.

**Comment by 0x524c** [comment] 2023-04-30 22:12
> > Then you can correct the problem by simply zooming out a bit your UI.
> 
> The issue with that is that the text becomes too small and barely legible. But I guess that's a valid workaround on some screen types.

@merc1er, @Foohx, I don't know why it always worked before, but a zooming out "fix" the problem and the vertical layout came back 🙏 Thanks!

Hey @filfreire, how are ayou?
When this bug is prioritized, I'll be happy to help with any testing you need on MacOS. I'm using it on a 13" Macbook air.

**Comment by KKghub** [comment] 2023-05-22 08:34
I have tried zooming in/out and changing the `Use vertical layout` checkbox to checked/unchecked and still cannot make response section come to the right.
I am on macOS (with `Larger Text` in display settings), and this is the first time I am using Insomnia and I am having trouble seeing the Graphql variables properly in vertical layout. hence I would like to see response in the right section with divider.

In postman graphql variables are on right and response is at bottom which is still okay. Will stick with postman for now I guess until this issue is fixed...

Here is Insomnia version info:
```text
Version: Insomnia 2023.2.2
Build date: 5/17/2023
OS: Darwin x64 21.6.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64
```

**Comment by LCSLITX** [comment] 2023-06-01 15:48
I don't know if this has been updated but apparently there's a misunderstanding about this feature.

```
Version: Insomnia 2023.2.2
Build date: 5/17/2023
OS: Linux x64 5.19.0-42-generic
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64
```

![Screenshot from 2023-06-01 12-32-41](https://github.com/Kong/insomnia/assets/58364540/58812d1a-e04e-43fd-9c73-7d1c8e43513e)

As we can see:

- While checked (Vertical), the option is supposed to stack Request and Response panels. Request to the top and Response to the bottom.
- While unchecked (Horizontal), the option (was supposed to) put both panels side-to-side. Request to the left and Response to the right.

Vertical or Horizontal terms are not related to the layout of one panel individually, but to the arrangement of both of them.

That said, I was also struggling with this problem, Checking or Unchecking this option didn't change nothing.

It seems that the problem is related to auto adjust based on window width/zoom. Smaller width and/or bigger zoom will automatically adjust to vertical layout.

And while there is an option to force vertical layout (which is already the standard one), there's no option to force the horizontal. The unchecked box do not force horizontal, opposite to what is possible to deduce.

Maybe having options to choose what layout to force would solve this issue?

**Comment by sindelio** [comment] 2023-07-24 15:54
Is there a solution for this? It's quite annoying

**Comment by mastazi** [comment] 2023-08-11 06:01
@sindelio my solution for now is downloading the last release that did not have the issue from here https://github.com/Kong/insomnia/releases/tag/core%402022.7.5 and disable software updates. In the meantime I'm keeping an eye on this ticket.

**Comment by sindelio** [comment] 2023-08-14 15:47
@mastazi That works for now, thx

**Comment by sindelio** [comment] 2023-08-25 22:48
I would very much like to see this fixed, Insomnia keeps updating and the bug comes back

**Comment by jackkav** [comment] 2023-10-31 13:47
It seems this issue is caused by unclear language in the checkbox description. Horizontal/Vertical vs column/row
Layout rules:
Use vertical layout: Checked
This will show request and response in a single column.
Use vertical layout: Unchecked
This will show request and response in a single row above 1200px, below this width, layout will be in a single column.

This approach allows us to use more horizontal screen space for tabs and such.

I've made a PR to update the tooltip to clarify this behaviour #6739

**Closed as completed by jackkav** 2023-10-31 13:47 UTC
Labels: B-bug, S-unverified

**Comment by mastazi** [comment] 2023-10-31 20:52
@jackkav regardless of language the problem is that on smaller screens (e.g. MacBook Pro 14") changing the setting doesn't do anything (unless you play around with zoom level but then the text becomes too small). At least this was true until recently. Like many others in this thread I disabled updates on my Mac, but I could re-enable and test if a fix is out, please advise.

**Comment by mastazi** [comment] 2023-10-31 21:05
@jackkav specifically this part of your comment is not true for me and the other people in this thread 

> Use vertical layout: Unchecked
This will show request and response in a single row above 1200px, below this width, layout will be in a single column.

We still see request and response in a single column with the setting unchecked

**Comment by subnetmarco** [comment] 2023-11-01 15:04
Hello everyone - I am trying to understand better what's happening here.

This is the standard layout with "Use vertical layout" **unchecked**:

<img width="1724" alt="Screenshot 2023-11-01 at 10 59 58 AM" src="https://github.com/Kong/insomnia/assets/964813/d8ade950-abf8-43e8-aaea-068db1e4d648">


And this is the layout with "Use vertical layout" **checked**:

<img width="1721" alt="Screenshot 2023-11-01 at 11 00 05 AM" src="https://github.com/Kong/insomnia/assets/964813/07cd4b3d-1742-4d75-bf6e-8da82d8ff043">


It seems that the layout is changing accordingly to the "Vertical" setting, with the response section on the right when **unchecked**, and the response section below (in a vertical stacked position) when **checked**.

When the screen size is too small, the application defaults to a vertical stacked layout by default (even when the "Use vertical layout" setting is unchecked) because there wouldn't be enough space to show all the columns otherwise. I seem to understand that this is the objection?

**Comment by mastazi** [comment] 2023-11-01 19:28
@subnetmarco 

> [...]  the layout is changing accordingly to the "Vertical" setting, with the response section on the right when unchecked, and the response section below (in a vertical stacked position) when checked.

Correct

> When the screen size is too small, the application defaults to a vertical stacked layout by default (even when the "Use vertical layout" setting is unchecked) because there wouldn't be enough space to show all the columns otherwise. 

Not true, there is plenty of space, download https://github.com/Kong/insomnia/releases/tag/core%402022.7.5 on a 13" Mac and see for yourself. The side-by-side layout is superior in all screen sizes because you can see more lines of JSON with less scrolling, it's one of the reasons I switched from Postman

> I seem to understand that this is the objection?

The objection is that before this checkmark existed we could have the side-by-side layout all the time, regardless of screen size and now this is impossible unless reverting to the old version of Insomnia.

**Comment by robwent** [comment] 2023-11-01 19:48
This is really weird..
People just want the same behaviour as it was before.
It seems that someone changed something because they thought it would be better for small screens, but those changes defied the options.

**Comment by mastazi** [comment] 2023-11-01 20:43
@robwent If enough folks are interested we could fork Insomnia, we would keep merging all the other updates from upstream, except the Postman-like layout. It would be better than being stuck on an 18-month-old version I guess?

**Comment by subnetmarco** [comment] 2023-11-02 11:26
@mastazi What does this have to do with the current issue we are discussing? 

If you want to contribute a fix on the layout problem we are discussing, you are welcome. If you want us to attempt to fix it, you need to have patience as we go through the issue. If you want to fork the project and fix this issue there, let us know when you do that so we can also merge the fix here.

**Comment by mastazi** [comment] 2023-11-08 01:48
@subnetmarco insomnia is open source, yes?  So what's wrong with forking? 

Your previous comment from Nov 2nd read like "this is working as designed by our team" so in that case forking would be the logical solution, I don't see what's wrong with that.

> If you want to contribute a fix on the layout problem we are discussing, you are welcome.

It seemed you did not want the fix to happen as I explained above.

>  If you want us to attempt to fix it, you need to have patience as we go through the issue.

I don't want you to do anything, I don't pay you and I have no say in how you use your time.

> If you want to fork the project and fix this issue there, let us know when you do that so we can also merge the fix here.

This is obvious, it's just how open source works.

**Comment by sindelio** [comment] 2024-04-23 16:34
Still seeing the same behavior, no matter what setting is employed. My scren is quite big, however the request and response panels are always stackd on top of each other. Rolling back to version 2022.7.5 works. @subnetmarco are there any plans to fix this?

**Comment by jackkav** [comment] 2024-04-25 09:33
<img width="326" alt="image" src="https://github.com/Kong/insomnia/assets/3679927/3fa6745d-11a0-4a98-a280-5f339c190af6">

**Comment by subnetmarco** [comment] 2024-04-25 13:33
@jackkav Is there any reason why we cannot reduce the `880px` threshold to better accommodate smaller screen sizes? I suggest we change it to `760px` to better work with the common `768px` resolution typically found in smaller screens.

**Comment by sindelio** [comment] 2024-04-25 15:37
@subnetmarco I think thre is really a bug in the UI, even in the latest releases my request/response panels are always stacked vertically. I rolled back to 2022.7.5 for now and I can properly set it to horizontally stacked, however this made me look into other alternatives such as Bruno and Thunder. None really satisfied my needs, so I'm keeping Insomnia for now, but note a simple UI bug might be leading users elsewhere.
