### ISSUE TITLE
Requests can no longer be reordered

### ISSUE THREAD

**Issue by DanielRouxSA** [getinsomnia/insomnia#6284] opened 2023-08-15 08:54 UTC
### Expected Behavior

When using the sorting dropdown menu or manually reordering requests, the requests should visually reorder.

### Actual Behavior

Neither sorting via the dropdown or via manually reordering works. In addition, the order of the requests appear to have been scrambled from what it used to be.

### Reproduction Steps

1. Go to a collection of requests
2. Attempt to reorder requests, either via dragging or via the dropdown.
3. The order of the requests does not change.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It does appear as if the sorting information is being saved, because attempting to reorder does result in metaSortKey updates in the Insomnia Sync history, but it has no effect on the actual displayed order of the requests

### Insomnia Version

2023.5.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2, macOS 13.5

### Installation method

Downloaded from insomnia.net

### Last Known Working Insomnia version

2023.4.0

**Comment by Karl255** [comment] 2023-08-15 14:34
Just updated to 2023.5.2 and started experiencing the same issue.

**Comment by tsptylertech** [comment] 2023-08-15 15:18
I reported this to support last night, when Insomnia updated from 2023.4.0 to 2023.5.0.  Today, Insomnia updated itself to 2023.5.2 and I still have the same problem.  Insomnia scrambled my collection's request ordering and will not allow me to reorder any of my collection requests.

Additionally, the interface is really slow to react to any user interaction.

**Comment by hnsewell** [comment] 2023-08-15 22:25
I'm having this issue as well. It reordered everything I had saved and as a QA Engineer, this is my nightmare. Arranged items were in a specific order for a reason. I hope a fix comes ASAP.

**Comment by Xenovore** [comment] 2023-08-15 23:03
Same issue here: it's now all re-ordered in some arbitrary order (not even alphabetical) and cannot be re-ordered by drag-and-drop as it could be prior to this breaking release.

**Comment by rakheepatel** [comment] 2023-08-16 03:31
Same deal with v2023.5.2. Creating a duplicate of a request and attempting to move it to another folder also doesn't work

**Comment by nettnikl** [comment] 2023-08-16 12:29
Hi, first time user here, so i have a fresh install with this issue. However, it seems to be a UI bug only - **Workaround**: open and close a folder or otherwise refreshing the tree view shows the changes done, they are just not displayed after movement.

**Comment by kevinpfox** [comment] 2023-08-16 14:56
This is has been an extremely disruptive bug to my development workflow. My query/mutations list is 100s of items long and it's in a specific order, with the items I used the most at the top of the list. The recent update scrambled the list so I can't easily find any of the most used items and to make it worse, there is no way to put the list back in the correct, previous order. I thought I could perhaps fix the issue by loading a saved backup, but that doesn't correct the two major issues mentioned.

It's like having a workshop you use everyday and someone coming in, taking all the tools you regularly put your hands on and throwing them all over the place so nothing is findable.

Speaking of findable, search feature no longer works. So in addition to list scrambling, now when doing a text search for a specific item, it doesn't do anything compounding the other two issues.

Please fix soon.

**Comment by marchpane** [comment] 2023-08-16 21:51
+1

**Comment by mijabr** [comment] 2023-08-16 23:06
+1. ordering is now random and cannot change it. Hoping we have not lost the ordering...

**Comment by kemalelmizan** [comment] 2023-08-17 04:34
Few recent updates have also been buggy on UI/rendering for me. My workaround is downgrading to [Insomnia 2023.2.2](https://github.com/Kong/insomnia/releases/tag/core%402023.2.2) and disabling automatic updates. Hope this helps people looking for quick fix.

**Comment by erinsbc** [comment] 2023-08-17 15:34
+1. I've depended on filtering/search to quickly get to the queries and mutations I need to run. Without it, insomnia has become almost unusable.

**Comment by filfreire** [comment] 2023-08-18 08:33
Hey folks, this issue and issue #6288 will be fixed in an upcoming patch release. We'll update you here as soon as possible.

**Comment by K2ouMais** [comment] 2023-08-18 12:51
Just updated to version 2025.5.4 and the problem still persists.

**Comment by nettnikl** [comment] 2023-08-18 13:20
It was not said the next, but in one of the next releases - #6329 is not merged yet, and this is supposedly the fix for this.

**Comment by suchislife801** [comment] 2023-08-18 14:13
## The link. Here is the link to the last working version.

# [2023.4.0](https://github.com/Kong/insomnia/releases/tag/core@2023.4.0)

**Comment by mjsharkey** [comment] 2023-08-18 16:22
Exact same problem everyone else here is having.

**Comment by nettnikl** [comment] 2023-08-18 17:11
Please, everyone reading this:

**Do _not_ comment to say "+1", "same here" or similar!**

Just press the +1 on the first post. You are spamming this thread for no reason or gain whatsoever. If you want to be notified, click subscribe, no reason to comment either.

Thanks.

**Comment by hnsewell** [comment] 2023-08-18 17:23
+2

**Comment by nettnikl** [comment] 2023-08-18 18:12
> > Please, everyone reading this:
> > 
> > **Do _not_ comment to say "+1", "same here" or similar!**
> > 
> > Just press the +1 on the first post. You are spamming this thread for no reason or gain whatsoever. If you want to be notified, click subscribe, no reason to comment either.
> > 
> > Thanks.
> 
> You are not our mom!

Son, go do your homework and stop arguing with people on the internet.

EDIT: Quite the bad sports, @marchpane :smile: - but for real, i'm not affiliated with this project and am confused you're getting so personal. Please don't ping people without adding information to the thread.

**Closed as completed** 2023-08-22 16:44 UTC
Labels: B-bug, S-verified
