### ISSUE TITLE
Issue with pull, push and commit

### ISSUE THREAD

**Issue by gautamtyagi81** [getinsomnia/insomnia#2458] opened 2020-07-28 07:58 UTC
**Describe the bug**
I created a new document in Insomnia designer and cloned a git repository. I switched to a branch and then created an API request. Now I am trying to push that onto my branch. As I click on push button it starts loading and remains same forever. Nothing get pushed. Also same problem with pull also. Also when I click on commit button it shows me nothing to commit.

**To Reproduce**
1. Create a new document with a git repository cloned to it
2. Checkout some branch other then master
3. Create an API request on debug mode of Insomnia designer
4. Now try to commit push or pull

**Expected behavior**
It should show me my changes on commit window and I should be able to push the changes.

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 64 bit
 - Installation Method: Downloaded application for windows and installed Insomnia designer
 - App Version: 2020.3.3

**Comment by skiat** [comment] 2020-08-10 14:58
Additional info to this issue:
- git server is a self-hosted: GitLab
- the branch is Not protected

(Hi @develohpanda FYI this is what we also discussed very quikly on slack a few weeks ago)

**Comment by develohpanda** [comment] 2020-08-11 04:11
Ah, self-hosted GitLab strikes again.

I merged https://github.com/Kong/insomnia/pull/2432 recently, and there is a beta release (2020.4.0-beta.4) coming hopefully tomorrow that includes this PR, which may help you debug. You can upgrade to the beta channel from Preferences if you'd like to try it, but please note this is _beta_ and not stable.

> Also when I click on commit button it shows me nothing to commit.

I find this to be the interesting one, as the git server shouldn't affect your ability to commit within the app.

Could you please try the following steps, with the console (View > Toggle Devtools > Console) open so that you can see git logs.
1. Create a blank document in designer
1. Create a request
1. Create a blank git repository in GitLab
1. Click "Setup Git Sync" in designer, and link your newly created repository
1. Commit -> this should show changes
1. Push -> you should see your commit in gitlab, or an error message in console

Please report back on findings to help me reproduce it 🎉

**Comment by skiat** [comment] 2020-08-11 08:52
> Also when I click on commit button it shows me nothing to commit.

I think this is related to the long time one have to wait to see changed requests like reported here: #2457

**Comment by develohpanda** [comment] 2020-08-12 06:19
> I think this is related to the long time one have to wait to see changed requests like reported here: 2457

Ah, gotcha. So you _do_, eventually, see changes in the commit dialog? You'll notice that I have put the accepted label on 2457, we'll get onto it when we get a chance.

In that case, with the upcoming beta release, please try those steps and report back. I'm hopeful that the additional logging that has recently been added will help to determine why push/pull isn't working for you.

**Comment by gautamtyagi81** [comment] 2020-08-13 06:37
> Ah, self-hosted GitLab strikes again.
> 
> I merged #2432 recently, and there is a beta release (2020.4.0-beta.4) coming hopefully tomorrow that includes this PR, which may help you debug. You can upgrade to the beta channel from Preferences if you'd like to try it, but please note this is _beta_ and not stable.
> 
> > Also when I click on commit button it shows me nothing to commit.
> 
> I find this to be the interesting one, as the git server shouldn't affect your ability to commit within the app.
> 
> Could you please try the following steps, with the console (View > Toggle Devtools > Console) open so that you can see git logs.
> 
> 1. Create a blank document in designer
> 2. Create a request
> 3. Create a blank git repository in GitLab
> 4. Click "Setup Git Sync" in designer, and link your newly created repository
> 5. Commit -> this should show changes
> 6. Push -> you should see your commit in gitlab, or an error message in console
> 
> Please report back on findings to help me reproduce it 🎉

yes It worked for me. Now I'll check again for my project. Thanks a lot

**Comment by gautamtyagi81** [comment] 2020-08-14 10:01
Its working If i create a new blank document. But it is not working if I create new API request in existing document which I synced from gitlab repository

**Comment by develohpanda** [comment] 2020-08-15 23:48
Hmm, that's interesting. A couple of questions:
1. Could you provide any information on what your document looks like? A few/a lot of requests, a few/a lot of commits in the repository, whether _you_ created the repository or you cloned an existing repository with the `.insomnia` directory.

1. Both the original repository, and the testing repository - did you create them, and can confirm you have the same permissions across both of them?

1. Are you trying to commit to master, or a child branch? If a child branch, did you _create_ it in Designer and are trying to push, or did you _checkout_ a remote branch?

1. Since the reproduction steps at the top of this issue are now out of date, would you be able to try reproduce what you are seeing, with a new document, in order to help me reproduce the issue that you're seeing?

It feels like you've hit an edge case of some sort, that's not necessarily related to your git provider, and I'd really like to get to the bottom of it. Thanks, @gautamtyagi81!

**Comment by gautamtyagi81** [comment] 2020-08-17 08:53
Yes @develohpanda . I cloned existing repository in insomnia designer which has already around 80 API requests.
1. I created a new folder in which I created 2 API requests. I tried with just 1 commit. I tried to push in existing branch which was made during development and fetched in insomnia designer.
2. I did not create the repository. It is existing project in gitlab and I was given access. There is only one repository which we are using for code (in phpstorm) and for API requests (in insomnia)
3. I am trying to commit in a branch which I created from git bash and pushed to remote and checked out in Insomnia.
4. I tried it with the beta version you have mentioned but still getting same issue. I can commit the changes but can not push.

**Comment by gautamtyagi81** [comment] 2020-08-17 13:52
I delete my document and cloned the repository again. Then I added my requests and then commit 
Commit goes fine but when I pushed then I got this error

TypeError: Cannot read property 'request' of undefined
    at httpPlugin (file:///C:/Users/91989/AppData/Local/insomnia-designer/app-2020.4.0-beta4/resources/app.asar/bundle.js:175820:19)
    at async Function.discover (C:\Users\91989\AppData\Local\insomnia-designer\app-2020.4.0-beta4\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:6453:15)
    at async Object.getRemoteInfo (C:\Users\91989\AppData\Local\insomnia-designer\app-2020.4.0-beta4\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:8429:20)
    at async GitVCS.canPush (file:///C:/Users/91989/AppData/Local/insomnia-designer/app-2020.4.0-beta4/resources/app.asar/bundle.js:33209:24)
    at async GitSyncDropdown._handlePush (file:///C:/Users/91989/AppData/Local/insomnia-designer/app-2020.4.0-beta4/resources/app.asar/bundle.js:193521:17)

**Comment by skiat** [comment] 2020-08-21 08:15
Hi
 I wanted to do a test also on my side using the beta 2020.4.0-beta.4, but with this version as soon as I start ( **fresh AppData** Insomnia folder and **fresh clone**) when I want to commit all of the requests are set to changed to be staged and committed :-O and if I try to rollback nothing happens

**Comment by develohpanda** [comment] 2020-09-03 05:37
> when I want to commit all of the requests are set to changed to be staged and committed :-O and if I try to rollback nothing happens

I literally just came across this 😮 

We've published 2020.4.0-beta.6 just now. I think there must be something curious with your repository, let me know if the new beta helps otherwise we'll need to dig further again to atleast try to reproduce this.

**Comment by anthros-niccolo** [comment] 2021-09-13 13:34
Hi, I'm getting the same error. Using a private repo but I'm able to pull code, just not push changes.

**Comment by develohpanda** [comment] 2021-09-16 05:00
Hi @anthros-niccolo, do you see anything in the Developer Console when trying to push changes? (View > Toggle DevTools)

**Comment by tom-at-bowntie** [comment] 2021-10-02 21:11
@develohpanda I'm running into this currently and can't push or pull any code to a private repo. My info:

```
Version: Insomnia 2021.5.3
Release date: 9/13/2021
OS: Darwin x64 20.5.0
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0
```

And the error I'm seeing in the developer console tools:

`[ErrorModal] TypeError: Cannot read property 'request' of undefined
    at Object.request (bundle.js:130995)
    at async Function.discover (/Applications/Insomn…-git/index.cjs:6559)
    at async Object.getRemoteInfo (/Applications/Insomn…-git/index.cjs:9343)
    at async GitVCS.canPush (bundle.js:87139)
    at async GitSyncDropdown._handlePush (bundle.js:309511)`

**Comment by develohpanda** [comment] 2021-10-03 06:28
Hi @tom-at-bowntie! Sorry to hear that. Looking at the stack trace this appears to be an issue within the git library we use and in the past this has often been attributed to permissions issues, though there may be something wrong in the way we integrate with that library as well. A few questions to help narrow down, as you don't see anything extra in the console logs:

1. Which git provider are you using?
2. Does sync work for you with a public repository?
3. With the same credentials, are you able to push to the same branch from git in the command line? (This should help identify whether the issue is within Insomnia or a permissions issue with your specific account/provider).

**Comment by tom-at-bowntie** [comment] 2021-10-03 19:02
Hey @develohpanda!

Which git provider are you using?
A: I'm using github with a private repo. It had worked previously, and I had suspicions that it could be the dev-generated access token. I attempted to generate a new access token with full permissions and am encountering the same error.

<img width="758" alt="Screen Shot 2021-10-03 at 1 52 31 PM" src="https://user-images.githubusercontent.com/66454382/135767498-94f80b43-c11e-47af-ac90-9bace6426afc.png">

Does sync work for you with a public repository?
I tried going through the setup git sync process again, and attempting to even link it is returning the same stack trace:

`TypeError: Cannot read property 'request' of undefined
    at Object.request (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:130995:27)
    at async Function.discover (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:6559:13)
    at async _fetch (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:7251:22)
    at async _clone (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:7628:42)
    at async Object.clone (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:7751:12)
    at async Object.shallowClone (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:309737:5)
    at async GitRepositorySettingsModal.onSubmitEdits [as _onSubmitEdits] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:168922:25)`

With the same credentials, are you able to push to the same branch from git in the command line? (This should help identify whether the issue is within Insomnia or a permissions issue with your specific account/provider).

I actually wanted to attempt to manually push from the CLI, but was unable to locate where in the MacOS filesystem the .insomnia directory was located for my project?
<img width="935" alt="Screen Shot 2021-10-03 at 2 00 44 PM" src="https://user-images.githubusercontent.com/66454382/135767764-09b7b360-9441-40ae-b353-5edfb27195e5.png">

**Comment by develohpanda** [comment] 2021-10-04 05:56
Thanks for that info! Did this start happening for you after a recent update of Insomnia, or just randomly now? I've tried with one of my repos and cloning/push/pull seemed to work fine with the existing token I had (with a private repo), but I'll try a few more iterations.

Regarding the `.insomnia` directory, that folder doesn't actually exist on the file system. I was just wondering whether the credentials & token work outside of Insomnia.

**Comment by tom-at-bowntie** [comment] 2021-10-06 15:52
@develohpanda It seems to have started just randomly now :-/ At this moment, I can't even go through the setup git flow anymore.

**Comment by basarito** [comment] 2022-06-30 10:02
Hello, I am also noticing issues with git pull in Insomnia. It's just stuck in 'loading' state and I cannot seem to update the branch:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/17669683/176650231-d6a8d5d6-be88-4b06-8906-5a76a2af4d7d.png">

Using `macOS v12.3.1` with Insomnia:
```
Version: Insomnia 2022.4.0
Build date: 6/9/2022
OS: Darwin arm64 21.4.0
Electron: 18.1.0
Node: 16.13.2
V8: 10.0.139.15-electron.0
Architecture: arm64
```

Repository I'm trying to fetch is on GitLab and is a private repo.

**Comment by kreosus** [comment] 2022-09-02 13:04
Hi @basarito 
Do you see the same behavior with our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4

**Comment by frodeopdahl** [comment] 2022-11-25 07:02
I am having issues with committing while having an spec in the Design tab. When trying to commit I get this error:
`/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:331 Uncaught (in promise) YAMLSyntaxError: All collection items must start at the same column
    at Collection.parse (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:331:24)
    at /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:1605:29
    at Document.parseContents (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:622:26)
    at Document.parse (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:685:19)
    at Object.parse (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:1723:18)
    at parseDocument (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/index.js:43:24)
    at Object.parse (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/index.js:55:15)
    at oP.stat (ne-db-client.ts:194:35)
    at async FileSystem.lstat (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:4324:21)
    at async status (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:13077:19)
    at async git-staging-modal.tsx:106:22`

If i remove the spec and only keep the debug and test content then committing works fine. This also still doesn’t work on Insomnia 2022.7.0-beta.5

Edit:
I managed to make my spec file work by running it through a prettifier https://jsonformatter.curiousconcept.com, and when I pasted that into the Design tab it let me commit and push my spec. I assume that sending in the spec as a one line json string causes the bug.

Edit 2:
I have been trying fruitlessly to make FastApi output a format that is easily understood by Insomnia by I can’t seem to make it work. I suggest that you add in an option or even automatically prettify the json that pasted/loaded into the Design since this would solve my problem.

**Closed as completed** 2023-02-06 08:58 UTC
Labels: N-author-input, A-design, A-git-sync, needs-triage
